### ISSUE TITLE
Feature request: Book structure display option for search page

### ISSUE THREAD

**Issue by PeterBizQIT** [BookStackApp/BookStack#1013]
A couple of days ago we started testing and now using BookStack as a replacement for our current knowledge base system. BookStack is a great application! Thank you for the amazing work! However I would like to submit a feature request for the search page.

**Describe the feature you'd like**
In our opinion the way in which the search page displays the results is a little bit unclear. When submitting a search query it shows all the books, chapters and pages at a random order. So we like to have an option to show the results by book structure. Just like the Book Navigation bar at the left side displays the book structure when viewing a page.

**Describe the benefits this feature would bring to BookStack users**
This will make the search page a lot clearer to read and helps sort out which page belongs to which book and/or chapter.

**Comment by PeterBizQIT** [comment]
Note:

Although there is a search bar for searching in specific books or chapters, we want to be able to search in all books and have that structured nicely.

**Comment by PeterBizQIT** [comment]
@ssddanbrown Could you tell me if this feature request is considered to be implemented in future releases?

**Comment by ssddanbrown** [comment]
Hi @PeterBizQIT,
Sorry for not responding sooner. 

I'd prefer to keep the search page as a standard list, since that will be most familiar to users and is simple for us to maintain and add features to.
Since this issue was opened, as of the last update, pages and chapters within the search listing should now show their parent book and chapter to provide more context to the user of where that page sits. I hope that helps towards the benefit you were targeting in this issue.
