### ISSUE TITLE
Feature Request: More condensed view in general, improve navigation

### ISSUE THREAD

**Issue by massaquah** [BookStackApp/BookStack#1032]
**Describe the feature you'd like**
During the past few weeks I gave BookStack, DocuWiki, XWiki, Wiki.js and several others a test run.
While I prefer Bookstack in terms of editor features and article layout I don't like the overall use of screen estate.
I would like to have a more condensed view e.g. for the list of pages and chapters within a book (there is much unused (= white) screen estate. And additionally I would like to have a classic navigation column on the left much like in classic wikis.
Navigation from page x in book a to page y in book b should take just one click. Right now, I have to click on "Books" in the navigation bar at the top, then choose the correct book, then klick on the page I want.

**Describe the benefits this feature would bring to BookStack users**
This would greatly improve the navigation experience and would increase the amount of information on one page.

**Comment by ssddanbrown** [comment]
Since this issue was created the design of BookStack has changed a fair bit and changes have been made to ensure navigation is more efficient:
https://www.bookstackapp.com/blog/beta-release-v0-26-0/

I probably won't support a global sidebar menu where items are one-click away since it's really difficult to make that scale-able and you'd soon probably end up worse off in many instances. 

Due to the above, I'm going to close this. If there's anything specific you feel that's missing that would benefit all BookStack users please open a new issue focused on that request
