### ISSUE TITLE
Allow pages to be directly assigned to shelves

### ISSUE THREAD

**Issue by aljawaid** [BookStackApp/BookStack#1036]
Just a quick one, I was looking into the new Bookshelves implementation today and had a question:

Is it a wrong way of doing, or how would we go about assigning certain pages of a book to a bookshelf?

Before I make a mess of my new bookshelf and chopping my books about, I thought I would get everyone's opinion, or at least @ssddanbrown  :)

Example:  One book is called `IT Manual` and it contains a page called `Public Sharing Links`.  The rest of the book is all about IT support articles etc.  My new bookshelf is called `Marketing`.  So I thought, how would I go about just the public links page into that bookshelf, or should I create a book (single page) just for that topic and then I will be able to add it to different shelves?

Any suggestions?

**Comment by Rubizzle** [comment]
I don't think there's a way to assign pages to a bookshelf - though that would be interesting! Since BookStack doesn't support sub chapters, I basically turned my chapters into books and put them all into relevant bookshelves to have that extra "sublevel."

In your situation, I'd probably create a book with just the single page and add it to different shelves. Or you can have a bookshelf and change the permissions where different groups can access?

**Comment by aljawaid** [comment]
I can see too many single-page books being created I think.... maybe if a book had a 'special page' like an appendix or reference page and then that 'special page' could be shared across books/bookshelves.

**Comment by ssddanbrown** [comment]
Just to confirm, Yeah, This is not currently possible but I'll leave this open to discussion to see if it gains support.

**Comment by ezzra** [comment]
I would like it, because this would make the shelve system more attractive to use.
