### ISSUE TITLE
Optimising meta-data & third party applications?

### ISSUE THREAD

**Issue by beachedward** [BookStackApp/BookStack#1041]
Hi guys

Forgive me for being unversed with programming:  I'm encountering issues with optimising the site for search engine use.

Is there a way to easily insert detailed metadata for each article in addition to the homepage?

Furthermore, how would one go about adding third party applications such as disqus or a 'did this article help' extension. Would I need to hire somebody to do this or is there a simple way to achieve these things

many thanks

**Comment by ssddanbrown** [comment]
Hi @beachedward,
Sorry for the very late response.

> Is there a way to easily insert detailed metadata for each article in addition to the homepage?

No, Not as it stands. BookStack is Primarily focused as a smaller internal wiki rather than a public-facing documentation site where SEO is a concern.

> Furthermore, how would one go about adding third party applications such as disqus or a 'did this article help' extension. Would I need to hire somebody to do this or is there a simple way to achieve these things

Such additions would really require some custom development work, As these are things I don't really see being included in the core project. Some of them may be possible/easier in the near future as we improve customizability.

To be honest though, from your questions, I think other solutions may be better for your use-case. You could find someone to help modify BookStack to include your required features but then you'll need active maintenance to keep up with releases.

**Comment by ssddanbrown** [comment]
Since the original questions were answered I'll close this. If there was any specific wishes in terms of the meta data please open a new issue focused on that request.
