### ISSUE TITLE
Import from Microsoft OneNote

### ISSUE THREAD

**Issue by eminphi** [BookStackApp/BookStack#1049]
**Describe the feature you'd like**
Ability to import pages and sections from a Microsoft OneNote notebook.

**Describe the benefits this feature would bring to BookStack users**
Attract more potential users who are actively using OneNote but not making the switch to BookStack due to high amount of pages they have accumulated over the past several years.

**Additional context**
N/A

**Comment by ssddanbrown** [comment]
Hi @bisherbas,
Thanks for this request.

I think this will be very tricky due to the flexible nature of one-note content along with the complex formats for Microsoft documents. 

The benefit listed, "Attract more potential users", In my view will always remain a lower priority than things that will enhance the experience for existing users although I can understand the benefit of importing existing content.

Will leave this open-to-discussion for a while, Incase someone knows a simple way this can be done, but I may close this at some point if no simple option can be identified.

**Comment by bisherbas** [comment]
@ssddanbrown 

Not trying to be the pessimist but I was trying out [Notion](https://www.notion.so/) and noticed that they are able to import from many different apps except Microsoft OneNote. Perhaps my request is not really that easy if not impossible...

**Comment by mp68** [comment]
Microsoft provides a REST API for their online services. At least for the users who choose to upload their notebooks it should be pretty easy to export full notebooks. Their page object returns valid HTML content so you just have to extract the images and store the HTML in the database. See more details here: https://docs.microsoft.com/en-us/graph/api/page-get?view=graph-rest-1.0

**Comment by onerousbudgie** [comment]
Is there a "For dummies" version on how to do that?  I have a ton of onenote notes and would like to switch.
