### ISSUE TITLE
How do I add an existing draw.io diagram?

### ISSUE THREAD

**Issue by Leon99** [BookStackApp/BookStack#1073]
I've got so excited to find a wiki that satisfies all the requirements we had only to realise that there (seems to be) no way to make use of all our current diagrams. Am I missing something?

**Comment by ssddanbrown** [comment]
@Leon99 Do you know the format of your current diagrams? (Draw.io has a few export options).
Are they embedded within other content?

By default BookStack uses png's with emedded draw.io info, Wrapped in a tag to identify them as diagrams.

**Comment by davidjgraph** [comment]
One way is create a blank diagram in Bookstack, open the original diagram, ctrl/cmd+a to select all in the original, ctrl/cmd+c to copy, then ctrl/cmd+v in the blank bookstack draw.io editor to paste the diagram in.

**Comment by davidjgraph** [comment]
@Leon99 If you have multiple layers it will [select only the active layer](https://trello.com/c/PL8aQB9t/207-copy-paste-objects-in-multiple-layers). Another question, would you pay for a cloud managed version of Bookstack? Something like an AWS, GCP image you running up with a premium pricing on the VM. Not that we intend to supply this, but I think Dan should be building this out full-time 8-).

@ssddanbrown we wrote a [Google Drive viewer for Confluence](https://marketplace.atlassian.com/apps/1214854/google-drive-connector-for-confluence?hosting=cloud&tab=overview), welcome to use the code.

It might seem strange people mixing cloud and on-premise tools, but we see a lot of requests for the connector in Confluence Server, but are often using on-premise because the cloud hosted options don't cut it.

**Comment by Leon99** [comment]
> David Benson moved this card from Feature Requests to Things that constantly annoy users

Hell yeah, copy-pasting all our diagrams layer-by-layer is not just annoying but time-consuming and error-prone, although looks likes there is no choice :(

Cloud-managed version? Maybe, depending on the price.

@ssddanbrown Is there a hope in
> By default BookStack uses png's with emedded draw.io info, Wrapped in a tag to identify them as diagrams.

?

**Comment by ssddanbrown** [comment]
@Leon99 Unfortunately not, Thinking deeper, it will be a lot of work to get the content in the format that BookStack expects. 

I just done a test using google drive and BookStack. I found exporting my drive drawing as XML then importing via the BookStack draw.io editor (File > Import from > device) did import the drawing with all layers as expected. I can understand this is a big hassle though. You can speed this up by dragging the downloading XML file into the drawing editor instead of using the import menu.

@davidjgraph Thanks for offering the code. I'll keep that in mind but gdrive integration has been an fairly uncommon request so far so probably not worth the effort right now to implement & maintain.

**Comment by ssddanbrown** [comment]
Since this conversation is over a year old, and did not move any further, I'll go ahead and close this off.
