### ISSUE TITLE
Pages in userlist (Settings)

### ISSUE THREAD

**Issue by Romeekk** [BookStackApp/BookStack#1089]
**Describe the bug**
At the moment we updated our Bookstack and we are now not able to view all our pages in the userlist in settings.
If we click for example page 2 it just stays on page 1, the url does change to https://bookstack.ssc-scalda.nl/settings/users?order=asc&search=&sort=name&page=2 but it just remains on page 1.

**Steps To Reproduce**
1. Go to 'settings/user'
2. Click on 'page 2 of the userlist'
3. Scroll down to 'x'

You will see then that nothing changes and it remains on page 1.

**Expected behavior**
Normally before the update you will see the second or third page.

**Screenshots**
![image](https://user-images.githubusercontent.com/44465975/47495409-5f265400-d854-11e8-9e47-e6d18384b72b.png)
![image](https://user-images.githubusercontent.com/44465975/47495426-6b121600-d854-11e8-89c4-1f4b484bb37d.png)

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): BookStack v0.24.1
 - PHP Version: 7.2
 - Hosting Method (Nginx/Apache/Docker):  Nginx

**Additional context**

**Comment by ssddanbrown** [comment]
Hi @Romeekk, Sorry to hear you are experiencing this issue.

I've tested this list in my own instance, Which is on the same version, and I can continue to the next page without issue. You mentioned that, before the update, this used to work as expected. Do you know which version you updated from?

Also, Does the sorting work correct when you click the headers (Name, Email)?

**Comment by ssddanbrown** [comment]
Since the last comment on this issue is relatively old I'm going to close this. If the issue remains and is something you still require to be fixed please open a new issue, referencing this one.

Looking at the above, I can only think this this could be due to URL re-writing causing the parameters to be altered as part of the server config. If you do look to follow my comment above, it would probably be good to post your server config if possible.
