### ISSUE TITLE
Cannot create book shelf

### ISSUE THREAD

**Issue by doc-jay** [BookStackApp/BookStack#1094]
Description:  No 'table' to drag the book over to in order to add it to a shelf.

**Steps To Reproduce**
1. Go to shelves
2. click 'create one now'
3. cannot drag over books from the right and drop on the left

Expected:  should be able to add books to the shelf

![bookstack-shelferror](https://user-images.githubusercontent.com/11081155/47598905-08f70500-d969-11e8-89a4-037cdf45fa53.PNG)

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings):  V.0.24.1
 - PHP Version:  7.0.30
 - Hosting Method (Nginx/Apache/Docker):   NGINX

**Additional context**
I am blocked from GITHUB on this server I'm updating an older install from (v.0.22.x).  I am doing a git pull from a different site, running 'php composer install', waiting until successful, and zipping it up and copying it to my site, unzipping it into a new dir, next to the older version.  When it is copied over, unzipped, and permissions given, I'm running 'php composer install' and it does its thing it needs, clears the cache & view.  I also run 'php artisan migrate' which finished successfully.

**Comment by Abijeet** [comment]
Hey @doc-jay 

Sorry to hear that you are having issues. 

This looks like an issue on the client side. Can you please tell us what browser you are using? 

What happens when you simply click on one of the books on the right? If nothing happens can you please open the developer tools and check the console for errors? This link might have some guidelines - https://kb.yoast.com/kb/how-to-find-javascript-errors-with-your-browsers-console/

**Comment by doc-jay** [comment]
I've tried in chrome, firefox and IE 11.  When I click on the books on the right, it takes me to the book and I browse through it and read the pages successfully.

**Comment by ssddanbrown** [comment]
@doc-jay My guess it that you don't have the latest [`public/dist`](https://github.com/BookStackApp/BookStack/tree/v0.24.1/public/dist) files since these hold the missing styles and functionality.

You can [download a zip of the latest release files here](https://github.com/BookStackApp/BookStack/archive/v0.24.1.zip) then copy the files over from the `public/dist` folder.

When you perform the git pull on your other site does it mention the `master` branch or the `release` branch? The main `master` branch does not include these files.

**Comment by doc-jay** [comment]
SOLVED:  thanks for that.  I copied those files over anyways and tried it again from the same machine and it still didn't change.   I then tried it from a different machine and it worked as expected.  In hindsight I should have done that step first to test.

Thanks for all of your help on this!

**Comment by piiq** [comment]
> @doc-jay My guess it that you don't have the latest [`public/dist`](https://github.com/BookStackApp/BookStack/tree/v0.24.1/public/dist) files since these hold the missing styles and functionality.
> 
> You can [download a zip of the latest release files here](https://github.com/BookStackApp/BookStack/archive/v0.24.1.zip) then copy the files over from the `public/dist` folder.
> 
> When you perform the git pull on your other site does it mention the `master` branch or the `release` branch? The main `master` branch does not include these files.

Hey @ssddanbrown ! Maybe you can help me out with it. I am experiencing the same issue.
We're running the latest release (0.24.3) in a docker container. When we build the container we download the tar.gz bundle from github.

I save tried doing it with the latest version of Chrome and Safari on MacOS 10.14.2

I have checked the content of `public/dist` and it the same an in repository.

I have attached an image of what I see in chrome's developer console when I go to the shelf edit page

![image](https://user-images.githubusercontent.com/11668535/50956437-b4294c00-14cc-11e9-88ac-185ec02f1539.png)

**Comment by ssddanbrown** [comment]
Hi @piiq,

> I have checked the content of public/dist and it the same an in repository.

How sure of this are you and what did you check this against?
The [`app.js` file ](https://github.com/BookStackApp/BookStack/blob/v0.24.3/public/dist/app.js) should be about 813KB rather than the 842KB shown in your screenshot. 

Also, What tar.gz bundle do you use?

Might be best to open this as a new issue if you continue to have problems as it's easy to miss things here since it's closed and you'll be altering everyone previously involved in this issue.
