### ISSUE TITLE
Optimize white space on the main Notebook page

### ISSUE THREAD

**Issue by bisherbas** [BookStackApp/BookStack#1131]
**Describe the feature you'd like**
Better utilize the white space on the main Notebook page. For example, provide user option to add more rows and columns. If a notebook contains dozens of pages, it doesn't make sense to force user to scroll down on the page to reach the desired page link. Demonstrated in the screenshot below.

![image](https://user-images.githubusercontent.com/42714627/48663106-37906900-ea59-11e8-8b21-8b2bc2a2b652.png)

**Describe the benefits this feature would bring to BookStack users**
Prevent unnecessary scrolling
Optimize white space
Quickly locate the desired page link

**Additional context**
See above.

**Comment by ssddanbrown** [comment]
Since the design update has now been released many whitespace efficiency improvements have been made:
https://www.bookstackapp.com/blog/beta-release-v0-26-0/

I think the main thing remaining might be a different view option for the books listing which is already covered by #530, Therefore I'll close this.
