### ISSUE TITLE
Translation/Multi Language Support

### ISSUE THREAD

**Issue by leomartinez** [BookStackApp/BookStack#115]
It would be really interesting and useful to support other languages.

**Comment by jaksz** [comment]
I can provide an Arabic translation, but we will need to make sure that RTL languages work.

**Comment by ssddanbrown** [comment]
@leomartinez I agree, I was going to wait a little longer so that BookStack was more stable but I'll start to take language support into account and start to organise/structure current english text to be translated.

@jaksz Thanks for the offer. I'll have to start organising the english content first. I'll update this issue as progress is made. I have little experience with RTL languages but I'll do what I can.

**Comment by sirgix** [comment]
We'll gladly provide french italian and german translations whenever possible as we have professional translators in our team!

**Comment by ssddanbrown** [comment]
Sorry it's taken a while but full support for translations is now pretty much fully baked into BookStack (For the next release). I've added some details to the [readme](https://github.com/BookStackApp/BookStack#translations) in regards to developing translations. If editing the text files via git is troublesome drop a comment below and I can look into translation management services (Or let me know if you have any recommendations in this area) to make things easier for any non-developers.

Since the base translation system is now all in place I will close this issue. There's likely to be a few errors or a few missing strings as it's taken a lot of work to put this into place so just open a new issue for anything extra.
