### ISSUE TITLE
master vs release contributing

### ISSUE THREAD

**Issue by ezzra** [BookStackApp/BookStack#1168]
The Readme states 

> All development on BookStack is currently done on the master branch. When it's time for a release the master branch is merged into release

but actually, branch `release` is 129 commits ahead `master`. Shouldn't the most recent code be located in master?

**Comment by ssddanbrown** [comment]
Hi @ezzra,
`master` does contain the development branch of code. For releases, the master branch is merged into `release`, The version is set and the CSS/JS files are built.
The 129 commits ahead you're seeing on `release` are just version bumps and CSS/JS build updates. 

Usually `master` will be ahead but recent development work, since the last release, has been done on separate branches. `master` will always contain matching or more recent source code.

The [network graph](https://github.com/BookStackApp/BookStack/network) helps visualise this strategy.

**Comment by ezzra** [comment]
ok thanks, I was just confused by the high number of ahead commits, but I got the picture now :)
