### ISSUE TITLE
question: why are user languages stored in settings table?

### ISSUE THREAD

**Issue by ezzra** [BookStackApp/BookStack#1176]
I am confused, that the user specific languages are stored in the settings table like:

```
user:11:language | en
user:12:language | de
```

I would expect to find this in the users table, is there a specific reasons for this? I am just checking out to work on #1152 and I would have stored the specific homepage data for roles in the roles table, but now I am unsure if I should follow this style?

**Comment by ssddanbrown** [comment]
This method of storage just provides a flexible way to store any user (& system) preferences really. The language could have been stored on the `users` table but it's not really queried or used much, Just in a single core place really. If it was used more, to the point language was shown in multiple views or if it needed to be searched upon then it might be worth moving it out otherwise the Settings system provides a nice abstraction where we can implement caching for example or additional logic (Storing guest data in the session for example).

If you're looking to implement something for #1152 I'd suggest maybe setting out a feature proposal before potentially wasting time building without a level of certainty that what you'd build would be implemented. The use-case on that issue is fairly specific.

**Comment by ezzra** [comment]
> maybe setting out a feature proposal before potentially wasting time

I am planning to do this, but before I wanted to check out the current code structure :) And anyway, thats a feature our team needs so I will have to build it in the next days.
