### ISSUE TITLE
Authorization controls in Socialite providers

### ISSUE THREAD

**Issue by h4ckninja** [BookStackApp/BookStack#1196]
**Describe the feature you'd like**
BookStack offers the ability to authenticate with a variety of third-party providers, which is fantastic. However, many use cases that's not enough. An example might be for Twitch authentication, checking which team(s) the person is in against an approved list so only people on a given Twitch stream team can use the wiki. Or with Discord, GitHub, etc.

**Describe the benefits this feature would bring to BookStack users**
Users can setup wikis for specific teams or groups, through trusted identity providers for their use case.

**Comment by ssddanbrown** [comment]
Our [logical theme system](https://github.com/BookStackApp/BookStack/blob/development/dev/docs/logical-theme-system.md) is now fairly mature, which allows back-end system extension.

As part of this, you can extend the system with added social providers [as shown here](https://github.com/BookStackApp/BookStack/blob/development/dev/docs/logical-theme-system.md#custom-socialite-service-example). With this system, you could provide your own tweaked provider, extending an existing one, with functionality as desired.

Alternatively the logical theme system allows hooking into login/registration events which you could use to run functionality upon login of certain providers.

Since we have the above, I'll therefore close this off. Just shout if further guidance is desired.
