### ISSUE TITLE
Keyboard shortcuts (Not inside the editor)

### ISSUE THREAD

**Issue by andreicocari** [BookStackApp/BookStack#1216]
**Describe the feature you'd like**
I know there are shortcuts available inside the editor, but I'd love to see more added outside of the text editor.  For example

- "E" to edit a page, chapter, book, (depending which screen you're on)
- "N" to create a new page
- "C" to create a new chapter
- "M to move
- SHIFT + DEL to delete
- etc

**Describe the benefits this feature would bring to BookStack users**
This will greatly increase productivity.

**Comment by andreicocari** [comment]
Hi Dan,

Thanks for considering my request.

I can see how "P" would make sense, however I was hoping to have "N" as the default new X action.
For instance, in the "Shelves" screen, "N" would create a new shelf, while in the "Book" screen, it would create a new book. Now, I believe that "Pages" are the default go-to inside of a book, therefore it should have the default shortcut.

Hope this makes sense?

**Comment by andreicocari** [comment]
They've been implementing Confluence at work.
Figured I'd share their [Keyboard Shortcuts](https://developer.atlassian.com/server/confluence/images/keyboard-shortcuts-example.png) as Inspiration

**Comment by ssddanbrown** [comment]
Just adding an implementation note, Will need to consider accessibility:

https://www.w3.org/WAI/WCAG21/Understanding/character-key-shortcuts.html

**Comment by GreatestFool** [comment]
Didn't notice this issue when I first posted my own, so I'll just include my suggestion here since it was closed as a potential duplicate.

BookStack is already going for the Bookshelf > Book > Chapter > Page aesthetic anyway, so for an end-user case, I think accesskey navigation would be nice. So that you can move between chapters, and pages under each chapter, using your arrow keys or similar.

@ssddanbrown pointed out to me that many users probably already use the arrow keys for navigation or similar anyway, so perhaps something like shift or control plus arrow keys instead of direct access would be better? I've seen sites use comma and period as a back and forward button, so that's also an option.

**Comment by sdenovan** [comment]
As a recent Confluence convert, I'm thrilled with BookStack but really miss the 'e'dit shortcut. While this feature request matures, here's a stopgap to get the 'e'dit shortcut today.

Settings -> Custom HTML Head Content
```
<script src="//cdnjs.cloudflare.com/ajax/libs/mousetrap/1.4.6/mousetrap.min.js"></script>
<script>
  Mousetrap.bind('e', function(e) {
    if (window.location.href.includes('/page/') && !window.location.href.endsWith('/edit')) {
      window.location.href=window.location.href+'/edit';
    }
  });
</script>
```

**Comment by HermasciousLevander** [comment]
> BookStack is already going for the Bookshelf > Book > Chapter > Page aesthetic anyway, so for an end-user case, I think accesskey navigation would be nice. So that you can move between chapters, and pages under each chapter, using your arrow keys or similar.
> 
> @ssddanbrown pointed out to me that many users probably already use the arrow keys for navigation or similar anyway, so perhaps something like shift or control plus arrow keys instead of direct access would be better? I've seen sites use comma and period as a back and forward button, so that's also an option.

Just a little thought about this, considering the apprehension for taking permanent control over the accesskeys could simply be a config setting. If it is left as disabled by default, people like me will still be able to make use of it instead of using potential hacky solutions to do it.

Personally, I prefer `Ctrl` + left or right accesskey to navigate.

**Comment by florian-obradovic** [comment]
I also come from Confluence (use it at work). 
I use Bookstack since 2 years for my private and freelancer IT Documentation and I'm still hitting **E** on my keyboard to enter editor when reading a page :)

It would be awesome to see some more hot keys.

Keep up the great work. Thank you very much!

**Comment by ssddanbrown** [comment]
UI Shortcut system added via PR #3830. Will be part of the next feature release.

**Comment by florian-obradovic** [comment]
Thank you very much for this awesome release - I love it!

**Comment by jankenr** [comment]
@ssddanbrown Is it correct I am missing the documentation in [https://www.bookstackapp.com/docs/user/](https://www.bookstackapp.com/docs/user/) regarding these shortcuts?
