### ISSUE TITLE
Predictive Search

### ISSUE THREAD

**Issue by cooter2** [BookStackApp/BookStack#1235]
Add predictive search to the search bar in BookStack (similar to when searching google or other systems that search on the fly).

This feature may help users by driving the to the proper search terms based on what they start typing. Google is the obvious example of this, but it is also in Cisco Prime and some other tools I use, find it very helpful when searching.

**Comment by over-soul** [comment]
Would be very helpful!

**Comment by mardukbp** [comment]
[TNTSearch](https://github.com/teamtnt/tntsearch) is a full-text search engine written in PHP that provides this feature.

**Comment by NikoVonLas** [comment]
Any progress?
I tried to do it through adding a component.
But it looks like themes folder don't support custom js files.

**Comment by tobsik** [comment]
Would be very helpful!

**Comment by BloodyIron** [comment]
I would like to add my interest for both predictive search terms, but also live search results as you type in the search field. Both of these functions are very useful and modern from a UX perspective, generally increasing operational efficiency. If we could get both of these aspects roadmapped I think it would be worthwhile. Any chance we can get these roadmapped?

I'm tagging in the live search results into this since #3290 was closed as duplicate to this ticket (#1235).

**Comment by BloodyIron** [comment]
Considering this original request was made Jan 2019, is this feature request on the roadmap in any way? I see that @ssddanbrown is active about closing dupes of this, so I'm hoping yes ;) Are there any roadblocks on this getting implemented?

**Comment by florian-obradovic** [comment]
@ssddanbrown 

I noticed when inserting links on pages there is a live-search:
![CleanShot 2022-10-21 at 22 51 54](https://user-images.githubusercontent.com/57985125/197286853-ebf53313-2943-4238-90c7-cc65ad051f83.gif)

I'd love to see that in the main search bar on the top or can I enabled this already?

Thanks a lot for your work! Awesome daily tool for me :)

**Comment by ssddanbrown** [comment]
There's an element of conflation in regards to exactly what this thread is asking for. There's:

- Live prediction of search term/phrase
- Live prediction/preview of search results

The original request could apply to either. Via other issues and requests my general feeling was that prediction/preview of search results was more often desired, at that would also be the most reasonable to technical implement since we don't store term ordering in our search index. Therefore I built this in as part of PR #3850 to be part of the next feature release.

If actual search term prediction was desired, this can be re-requested via a new issue where the benefits and requirement can be explained but, with it being on a technically different level to implement in a useful way, it'd be less likely for implementation anytime soon.
