### ISSUE TITLE
Favicon not showing 

### ISSUE THREAD

**Issue by TheKorbi** [BookStackApp/BookStack#1245]
**Describe the bug**
Favicon for BookStack installation not showing in the tab bar or bookmarks of browser.

**Steps To Reproduce**
n.a.

**Expected behavior**
Favicon should show in tab bar and bookmarks

**Screenshots**
![image](https://user-images.githubusercontent.com/33149584/51900340-54301200-23b5-11e9-876a-c5303e78d9a6.png)

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): v0.25.1
 - PHP Version: PHP 7.1
 - Hosting Method (Nginx/Apache/Docker):  Nginx

**Comment by ssddanbrown** [comment]
Hi @TheKorbi,

By default bookstack will show a favicon via the browser's default `/favicon.ico` fetching but that will fail for you since you have installed BookStack within a URL subdirectory. 

You could either place a favicon at `/favicon.ico` or you could add:
```
<link rel="icon" href="/<bookstack_subpath>/favicon.ico" type="image/x-icon" />
```
to the `custom HTML head` setting in the admin area.

**Comment by TheKorbi** [comment]
Hi @ssddanbrown ,
that solved my problem thanks! Works like a charm.
