### ISSUE TITLE
Homepage Improvement Or Alternative Option

### ISSUE THREAD

**Issue by KTSCode** [BookStackApp/BookStack#126]
Right now, the homepage is not really useful for making pages easy to find. All The information on there is useful, but would be better on a "recent activity" page.

I would find it much more useful to have a standalone _page_ that is not part of a book or chapter called "homepage". When landing on the homepage _page_ the book/chapter nav that normally floats to the right of pages, could be replaced with recently viewed _pages_, and/or the books list.

**Comment by unixfox** [comment]
:+1:

**Comment by davidPilkington** [comment]
Perhaps even allowing users to set the homepage to books

**Comment by tmikaeld** [comment]
I was just about to make a new issue about this.

Either add the option to select the "start" page for roles - and add the option to hide recent activity, it's unnecessary for viewers to see and in many cases it is not desired.

**Comment by Ethanb00** [comment]
I kinda like the idea of Books being displayed using HTML cards (and Book color could/would be customizable). Clicking a book then lets you dive into the chapters and pages like it is now. Just a suggestion. I generally like the idea of improving the usefulness of the homepage.

**Comment by patoroco** [comment]
It will be really useful to have a by-user homepage.

Usually, my flow using bookstackapp is enter to homepage and use search, I don't use tree organization because I need to click on Books >Chapter...

Maybe a good "fav-pages" should be great, what do you think?

**Comment by ssddanbrown** [comment]
@patoroco Yeah, I've been playing with the idea of having 'Bookmarks' or 'Favorites' for a while. Something like that would be great on the homepage.

**Comment by lxtv** [comment]
Thanks for the reply on my other thread. Our Bookstack site has been been live for a couple weeks, and my users are really happy with it, especially in terms of speed (we came from a Wix site, dear lord) and ease of finding info. And the tweak I found for showing books on the home page works well, even though I know it will probably break on updates.

Now that we've had time to play around with it, I have a few more thoughts about some small customization options that would make a big difference for me and my team, and should be fairly easy to implement. I say easy, because I've already got a pretty good idea of how to hack the php files and alter the css, but I know I'm better off waiting for an official implementation.

- Home page layout options, as discussed in #345 . Maybe just as simple as showing/hiding css classes. For instance, I would like to have a list of books, and nothing else. The Recently Viewed and Popular are hilariously redundant because we only have 5 books!

- Ability to add a home page block consisting of user-defined links or text, like fav-pages suggested by patoroco above. I would love to have some quick links to our most important pages (not necessarily popular!) directly on the home page, as well as external links.

-  Ability to specify that one column have larger text than the other. For instance, the links on the Books page are all H4, even though the left column is the primary navigation.

- I would love the option of naming "Books" something else, like "Guides," at least in terms of the header on the books page.

Thanks for considering these suggestions.

**Comment by tmikaeld** [comment]
> I would love the option of naming "Books" something else, like "Guides," at least in terms of the header on the books page.

This is a great suggestion, in some cases Articles is more fitting, in other Docs or even Issues depending on the context. So a custom name for what to call the Items would be superb!

**Comment by Shackelford-Arden** [comment]
I'll just put a +1 to all of the above mentioned items haha

**Comment by ssddanbrown** [comment]
Currently working on a design update (#480) so now would be a good time to implement this.

@lxtv @tmikaeld The renaming of entities has been created as a separate issue under #406.

Here's what I'm proposing for this implementation:

### Current View

The current view would remain the default for new BookStack installs.
On the current view, 'Recently Created' would be removed and 'Recently updated pages' would be extended as they often heavily overlap in contents anyway.

### New Option

A **Instance** level option to specify a page to show on the homepage would be available to admins. This page will be shown in full on the homepage and the current homepage lists would move into a sidebar.

The set page would be an existing page within a normal book. This is because duplicating out the page creation/edit views, storage & logic for a one-off page would be a waste of effort.
Once set, This page would show on the homepage to all; even if permissions are set on the page or parent book.

With this setup you could create a book, named something like `System`, and store different homepages in there. You could set permissions on the book so only admins could view the contents. Then you could easily go into settings and switch homepages whenever you wanted.

### Why instance level?

Really it comes down to simplicity. In the use case of BookStack I think a lot of admins would want to ensure a consistent homepage for everyone for ease of support and (If custom pages have been set) to ensure everyone sees any information (News, updates) set on the homepage.

If we were to add a user-option then we'd likely end up with all the following options:
* Instance level default homepage option.
* User level homepage option.
* Instance level option to toggle whether users can set their own homepage.

Additional options and options that rely on other options do take a toll on implementation and maintenance effort so for now we'll keep things instance level. It could always be extended in the future if demand was high.

If users did want a custom homepage, They could achieve the same thing using a browser bookmark on any other page. 

---

This would also close #372.

I've assigned this to be part of the next feature release, [v0.18](https://github.com/BookStackApp/BookStack/milestone/11), so if anyone has feedback on the above then sooner is better.

**Comment by Ethanb00** [comment]
Thank you for the time and thought put into this. 

Personally speaking, I would prefer to not have to dedicate a book just to, essentially, config docs. That said if this is planned as an iterative step than I am all for it. 

My preference for constructing the homepage would be to set it on a dedicated page within the administrative settings menu.  As of now, I don't have a book for just BookStack information. 

However, like I said at the top, I am really glad to see some work being done on this front and I appreciate all the effort @ssddanbrown!! cheers!

**Comment by lxtv** [comment]
I like this solution @ssddanbrown. Simple but flexible.

**Comment by tmikaeld** [comment]
Seems like a simple, effective and flexible way to do it, I'm all in 👍 

Just like @Ethanb00  said, It's very fun to see someone put so much thought and care into it!

**Comment by ssddanbrown** [comment]
The above is now implemented in master so is therefore queued for the next release. 

[Preview of the implementation can be seen here](https://gfycat.com/WetOblongCamel).

**Comment by tmikaeld** [comment]
Love it, thank you!
