### ISSUE TITLE
 Switch language

### ISSUE THREAD

**Issue by Kazakhstanec94** [BookStackApp/BookStack#1285]
Good day guys.

On the test server, I deployed BookSTACK. After changing the language, the Shelves section and user role descriptions remain in English. Changed language to russian.
![image](https://user-images.githubusercontent.com/26080163/52992213-f7ff6180-3439-11e9-8cfd-6554c3215a68.png)

**Comment by ezzra** [comment]
Thats because there is still no russian translation for the shelf stuff. Because, when the first russian translation was made the shelf feature didn't exist, and now the system falls back to english for the missing translations. But if you want you can contribute the russian translations for shelves, just look up the parameters for shelves in https://github.com/BookStackApp/BookStack/tree/master/resources/lang/en and add them to https://github.com/BookStackApp/BookStack/tree/master/resources/lang/ru with new translations.

**Comment by ssddanbrown** [comment]
Thanks @ezzra for explaining this one. 

Generally translations upon EN, for newer features, will lag behind a bit since these are community-supported.
