### ISSUE TITLE
Feature Request: Private Shelves and Books

### ISSUE THREAD

**Issue by JtheBAB** [BookStackApp/BookStack#1286]
**Describe the feature you'd like**
It would be cool when a user can create private shelves and books.

**Describe the benefits this feature would bring to BookStack users**
At the moment every book is open and not every information want to be shared. You can create roles to change permissions but creating roles for just one user is a overkill. Allowing the user to create private shelves and books will help that the user can use bookstack as personal evernote replacement. 

Best regards

JtheBAB

**Comment by JtheBAB** [comment]
It looks like i can achive this when i create a role that allows access to own and not all shelves, books, ....

**Comment by ssddanbrown** [comment]
Thanks for opening this request @JtheBAB.

As you have found, the `*-own` permissions can help you here.

In the future, As part of the permission system review shown on the roadmap, I'd like change the permissions page of the items (books, shelves, chapters etc..) so you can add specific roles and users, instead of having to configure all roles, which should help further achieve what you want.

Since this issue is very similar to the existing #747 I'm going to close this to cut down on duplicate ideas.
