### ISSUE TITLE
Seperate Storage Types for Images and Attachments

### ISSUE THREAD

**Issue by Zeigren** [BookStackApp/BookStack#1302]
In setting up a secure Bookstack instance there's a bit of a wrinkle when it comes to secure images. Since secure images are only available with `STORAGE_TYPE=local_secure` you're stuck with hosting all attachments locally as well.

I don't know if it's possible to do secure images over S3 so the next best thing would be to have separate storage types.

arigathanks gozaimuch

**Comment by ssddanbrown** [comment]
Thanks @Zeigren for the suggestion. 

I think secure images over a network call (to S3) would cause trouble due to the rapid nature of image access when using the system.

Being able to define a separate storage system for attachments is a good idea though, and something I imagine would be useful to many others. 
Shouldn't be too hard to implement so have marked it for the next feature release. I'm going to update the issue title to focus on the separate storage types, Hope that's okay.

**Comment by ssddanbrown** [comment]
Moving this out by a feature release, Due to the current release already being overdue and large in scope. Next release cycle should be a fair bit quicker than the current though.

**Comment by ssddanbrown** [comment]
Now included in master to be in the next release.
Variables will be as per the below example .env snippet.

If you're changing an existing storage_type in use, you'll need to migrate your content first to the new storage system. The docs detail locations of files for various storage systems:
https://www.bookstackapp.com/docs/admin/upload-config/

https://github.com/BookStackApp/BookStack/blob/762d1d759590aa25466c3702279baff92c09e854/.env.example.complete#L98-L106

Thanks again for the feature request.
