### ISSUE TITLE
Bug: Add multiple (1+) attachments with drag and drop failse

### ISSUE THREAD

**Issue by JHenneberg** [BookStackApp/BookStack#1303]
**Describe the bug**
In addition to #591 if you add more then one attachment with drag and drop it is not possible.

**Steps To Reproduce**
1. add attachement one
2. drag and drop it to text
3. add attachment two
4. drag and not be able to drop

**Expected behavior**
Should work not matter how many attachments were added.

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): v0.25.0

**Comment by ssddanbrown** [comment]
Hi @JHenneberg,
Thank you for reporting this.

Unfortunately, This bug is reported against a non-supported feature (Dragging links into page content was never supposed to be a feature but just happens to be possible due to the nature of browser functionality). Therefore I'm going to close this to keep the issues here somewhat focused.

If #591 becomes implemented and you still experience this issue feel free to request this to be re-opened or create a new issue and we will address it.
