### ISSUE TITLE
Question: Wildcard support

### ISSUE THREAD

**Issue by Nebucatnetzer** [BookStackApp/BookStack#1311]
I'm using BookStack as my main landing point for 2li.ch and *.2li.ch
This means that when someone enters a subdomain which doesn't have a server behind it they redirected to my BookStack instance.
However when the URL is a subdomain it doesn't recognize that the use is logged in, is there a way to do this with BookStack so that it works with subdomains?

**Comment by ssddanbrown** [comment]
Hi @Nebucatnetzer,

Just as a foreword we don't really support multiple host domains being used for a single BookStack instance.

That said, you are probably getting this due to the session cookies being served per-domain.
You can try adding this to your `.env` file:
```
SESSION_DOMAIN=2li.ch
```

That way I think the cookies will be shared across 2li.ch and all subdomains.
Let me know if that works for you.

**Comment by Nebucatnetzer** [comment]
Works perfectly, exactly what I needed. Thank you for your help and the great work :)
