### ISSUE TITLE
The default language setting does not affect by the APP_LANG parameter

### ISSUE THREAD

**Issue by Nico207** [BookStackApp/BookStack#1316]
**Describe the bug**
When a user is created, the APP_LANG parameter is not use to set the default language.

**Steps To Reproduce**
1. In .env, set the APP_LANG to "fr"
2. Login with an admin user
3. Create un new user
4. Go into his profil (https://www.domain.example/settings/users/xxx)
5. The default language is set to "English"

**Expected behavior**
The default language must be the language define in the .env file

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): V0.25.1
 - PHP Version: PHP 7.2.15-0ubuntu0.18.04.1 (cli) (built: Feb 8 2019 14:54:22) ( NTS )
 - Hosting Method: Apache/2.4.29 (Ubuntu)

**Additional context**
> APP_LNG=fr
> APP_AUTO_LANG_PUBLIC=false

**Comment by ssddanbrown** [comment]
Thanks @Nico207 for reporting this.

Note, the new user will have a default language of the `APP_LANG` option, If they were to log-in after creation.

It's just the dropdown in the user view won't reflect this since the default is not correctly loaded at that stage.

Should be a simple fix so will add a patch for the next release.
