### ISSUE TITLE
Allow public viewing with hidden profiles

### ISSUE THREAD

**Issue by craftbyte** [BookStackApp/BookStack#1319]
**Describe the feature you'd like**
Allow public viewing of the wiki, but don't allow displaying metadata for pages (Author, revision, ...) as well as browsing users of a wiki.

**Describe the benefits this feature would bring to BookStack users**
This feature would allow IT departments and similar to publish documentation to the world, while preserving privacy of the members of the IT team.

**Comment by ssddanbrown** [comment]
Thanks for the suggestion @craftbyte.

I understand your use-case but I think this would take the permission system to a level of granularity that I'd prefer not to achieve. 

Instead this would probably be a use-case for the theming (View override) system. I'll leave this open as a reminder to circle back to this once the theming system is formalised. 

If you'd like I could give an overview of how you could achieve this now but it's a kind of at-your-own-risk kind of thing and will require some manual work as you journey through BookStack updates.

**Comment by ssddanbrown** [comment]
I'm going to go ahead and close this off since this could now be achieved via the [visual theme system](https://github.com/BookStackApp/BookStack/blob/development/dev/docs/visual-theme-system.md). 

[This would be the view to override](https://github.com/BookStackApp/BookStack/blob/development/resources/views/entities/meta.blade.php).
