### ISSUE TITLE
[UX] Enable Custom Permissions : checkbox should be mandatory to be able to change roles/actions sheet

### ISSUE THREAD

**Issue by tpoindessous** [BookStackApp/BookStack#1324]
Hi ! 

I made a shelve and I wanted to limit permission to a single role. So I checked the right boxes for this role. I saved my changes and still, users with this role couldn't see shelve. It takes me a long time to figure that I needed to check "Enable Custom Permissions"

**Describe the feature you'd like**
If "Enable Custom Permissions" is not checked, I can't check boxes in roles/actions sheet.
The documentation should also mention that.

**Describe the benefits this feature would bring to BookStack users**
It would be more explicit that this checkbox is mandatory for editing custom permissions.

Thanks !

**Comment by ssddanbrown** [comment]
Thanks for your feedback @tpoindessous.

This is somewhat intentional, To allow a user to easily toggle custom permissions on an entity while still saving the role options in the event permissions are re-inforced.

That said, I do admit this is bad UX. 
A bigger revamp is due for the permission system later in the [road map](https://github.com/BookStackApp/BookStack#road-map). It will likely be at that point this will be improved upon.

**Comment by ssddanbrown** [comment]
Just came across this again, @timoschwarzer effectively covered this issue in the changes within #1505, Which hides the permission checkbox table unless custom permissions are active. This change was included in v0.27.

Therefore I'll close this off.
