### ISSUE TITLE
Authenticate as user from other system

### ISSUE THREAD

**Issue by stefnats** [BookStackApp/BookStack#1338]
Hi,

we have a customer login and we want to provide some help & documentation for that. However this should not be public, but we also don't want to share a private password.

Would it be possible to login as user from our original database?
Best case would be that the user wouldn't have to login a second time (login for bookstack)

Thanks!

**Comment by ssddanbrown** [comment]
Hi @stefnats,

Unfortunately, What you are asking is not currently possible, Assuming your other system is using it's own login system and not a standard, external authentication system such as LDAP.

If your system is using LDAP then both BookStack and your other system could connect to the same LDAP system.

Other than that, to be totally honest, I'm not going to be looking to add support for authenticating via other system's databases due to the variance and complications involved.

There are some plans for an API on the roadmap, At which it may be possible to custom-build a solution that connects to BookStack, but that would still need some custom external development.

**Comment by poVoq** [comment]
Is there any guidance on how to add a custom OIDC / Oauth2 provider though?
There are plenty already supported, see: https://www.bookstackapp.com/docs/admin/third-party-auth/

But I would like to add my own Nextcloud instance as the user backend since that is not possible, see for example: 
https://www.claudiuscoenen.de/2018/10/oauth2-with-nextcloud-provider-and-gitlab-client/

**Comment by ssddanbrown** [comment]
Hi @poVoq,
There is no current way to add a generic Oauth2 provider at the moment although this is something that could be good to support instead of adding built-in support for many others.
If this is something you'd like to see I'd advise creating a new issue, since the original issue here is for a bit of a different use case (Generic alternative database login).

Since it's been a small while since last response from the issue creator I'll close this.
