### ISSUE TITLE
Password protected shelf/book/chapter/page

### ISSUE THREAD

**Issue by caesartcs** [BookStackApp/BookStack#1340]
**Describe the feature you'd like**
Password protected Shelf/Book/Chapter/Page

**Describe the benefits this feature would bring to BookStack users**
This could add another layer of protection for passwords and/or other critical information regardless of set user roles/permissions. Sometimes its faster to enter a password if you know it then to provision permissions for a specific user.

**Additional context**
Although I think there might also have to be some back-end encryption for the password-protected Shelf/Book/Chapter/Page as it would be plain-text from a sql dump, but I am not 100% positive.

_However, good job +thank you. This is good stuff._

**Comment by ssddanbrown** [comment]
Thanks for the request @caesartcs.

This is very similar to #820 (Request to add encrypted pages).

I think encrypting a whole entity chain (Shelves > Books > Chapters > Pages) could just cause too many issues and technical implementation issues due to the sheer amount of elements of the UI and backend system this would affect.

Do you see the requirement, of being able to encrypt the items above pages, as an important part of your request?

**Comment by caesartcs** [comment]
I do **NOT** see the **items above Pages** as an important part of the request. But just Pages.

I believe that at the Shelf/Book/Chapter level, the permissions functionality should be enough to suffice for user segregation.

Would this request be feasible in regards to Pages only?

**Comment by ssddanbrown** [comment]
@caesartcs Thanks for the reply. 

Yes, pages only is feasible. 

In that case, to keep issues focused, I'll close this one since the core requested functionality is already open on #820. It's worth giving the first post on that issue a thumbs-up to show support.
