### ISSUE TITLE
[Feature request] Creation of additional bookcases

### ISSUE THREAD

**Issue by KroonIT** [BookStackApp/BookStack#1353]
**Describe the feature you'd like**
The ability to create multiple bookcases.

**Describe the benefits this feature would bring to BookStack users**
In this way there is a broader way of categorizing.

**Additional context**
Current situation:
Shelve -> Books -> Chapters -> Pages

Desired situation:
Bookcase -> Shelves -> Books -> Chapters -> Pages

**Comment by ssddanbrown** [comment]
Hi @KroonIT,
Thanks for the suggestion.

To be totally honest with you, This is not something I'd want to implement. 
The content structure is pretty core to BookStack and I'm apprehensive to expand it even further since I feel complexity will start to heavily set in. I'd much rather focus on improving the items in the existing structure. 

However many levels we add, There will always be a demand for an extra level.
We have been through this in #95 if you want more context.

**Comment by KroonIT** [comment]
@ssddanbrown 
That's right, I'll figure out a structure to make it work for us.
Thanks for taking the time to reply.

Keep up the awesome work!
