### ISSUE TITLE
Support page-level comment permissions

### ISSUE THREAD

**Issue by akurzawa** [BookStackApp/BookStack#1361]
hi

two question:

1) how to allow user to comment page but without whole page edit permisions?

2) how to allow user to edit / delete own comments?

**Comment by ssddanbrown** [comment]
Hi @akurzawa,
Have you tried using the available role-level permissions for your requirements?:

![image](https://user-images.githubusercontent.com/8343178/55405639-6dd70c80-5552-11e9-9f4d-bd30d4db4ff0.png)

**Comment by akurzawa** [comment]
Well later yes, it works - GLOBALLY, but now I'm trying to disable comments in one page - any idea how to do that?

**Comment by ssddanbrown** [comment]
@akurzawa Sorry for my late response. Currently there is no way to do this. I'll update the title of this issue to focus on that request to see if this is a feature that others would be interested in.

**Comment by akurzawa** [comment]
any changes in this matter?

**Comment by ssddanbrown** [comment]
I'm going to close this off since there's been little additional request for comment permissions, and I'd prefer not to add further complexity with more fine-grained comment permissions where possible.

On recent releases, you could visually hide the comments at a per-page level (For all users) by using tags and some custom CSS. I can provide an example, and further details, of this upon request if desired.
