### ISSUE TITLE
paste tables into editor

### ISSUE THREAD

**Issue by ezzra** [BookStackApp/BookStack#1367]
It looks like it is currently not possible to paste tables to the editor (from html or excel for example). It would be a great benefit to make that possible if your work process relies on tables. 

Because there currently is no sort function for example, it could be done external and pasted back to the wiki.

**Comment by ssddanbrown** [comment]
Hi @ezzra, Could you confirm which editor you are using in this scenario.

There is a known issue with pasting table content (#987) which will be fixed in the next patch release. From my testing during development this will enable the pasting from a spreadsheet into the WYSIWYG editor as a table. The content will appear as text in the markdown editor.

**Comment by ssddanbrown** [comment]
Since there's been no follow-up I'm going to close this. If the issue remains and is something you still require to be fixed please open a new issue, referencing this one.
