### ISSUE TITLE
Activity time wrong calculated?

### ISSUE THREAD

**Issue by JtheBAB** [BookStackApp/BookStack#1397]
**Describe the bug**
The time in the revision or activity tab is not correctly calculated.

**Steps To Reproduce**
1. Login into bookstack
2. Check the "Recent Activity"
3. See that for example 1 day ago is actually 2 days ago

**Expected behavior**
The time should be correctly calculated

**Screenshots**
![image](https://user-images.githubusercontent.com/42135332/56286575-5b480000-611a-11e9-8c1c-df68b3d50ad5.png)

For me it should be 2 days ago.

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): v0.25.5 
 - PHP Version: 7.3
 - Hosting Method (Nginx/Apache/Docker): Apache

**Additional context**

**Comment by ssddanbrown** [comment]
Hi @JtheBAB,
Relative times will generally be rounded to some level. Depending on your timezone, it may have not yet been two days (In terms of 24 hours periods) since the revision date. If you check if a few hours after 2PM in your timezone I'd expect it to say 2 days ago, Let me know if it does not.

**Comment by JtheBAB** [comment]
You’re right. Now it say‘s 2 days ago. Somehow just strange that it is not that accurate as it is (maybe) expected.

**Comment by JtheBAB** [comment]
Ok. Thanks
