### ISSUE TITLE
Book navigation visual redesign

### ISSUE THREAD

**Issue by jorgedeloera** [BookStackApp/BookStack#1406]
### **Visual design improvements in the components of book navigation**
The visual improvements allow a more focused design in reading the book.

![Page view](https://user-images.githubusercontent.com/18191486/56700573-a6d14f80-66c0-11e9-949b-e17aa826b455.png)

**Considerations:**
- Sidebar
- Subheader

**Sidebar**

The redesign allows to sidebar get the focus it on the navigation, the book navigation and page navigation in the same component, and the details can be move to subheader 👇.

![aside](https://user-images.githubusercontent.com/18191486/56700938-62df4a00-66c2-11e9-98cf-593092e505f3.png)

**Subheader**

Allows to sidebar get more space. The color and background of subheader improve the first view of user on the page content.

![subheader](https://user-images.githubusercontent.com/18191486/56700908-3e836d80-66c2-11e9-9b01-57c0ba68157c.png)

**Comment by ssddanbrown** [comment]
Hi @jorgedeloera,
Thanks for providing some design ideas. 

### Feedback

I understand that you want to put more focus on the book navigation, but to do these changes you've sacrificed quite a lot of elements to get there. Details such as revision count, creation info & permissions have been removed and the ability to export option is an extra click away. Space would also be needed for attachments and tags.

The combined page and book navigation is a good idea but without headings it is somewhat more abstract and could confuse new users. Also, I'm not sure it scales to larger books since the current page could be 15 chapters down, The page nav could easily end up below the fold. 

### Upcoming Update

For reference, here's pretty much the same content as part of the upcoming design update:

![bookstack local_books_all-about-bookstack_page_bookstack-general-usage-copy-92c](https://user-images.githubusercontent.com/8343178/56850736-49c2dd00-68fe-11e9-946b-7e5c4134dd25.png)

**Comment by tylerlucas** [comment]
Just want to chime in and say that the redesign looks really good. When will that update go live?

**Comment by ssddanbrown** [comment]
@tylerlucas The one in my comment above? Is due to go live with the next release. Was hoping to get it released on Easter Weekend but went down a rabbit hole of improving how images are handled which has now delayed things a fair bit. I'm aiming for next weekend as long as no other hurdles arise. More info on the redesign can be found in #1153.

**Comment by ssddanbrown** [comment]
I'll close this now, since there has been no further discussion.

Something mildly interesting, I noticed the proposed design has quite a few similarities to one of the early BookStack design revisions:

![BookStack old design](https://www.bookstackapp.com/images/2016/07/feature-dump-page.png)
