### ISSUE TITLE
BookStack Discord Trial

### ISSUE THREAD

**Issue by TimmKroe** [BookStackApp/BookStack#1442]
## Discord Server Link

https://discord.gg/AxDeaYE

## Original Issue

**Describe the feature you'd like**
Just like many other Open Source projects it would be nice to have a central place where all contributors can meet to talk and discuss topics related to Bookstack.
The community could help new members with configuration mistakes or new contributors can ask simple questions directly without creating an issue on Github

**Describe the benefits this feature would bring to BookStack users**
* better Community Support
* improved way to communicate

**Comment by TimmKroe** [comment]
I created a [Server](https://discord.gg/AxDeaYE). I will transfer the ownership to @ssddanbrown as soon as he joins the server so he can manage it.

**Comment by ssddanbrown** [comment]
Liking the eagerness @TimmKroe. Not so sure on having an "Official" instant chat place myself though. I'll dump my thoughts:

## Pros

* Will offer faster communication, when needed.
* Offers a non issue-focused placed for people to talk about the project which could lead to more positive conversations about BookStack rather than just its flaws.
* Provides a lower barrier for people to ask questions or talk about the project, whereas GitHub may feel a bit intimidating to some, especially people that are less developer-focused.
* _Could possibly reduce issues raised here on GitHub, keeping things here a little more focused_.

## Cons

* Is another community to moderate and support which could take a lot of time by itself.
* The lower barrier to message, and the nature of instant messaging, may lead to many comments that are less detailed, welcoming or as thoughtful as they need to be, mine included. 
* The ease of instant conversation may entice people to jump straight in and start asking questions rather than searching for previous similar issues potentially leading to more duplication and busier issue management.
* I'm personally pretty useless socially and tend to shy away from instant messaging. I'd be worried that I'd come across somewhat negative whereas on here the comments box and non-instant nature force me to think things through a bit and review how my comments could be perceived. 

---

Will have a think, Could give it a try I guess, Never really used discord before, could have a look if there's anything to guide people to search existing issues here first before asking, to reduce the effect of some of the cons.

**Comment by HurchelYoung** [comment]
Go for it ssddanbrown.  I completely agree with your pros and cons, and I also think the last pro (_Could possibly reduce issues raised here on GitHub, keeping things here a little more focused_) is well worth the effort.  I've seen discord used in a few other development communities and most of the time there is not a lot of activity, however when a conversation is needed it really makes a difference. imho

**Comment by DirtyCajunRice** [comment]
Community support/help is a huge deal. Of the many communities I am a member and/or moderator of for github projects, almost all of them have MANY helpful people who share in information they have learned from their issues reducing the amount of support you personally would need to answer

+1 from me

**Comment by TimmKroe** [comment]
@DirtyCajunRice Oh sorry I didn't notice; I will update the link in a second!

**Comment by ssddanbrown** [comment]
Issue title updated and issue pinned for visibility to see how it goes. 
If I'm happy with how things are going after a couple of months I'll update the readme with a prominent link and close this off. 

Thanks for setting this up @TimmKroe

**Comment by TimmKroe** [comment]
@ssddanbrown could we integrate Github into the Discord a bit more? How about Webhooks for releases and issues?

**Comment by henri9813** [comment]
Why not slack ?, it's the most used in opensource project ?

**Comment by ssddanbrown** [comment]
@henri9813 Because discord was proposed first tbh. 

Also, some of the popular core technologies BookStack uses (Laravel, Vue) also use discord as their primary chat solution so discord as a choice is not exactly wild. Plus, it seems like a decent app; can't really think of any functional reasons to use slack over discord for a public project like this.

**Comment by ssddanbrown** [comment]
Okay, I think the discord has worked out well so far. It has been nice to have an area for less formal interaction. So might as-well close this off.

I've added extra links into the project readme and added links in the header & footer of the official site. Thanks again @TimmKroe for getting this started and thanks everyone else for the insight and encouragement.
