### ISSUE TITLE
Export markdown always to files

### ISSUE THREAD

**Issue by IJustDev** [BookStackApp/BookStack#1453]
**Describe the feature you'd like**
I want all markdown files automatically exported as markdown file into a certain folder in order to keep them tracked as a git repository.

**Describe the benefits this feature would bring to BookStack users**
Changes without UI will be possible and a opportunity for treating the each book pages as markdown files.

**Comment by ssddanbrown** [comment]
Hi @IJustDev,
Thank you for your request.

For the benefit you have described (_"Changes without UI will be possible"_) we'd need to got to much greater lengths than simply auto-exporting markdown. We'd have to auto-export then auto-detect changes then load any updated content back in which would require a considerable amount of effort and future maintenance.

This is quite a use-case specific feature that I'd prefer not to support in the core platform. Upcoming on the road-map is a REST API. Once this is implemented It would be viable for someone to create a cli app to auto-export/import markdown for tracking/editing in an external source.

Due to the above, and due to existing similar discussions in #776, I'm going to close this to keep issues focused.

**Comment by IJustDev** [comment]
You're right. And what if there is a function for exporting only one file as markdown. I find out that the markdown text is saved in mysql as a specific row. I think it would be a huge benefit if each file could be exported not as html or pdf but as markdown. This will result in a generalized way for backups and a much simpler opportunity for migrating bookstack pages into another system.

**Comment by ssddanbrown** [comment]
>  I think it would be a huge benefit if each file could be exported not as html or pdf but as markdown. 

Feel free to open that as a new issue request if you think it'd benefit. That said, in the migration scenario described you'd probably be much better off just grabbing the markdown content via a DB query rather than manually exporting each page.

**Comment by DanCInOz** [comment]
> You're right. And what if there is a function for exporting only one file as markdown. I find out that the markdown text is saved in mysql as a specific row. I think it would be a huge benefit if each file could be exported not as html or pdf but as markdown. This will result in a generalized way for backups and a much simpler opportunity for migrating bookstack pages into another system.

I'm also interested in working with Markdown.    My bookstap has different types of users.  Ones that are familiar with markdown and others that just want to use the (excellent!) wysiwyg editor.

I'd also like to be able to bulk - import existing documentation (md formatted) into bookstack.

I'll check where the API is up to.
