### ISSUE TITLE
Attachment as link improvment

### ISSUE THREAD

**Issue by JtheBAB** [BookStackApp/BookStack#1460]
**Describe the feature you'd like**
Please add a possibility to create a link within a page that open directly the attachment.

**Describe the benefits this feature would bring to BookStack users**
Adding attachments to the page is create. But sometimes you want to give more context to it. With a link in the text the user can get the correct attachment during they read the text.

**Additional context**
It is already possible to to this:
![suggestion](https://user-images.githubusercontent.com/42135332/58250301-6289ab80-7d61-11e9-8944-c8923ee49748.gif)

Perhaps it is possible that it creates during this process also the link?

**Comment by ssddanbrown** [comment]
Thanks for the suggestion @JtheBAB.

Somewhat related to #591.

**Comment by XVilka** [comment]
Is there any progress towards solution?

**Comment by andre-lx** [comment]
In my opinion, I think that can be better to add a new icon (next to the pencil) to download the file and when you click the link (currently this downloads the file) , creates a link in the text like:

**Comment by gurpal2000** [comment]
That drag drop doesn't work for me. It gives a "no entry/exit" sign.

**Comment by ziermmar** [comment]
+1 from me for this feature. Is there some progress already? Will this be implemented?

**Comment by ssddanbrown** [comment]
Spent many hours on this for v0.30.0.

Initially tried to implement a drag+drop solution but I could not get a consistent result in all browsers due to the WYSIWYG editor's (TinyMCE) manual, complex handling of various drag+drop/mouse events.

Therefore I've added a button to the attachment cards which inserts a link, with the correct attachment name, into the editor (Both WYSIWYG and Markdown Editors) when clicked. 

I've left some of the drag+drop code in still which should still allow you to drag the attachment "card" into your content when using (Any editor in Firefox) or (Markdown editor in any browser).  

This will be part of the v0.30 release.
