### ISSUE TITLE
Update version != Install script version

### ISSUE THREAD

**Issue by battosai30** [BookStackApp/BookStack#1466]
**Describe the bug**
Update procedure descrived [here ](https://www.bookstackapp.com/docs/admin/updates/ )leads to v0.25.1 while new install from script leads to v0.26.1

**Steps To Reproduce**
One new server, just run the ubuntu install script
One "old" installation, upgrade using this [procedure](https://www.bookstackapp.com/docs/admin/updates/)

**Expected behavior**
It should leads to the same version (if v0.26.1 is the last, update may leads to v0.26.1 too, of if it's consider not stable, install script should leads to v0.25.1

**Your Configuration (please complete the following information):**
Both configuration :
 - PHP Version: 7.2.1 (old server) 7.2.17 (new server)
 - Hosting Method (Nginx/Apache/Docker):  Nginx reverse proxy (another server) + apache
- New server use Ubuntu 19.04, old 18.1

**Comment by ssddanbrown** [comment]
Hi @battosai30,

Both the update process and install script process pull from the same code location.

When you run the update command, do you get any visible errors in the command line output?

Otherwise, Can you post the output of running the command `git status` in the BookStack installation folder?

**Comment by battosai30** [comment]
Hum I don't know why, now update seems applied. Maybe a cache issue or something like that ... Sorry for the loss of time, I really love Bookstack :)
