### ISSUE TITLE
Presentation Mode

### ISSUE THREAD

**Issue by lucassmacedo** [BookStackApp/BookStack#1482]
Hello! we are using the bookstack in our company and one thing we miss, is the option to see the books in "mode of presentation", that it is possible to "hide" the scabs that are on the side of the book.
It is a suggestion that would make it easier to "read" in full mode

If has a option to "hide" sidebars, button like this.

**Comment by ssddanbrown** [comment]
Thanks for the request @lucassmacedo.

Is this different to #1291? From your request it sounds similar.

Otherwise, I'm not too sure what a "Presentation Mode" would fully entail. I can't see presentation usage of BookStack being a big enough use-case to justify the effort of adding and maintaining an additional UI mode throughout that application.

**Comment by lucassmacedo** [comment]
Sorry @ssddanbrown, #1291 it's perfect this solution.
