### ISSUE TITLE
XML Import

### ISSUE THREAD

**Issue by davidPilkington** [BookStackApp/BookStack#149]
Any thoughts on including an xml import tool? allowing users to import from other wiki's, evernote, phpdoc2 checkstyle, etc?

This would allow users to export from existing data sources into a new book. For example "my evernote book that was created because evernote started being d**k's" or "my book that was imported from a phpdoc xml because their ux is kinda crappy"

**Comment by nydeggerm** [comment]
It would be nice if it is possible to import from Confluence.

**Comment by leveled** [comment]
I posted a $25 bounty here. https://www.bountysource.com/issues/36011761-xml-import I'm sure others would love to be able to switch off Evernote, Confluence, etc.

**Comment by ssddanbrown** [comment]
Still not sure about bounties applied to bugs, having features dictated by money.

Just as an FYI, For anyone looking to get the bounty, It is at my complete discretion to accept or deny potential merge requests for any reasons. 

Overall, A general "XML import" feature may not be the best way to achieve this. I don't really know the various formats of other systems but it could be better to work on building an API which then people could script "importers" to.  In which case, the API is probably something I'd like to build myself (At least the base of it) at some point.

**Comment by ssddanbrown** [comment]
I'm going to close this issue off since I don't see it going anywhere due to being too abstract/general since there's no general standard XML format. There are some existing issues, such as #1049, for platform specific imports, but in general I'd leave this to be done by others outside of the core project using the API.

Thanks though @davidPilkington for the initial suggestion.
