### ISSUE TITLE
Cannot include code block in numbered list. Callout works a bit better.

### ISSUE THREAD

**Issue by MarsWarrior** [BookStackApp/BookStack#1533]
**Describe the bug**
It is about the numbered lists where I can not insert a code block style. The code block style is greyed out in a numbered list.

**Steps To Reproduce**
See first screenshot. I did copy that from the Docker website.
Bookstack does display this without any problems.
However if I try to reproduce this manually, it is NOT possible.
- Create numbered list
- shift enter
- try to insert a code block. Impossible. Greyed out in "Formats" menu, OR the code block takes the complete part of the numbered list as input, which is of course not the intention.

**Expected behavior**
I can insert a code block in a numbered/bulleted list.

**Screenshots**
![image](https://user-images.githubusercontent.com/1220775/61078292-978cb300-a420-11e9-8c5f-5c05eb2a451c.png)

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): 0.26.2
 - PHP Version: 7.3
 - Hosting Method (Nginx/Apache/Docker): Docker, linuxserver/bookstack image.

**Additional context**

**Comment by ssddanbrown** [comment]
Thanks for the clear description of this @MarsWarrior.

As it stands, Code blocks are block level elements which are currently not supported within list items due to the formatting and editor complexities it can introduce, but I can see why you may want this feature.

Since this has already been requested in #534 I'm going to close this off as a duplicate. Adding a :+1: to the original post there will help show support.
