### ISSUE TITLE
New Function Suggest: Bulk export

### ISSUE THREAD

**Issue by fanbin** [BookStackApp/BookStack#1543]
Very likely that user wishes to export one entire book at a time. Or even better, they can export the book with markdown format

**Comment by ssddanbrown** [comment]
Thanks for the request @fanbin.

Books currently support options for exporting.
Shelf exports have been requested in #1138.
System export is discussed in #43.

For anything further it's generally advised to await for the BookStack API, at which point any custom requirements can be scripted in an easier manner.

Due to the above open issues and thoughts, I'll close this off as a general duplicate.
