### ISSUE TITLE
Cloudron installation

### ISSUE THREAD

**Issue by gramakri** [BookStackApp/BookStack#1544]
**Describe the feature you'd like**
Create a BookStack Cloudron package that will allow it to be installed in 1-click

**Describe the benefits this feature would bring to BookStack users**
This app has been often requested by the Cloudron community - https://forum.cloudron.io/topic/1182/bookstack-knowledge-management-application

**Additional context**
Cloudron is a platform for installing and managing self-hosted apps like BookStack.

**Comment by gramakri** [comment]
Girish from Cloudron.io here. First off, thanks a lot for BookStack. We have seen BookStack requested a lot by our community. The initial package was contributed by one of our customers (msbt, not sure what his id is on GitHub). The source code of the package is at https://git.cloudron.io/cloudron/bookstack-app . We also have automated selenium tests (which is part of our auto-update mechanism to verify new updates) at https://git.cloudron.io/cloudron/bookstack-app/tree/master/test. I have also opened a PR to get Cloudron listed as an installation mechanism - https://github.com/BookStackApp/website/pull/45

I wasn't sure what the best way to talk to you guys was since I didn't see a forum, so I opened an issue.  Thanks again for BookStack.

**Comment by ssddanbrown** [comment]
Hi @gramakri,
Sorry for my very very late response.

Just had a play about with BookStack on your demo cauldron instance, Seems like a really cool system. Thank you and @msbt for adding support there.

I'll review the docs PR soon. Had a quick look. To be totally honest, I'm very wary about linking out to anything commercial, or even any "service providers" in general, within our official docs.  I'll have a think about how I want to position it. Will likely be a link listed under "Other hosting options" or something like that. 

Since you'be already created a package, and therefore addressed the topic of the issue, I'll close this off.

**Comment by gramakri** [comment]
@ssddanbrown Listing it under "Other hosting options" is totally fine by me. I can edit the PR accordingly.
