### ISSUE TITLE
Feature Request: Permanent link

### ISSUE THREAD

**Issue by vladaman** [BookStackApp/BookStack#1551]
We'd welcome to create permanent link for a page. Internally the pages would also be linked with this permanent link/shortcut.
Current issue is that if we change title of the page, all other links become broken. Also external links would not work obviously.

**Comment by ssddanbrown** [comment]
Thanks for the request @vladaman.
Since there are various open issues regarding linking (#441, #288, #732) I'm going to close this off as a duplicate.

Couple of notes though:

When you select some text of a section BookStack should show a popup which allows you to copy a permalink to that page, specifically that block of content:

![image](https://user-images.githubusercontent.com/8343178/62413657-5e9fc280-b609-11e9-845d-085ea74cf852.png)

This link is ID-based instead of slug-based.

---


> Current issue is that if we change title of the page, all other links become broken.

BookStack does do some level of resolving here. If a page is not found the revisions will be checked for an older page using that URL and, if found, the user will be redirect to the new version of the page. There are some circumstances that cause this to fail though.
