### ISSUE TITLE
Feature Request: Custom Metadata for Pages

### ISSUE THREAD

**Issue by vladaman** [BookStackApp/BookStack#1552]
Since many of us use BookStack for documentation **it would nice to have additional metadata which can be associated with single page**.

One of the ideas I have is to take advantage of rise of chatbots which could later easily integrate to answer questions. Imagine I would be able to add additional "questions" to a page, which would be used by Chatbot to easily find content and answer user's questions.

Proposed flow:
1. Assume I have a page called "Language Settings" in which I describe how to change language of an application
2. I click on edit and I want to add page "_meta data_"
3. Pick arbitrary meta key (in my case "Question")
4. Enter value (in an example "How can I change my language?")
5. I can enter multiple Questions

Then I can have a bot integrating BookStack, reading the articles & Questions metadata and build more powerful bot/search engine.

However my proposal is to **make this generic**, so other users can utilize this and go beyond tags. I just propose to have key-value option for each article I could take advantage of.

**Comment by ssddanbrown** [comment]
Thanks for the request @vladaman.

I'm hesitant to consider adding another key => value system, upon tags, unless there is clear widespread benefit.

Once we have the API done, It'll be interesting to see if some sort of metadata becomes requested. Perhaps we could instead look to extend the tagging system for this, So tags with a certain name prefix are hidden in the UI. Name kind of works since you'd still be 'tagging' the content with metadata, Just not as a visible tag.

**Comment by bridgeyuwa** [comment]
lack of Metadata to me has greatly handicapped bookstack when it comes to SEO.  

Not everyone uses bookstack privately.

**Comment by ssddanbrown** [comment]
I'm going to now close this off since there's been no further request or discussion for such system. Happy to still consider it though as previously proposed if there's still desire but, as per the above, I don't think this'll be worth creating whole new systems form.

@bridgeyuwa As far as I can tell, this request is not specifically in relation to meta tags or opengraph data or anything similar. This does not directly impact SEO.
