### ISSUE TITLE
Search Bar on Mobile Page

### ISSUE THREAD

**Issue by dannyhanes** [BookStackApp/BookStack#1563]
**Describe the feature you'd like**
When browsing on mobile, I would like to see a search bar on the page itself. It would be nice if this could be a toggle option in the settings. 

**Describe the benefits this feature would bring to BookStack users**
Bookstack is a Wiki platform and the first thing people want to do when arriving at a Wiki, is perform a search. Getting to a search box should't require extra clicks, like through the 3 dot menu

**Comment by ssddanbrown** [comment]
Thanks for the request, but I'm going to close this off since it's had no further demand since opening.
If needed, it would be possible to add and always-visible search bar via the [visual theme system](https://github.com/BookStackApp/BookStack/blob/development/dev/docs/visual-theme-system.md) with a little hacking.

**Comment by kruecab** [comment]
Just came to ask for the same thing. Thanks for the tip on the visual themes @ssddanbrown - I’ll check that out. But I do think it’s something people would like, as I’ve been wanting it for some time and only now thought to search GitHub for it. :)
