### ISSUE TITLE
Tag based automatic organization

### ISSUE THREAD

**Issue by mainmachine** [BookStackApp/BookStack#1578]
It might be useful to use tagging to automatically assemble books, shelves or pages. For example, we have two shelves, "Stuff" and "Things". Create a new book, tag it with "Stuff", "Things" and "Flotsam". On save, the new book is automatically added to the both "Stuff" and "Things" shelves, and if a new shelf named "Flotsam" is created, then it would be automatically added to that as well.

This would allow for some interesting automatic organization to occur.

**Comment by ssddanbrown** [comment]
Thanks for the request @mainmachine but I'm going to close this off since there's been little demand for such a feature since this original request.

If happy to hack, it technically would be possible to listen to update events [via the logical theme system](https://github.com/BookStackApp/BookStack/blob/development/dev/docs/logical-theme-system.md) then apply custom logical to apply your organization desires.
