### ISSUE TITLE
FTP upload

### ISSUE THREAD

**Issue by Ghost-chu** [BookStackApp/BookStack#1579]
**Describe the feature you'd like**
A clear description of the feature you'd like implemented in BookStack.
Let BookStack support FTP picture/files upload
**Describe the benefits this feature would bring to BookStack users**
Explain the measurable benefits this feature would achieve.
It's good for small storage machine, we can use our CDN and OSS.
**Additional context**
S3 is good but we hadn't it, we can storage files to CDN/OSS/NAS anywhere we want.

**Comment by ssddanbrown** [comment]
Thanks for the request @Ghost-chu.

Since there's been no real other desire for this feature, and since implementation would require support & maintenance into the future, I don't see this feature being worth implementing within the core project.

The paths for file uploads are specified in our documentation here:
https://www.bookstackapp.com/docs/admin/upload-config/
There may be a way you could achieve this via alternative means using the existing folder locations. (For example, mounting your FTP storage, at a system-level, to these locations; Or mounting then using symlinks to these paths).
