### ISSUE TITLE
Hide Export - not working public

### ISSUE THREAD

**Issue by JtheBAB** [BookStackApp/BookStack#1582]
**Describe the bug**
I added the custom header as suggested [here](https://github.com/BookStackApp/BookStack/issues/1251#issuecomment-510182242).

When i am logged in i can't see the export button. 
When i am not logged in and access a public book the export button is visible.

**Steps To Reproduce**
1. Activate public access
2. Add the custom header from [here](https://github.com/BookStackApp/BookStack/issues/1251#issuecomment-510182242)
3. Go to a page with public access
4. You see the export button
5. Login with a user
6. Export button is hidden

**Expected behavior**
Export button is always hidden.

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): 0.26.4
 - PHP Version: 7.3
 - Hosting Method (Nginx/Apache/Docker): apache

**Comment by ssddanbrown** [comment]
Hi @JtheBAB,

You could use this style rule instead:

```html
<style>
.tri-layout-right-contents a[href$="/delete"] + hr, .tri-layout-right-contents .actions hr + .dropdown-container {display: none;}
</style>
```

Will cause an empty "Actions" list to be left for public viewers. Can't currently think of a way to remove that with only CSS as it stands. 

I'll close this since the above has been provided and since this is technically not a supported feature.
