### ISSUE TITLE
Generalize Image browser to support any kind of binary files.

### ISSUE THREAD

**Issue by raisoftware** [BookStackApp/BookStack#159]
Desired Feature:
Users should be able to attach generic files (like PDFs or UMLs), not just images. If the file is not an image an automatic icon specific to the file type should be attached.

Expected Behavior:
Be able to upload PDFs

Actual Behavior:
Only images can be uploaded and linked.

**Comment by ssddanbrown** [comment]
Hi @raisoftware, Apologies for my 8 month late reply 😨 . I think i'd like to keep images and files separate. Images are part of the content of pages whereas files are secondary references. I ideally want to keep that distinction.

As of the November update, v0.13, files can be attached via page attachments anyway which covers a large part of this issue.

Feel free to reply if you disagree with the above otherwise I'll close this issue.
