### ISSUE TITLE
Notification overlaps save button

### ISSUE THREAD

**Issue by tiger5226** [BookStackApp/BookStack#1591]
Wonderful app! I love it. Since I see UI/UX is a driving force behind the project, might I suggest that we change the notification placement or some other solution where it does not overlap with the save button when editing a page?

**Comment by ssddanbrown** [comment]
Thanks for the suggestion.

Since it doesn't seem that many others have found this to be a particular annoyance in the last few years I'm going to close this off. Moving the notification may make it easier to miss, and there's always a risk of overlapping something. Notifications will auto-hide anyway unless deemed important to be read, in which case a simple press will dismiss it.
