### ISSUE TITLE
Support IE Again

### ISSUE THREAD

**Issue by jesseg34** [BookStackApp/BookStack#1592]
I would love to use this app however my company still has IE as the default browsers and isn't looking to change that because so many of our vendor tools require IE. I may be a one of the few still in this situation but would you ever consider supporting IE again?

**Comment by ssddanbrown** [comment]
@jesseg34 Probably would never support IE again I'm afraid. It just makes development so much nicer not having to consider IE, since all remaining browsers are continuously updated and much more aligned in terms of feature support. 

How long is your company planning to stay on IE? I'd imagine more and more of the web will start to break on IE. I'm surprised your company doesn't have IE for legacy apps but allow a modern browser for the web and newer apps.

**Comment by ssddanbrown** [comment]
Since there's been no follow-up I'm going to close this. I've recently shared my thoughts on IE support on another issue here: https://github.com/BookStackApp/BookStack/issues/1656#issuecomment-743790554
