### ISSUE TITLE
Make Book render a github Markdown File

### ISSUE THREAD

**Issue by ghost** [BookStackApp/BookStack#1593]
At first, I like to thank you for the awesome Work you are doing with Bookstack! I Am just migrating from Mediawiki and so far I love it! There's just one thing I wonder. I didn't find an Issue or wiki Article related to this question, so I am creating this Issue now:

There are tons of already existing  wikis hosted on Github. These Wikis use already Markdown, which Bookstack already supports. Is it possible to include a README.md from a Github page to render in my Bookstack instance as it own book?

I Don't know if this is Already possible. Maybe it would be a good idea to include this in the Wikipage for Markdown, if this feature is already existing.

EDIT: I know I could just copy the Markdown file, but then it wouldn't get updated if the Author changes something.

       - Thanks

**Comment by ssddanbrown** [comment]
Hi @chrissly90,

Thank you for your suggestion and kind feedback. Unfortunately I don't see live rendering of content from other systems being something we'd look to support as part of the core project.

Once we get the API implemented then it could then be not to difficult too script this kind of process  otherwise copy & paste is the only official means of including that content.

**Comment by chrissly90** [comment]
@ssddanbrown  Thank you for clarification

**Comment by ssddanbrown** [comment]
Closing this since the API has now been implemented, the original issue creator has been deleted and since there's noone else watching this.
