### ISSUE TITLE
Restrict PDF export to certain user groups. 

### ISSUE THREAD

**Issue by over-soul** [BookStackApp/BookStack#1605]
**Describe the feature you'd like**
Ability to restrict PDF export feature to certain user groups as it is resource intensive. 

**Describe the benefits this feature would bring to BookStack users**
Would allow for better control of resources and also would enable better control of content export as not everyone should necessarily be able to export content. 

**Additional context**
N/A

**Comment by ssddanbrown** [comment]
Thanks for the request @over-soul.

The issue #1251 is open to discuss the idea of export permissions. I don't think I'd look to add UI options or controls to hide specific export options at this time since that's getting rather granular.

If you did want to simply hide the PDF export option you could add the following to the "Custom Head HTML" setting although I understand this would not achieve the role-level visibility you desire:

```html
<style>
	.dropdown-container a[href$="/export/pdf"] {
		display: none;
	}
</style>
```
