### ISSUE TITLE
Password manager / Encrypted notes

### ISSUE THREAD

**Issue by rootella** [BookStackApp/BookStack#1611]
Hi, since I use bookstack for **IT Documentation** (and it works great!), I would like to have an encrypted/secured password manager integration  for store clients credentials

This addidtion can be very usefull for people like me (tech, sysadmins, etc) or anyone needs a more secure type of note storage into the app

If this can help, here you can find some other projects: https://github.com/Kickball/awesome-selfhosted#password-managers

Thank you

**Comment by ssddanbrown** [comment]
Hi @rootella,
Thank you for your request. 

I think password manager integration with BookStack would be a little too far out of scope for the platform while being technically complex since there are various different password managers out there, each with different levels of available extendability, and there'd be a large underlying security concern. 

Encrypted content is something that fits well with such a platform as BookStack and there's already an existing issue open under #820.

Due to the above I'll close this off.
