### ISSUE TITLE
support LNMP

### ISSUE THREAD

**Issue by emperinter** [BookStackApp/BookStack#1614]
# Could this support LNMP or has some tips to do that?

**Comment by ssddanbrown** [comment]
When you say LNMP do you mean Linux+Nginx+MySQL+PHP or does LNMP mean something else?

**Comment by emperinter** [comment]
almost,LAMP is ok too.I have set up a WordPress website which use this.It's very easy to set up a website when we have a **install.php** file after we install **LAMP or LNMP **.Simply say is that It's not easy to most of people to deal with a lot of technology when we using it.

the installer script is [LNMP.org](https://lnmp.org/)

I really love BookStack when I first see it.But I try a lot of ways on my own server(ubuntu),It's not work .At the same time,I need to consider my WordPress blog  which using Linux+Apache+MySQL+PHP.

**Comment by ssddanbrown** [comment]
I'm afraid we can't really support compatibility with every other setup or installer script out there, We don't really have the resources. BookStack should run on the core components that the script may install, but it may just require some system configuration to get things working.

There's a few scripts and config pieces in [the dev repo](https://github.com/BookStackApp/devops) that may help. 

We are looking to improve the install process to make it easier but this will not be a focus until later in the roadmap. If you are having specific issues feel free to open new issues here so we can help support but we'd need to know what components you've installed, Otherwise I'll close this for now.
