### ISSUE TITLE
Problem with paste images

### ISSUE THREAD

**Issue by przemkiemzwany** [BookStackApp/BookStack#1638]
When I copy article from Confluence, text and images are pasted properly - I see all in page - but if I open my site on other browser I can see a images (only text)
Is it a bug? Must I upload images?

**Comment by over-soul** [comment]
Upgrade to the latest version.

**Comment by ssddanbrown** [comment]
@przemkiemzwany  As said above, Upgrading to the latest version of BookStack may help since there was recently a bug that causes the paste-to-upload functionality to break.

If you're trying to copy+paste multiple images at a time, Then you're likely running into the limitation discussed here: #449 (We can't yet see a sustainable way to support multi-image paste)

**Comment by ssddanbrown** [comment]
Since the last comment on this issue is relatively old I'm going to close this. If the issue remains and is something you still require to be fixed please open a new issue, referencing this one.
