### ISSUE TITLE
Would like to Request CAS Authentication

### ISSUE THREAD

**Issue by jblankenship30** [BookStackApp/BookStack#1640]
Would like to request CAS as an SSO Authentication option for Bookstack.
Higher Education primarily uses CAS or Shibboleth for SSO Authentication.

Your product is an awesome tool!

**Comment by ssddanbrown** [comment]
Thanks for your request @jblankenship30, and apologies for my late response.

To be totally open, I would really prefer not to extend to extra auth protocols unless found critical by a large group of users, which CAS really is not since this is the only request so far.

Since you opened this issue we have added SAML2 in a recent release:
* [Blog Post](https://www.bookstackapp.com/blog/beta-release-v0-28-0/#saml2-authentication)
* [Docs Page](https://www.bookstackapp.com/docs/admin/saml2-auth/)

I see a lot of CAS-Support auth systems support SAML2, as does modern versions of Shibboleth. Does that suit your need?

**Comment by jblankenship30** [comment]
Yes, now that bookstack supports SAML2, my needs are met.
Thanks for a great product!


[https://banapp.tulsacc.edu/i/tccemailsig2.jpg]<https://www.tulsacc.edu/>
Jason Blankenship
Lead Oracle Database Administrator, Tulsa Community College
{o} 918-595-7052 | {c} 918-720-2253 | {w} www.tulsacc.edu
{a} 909 South Boston Ave | Tulsa, OK 74119

**Comment by ssddanbrown** [comment]
@jblankenship30 Great & Thanks! I'll therefore close this off since SAML2 covers your requirement.

Note: I Updated your comment and deleted the original revision, to prevent your email address being visible on a public web-page. Looks like the GitHub email-reply system (And included office365 safelinks) can leak a person's email address pretty easily.

**Comment by jblankenship30** [comment]
Thanks!
