### ISSUE TITLE
BookStack Community Forum?

### ISSUE THREAD

**Issue by Wookbert** [BookStackApp/BookStack#1653]
Not exactly a feature request, but more a general request: Could you set up a forum/message board, where BookStack users can ask questions, help each other and discuss?

(For instance I'm just asking myself if there is a way to link a BookStack page in a text link on another BookStack page using the page ID, so the link doesn't break if the page title gets changed. Can't figure out how to accomplish that, not documented. Saw [this one](https://www.bookstackapp.com/docs/user/reusing-page-content/), but that’s for reusing the content, not the link to the content.

Edit: Just figured out that an internal page link somehow is always memorized under its URL in the moment when linked, regardless of a later page title change and thus URL change).

**Comment by ssddanbrown** [comment]
Hi @Wookbert,
I'd rather not have an additional source of discussion via a forum since it gets hard to keep on top of these things.

The best alternative for open discussion would be the discord chat, [Details here](https://github.com/BookStackApp/BookStack/issues/1442).

As you found, BookStack will attempt to resolve old URLs if a page has been renamed. There is some cases where this can fail so it's not 100%. It is possible to get a id-based link to a page via the popover that shows when you select some text:

![image](https://user-images.githubusercontent.com/8343178/64764975-2b6f1e00-d53b-11e9-90b2-6004c3461a9b.png)

This specifically references the selected section but you can just remove the hash, and all content afterwards, from the link to only reference the page.

**Comment by ssddanbrown** [comment]
I'll go ahead and close this since the core question has been answered and there has been no further discussion.

**Comment by theAkito** [comment]
@ssddanbrown 

So there's no plans or at least the possibility for an actual forum? Discord is quite a horrible application, which I won't use, at all.
Pretty much every other open source project has a Discourse forum and maybe additionally a Discord or IRC or anything similar. Relying only on something like Discord sounds like a really bad idea not only because the platform itself is really bad but also because this type of community exchange and communication is far less result-oriented than an actual forum where you can actually find what someone has written a couple of months ago instead of getting lost in the history of inifinite chat... So it would pretty much save time in the long run to have an actual forum rather than having a chatting platform that, as already mentioned, is atrocious in the first place, because you don't have to repeat the same stuff over and over again. With a forum, you can easily find old conversations about a topic and save the time of both community members seeking help and members providing help. (That is just one of the biggest factors, there are many other reasons I can't go into detail about.)

**Comment by Wookbert** [comment]
@theAkito 

I assume that time/human resources is the biggest problem here. Setting up a forum is one thing, moderating it another. We need people here who are willing to come forward and spent time and energy on this. Unfortunately I'm already loaded with work.

**Comment by ssddanbrown** [comment]
Yeah, @Wookbert is spot on here.

We already have the GitHub issues, the discord chat and a semi-official subreddit. 
Discord acts as the informal, temporary discussion solution. The GitHub issue list is the more permanent, formal discussion solution. It'll be too much work at this time to monitor and maintain yet another community option. 

GitHub are exploring the concept of discussions, I may look to enable that when available but the differences between that and issues would need to be clear, which I think will be tricky.
