### ISSUE TITLE
Bookstack and IE 11....

### ISSUE THREAD

**Issue by legallion** [BookStackApp/BookStack#1656]
**Describe the bug**
Bookstack Looks silly on IE 11

**Steps To Reproduce**
Navigate to your bookstack install using IE 11

**Expected behavior**
I wouldn't expect anything Less of IE..

**Screenshots**
![image](https://user-images.githubusercontent.com/44210944/64816622-05b33a80-d576-11e9-8216-e40023ba9cc1.png)

**Your Configuration (please complete the following information):**
 - BookStack v0.26.4
 - PHP Version: 7.1
 - IIS10 Baby!

**Additional context**
So yeah, What can I say... I understand Bookstack is not supported in IE 11. I'm not looking for anyone to really put forth much effort in coming up with a solution. Just putting some feelers out there to understand if anyone has already come up with a band-aid of any sort?

That being said, anyone know of an easy way to at least get the "columns" to display correctly in IE 11? Unfortunately our Core application provider does not support anything other than IE11, and I'm trying to make this as easy as possible for my end users to navigate.

If not, no worries, thanks all.

**Comment by c0shea** [comment]
@ssddanbrown I understand maintaining backward compatibility is tough, especially given how old IE is. However, a major use case for us is displaying pages in a read-only view in IE in a corporate application that is only supported in IE. All editing and maintenance is done through Chrome, but please don't break the ability to view pages in IE.

**Comment by Forn21** [comment]
I would echo @c0shea's point that I don't need any features but if the read view could just be passable, I would be happy.

**Comment by ssddanbrown** [comment]
At over a year on, I think I'll close this off. I don't see it being worthwhile supporting IE11 as it slowly walks out of relevance. If anyone wants to put together a bunch of css patches and share them here then great. Otherwise, I don't really want to go out my way spending my free time supporting the bad practices of enterprises that have a lot more resources than this little open source project. 

I'm genuinely sorry if you needed to support this case. Hopefully edge with its IE mode has helped things here.
