### ISSUE TITLE
Evolution : Color selector for table borders and cells

### ISSUE THREAD

**Issue by Zciwobukaj** [BookStackApp/BookStack#1670]
**How it is :** 
![image](https://user-images.githubusercontent.com/35924688/65132181-d2066380-da00-11e9-8b93-5a13b97089be.png)

**How it should be :** 
same interface with color picker

**Comment by ssddanbrown** [comment]
Thank you for your suggestion @Zciwobukaj but implementing and maintaining a color picker for specific table properties is the low level of detail that I'd like to avoid in this project, especially since the editors will be reconsidered later in the roadmap. Therefore closing this off as out-of-scope.

**Comment by Spacefish** [comment]
It´s easy to implement this, just add "colorpicker" to the list of tinymce plugins, when loading tinymce..
if you want to test this in your local installation:
edit `public/dist/app.js`  search for `plugins=`and add `colorpicker`to the list.
reload your bookstack with ctl + f5 such that the js get´s fetched again -> voila color picker added 👯 

just created a PR for it here: https://github.com/BookStackApp/BookStack/pull/3621
