### ISSUE TITLE
Cannot move code block in page editing / stuck in drag n' drop mode

### ISSUE THREAD

**Issue by jaylik** [BookStackApp/BookStack#1673]
**Describe the bug**
Cannot move code block in page editing / stuck in drag n' drop mode

**Steps To Reproduce**
1. Add code block
2. Save page
3. Edit page
4. Try to move code block >> stuck in drag n' drop

**Configuration:**
 - Exact BookStack Version v0.27.4
 - PHP Version: 7.0.33-0+deb9u3
 - Hosting Method: nginx & fastcgi

**Comment by ssddanbrown** [comment]
Thanks for reporting this @jaylik and sorry for my lack of response.

I think I missed this originally and ended up opening a duplicate issue (#1901) myself. This was addressed in BookStack v0.28.1. If you still experience the issue after upgrading to a version greater than that feel free to open a new issue, referencing this one, otherwise I'll close this off.
