### ISSUE TITLE
Remove dotted outline for links

### ISSUE THREAD

**Issue by moucho** [BookStackApp/BookStack#1678]
**Describe the feature you'd like**
Remove the dotted outline on links, buttons, etc when clicking/focusing on them.

**Describe the benefits this feature would bring to BookStack users**
Better UI (IMO)

**Additional context**
a {
   outline: 0;
}

**Comment by james-geiger** [comment]
Hi @moucho 

This was done in order to improve accessibility by default.  If, for some reason, your users won’t require the additional level of accessibility consideration, the commit outlining what was changed is https://github.com/BookStackApp/BookStack/commit/b27a5c7fb876c74c676eb9114383c25d82eb87fb

You can override this by adding

```
*:focus {
    outline-style: none;
}
```

in a style tag in the Custom HTML Head Content in BookStack settings.

**Comment by moucho** [comment]
@james-geiger thanks for your suggestion, I thought it was a change in the new layout, not something related to accessibility.
