### ISSUE TITLE
Developer guides

### ISSUE THREAD

**Issue by NaLiJa** [BookStackApp/BookStack#1685]
It would be great to have some guides or tutorials for developers on extending Bookstack, say some overview about the app structure and some hints about properly implementing new features.

For example I am considering adding a plugin to bookstack and I could probably add it „somehow“, but what would be the preferred way of
* adding a new icon to the page editor
* opening an editor window like the code editor
* handling database changes
* storing and identifying the data (binary or json data)
* loading the dats on page 
* ...

Thanks for reading

**Comment by ssddanbrown** [comment]
Hi @NaLiJa,
We currently do not provide, or really support, a way to implement plug-ins in this manner at all.
We're looking to increase the extensibility of the platform in the future but, as of now, it's fairly locked-down. 

Even writing documenting for the subjects listed, in regards to hacking the existing BookStack code,  would take quite a while and would quickly become outdated.

**Comment by ssddanbrown** [comment]
Since my last comment, I have set-up the following page in the docs:
https://www.bookstackapp.com/docs/admin/hacking-bookstack/

This provides a little more information to those that are a bit more adventurous. I probably won't go any further than that in terms of detail. Therefore I'll close this off.
