### ISSUE TITLE
Add page break plugin

### ISSUE THREAD

**Issue by ismaelp192** [BookStackApp/BookStack#1689]
hi i need add the page break plugin to my text editor, i'm tryng change the tinymce.min.js but has 13000 lines, somebody know add a new plugin?

**Comment by ssddanbrown** [comment]
The BookStack source code for defining the TinyMCE plugins can be found here:

https://github.com/BookStackApp/BookStack/blob/7cd956b24b7a08a8b274d9f244bf6ab482de9635/resources/js/components/wysiwyg-editor.js#L411

This code runs through a build system before release and becomes minified here:
https://github.com/BookStackApp/BookStack/blob/release/public/dist/app.js

If you wanted to edit the source and then build the code, details of the process can be found here:
https://github.com/BookStackApp/BookStack/blob/release/public/dist/app.js

Note that editors to any of the source files are not recommended, unless you're developing, and any changes may be lost or cause issues on updating.

**Comment by atulcj** [comment]
Let me begin by thanking you guys for this wonderful app. I recently came across this and am enjoying the utility that it affords.

To come to the topic/request being discussed, let me first declare that I am not a programmer, please forgive me if this does not sound right.

How if the above .js file can reference / include / import code from another file that persists through code updates, and any custom code could be added to this file. I don't really know if this file would also be required to go through the build system. I was thinking about other plugins to TinyMCE and was wondering if those could be accommodated as custom code.

Similarly I do love the "Custom HTML Head Content" area and have already placed some code shared by @ssddanbrown and other members of the community, can this code be put in another file and be referenced. Just so that the "Custom HTML Head Content" area can be used for testing, but once we think that the code can be made permanent we can add it to the file leaving the area free for additional testing.

**Comment by ssddanbrown** [comment]
Due to the lack of response from the original issue author I will close this.
