### ISSUE TITLE
Code Prettify Support

### ISSUE THREAD

**Issue by KevinHaeusler** [BookStackApp/BookStack#169]
Desired Feature: Integration of https://github.com/google/code-prettify

**Comment by chKaze** [comment]
Ah my bad you are using highlight.js but you are not able to detect or set language for code snippets

**Comment by chKaze** [comment]
http://docs.mmkyun.xyz/books/code-examples/page/asciic updated the plugin on a fork. Kinda new to github contributions so it might take a while to figure out how to request it to be included.

**Comment by chKaze** [comment]
http://docs.mmkyun.xyz/books/code-examples/page/asciic

Preview with prettify

**Comment by patoroco** [comment]
I just added three ` before and after code, and it colourized correctly (I used PHP code for that example).

Maybe you were talking about an old version? On this case, please close this issue :D

**Comment by ssddanbrown** [comment]
Thanks for opening this feature request. The desired library would conflict with the new CodeMirror based system introduced in v0.17.

Since code highlighting support has been improved since this issue was created I will close this.
If a particular feature of the `google/code-prettify` library was desired please open a new issue specifically for that feature.
