### ISSUE TITLE
Allow following deeplink after login

### ISSUE THREAD

**Issue by JtheBAB** [BookStackApp/BookStack#1706]
**Describe the feature you'd like**
Unsure if bug or feature request. 

When a user send a Bookstack link that is deep inside a book that requires a login, then it doesn’t work currently. You get a page not found and when you login through the upper right login button then you are on the default page. When you click again to the link you come to the right page. 

**Describe the benefits this feature would bring to BookStack users**
When the user can login and then got access directly to the requested page, then the general usability would be improved.

**Comment by cw1998** [comment]
From my understanding, this is intentional. If a page isn't public (ie, you must log in to view it), then the URL should not reveal to the public that it is valid by showing a login form instead of a "Not found" page.

**Comment by JtheBAB** [comment]
I understand that. But the page could say 

„page not found or not enough permission“ 

and offer the login form. Then it is still unclear if the page really exist.

**Comment by ssddanbrown** [comment]
@JtheBAB I'm assuming you have public viewing enabled on your instance?

What you describe is the behaviour that should occur but things get a little complicated when public viewing is enabled as the user's intended desired location gets harder to track. Pretty sure it's been discussed before but having trouble finding the history of that.

**Comment by JtheBAB** [comment]
Yes, public is enabled.

**Comment by ssddanbrown** [comment]
As part of #1817 and 7f6cbead333415c9ead093827942a0e08116847a, This has now been implemented in master to be in the next patch release.

The 404 page has been updated to indicate such a scenario could be due to permissions, and "Login" has been added as an action on that card to encourage that as the user's next step. 

![image](https://user-images.githubusercontent.com/8343178/76688238-f4311500-6622-11ea-93ff-74d423c83e77.png)
