### ISSUE TITLE
Make buttons for shelves and books more visible

### ISSUE THREAD

**Issue by PTS93** [BookStackApp/BookStack#1718]
**Describe the feature you'd like**
It would be nice if the menu items for Shelves, Books and Settings could be larger. Increasing to the font size from 14px to 18px or so should already do the trick.

Currently they are really small and feel like insignificant optional things to look at. When a user first logs in they are presented with what they did and others did recently but its not very clear where to go to view what's available. It takes a while to discover those small button that only take up about 1/4 of the available space in the menu bar.

Making them more prominent should help that they pop into the eye of the user on the first glance.

This is on Desktop, haven't looked at it on a mobile device.

**Describe the benefits this feature would bring to BookStack users**
Better UX for first time users.

**Comment by ssddanbrown** [comment]
Hi @PTS93,
Thank you for your request. 

The trouble with design suggestions is that they are very much opinionated. Personally I wouldn't want to increase the size of these any more, I don't want to use more vertical space or have them stick out in the design.

While I get how this may help guide new users, That will ultimately depend on your setup and in my opinion the existing-user experience takes precedent for a platform like BookStack since that should be more common in the designed use case. 

If you want to enable this change on your own instance you can use the "Custom HTML head content" setting to insert CSS to change the text size of these links. If you need any help in defining these CSS rules just let me know.

**Comment by ssddanbrown** [comment]
Closing this off since there has been no further development.
