### ISSUE TITLE
AD groups starting with # don't work for Role External Authentication IDs

### ISSUE THREAD

**Issue by GitAdrianHub** [BookStackApp/BookStack#1741]
Active Directory security groups that start with # (our standard) don't work for mapping AD groups to Roles using either the Role Name or External Authentication IDs. When A user who is a member of that group logs in, their role will not be applied.

Ubuntu 18.04 fresh install and used the supplied Ubuntu install script and supplied ldap config.

**Comment by ssddanbrown** [comment]
Hi @GitAdrianHub,
I've had a little play on my side on this although I'm using OpenLDAP instead of AD.

It's a bit awkward since hash is not a valid character on its own and has to be escaped within a DN.
While testing I found that the BookStack side of things receives an escaped character code instead of a hash itself.

When setting an "External Authentication ID" on role of `\23groupname` (So a `\23` instead of a `#`) I found it would then match correctly. Can you give this a go on your side to see if that gets things working?

**Comment by GitAdrianHub** [comment]
That seems to work, thank you!

**Comment by ssddanbrown** [comment]
@GitAdrianHub Awesome! I'll therefore close this off, Hopefully should not be a frequent issue but if it pops up again I'll keep this in mind and potentially add a note to the docs.

Thanks for confirming!
