### ISSUE TITLE
Dedicated API Docs Feature

### ISSUE THREAD

**Issue by ByWaleed** [BookStackApp/BookStack#1759]
**Describe the feature you'd like**
A clear description of the feature you'd like implemented in BookStack.
Allow users to create documentation pages or sections for APIs which could include resource description, endpoints and methods, parameters and examples. API docs can currently be written, but the formatting is time-consuming and doesn't look the best, as the structure of an API document is different from regular program docs.

**Describe the benefits this feature would bring to BookStack users**
Explain the measurable benefits this feature would achieve.
This could be another feature in the list of features that the app offers and would be more attractive as a complete package, as compared to without the API docs.

**Additional context**
![Screenshot_2019-10-30 API - Documentation - Online Dedibox - Console](https://user-images.githubusercontent.com/33402306/67905668-0033a300-fb6a-11e9-9ac0-8fce2cd4725f.png)
![Screenshot_2019-10-30 Planning Center API Documentation(1)](https://user-images.githubusercontent.com/33402306/67905669-0033a300-fb6a-11e9-9626-c76e6d48ed45.png)
![Screenshot_2019-10-30 Planning Center API Documentation](https://user-images.githubusercontent.com/33402306/67905671-0033a300-fb6a-11e9-963c-80df10ce5fdd.png)

**Comment by ssddanbrown** [comment]
Hi @ByWaleed,
Thank you for the request with the detail and images.

Unfortunately this is not something I'd look to specifically support as part of the core platform. Here's why:

### Focus

Having features for specific types of documentation would require implementation, maintenance & support efforts for functionality that, by design, would only be suited for a specific part of the user-base. Additionally, If we supported this particular type of documentation that would open up the doors to other specific types of documentation, which is something the project could not support at this time.

### Existing Solutions

There are many existing solutions out there to write or generate API documentation. API documentation is often done by those with technical proficiency which opens up platform/development/application options in itself. I'd prefer to focus BookStack towards the less-technical audience as that's the gap and core use-case its intended for, A specifically technical feature such as this would be meandering away from that.

### Defined Benefits

In your request, the defined benefits are as follows:

> This could be another feature in the list of features that the app offers and would be more attractive as a complete package, as compared to without the API docs.

Essentially this is stating the benefit would be a potentially wider audience, or more popular platform. I try to stay away from making that a goal in itself, since it can steer the project off it's path resulting in a wider more generalised outcome rather than a richer, focused project.

---

Apologies that this is probably not the outcome you wanted to hear but hopefully the above explains my reasoning with clarity.

**Comment by ByWaleed** [comment]
Hi @ssddanbrown 

Thank you for your comprehensive feedback and the clarity on the matter.

**Comment by LukasCCB** [comment]
> Hi @ssddanbrown
> 
> Thank you for your comprehensive feedback and the clarity on the matter.

Did you find something similar? I wanted it.
Thanks in advance.
