### ISSUE TITLE
Revision URI

### ISSUE THREAD

**Issue by mattstanyon-tall** [BookStackApp/BookStack#1769]
When looking at previous revisions the URL is similar to below:
https://bookstack.domain.com/books/book1/page/page1/revisions/2180

With the current revision being:
https://bookstack.domain.com/books/book1/page/page1

We would like to link to the actual revision is a document.  So, if it is current, we would like like to use a revision number, therefore, if the document changes, we will also link to the correct version.

This is, I guess, not possible.  This would really help with Change Control - thought I would ask!

Thanks very much

**Comment by ssddanbrown** [comment]
Hi @mattstanyon-tall,

There's no friendly way to access exactly what you want, since BookStack will generally promote the "live" current version, And the direct link to that "version"in the database is hidden to prevent confusion between the two, but there is a cheeky way around this:

1. Go to the "Revisions" view for the page.
2. For the current version, click on "Changes". A new tab will open to reflect the changes in the latest revision.
3. In the URL bar, remove the `/changes` part from the URL.
4. You've now got to the "Preview" link for the current revision.

Note that the revision view pages are supposed to be a preview, Some things like code highlighting are disabled on this page to provide a more strict and simple view of the raw content.

Also, If you have some process that relies on linking to revisions, Please ensure you have tweaked the [revision limit variable](https://www.bookstackapp.com/docs/admin/other-config/#revision-limit) in your `.env` file to ensure revisions won't be trimmed.

**Comment by ssddanbrown** [comment]
Closing this off since the original post was answered above.
