### ISSUE TITLE
Export whole books / chapters

### ISSUE THREAD

**Issue by ghost** [BookStackApp/BookStack#177]
Hey, I was wondering if it's possible to add a feature to export the whole book / some chapters?

**Comment by mayrmartin** [comment]
For me as Student it would be a great feature!
So +1

**Comment by davidPilkington** [comment]
This would be a great feature, it would allow us to keep one set of printable documentation for our clients.

**Comment by mayrmartin** [comment]
Any idea if/when this feature might see the light of day?

**Comment by ssddanbrown** [comment]
@mayrmartin :smile: 

What exports formats we thinking for this then?

Zip of HTML/Text files? Something else?

**Comment by msander** [comment]
A single PDF would be nice

**Comment by mayrmartin** [comment]
A single HTML file would be perfect for me...so I could convert it to a E-Book.

**Comment by mayrmartin** [comment]
But also a single PDF file would be nice.

**Comment by ginal** [comment]
Also a zip archive of markdown files would allow to extract the content and keep it versioned in git. Interfacing with a git repo would be a killer feature.

Great project!

**Comment by jeffreywyman** [comment]
Would also love "export ALL" feature. I don't care about pdf/html/md. Any one would be good.

**Comment by lommes** [comment]
I created a [command ](https://gist.github.com/lommes/5e0a02169346499128182fbe898e0057) to export a whole book to pdf. It is pretty dirty and not production-ready but works for what I needed it for. Maybe it helps somebody. Due to changes on master it only works with current release branch.

After loading in Kernel.php you may call `php artisan book:export <bookslug>`, where <bookslug> has to be replaced with the slug of the desired book. This will create a bookslug.pdf in BookStacks root directory.

**Comment by ssddanbrown** [comment]
Okay, I've now created chapter/book export options based on the page exports that were available (PDF/HTML/TXT). This will be in the next release (v0.15) which I'm hoping to send out in the next day or two.

For other export options or other export improvements please open a new, specific issue.

Thanks @lommes for sharing that script to tide people over.
