### ISSUE TITLE
Add support for PDF embedded bookmarks on exports 

### ISSUE THREAD

**Issue by or0or1** [BookStackApp/BookStack#1788]
exporting  pdf, I find the pdf file has not bookmark,thought I use mutilple #  before line header with markdown styling .   

what is the problem?   

version: 0.27.5

thank you.

**Comment by ssddanbrown** [comment]
Hi @or0or1,
We're going to need some more information to be able to support this issue.

* What are you exporting? (Book, Chapter, Page)
* When are you referring to as BookMarks?
* Where are you using mulitple `#` characters? 
* What editor are you using? (Markdown or WYSIWYG)

**Comment by or0or1** [comment]
thanks a lot.  @ssddanbrown 

I am so sorry.

Q1:  page

Q2 & 3 :
markdown file content: 
![image](https://github.com/or0or1/docker-bookstack/blob/master/20191117191706.png?raw=true)

exporting it ,  and expect the pdf file  is the same as the photo:

![image](https://github.com/or0or1/docker-bookstack/blob/master/20191117185747.png?raw=true)



Q4:   markdown

**Comment by or0or1** [comment]
any plan ?  thanks. @ssddanbrown

**Comment by ssddanbrown** [comment]
No, No plan at the moment @or0or1 but your follow up comment did help me understand what you meant by BookMarks. I had a quick search before but didn't find anything about how our PDF libraries within BookStack could generate bookmarks so didn't look like a quick issue to solve.

**Comment by ssddanbrown** [comment]
Just done some further looking into PDF generation as part of issue #2052.

Such links would be generated as an "Outline" or "Table of Contents" rather than bookmarks. As mentioned on #2052 it is possible to generate a ToC but with some workarounds due to issues in the libraries we use. 

I'm going to close this in favour of #2052, since they're essentially requesting the same functionality.
