### ISSUE TITLE
Cant log into admin account / temp admin accounts

### ISSUE THREAD

**Issue by ITman2019** [BookStackApp/BookStack#1799]
**Describe the bug**
Can't log into bookstack using admin account. I tried to add additional admin accounts using the php artisan command. It accepted the new users but on trying to login it says invalid credentials
**Steps To Reproduce**
1. Go to 'login'

        if (!$user->exists) {
            // Check for users with same email already
            $alreadyUser = $user->newQuery()->where('email', '=', $user->email)->count() > 0;
            if ($alreadyUser) {
                throw new AuthException(trans('errors.error_user_exists_different_creds', ['email' => $user->email]));
            }
**Expected behavior**
login account

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings):
 - PHP Version:
 - Hosting Method (Nginx/Apache/Docker): Apache

**Additional context**
LDAP / AD authentication

**Comment by ssddanbrown** [comment]
Hi @ITman2019,
This will generally occur if BookStack finds a matching user if the LDAP system but there is already a BookStack user using the same email address, where that existing user does not have an ID that matches with the LDAP system.

I think, Upon LDAP user first login, BookStack will store the `uid` attribute, or the DN as a backup if `uid` does not exist` and then it'll use that value later to link users.

The admin artisan command will create admin users but you'll need to change the auth method back to `standard`, at least for a short while, to login otherwise BookStack will query the LDAP system.

**Comment by ITman2019** [comment]
ah that makes sense, how do i change the login method then if i cant get

**Comment by ITman2019** [comment]
fixed. thanks!
