### ISSUE TITLE
Default page templates

### ISSUE THREAD

**Issue by NikolayPolyagoshko** [BookStackApp/BookStack#1803]
**Describe the feature you'd like**
Page templates is great, and i think it would very useful if a template could be set as default one for new pages in a book (book-level setting).

**Describe the benefits this feature would bring to BookStack users**
Simplify creation of pages with predifined structure. E.g. problem-solution articles, etc.

**Comment by cod3monk** [comment]
I would love this feature to be added, an intermediate solution (for my problem at hand) would be a create-page link that will auto insert a specified template.

**Describe the benefits this feature would bring to BookStack users**
I want to pass a link to a large crowd (of mostly non-techs) that will allow them to quickly create a page with a predefined structure. Having to explain how to insert a template significantly reduces the experience for them. Especially because it is not easy to explain in words the "Template Icon".

**Comment by ssddanbrown** [comment]
Thanks to @lennertdaniels in #3918, followed by some further changes in #4721, this functionality has now been added and will be part of the next feature release.

Thanks @NikolayPolyagoshko for the original request, and thanks @cod3monk for providing an intermediate solution, even if we didn't get round to implementing in the mean time.
