### ISSUE TITLE
NPM cannot download node-sass binding for Node 13

### ISSUE THREAD

**Issue by Grawl** [BookStackApp/BookStack#1820]
**Describe the bug**

Because of `image: node:alpine` in `docker-compose.yml`, fresh Node.js v13 is used. But there is no `node-sass` bindings published for Node 13 on Alpine.

```
> node-sass@4.12.0 install /app/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.12.0/linux_musl-x64-79_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.12.0/linux_musl-x64-79_binding.node": 

HTTP error 404 Not Found

```

**Steps To Reproduce**

1. Clone this repo with `master` on this commit: https://github.com/BookStackApp/BookStack/commit/b93f8a4d4680cfe34e3b64db95f0f9683152c22a (last commit when I write this issue)
2. Run `docker-compose up -d --build`
3. Open `node` container logs

**Expected behavior**

All containers is up

**Your Configuration (please complete the following information):**

 - Exact BookStack Version (Found in settings): `v0.28-dev`
 - PHP Version: `7.3`
 - Hosting Method: Docker

**Additional context**

To fix this, I change `docker-compose.yml` to specify Node container version:

```diff
  node:
-    image: node:alpine
+    image: node:12-alpine
```

**Comment by ssddanbrown** [comment]
Thanks @Grawl for reporting this.

I have just fixed this in `master` by updating the npm dependencies so the project uses a node-13 compatible version of `node-sass`. Have tested by bringing up the docker-composer setup and checked it built the SASS files. 

I thought about pinning the node image version as per your fix but I think I'll leave it for the mean-time since it was quite useful in this case; Using the latest version indicated that a dependency update was probably needed.
