### ISSUE TITLE
configuration and/or authorization information issue?

### ISSUE THREAD

**Issue by stinkcheese** [BookStackApp/BookStack#1831]
Hello All,
Not sure if this has been brought up before, but i was poking at my bookstack instance with a web app analysis tool called nikto, and it was telling me of a directory that could contain config or authorization information. Going to the directory below prompted for a download of what appears to be a config file. Im not sure how important the file is in terms of security, but i figured i would pose the question here. 

 OSVDB-3093: /.htaccess: Contains configuration and/or authorization information

navigating to /.htaccess downloads a file that has the following information in it;

<IfModule mod_rewrite.c>
    <IfModule mod_negotiation.c>
        Options -MultiViews -Indexes
    </IfModule>

    RewriteEngine On

    # Redirect Trailing Slashes If Not A Folder...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule ^(.*)/$ /$1 [L,R=301]

    # Handle Front Controller...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^ index.php [L]
</IfModule>

Im pretty much a noob in the security field, but i just wanted your opinion.

Thanks!

**Comment by ssddanbrown** [comment]
Hi @stinkcheese,
Sorry for the really late reply; Yeah, it's totally possible for this to be downloaded since it's in the `public/` folder and therefore exposed by the webserver. 

This file is fine to view or be downloaded, it's just an Apache config file that might be used by users serving BookStack via apache. The file is publicly available here and should never contain anything private within.
