### ISSUE TITLE
Cannot disable gravatar image fetching through `AVATAR_URL` option

### ISSUE THREAD

**Issue by Statium** [BookStackApp/BookStack#1835]
![Screenshot_1](https://user-images.githubusercontent.com/4026090/72205672-cce58c80-34a7-11ea-9631-a58c442bf3bf.png)
Sometimes when creating a user avatar gets up incorrectly.

incorrect path looked in the source page:
http://localhost/uploads/images/user/2020-01/1737-%D0%9C%D0%B8%D1%85%D0%B0%D0%B9%D0%BB%D0%BE%D0%B2%D1%81%D0%BA-%D0%A3%D1%80%D0%B0%D0%BB%D1%8C%D1%81%D0%BA%D0%B0%D1%8F-16/thumbs-40-40/4-avatar.png

adjacent correct path:
http://localhost/uploads/images/user/2020-01/thumbs-40-40/1736-%D0%9A%D1%83%D1%80%D0%B3%D0%B0%D0%BD-7-%D0%A0%D0%BE%D0%B4%D1%8C%D0%BA%D0%B8%D0%BD%D0%B0-avatar.png

we conclude that the paths are different, why did not find out.

**Comment by Statium** [comment]
Another example is exactly the same paths (user names are different), both gravatars are in the same folder, both paths are correct, both gravatars open from the folder, not broken, but one path does not open. The problem arises randomly. File permissions are the same.

**Comment by Statium** [comment]
Also in my .env is AVATAR_URL = false
but gravatars are still created for new users, the cache is cleared by the command through the command line.

**Comment by ssddanbrown** [comment]
Thanks for reporting @Statium.
Could confirm the `AVATAR_URL=false` behaviour.
It looks like the path/naming issue had been previously addressed in an image name scheme change, although I have changed it a little further today, so that has not been an issue for a while for new gravatar fetches.

Fixes to false behaviour made in d4a119b2aa05491eb21824f466b5b4d9851a0ddc and will be part of the next feature release.
