### ISSUE TITLE
inability to edit and delete page

### ISSUE THREAD

**Issue by Statium** [BookStackApp/BookStack#1840]
Sometimes, under very strange circumstances, when creating a page and saving it, after trying to edit the created page, the page is not saved, the first version of the page always remains. While deleting this page is also not possible. I did not find the patterns of such behavior; in the Mariadb database, the page and all its fields look similar to the other page that is being edited. In order for the page to start editing, in the same place in the database you need to change the text, for example, to "123" and the page starts to be edited using bookstack tools

Bookstack latest version.

**Comment by ssddanbrown** [comment]
Thanks for raising @Statium.

Since this is now relatively old and since there are no clear steps to re-produce I'm going to close this off. If this remains an issue please open a new issue, filling all the requested details in the template when creating an issue so we can get an idea of your setup.
