### ISSUE TITLE
[Feature Request] In-page permissions

### ISSUE THREAD

**Issue by clafee** [BookStackApp/BookStack#1860]
Hello,

I'd love to see an in-page permissions system, where one can choose to hide certain elements (for example passwords, or other "sensitive" data) that not everyone should be able to see.

This would allow documentation made in BookStack to be much more complete.

I hope that other people will find it useful.

Thank you !

**Comment by ssddanbrown** [comment]
Thanks for providing your idea @clafee.
The core functionality wished for in this request has already been requested in issue #978 therefore I'm going to close this to cut-down on duplicates. 

Although I can understand your use-case, I probably wouldn't look to implement this due to the fact this would introduce additional very granular control, will make maintenance of editing and permissions system more complex, and will only used by a small portion of BookStack users.

I'll keep the other issue open though for further feedback and so others can voice support.
