### ISSUE TITLE
Reusing Page Content and page_id

### ISSUE THREAD

**Issue by roberteinsle** [BookStackApp/BookStack#1861]
I can't find the page_id so I can include the content.
This information should be display under _details_

**Comment by james-geiger** [comment]
Hi @roberteinsle,

The [BookStack documentation](https://www.bookstackapp.com/docs) has a short video showing how to find the page ID for reusing content.

The section on [reusing page content](https://www.bookstackapp.com/docs/user/reusing-page-content/#easily-grabbing-the-syntax) should have all the details you need to get this up and running.

Let me know if you have any questions.

**Comment by ssddanbrown** [comment]
Thanks @james-geiger for providing the details of this. I wouldn't really want to include the page ID under the details unless there's more value to doing so, which I don't think there is right now since it's only really used, on the front-end at least, for include tags or short-links which have the specially crafted UI, as shown above, to retrieve anyway. 

Since a method of finding an ID has been provided I'll close this off.

**Comment by KardinalReusen** [comment]
The solution applies to my desktop PC. With my mobile devices (android and ios) on the other hand, the context menu does not appear.
