### ISSUE TITLE
Invalid characters passed for attempted conversion, these have been ignored PHP 7.4 Dompdf

### ISSUE THREAD

**Issue by lucyhancock3533** [BookStackApp/BookStack#1864]
**Describe the bug**
When exporting a page to PDF using the default Dompdf renderer, on PHP7.4, and E_DEPRECIATION error is produced. This can be seen in the upstream at [https://github.com/dompdf/dompdf/issues/2003](https://github.com/dompdf/dompdf/issues/2003). "Invalid characters passed for attempted conversion, these have been ignored".

**Steps To Reproduce**
Using a PHP 7.4 installation export any bookstack page to PDF with default dompdf renderer.

**Expected behavior**

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): BookStack v0.27.5
 - PHP Version: 7.4.2
 - Hosting Method (Nginx/Apache/Docker): Apache

**Additional context**
The issue may not be resolved upstream, the ticket is closed yet whether it is fixed or not is a bit unclear.

**Comment by ssddanbrown** [comment]
Thanks for reporting this @lucyhancock3533.

I've just been testing on my dev system and it looks like this is no longer an issue for BookStack > v0.28 since that uses a later DomPDF version which includes the patch for PHP7.4.

Therefore I'll close this but if you do still see errors feel free to open a new issue.
