### ISSUE TITLE
Export to PDF broken

### ISSUE THREAD

**Issue by mattstanyon-tall** [BookStackApp/BookStack#1886]
After upgrading to 0.28 we are no longer able to export to PDF - trace attached.

[pdferror.txt](https://github.com/BookStackApp/BookStack/files/4180256/pdferror.txt)

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): 0.28
 - PHP Version: 7.2.24
 - Hosting Method (Nginx/Apache/Docker): Apache

**Comment by jnikoletich** [comment]
I was having the same error as well. Installing wkhtmltopdf and adding it to my .env file solved the issue for me.

**Comment by hansluebken** [comment]
Same error as well. 
Same Error occured on the Demo when you try to export to PDF.

**Comment by MCStreetguy** [comment]
I experienced the same error message as well, but this seems to be related to DomPDF in some way. I switched to the alternate wkhtmltopdf export option and now the PDF export is working again just as expected. See [the docs](https://www.bookstackapp.com/docs/admin/pdf-rendering/) for infos on how to set this up.

**Comment by hansluebken** [comment]
Hello MCStreetguy, i installed wkhtmltopdf and did the setup in .env for wkhtmltopdf, but i still have the same error.
:-(

**Comment by MCStreetguy** [comment]
@hansluebken For me it started working after executing `php artisan clear` and `php artisan optimize`. Seems as the used export library is cached in some way. If after that it still doesn't work, maybe it's not the library itself, but then I don't really know what to do. I just discovered this as a solution for me and hoped that it might help you too.

**Comment by hansluebken** [comment]
uuupppssss... 
php artisan clear and php artisan optimize break my Bookstack Instance. I installed a new instance and set the wkhtmltopdf settings in the .env before i  migrate. That works for me now! 
Thx a lot for your help.

**Comment by gren236** [comment]
Same error with clean installation on FreeBSD/Nginx/MariaDB stack.

**Comment by eferreira2** [comment]
Same error for me as well. I migrated a customer from v0.25 to v0.28. As mentioned above, I worked around the problem by using wkhtmltopdf.

**Comment by p1xelshader** [comment]
Same error here v0.275 to v0.28 on Ubuntu 18.04.4 LTS

**Comment by ssddanbrown** [comment]
Can confirm, Have assigned to next patch release.

**Comment by ssddanbrown** [comment]
I've just deployed [v0.28.1](https://github.com/BookStackApp/BookStack/releases/tag/v0.28.1) in which I have made some updates to exports which fixed DomPDF exports on my development system. 

Would be good to get some feedback though to confirm this is fixed for others before I close this off.

**Comment by bdillahu** [comment]
I'm running the docker image (on unRaid) and this update does seem to have fixed PDF export.

I do notice that tables aren't quite right - the columns are all about 1" wide, instead of filling the entire page width. I'm new to bookstack, so I'm not sure if this is expected or not (I just loaded it the other day and this is the first time PDF exports have worked.

**Comment by gren236** [comment]
Tried on FreeBSD clean install - it works!

**Comment by ssddanbrown** [comment]
Thanks for confirming on this, Will therefore close this off.

---

@bdillahu Yeah, You'll find that the default PDF output can be rocky due to the general complexities in rendering to PDF. As mentioned above, [switching to WKHTML](https://www.bookstackapp.com/docs/admin/pdf-rendering/) would generally provide a better output closer to the view in BookStack.
