### ISSUE TITLE
heroku support?

### ISSUE THREAD

**Issue by patlecat** [BookStackApp/BookStack#1906]
heroku uses postgres for free accounts. wouldn't it be possible to add support for it too? Using Laravel migration and Eloquent should be RDBMS agnostic, right? So why require only MySQL?

Maybe if someone could add an installation and update guide for heroku would be cool too.

**Comment by ssddanbrown** [comment]
Hi @patlecat,
My thoughts on postgres support can be found here:
https://github.com/BookStackApp/BookStack/issues/76#issuecomment-494956958

In regards to Heroku, I try to keep away from providing any official support for system vendors / cloud platforms. It's probably worth looking for general "Laravel Heroku" guides since the process should be fairly similar.

**Comment by patlecat** [comment]
Yeah but it's not about Laravel but about adding support for Postgres, and that's even independent of heroku. I hope you you will add that instead of requiring MySQL?

**Comment by ssddanbrown** [comment]
Then my response on https://github.com/BookStackApp/BookStack/issues/76#issuecomment-494956958 remains relevant inferring it's not currently on the roadmap to be implemented anytime soon. Any additional comments for postgres can be added to #76 if required otherwise I'll go ahead an close this since, as per the above, I'm not specifically looking to go out the way to add specific system vendor support.
