### ISSUE TITLE
Word wrapping caused on theme color selectors in longer-worded languages

### ISSUE THREAD

**Issue by Statium** [BookStackApp/BookStack#1930]
![image](https://user-images.githubusercontent.com/4026090/75707315-81e63980-5ce0-11ea-89e6-44d41beadde8.png)

In Russian, in the latest version of BookStack there is a problem with word wrap (seen in the screenshot). In other languages, the problem also has a place to be. Please correct layout.

The problem is solved by disabling the class.
![image](https://user-images.githubusercontent.com/4026090/75707666-1a7cb980-5ce1-11ea-8aa7-c23e652345ff.png)

**Comment by Statium** [comment]
![image](https://user-images.githubusercontent.com/4026090/75874157-fe892d00-5e32-11ea-9965-01345cf695ca.png)

At this point, a slight flaw in the form of different indents.

**Comment by ssddanbrown** [comment]
Thanks for reporting these @Statium. There will naturally be some wrapping of blocks like this dependant on text length and fonts in use but I am happy to address it if it's a quick win. 

I've just pushed a commit to align the spacing as shown in your second screenshot. Since that has been addressed, and since your pull request addressed the first screenshot, I'll close this off. All these changes are in master to be part of the next patch release.
