### ISSUE TITLE
Inherit permissions from parent

### ISSUE THREAD

**Issue by Kudja** [BookStackApp/BookStack#1932]
Would be nice if
- New page inherit permissions from it's parent (chapter or book)
- New Chapter from book
- Ability to change permissions for some node (for example book or chapter) and autoupdate them for all childs as well

This will help users work faster

**Comment by ssddanbrown** [comment]
Hi @Kudja,
Book & Chapter permissions should already cascade automatically to child items. If a child item has its own permissions set upon it then these permissions would override the auto-inherited permissions.

Shelf permissions do not cascade, due to their more complicated relationship with the child books, but a command line action exists to auto-copy shelf permissions to books to make it possible to automate such situations where wanted (via cron or similar).

**Comment by Kudja** [comment]
Thanks @ssddanbrown!
That's great news for me.

Closing request.
