### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by Statium** [BookStackApp/BookStack#1934]
1. Create API Page Translation:
http://hostname/api/docs
2. Consider translating the WYSIWYG editor into other languages.
Thanks.

**Comment by ssddanbrown** [comment]
Hi @Statium,

#### API Translations

I'm not looking to translate the API docs, at least yet. Since they're only in an initial stage I'd want them to be further along before even thinking about supporting translations there since I'm sure things will be tweaked. Even once complete, I'm uncertain if the burden upon translators would be worth it. I would image a good portion of developers would be familiar with English plus the content is static & all on one page, so browser-page-auto-translate features may be enough for the remainder. 

#### WYSIWYG Editor Translations

I would look to support WYSIWYG editor translations but not at this stage of BookStack's life. The next stage of the road-map, once the API is somewhat complete, is to review and likely replace the editor in use. Therefore I don't want to add translations right now that we'll just be replacing, and the demand for editor translations is not enough to warrant doing them now. 

Translations will be a priority for the new chosen editor. 

---

Since I see this as answered I'll close this off.
