### ISSUE TITLE
Language to Add Slovenian

### ISSUE THREAD

**Issue by mrjaboozy** [BookStackApp/BookStack#1946]
### Language To Add Slovenian 
Please add Slovenian language. I'm willing to do the traslation. 
Thank you!
BTW I'm loving the app. 

----

_This issue template is to request a new language be added to our [Crowdin translation management project](https://crowdin.com/project/bookstack). Please don't use this template to request a new language that you are not prepared to provide translations for._

**Comment by ssddanbrown** [comment]
Thank you very much @mrjaboozy for offering to translate BookStack into an additional language!

I've setup Slovenian on Crowdin here:
https://crowdin.com/project/bookstack/sl#

Let me know if you have any issues getting started otherwise I'll close this GitHub issue off soon.

**Comment by ssddanbrown** [comment]
Thanks again @mrjaboozy, I see you've made a start on translating.
I've just deployed v0.28.3 and as a part of that I've included what you've done so far:
https://www.bookstackapp.com/blog/beta-release-v0-28-3/

I'll therefore close this off now since you've made a great start. Any future changes/additions via crowdin will still be included in future releases.
