### ISSUE TITLE
When exporting PDF file, Chinese is in disorder

### ISSUE THREAD

**Issue by wzhz** [BookStackApp/BookStack#1964]
**Describe the bug**
I found that when I export a file in PDF format, there is a garbled code in Chinese

**Steps To Reproduce**
1. Write Chinese page
1. Open authored page
1. Click export function and select export PDF file

**Expected behavior**
It should show the effect consistent with the page

**Screenshots**
Look at accessories

**Your Configuration (please complete the following information):**
 - I deployed the service through docker

**Enclosure**
[Garbled file](https://wzhz.xyz/download/%E5%A6%82%E4%BD%95%E7%A7%91%E5%AD%A6%E7%9A%84%E5%9C%A8docker-container%E4%B8%AD%E8%BF%90%E8%A1%8C%E5%A4%9A%E4%B8%AA%E6%9C%8D%E5%8A%A1.pdf)

**Comment by ssddanbrown** [comment]
Thanks for raising @wzhz. I believe this is essentially due to the same thing as issue #719 so I'll close this.

In short: it's tricky for us to support all font options for the default PDF rendering system in an efficient manner. BookStack does support an alternative PDF rendering system ([WKHTMLtoPDF](https://www.bookstackapp.com/docs/admin/pdf-rendering/)) which can be trickier to set-up (Especially in docker environments) but has much better UTF8 support & and more accurate page rendering.

**Comment by wzhz** [comment]
> 感谢您提出@wzhz。我认为这本质上是与问题[＃719](https://github.com/BookStackApp/BookStack/issues/719)相同的缘故，因此我将关闭它。
> 
> 简而言之：对于我们而言，要有效地支持默认PDF呈现系统的所有字体选项是很棘手的。BookStack确实支持替代的PDF呈现系统（[WKHTMLtoPDF](https://www.bookstackapp.com/docs/admin/pdf-rendering/)），该系统设置起来比较麻烦（尤其是在docker环境中），但具有更好的UTF8支持和更准确的页面呈现。

Thank you very much for your reply

**Comment by Cconatus** [comment]
I also encountered the same problem, using English can export pdf perfectly, but using Chinese seems to be unable to render, I am using the latest version 0.31.6  Ubuntu 20.04
