### ISSUE TITLE
Can you set the page, chapter or bookshelf to be private? I see many projects in China have this approach.

### ISSUE THREAD

**Issue by wzhz** [BookStackApp/BookStack#1965]
**Describe the feature you'd like**
Can you set the page, chapter or bookshelf to be private? I see many projects in China have this approach.

For example:

[lifei6671/mindoc](https://github.com/lifei6671/mindoc)
[TruthHun/BookStack](https://github.com/TruthHun/BookStack)

When creating a page or project, you can choose not to publish it. Because sometimes I don't want to publish my articles.

**Describe the benefits this feature would bring to BookStack users**
I don't know what's good for others, but I think in China, there are many people who will choose not to publish their own articles or codes.

**Additional context**
![20200316215557](https://user-images.githubusercontent.com/21847991/76765303-25e7de80-67d1-11ea-8d73-4ceccf9a79e2.png)

**Comment by ssddanbrown** [comment]
Hi @wzhz,
Thank you for your request. You can create groups for people and then assign permissions for your content for each of those groups. There are also a range of "-own" role permissions which could be utilised. Things in BookStack are generally designed to be shared though, so there's no specific "Private" switch on content, and I can't see there being anytime in the near future.

I may close this off soon as a duplicate, since the fundamental idea of "Private content" has already been requested in #747.

**Comment by wzhz** [comment]
> 嗨@wzhz，
> 谢谢您的请求。您可以为人员创建组，然后为每个组的内容分配权限。也可以使用一系列“自有”角色权限。虽然BookStack中的内容通常设计为共享的，所以在内容上没有特定的“私有”切换，而且我看不到在不久的将来会出现任何情况。
> 
> 我可能会一口气将其关闭，因为[＃747中](https://github.com/BookStackApp/BookStack/issues/747)已经要求“私人内容”的基本概念。

Thank you very much for your answer, but I didn't find the relevant group settings.

Can you elaborate on the steps of group setting
