### ISSUE TITLE
export wallabag links to a book

### ISSUE THREAD

**Issue by ChangePlaces** [BookStackApp/BookStack#1966]
Wallabag is a bookmark database, with an archive of the page made at that time. It has an API. I'd like to be able to make a book that is updated from the bookmarks from my wallabag instance for all links, or a particular tag.

This would allow me to group together important documents / bookmarked content for a particular theme / research subject and print them all out together into one sortable collection.

**Comment by ssddanbrown** [comment]
Thanks for the suggest @ChangePlaces.

Since this is based on connecting with an external system I'm going to mark this as out-of-scope for the core BookStack platform but I'm going to keep it open for a while, at least until we implement the BookStack Page & Chapter API's, which would make this more achievable to script together.

I'm not familiar with Wallabag but it looks like it saves the content in some manner, Am I right in thinking you'd want each wallabag bookmark saved as a page in BookStack with it's content within?

**Comment by ChangePlaces** [comment]
> Am I right in thinking you'd want each wallabag bookmark saved as a page in BookStack with it's content within?

Yes, that's right. Then one can sort and edit as necessary!

**Comment by SimonMGS** [comment]
It would helpful if this were possible. We use Wallabag, and it would be great if the bookmarked articles could be placed in context within Bookstack books.

**Comment by ssddanbrown** [comment]
Since the API is now implemented for core page, chapter & book operations I'll close this off.
The API scripts holds some examples of using the BookStack API: https://github.com/BookStackApp/api-scripts
