### ISSUE TITLE
Incomplete translation on page 404

### ISSUE THREAD

**Issue by Statium** [BookStackApp/BookStack#1967]
The phrase is not translated on page 404.
Highlighted in red on the screenshot.

![image](https://user-images.githubusercontent.com/4026090/76790932-9e569b80-67e1-11ea-8e5c-5273d4608963.png)

**Comment by ssddanbrown** [comment]
Thanks for reporting @Statium but this is just something that will generally occur as changes are made in the project. We generally do not delay releases for translations to catch-up, otherwise it gets hard-to-manage and can cause a knock-on delay effect. Therefore I'm going to close this off.

Thank you though for offering the RU translations very quick, They will likely be part of the next release, or a sooner patch.
