### ISSUE TITLE
[Future Request] Why there is no media gallery like wordpress'

### ISSUE THREAD

**Issue by ayyilmaz** [BookStackApp/BookStack#1968]
I can not chage cover images by image gallery. The system force me to select from local pc. How can I select images which are uploaded before?

**Comment by MikeyMJCO** [comment]
Short answer to the question in your issue title - because there isn't.

Long answer - it could be implemented (it exists as it's used by the page editor - it just hasn't been important/requested by the looks of things).

Also - possible typo in your issue title - you probably mean "Feature Request" not "Future Request"

**Comment by ssddanbrown** [comment]
Cover images, along with app logo and user profile images, were originally managed via the image manager interface that's used for page content images.

I changed this a few releases ago though, since the permission model could get complicated using a gallery interface. Also, a singular file input was easier to manage and maintain. These upload locations usually had a low chance of image reuse making a gallery interface fairly redundant, leading to a build up of unused images.

If you want this request as a feature please advise the functional benefits it would bring to BookStack users, otherwise I may close this soon as we have already been down this path and diverted to a preferred one.

**Comment by ssddanbrown** [comment]
As per above, closing this off.
