### ISSUE TITLE
ldap configuration takes no effect when changed to another ldap

### ISSUE THREAD

**Issue by rainshiny** [BookStackApp/BookStack#1977]
**Describe the bug**
Ldap configuration works well with a ldap in  centos7 environment,while takes no effect with another ldap in debian7 environment.

**Steps To Reproduce**
I've installed bookstack v0.28.3 with docker.
And my ldap configuration is as follows:
AUTH_METHOD=ldap
LDAP_SERVER=[IP ADDRESS]
LDAP_BASE_DN=DC=COMPANY,DC=com
LDAP_DN=cn=admin,DC=COMPANY,DC=com
LDAP_PASS=password
LDAP_USER_FILTER=(&(cn=${user}))
LDAP_DISPLAY_ID_ATTRIBUTE=cn
LDAP_VERSION=false
LDAP_EMAIL_ATTRIBUTE=mail
LDAP_DISPLAY_NAME_ATTRIBUTE=cn

**Expected behavior**
This works well with a ldap in  centos7 environment.
But it takes no effect with another ldap in debian7 environment.

**Comment by ssddanbrown** [comment]
Hi @rainshiny,
Sorry to hear you are having trouble with this.

Can you explain what is meant by "takes no effect"? Does the login screen not change to allow LDAP details (showing username input instead of email) or does it just not authenticate with LDAP in the same way? Or are you getting some kind of error?

**Comment by ssddanbrown** [comment]
Since there was no follow-up on this I'll close it off.
