### ISSUE TITLE
Code documentation 

### ISSUE THREAD

**Issue by alvaropc** [BookStackApp/BookStack#1982]
**Describe the feature you'd like**
Hi! I was looking for a way to add code documentation to BookStack but it does not seem to be possible right now.

Since I am writing a project documentation book it would be nice to add there code documentation too. 

In my case I use Python and Sphinx to create the code documentation, the final result is a html page. 

I really do not know how but adding this kind of documentation would be very useful!

**Describe the benefits this feature would bring to BookStack users**
Users could have project and code documentation in the same place and won't need another instances to put their code documentation. 
Having all together would be really comfortable to anyone reading the documentation.

In this issue I am assuming there is not possible to do so in any way, but if there is some kind of workaround I would love to know about it!

Thank you so much!

**Comment by MikeyMJCO** [comment]
Generate your code documentation into Markdown format - you can then input this into Bookstack using the Markdown editor (and probably eventually using the API when this is fully developed!)

https://stackoverflow.com/questions/13396856/markdown-output-for-sphinx-based-documentation

https://github.com/codejamninja/sphinx-markdown-builder/

**Comment by ssddanbrown** [comment]
Hi @alvaropc,

BookStack has support for inserting code blocks via both the Markdown and WYSIWYG editor, If you had not found that just let us know and we can point it out.

Upon those basic editor features, I don't really want to go down the road of including code/developer/api focused features within the core BookStack project. This comment expresses my reasoning for this:
https://github.com/BookStackApp/BookStack/issues/1759#issuecomment-554514238
It's referencing API documentation but that same applies to code/developer specific documentation.

Otherwise, a custom scripted solution as suggested by @MikeyMJCO may suit you best.

Therefore I'm going to close this off as out-of-scope.
