### ISSUE TITLE
switch images from http to https

### ISSUE THREAD

**Issue by denisdal** [BookStackApp/BookStack#1987]
Hi there,
I have to move from HTTP to HTTPS but I have an issue similar to #1121 
Settings are ok but all images inside an article are still served in HTTP.
I have managed to update the url in images mysql table with no luck.
There is something else to update o clear ?
(`php artisan cache:clear` already executed and apache service restarted)

**Comment by denisdal** [comment]
Anyone ?

**Comment by venkat0304** [comment]
In .env file APP_URL to https? 
In apache config I have rewrite rules like this for port 80. And, If you have cloudflare, there is an option to force http to https "Always Use HTTPS"

```
<VirtualHost *:80>
	ServerName domain.com
	RewriteEngine On
	RewriteRule ^(.*)$ https://%{HTTP_HOST}$1 [R=301,L]
</VirtualHost>
```
.....

**Comment by denisdal** [comment]
APP_URL in .env is in https
Here my http virtualhost:

> <VirtualHost *:80>
    ServerName blabla.domain.com
    RewriteEngine On
    RewriteRule (.*) https://%{SERVER_NAME}/$1 [R=301,L] 
 </VirtualHost>

No cloudflare o cdn used

**Comment by ssddanbrown** [comment]
Hi @denisdal,
Sorry for the lack of response.

It's the `html` column on the `pages` table that's causing this.
In the next release of BookStack will be a built-in command to update these links on all the required columns automatically (#1225).

Otherwise, @lieszkol has written a handy blog post on the matter here which may help you: https://kb.zensoft.hu/migrating-your-bookstack-app-to-a-new-domain/

**Comment by denisdal** [comment]
Thank you !
This solved the issue

**Comment by ssddanbrown** [comment]
Great! will therefore close this.
