### ISSUE TITLE
[Feature request] File Archive

### ISSUE THREAD

**Issue by zeular** [BookStackApp/BookStack#1991]
Someone may have already suggested this or maybe there is, but I haven't found it.

I would need some kind of file archive. I want to be able to upload files, most documents (docx & pdf) but also other types of files. Without having to create a "page". And preferably be able to access the files directly from the start page. And the file names should be searchable.

I want to take this opportunity to thank you for a great job! :)

**Comment by ssddanbrown** [comment]
Hi @zeular,

Thanks for the request and the feedback!
I'm going to close this off since it's very similar to the existing issue #924 

To be honest, I'm worried about going much further down the road of files/attachment features since it blurs the scope of BookStack entering the file manager / cloud storage area, and makes it easier for users to just upload files instead of actually adding it as content.
