### ISSUE TITLE
User trying to edit BookStack page does not get a warning message when there is already another user editing the same page

### ISSUE THREAD

**Issue by indyng** [BookStackApp/BookStack#2000]
This does not seem to be true.

<img width="920" alt="Screen Shot 2020-04-03 at 2 53 32 PM" src="https://user-images.githubusercontent.com/15253855/78397833-f2be9100-75bf-11ea-9072-eab9d59bee2c.png">

**Comment by ssddanbrown** [comment]
Hi @indyng,
Congrats on being the proud owner of issue #2000! What a milestone :tada: 

Anyway, Just given it a test, the system I referred to there still looks to be in place:

![image](https://user-images.githubusercontent.com/8343178/78406425-8319c780-75fa-11ea-86b1-c4e9c14774cb.png)

My comment highlighted above was rather brief so does not detail exactly how that system works, so it could be a case of that particular condition not being triggered.

When you start editing a page BookStack will look at the page revisions table for any draft copies of the page created by others users, within the last hour, since the page was last saved. If such a draft exists then the above screenshotted message will be shown.

If you think the system definitely does not work in that case feel free to list the exact steps you're taking and I can look into it.

**Comment by indyng** [comment]
Thanks Dan for the quick reply.

Rick

**Comment by ssddanbrown** [comment]
Since this has been explained I'll close this off.
