### ISSUE TITLE
Upcoming feature requests

### ISSUE THREAD

**Issue by venkat0304** [BookStackApp/BookStack#2006]
**1. Restore book option**
(Users can edit the book and can also delete the book, but what if they deleted a book by mistakenly or intentionally? Admin should restore that book.)

**2. Captcha integration** 
This will prevent bots or spammers to avoid multiple login attempts. 

**3. Footer page**
This will help to add contact page, privacy page etc.

**4. Additional CSS/js block in admin.**
Currently, there is an option to add custom css/js code in the admin panel to overwrite the default css settings. But this content is adding to the top page in source code. There should be an option to enter code after body content tag. So that heavy js files will not load at the beginning of the page. 

**5. Show related books**
When a user reading a book that belong to A shelves, other books in that shelve should be visible above the edit, insert options.

**6. User Points**
If a user get points for creating a page(ex:100), chapter(:1000), and 10 for every approved edit. It would be great.

**Comment by codemicro** [comment]
> 4. Additional CSS/js block in admin.
Currently, there is an option to add custom css/js code in the admin panel to overwrite the default css settings. But this content is adding to the top page in source code. There should be an option to enter code after body content tag. So that heavy js files will not load at the beginning of the page.

When importing a JS file, you have the option to defer it using the `defer` keyword - see https://javascript.info/script-async-defer#defer.

**Comment by ssddanbrown** [comment]
Thank you for your suggestions @venkat0304.

> 1. Restore book option

Recycle-bin functionality is already open under #1017.

> 2. Captcha integration

Recaptcha integration has already been suggested under #1114.

> 3. Footer page

System footer has been requested under #854, with a recent PR under #1973.

> 4. Additional CSS/js block in admin.

As said by @codemicro, You can defer scripts. If you need something deeper than that, you could use the [theme system](https://www.bookstackapp.com/docs/admin/hacking-bookstack/#view-files).

> 5. Show related books

I'm not sure showing books on connected shelves would work well for most users since book topics have a good chance of differing to a current book and may act more as a distraction. Generally, within the default state of the UI, we may show on sibling and parent. You could say that books within a shelf could be classed as siblings, so they could be shown on the book view (Not chapter or page) but I'd kind of class them as cousins instead, due to books being on multiple shelves.

We do have something that kind of covers this which may help: Within the breadcrumbs you can click the dividers to jump to sibling-level items along your current access chain:

![image](https://user-images.githubusercontent.com/8343178/78508799-8e4b2f80-7781-11ea-8d22-e2731baeac1a.png)

> 6. User Points

I really don't want to wonder into the area of gamification for BookStack, It stretches the intentions and use of the platform into something else. In addition, it is a feature that would require a fair amount of effort while needing to be togglable, for users that don't want/need it, and something that would likely spawn requests for further configuration and additions. Therefore I'd probably say this is out-of-scope for this project.

---

Since these points have been answered or have existing issues open for them I'm going to close this off.
