### ISSUE TITLE
Empty options under Actions

### ISSUE THREAD

**Issue by venkat0304** [BookStackApp/BookStack#2007]
When a user with Editor role open the Shelves and click item in the shelves, it shows blank options under Actions. It would be great if you hide or add grid/list icon over there. 

https://domain/shelves/shelvename

<img width="361" alt="Screen Shot 2020-04-05 at 10 50 45 PM" src="https://user-images.githubusercontent.com/62632577/78521626-17696300-7790-11ea-87ff-07653ca56b53.png">

**Comment by venkat0304** [comment]
Actually, When a user click Books link in the top menu header,  he can add NEW books. 
But, when a user click Shelves link and went inside one of the Shelves (lets say "Monitoring"). He can't create books under Monitoring Shelves.  If a user has access to create books, he should be able to create a book under the shelves too, isn't ? or at least he should be able to select shelve when creating a book.

<img width="732" alt="Screen Shot 2020-04-05 at 11 06 54 PM" src="https://user-images.githubusercontent.com/62632577/78522186-294c0580-7792-11ea-91fe-03a53ab91fdc.png">

**Comment by ssddanbrown** [comment]
Hello @venkat0304,

An existing issue for the empty action list on shelves is already open under #1632.

In regards to having a "Create Book" action on the shelf, this will show if the user has permission to create books **_AND_** has permission to edit the shelf (Since they are effectively editing the contents of the shelf). 

Since the advise issue here is already open under another issue, I'll close this off as a duplicate.

**Comment by venkat0304** [comment]
Thank you Dan
