### ISSUE TITLE
Markdown Toolbar

### ISSUE THREAD

**Issue by ZerGBlunt** [BookStackApp/BookStack#2019]
I have used this app for school many times in the past. After installing this onto my serve, I am not seeing the markdown toolbar I am used. Anyway we can updates this in the code or settings or do we have to remember the markdown cheat sheet?

**Comment by ssddanbrown** [comment]
Hi @ZerGBlunt,
There is no built-in toolbar for the Markdown editor right now.

If you are not comfortable with using Markdown, you could instead use the standard WYSIWYG editor instead, by selecting that editor in the settings, if applicable for all users in your instance.

Since this request is already open under #1663 I'm going to close this off as a duplicate.
