### ISSUE TITLE
Upgrading to Beta v0.29.0 results in 500 error

### ISSUE THREAD

**Issue by over-soul** [BookStackApp/BookStack#2030]
Hello,

Upgrading from v0.27.2 to v 0.29.0 on Ubuntu 16.04 breaks the site (gives 500 error). 

Here is the error I get while upgrading: 

`create mode 100644 tests/test-data/compressed.png
Deprecation Notice: The behavior of unparenthesized expressions containing both '.' and '+'/'-' will change in PHP 8: '+'/'-' will take a higher precedence in /usr/share/php/Composer/Downloader/GitDownloader.php:223
Deprecation Notice: The behavior of unparenthesized expressions containing both '.' and '+'/'-' will change in PHP 8: '+'/'-' will take a higher precedence in /usr/share/php/Composer/Downloader/SvnDownloader.php:132
Loading composer repositories with package information
Installing dependencies from lock file`
                                                                    
`  [ErrorException]                                                                         
  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?  `
                                                                                           
`install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [--] [<packages>]...`

**Comment by codemicro** [comment]
Hello!

This can be fixed by making a fresh install of Bookstack in a new directory and copying the following files/folders to the new instance:
* `public/uploads`
* `storage/uploads`
* `.env`
Then run `php artisan migrate` in the new directory and you should be good to do.

These instructions worked for me and at least one other person that I know of.

:)

**Comment by ssddanbrown** [comment]
Hi @over-soul , could you please confirm your versions of PHP and composer?

My thinking this may be due to PHP version change requirements in v0.28 or due to a much older version of composer.

**Comment by over-soul** [comment]
Hi @ssddanbrown,

PHP 7.4.4
Composer 1.0.0-beta2

**Comment by ssddanbrown** [comment]
Thanks @over-soul,

I'm assuming that's the an os-provided composer package?
I think this may be due to that composer version being fairly old now, and possibly having compatibility issues with modern php versions. 

Could you try removing that composer install and instead install a modern version. [Global install instructions here](https://getcomposer.org/doc/00-intro.md#globally).

**Comment by over-soul** [comment]
Looks like composer was the issue. Updated it to the latest version and the upgrade went smoothly. 
Thank you!

**Comment by Valiantiam** [comment]
Composer was my issue as well. Might I recommend the version specific upgrade documentation be updated to reflect a new composer version requirement as well 
@ssddanbrown 

Thanks!
