### ISSUE TITLE
Edit title with single click

### ISSUE THREAD

**Issue by Smoin1** [BookStackApp/BookStack#2036]
**Describe the feature you'd like**
When a new page is create the title is "New Page". To change the title it needs to be selected, deleted and then text can be written. Instead it would be nice to click into the area and directly be able to write the new title.

**Describe the benefits this feature would bring to BookStack users**
Just a small convenience feature

**Additional context**
I hope it is somehow understandably what I mean :D

**Comment by Smoin1** [comment]
as another improvement: the focus could already be on the title, so when I click on new page I am directly able to type. (maybe that would solve also this, thats why I am not creating another issue ^^)

**Comment by ssddanbrown** [comment]
Hi @Smoin1,
Thanks for the suggestion.

I have just made an update to the focus behaviour in 4ef362143bf9f2508b69da260e07ba0330ca6edf, following your suggestions.

If done things a little different, with the behaviour like so:
* Upon edit, if the page title matches the default text for the current user's language then focus on the title element and pre-select all content for easy replacement.
* Otherwise focus on the editor body instead.

Let me know if that doesn't suite, Otherwise I'll close this off and this behaviour will be part of the next patch release.

**Comment by Smoin1** [comment]
yes, good addon! :)
