### ISSUE TITLE
image section selection for cover images

### ISSUE THREAD

**Issue by Smoin1** [BookStackApp/BookStack#2040]
**Describe the feature you'd like**
it is difficult to have a picture exectly in the desired size. it should be possible to select which area of the picture should be used as cover images

**Describe the benefits this feature would bring to BookStack users**
no need for external image manipulation tools

**Additional context**

**Comment by Smoin1** [comment]
just a,lso found out:
even a image reset via maintenance is no workaround: the image is not cleanup up ("no unused image found")
instead the old image has been readded after adding a new one with the same name
only solution currently: upload file with different name

**Comment by ssddanbrown** [comment]
Hi @Smoin1,
Thank you for your suggestion.

I can understand why you may wish for this kind of feature but this would essentially require having options for meta-content, which is a level of option I really don't want to go down to within BookStack. Therefore I'm going to close off this request.

> instead the old image has been readded after adding a new one with the same name
only solution currently: upload file with different name

If this is a different issue to #2039 feel free to open a new issue with clear steps as to how to produce this issue and what the expected behaviour is.

**Comment by Smoin1** [comment]
sry, the comment I made was intended for a different issue ^^

regarding this one: ok, good to know, for now ;)
