### ISSUE TITLE
I can't search after editing the post.

### ISSUE THREAD

**Issue by migk153** [BookStackApp/BookStack#2042]
Let's say I wrote a post.
 -> What ever there is on the post I can search it.
Then, let's say I edited the content of the post.
 -> Now, obviously, you will have to be able to search the edited content but you cannot.
      What it is possible is to search with the content of the anterior post.

Why is this happening? Do I have set something wrong? or Is this a bug?
The point here is that I can only search the previous or first content and not the edited(latest) content.

I am using BookStack v0.28.3.

**Comment by ssddanbrown** [comment]
Hi @migk153,

Please could you provide clear step-by-step instructions that can reproduce this issue? Please include the example content you are using on a page and the search terms, So I can follow the exact same steps.

Additionally, Could you confirm if this occurs on [the demo site](https://demo.bookstackapp.com/login?email=admin@example.com&password=password)?

**Comment by ssddanbrown** [comment]
Just came across the cause of this one when reviewing code while working on the API. Could re-produce. Was due to the mis-ordering of content updating and search indexing.

A fix has now been applied in `master` to be part of the next feature release. A test has been added to cover this scenario. 

Thank for reporting @migk153.
