### ISSUE TITLE
image and callout placement

### ISSUE THREAD

**Issue by Smoin1** [BookStackApp/BookStack#2055]
**Describe the bug**
Images and Callouts do not seem to like each other (see screenshot) they overlap if placed next to each other (btw: the image also overlaps the end of the page, maybe this is related)

**Steps To Reproduce**
add image
add text as bullet list
define a callout in the text (one line)
select "align left" on image -> test will be put right to the image
click save (important! in the editor it is correct)

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/53152348/79703163-4ad8e100-82aa-11ea-8b12-d80e5c74ed62.png)

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings):
 - PHP Version:
 - Hosting Method (Nginx/Apache/Docker): 

**Additional context**

**Comment by ssddanbrown** [comment]
Thanks for reporting this @Smoin1 with the helpful visual screenshot of the issue.

I have applied a couple of commits so that callouts, blockquotes and the page body now account for floated content in a better way:

### Before

![Screenshot from 2020-04-25 19-52-45](https://user-images.githubusercontent.com/8343178/80288377-8acb1880-872f-11ea-93d9-f67fbe435ff6.png)

### After

![Screenshot from 2020-04-25 19-54-18](https://user-images.githubusercontent.com/8343178/80288378-8f8fcc80-872f-11ea-8554-9a42a66257c6.png)

---

These fixes have been applied to our `master` branch, to be part of the next BookStack patch release.
