### ISSUE TITLE
Feature request: pin a page to home

### ISSUE THREAD

**Issue by obinoby** [BookStackApp/BookStack#2056]
Hi,

I love Bookstack. We use it everyday. It may be the best documentation app we ever used.

We have two needs though that we think can benefit every BS user.
One of them is covered by #182 .
The other would be to be able to pin a selection of pages to the home screen. It could use the same layout as the recently viewed pages, etc.

Do you think it would be compliant with BS phylosophy and if so will it be added to your roadmap ?

Best regards,
Ben

**Comment by ssddanbrown** [comment]
Hi @obinoby,
Thanks for your feedback and nice comments!

> Do you think it would be compliant with BS phylosophy and if so will it be added to your roadmap?

I do think this would be a useful feature for others and fits into the BookStack use-case/philosophy. It probably won't be an official roadmap point since roadmap feature are generally larger than this (Spanning multiple releases) but this may be a prerequisite for system notifications which is something I'd like to incorporate soon.

"Pinned" items would essentially come as part of a favorite/starred/pinned/bookmark system. Such requests are already open under issues #1376 and #505. Therefore I'm close this off as a duplicate but I'll open an new issue here to gather feedback on details to move such a feature forward.

**Comment by ssddanbrown** [comment]
#2063 opened to discuss options.

**Comment by obinoby** [comment]
Hi @ssddanbrown ,

Thank you for reviewing my feature request.

In those issues it seems to be a user defined pinning of favorites. What we intended was a system wide pinning where the admin can pin some key books, pages or chapters on every users home page ; or better on every members of a designated group.
