### ISSUE TITLE
HTTP ERROR 500

### ISSUE THREAD

**Issue by Blade2021** [BookStackApp/BookStack#2062]
**Describe the bug**
HTTP ERROR 500 when going to site.  I upgraded to the latest and greatest, updated my php to version 7.4, installed all the dependents (as far as I know).  

**Steps To Reproduce**
Going to site, I get HTTP ERROR 500

**Expected behavior**
I would intend for the site to load as it did before updating.

**Screenshots**
None.

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): Updated to latest origin.
 - PHP Version: 7.4 ( PHP 7.4.5 (cli) (built: Apr 19 2020 08:42:37) ( NTS ))
 - Hosting Method (Nginx/Apache/Docker):  Apache

**Additional context**
I've had this issue before.  I believe I had to play with file permissions to get it to work but can't remember which files had to be adjusted.

**Comment by ssddanbrown** [comment]
Hi @Blade2021,
If you think this may be due to permissions, The following directories (And all subdirectories) need to be writable by BookStack:

* `bootstrap/cache`
* `storage`
* `public/uploads`

If running Ubuntu you can generall achieve this by running the below from your BookStack install directory:

```bash
chown www-data:www-data -R bootstrap/cache public/uploads storage && chmod -R 755 bootstrap/cache public/uploads storage
```

**Comment by Blade2021** [comment]
Hello @ssddanbrown 

I appreciate the quick follow up.  I have ran that command but i'm not seeing any changes on my end.  I believe chown was the ticket to getting it working last time but I'm not sure.

I added the debug line to my .env and moved the old larvellog to a new filename but i'm not seeing any logs being generated.  I also restarted apache to try to force it to update the log.

**Comment by ssddanbrown** [comment]
@Blade2021 If the 500 error page, that you see, a default-looking white one? Or does the BookStack header still show?

**Comment by ssddanbrown** [comment]
@Blade2021 If it's a default white one, You'll be better checking the apache log, often found here on Ubuntu:
```
/var/log/apache2/error.log
```

**Comment by Blade2021** [comment]
Ahh! good call!

I pasted the output of the log file here.  Dissecting it now.
https://pastebin.com/xpH4Pvy4

**Comment by ssddanbrown** [comment]
@Blade2021 My guess is that maybe BookStack is running on an older, not supported, version of PHP? I know you stated a PHP version of 7.4 but the output was from the command line, Is Apache using PHP7.4 or is it using an older version of PHP that's still on the system?

**Comment by Blade2021** [comment]
@ssddanbrown 

When I run php -v it says 7.4 but i'll double check.

**Comment by ssddanbrown** [comment]
Yeah, That will show the command line php version, The version Apache is using can be quite different.

**Comment by Blade2021** [comment]
Well solved that problem but broke another.  I have another site that is using php7.0 so disabling php7.0 globally isn't going to work.  Do you know of a way to make php7.4 run for that virtual host?  I did a quick search but every answer was going a completely different direction.

**Comment by ssddanbrown** [comment]
@Blade2021 BookStack will work down to php7.2, So if the other app at least works up to 7.2 maybe you could use that as a common-compatible version?

Otherwise, Have never done mulitple PHP versions on apache, only on Nginx. This guide looks sensible:
https://tecadmin.net/install-multiple-php-version-apache-ubuntu/
You could leave the default version for apache as php 7.0 then only follow the guide for the BookStack install & php7.4, to reduce setup required.

**Comment by ssddanbrown** [comment]
Since this conversation has gone quiet, I'll close this off.
