### ISSUE TITLE
Formats dropdown menu is not readable in dark mode.

### ISSUE THREAD

**Issue by much-doge** [BookStackApp/BookStack#2070]
**Describe the bug**
The formats dropdown menu is not readable in dark mode. I suppose it is caused by the fact that the font color didn't change.

**Steps To Reproduce**
1. Enable dark mode
2. Go to any page editor
3. Click on formats
4. The drop down menu is not visible

**Expected behavior**
The menu should be visible

**Screenshots**
Light mode
![Screenshot from 2020-04-28 11-44-02](https://user-images.githubusercontent.com/20739853/80452397-68fcac00-8950-11ea-9fbe-4b090114340b.png)
Dark mode
![Screenshot from 2020-04-28 11-43-50](https://user-images.githubusercontent.com/20739853/80452400-6ac66f80-8950-11ea-83a4-739a9a59b2b8.png)

**Your Configuration (please complete the following information):**
 - Exact BookStack Version : BookStack v0.29.0 
 - PHP Version: 7.3
 - Hosting Method (Nginx/Apache/Docker): Apache

**Comment by ssddanbrown** [comment]
Hi @much-doge,
The text should have supported styles, It could just be cached as found in #2029. You could try clearing your browser cache and see if that helps. 

Otherwise, could you check if this occurs on the demo site?:
https://demo.bookstackapp.com/login?email=admin@example.com&password=password

**Comment by much-doge** [comment]
Ah thanks, just like https://github.com/BookStackApp/BookStack/issues/2029 , my issue was also the cache. Clearing it solves the problem.

Thank you.
