### ISSUE TITLE
Migrate LDAP to SAML

### ISSUE THREAD

**Issue by JtheBAB** [BookStackApp/BookStack#2101]
Hi

I would like to change my bookstack instance with a lot of ldap users to SAML authentification.

Is this straightforward or do i need to change something so that currently existing ldap users can login with SAML?

Thank you

**Comment by miterion** [comment]
Hi,

our organisation switched from ldap to SAML. Users could login afterwards to their accounts created using the ldap authentication.

Matching of users is done using the `SAML2_EXTERNAL_ID_ATTRIBUTE` attribute, so make sure it contains the same value as the `LDAP_ID_ATTRIBUTE` (for the same user).

**Comment by ssddanbrown** [comment]
Yeah, @miterion is spot-on here. Both systems match existing users by checking their stored `external_auth_id` with the id provided by the LDAP/SAML system. If you're using the same attribute (That has the same values), you should be good otherwise you might need to update the `external_auth_id` of existing users on migration.

The `external_auth_id` is just stored as a column on the `users` table within the database, if you need a programmatic/bulk way of updating. 

If you're using group/role sync then that may be an additional consideration. Is supported in SAML but there could be differences in how your auth system provides those groups to BookStack. Additionally, with LDAP we walk up the group chain to get parent groups whereas I don't think there's a standardised way to do this on the SAML side.

**Comment by JtheBAB** [comment]
Thank you both for the explanations. I will check if and how i will do it.
