### ISSUE TITLE
Migrate to Secure Images

### ISSUE THREAD

**Issue by mikeyz24** [BookStackApp/BookStack#2104]
I followed the instructions in the doc for Securing Images but after making the changes any images I upload as a cover page or part of page content are not showing up.

I can confirm that the image file is being saved to the storage/uploads/images folder and it has the correct permissions and ownership.

When looking at the source code of a page for example, the link that is being saved for the image is in this format:  `<a href="http://bookstack/uploads/images/gallery/2020-05/lU9FrfnU0EtFr4PR-image-1588789464792.png">`

Taking a look inside the DB in the IMAGES table, the entry for this image looks as follows:
 

```
id: 134
name: image-1588789464792.png
url: http://bookstack/uploads/images/gallery/2020-05/lU9FrfnU0EtFr4PR-image-1588789464792.png
created_at: 2020-05-06 14:24:25
updated_at: 2020-05-06 14:24:25
created_by: 3
updated_by: 3
path: /uploads/images/gallery/2020-05/lU9FrfnU0EtFr4PR-image-1588789464792.png
type: gallery
uploaded_to: 83
```

If I try to visit the link `http://bookstack/storage/uploads/images/gallery/2020-05/lU9FrfnU0EtFr4PR-image-1588789464792.png` I get a 404 error.  What should the correct path be with Secure Images setting enabled?  Do i have to make some changes in the NGINX config file to point it at the correct location or is this a bug?

**Comment by ssddanbrown** [comment]
Hi @mikeyz24,

Sorry for my lack of response here. The image links themselves should remain the same after changing to `STORAGE_TYPE=local_secure`. Requests for these should automatically get routed through the application as long as a matching file does not exist in the `public` folder. 

> If I try to visit the link http://bookstack/storage/uploads/images/gallery/2020-05/lU9FrfnU0EtFr4PR-image-1588789464792.png I get a 404 error. 

That's what I'd expect since no image links should have `storage` in the path. I'd need to know what you'd get if visiting `http://bookstack/uploads/images/gallery/2020-05/lU9FrfnU0EtFr4PR-image-1588789464792.png` directly while logged in.

**Comment by ssddanbrown** [comment]
Since there's been no further follow-up I'll close this off.
