### ISSUE TITLE
Laravel.log filling up quickly

### ISSUE THREAD

**Issue by vincentmakes** [BookStackApp/BookStack#2110]
I have Bookstack v0.29.2 and my laravel.log is filling up pretty quickly with this kind of error:

_[2020-05-08 18:47:01] production.ERROR: Page not found {"userId":1,"exception":"[object] (BookStack\\Exceptions\\NotFoundException(code: 404): Page not found at /var/www/bookstack/app/Entities/Repos/PageRepo.php:56)
[stacktrace]
....
[2020-05-08 18:47:38] production.ERROR: Page not found {"userId":1,"exception":"[object] (BookStack\\Exceptions\\NotFoundException(code: 404): Page not found at /var/www/bookstack/app/Entities/Repos/PageRepo.php:56)
[stacktrace]_

Not sure where it's coming from as I never had a 404 error on that day and time and I'm the only user. Any idea how to limit the data logged ? Thanks

**Comment by ssddanbrown** [comment]
Hi @vincentmakes,
Thanks for reporting. Looks like those are logged whenever an item is not found. We shouldn't really be logging those events so I'll update these events to be ignored by the logger for the next release. 

I think you have to of had some requests coming in to `/book` endpoints to get these. Could be bots if your instance is public. If not, you could maybe check the webserver access logs for around those times to see if that provides any extra info.

**Comment by vincentmakes** [comment]
Those are my requests but I never got a 404 error on the screen and this is the weird part.

**Comment by ssddanbrown** [comment]
Can't really think why there'd be extra requests or why these not found events wouldn't be shown. If you can re-produce it might be worth watching the network panel in the browser devtools to see if there's any extra requests fired that lead to a 404 page. Possibly a plugin? 

Otherwise, I've now updated `master` so such events will not fill the logs & added testing to cover. Will be part of the next feature release.
