### ISSUE TITLE
Sub Chapters; More nesting levels 

### ISSUE THREAD

**Issue by JohnnyWild89** [BookStackApp/BookStack#2128]
It would be great to have opportunity to set an option in specific book and call it like an "Expand branching\nesting". Current architecture only allows put Chapter in book and pages into chapters what makes using BookStack a bit lack for Wiki purposes. More branching will allows to use more structured documentation which necessary in some cases. 
Adding sub chapter may allow to have such book structure:

Book
∟Page
∟Chapter
-∟ Sub chapter 1
--∟ Sub chapter 2
---∟Page 1
---∟Page 2
--∟ Sub chapter 2
---∟ Sub chapter 3
----∟Page 1
----∟Page 2
---∟ Sub chapter 3
----∟Page 1
----∟Page 2

More flexibility for growing Wiki documentation. 

Possible amount of nesting levels should be somewhere like 5.

**Comment by ssddanbrown** [comment]
Hi @JohnnyWild89,

The current limitation is by design really, A deeper discussion regarding this can be found in https://github.com/BookStackApp/BookStack/issues/95.

**Comment by JohnnyWild89** [comment]
@ssddanbrown thanks for reply and sorry for doubling thread (haven't found that you pointed). Will still to hope anyway :)

**Comment by prelogic-greuter** [comment]
I also back this request for more nestability, but i think it should be done via chapters and sub chapters.

The reason is that bookstack orients itself on real world books. organizing a whole major topic in books, sub-topics in chapters. several major topics (books) in shelves.

Following this example, it would make sense to allow chapters and sub chapters, because almost any technical book i have consists of  main chapters and sub chapters (my old Math book, any technical handbook etc)

I understand that pages are the most atomic unit, which seems fine (its the same way in a book) and a page can further be structured with headings. However having chapters and sub chapters (even if it is limited to lets say 2-3 levels) would greatly improve the way i would be able to organize my documentation.

example:

- shelf called "technical documentation"
-- Book "Software Product A
-- Book "Software Product B"
----Chapter "Introduction"
-------Page "Target Audience"
-------Page "Main Use Cases"
----Chapter "Installation and Configuration"
-------Sub-Chapter "Prerequisites"
----------Page "Hardware"
----------Page "Software"
----------Page "External Storage"
-------Sub-Chapter "Installation"
----------Page "Installing NGINX"
----------Page "Installing Software Product B"
-------Sub-Chapter "Configuration"
----------Page "Default confguration"
----------Page Config for Customer A
----------Page Config for Customer B

- Shelf called Finance
-- Book "Accounting Guidelines"
-- ...

to me, limiting to just one levels of chapters seems artificial, there are tons of real books with a chapter hierarchy. It is also one of the first things my employees ask: Why cant i create sub-Pages/sub-chapters. then they need to work around that limitation, wich seems a bit artificial

I really love bookstack otherwise: the page editing functionalities,  table support etc are really Top-Notch.
