### ISSUE TITLE
Breadcrumbs Issue

### ISSUE THREAD

**Issue by xsxavier** [BookStackApp/BookStack#2135]
I'm not sure if this is intended or not. If I understand correctly breadcrumbs are used to get to a higher level page/folder, not to a previous page. However this is what happens:
**a**. Open a book through the top Books link and then a page. The breadcrumb at that moment shows the book as the top breadcrumb, the shelf does not appear.
**b**. Opening a book through the shelves view, the shelf does appear in the breadcrumb.

Scenario **a** is unexpected. It apparently takes the top page from where you've opened it either the books page or shelves page.
So when using the breadcrumb in that instance I can not get back to the shelf page and end up in the books list, which is unorganized. So the breadcrumb doesn't adhere the page hierarchy in scenario **a**.

**Comment by ssddanbrown** [comment]
Hello @xsxavier, This is indeed intended behaviour.

Since a book can be part of multiple shelves we can't necessarily assume the correct shelf for a book, An in some cases BookStack can be used without shelves at all, so BookStack will attempt to track the entry route to the viewed content to see if it was in the context of a particular shelf and, if so, show that shelf in the breadcrumbs.

**Comment by xsxavier** [comment]
Hello @ssddanbrown,

Thanks for the clarification. This does make sense, I hadn't considered books being part of multiple shelves.
