### ISSUE TITLE
Import/Export file to a Page (.docx, .txt...)

### ISSUE THREAD

**Issue by wisoez** [BookStackApp/BookStack#2142]
Hi there,
I need to import .docx file as a page. But Bookstack doesn't support.
I think everybody need this feature. Thank you!

**Comment by ssddanbrown** [comment]
Hi @wisoez,
Exporting to more formats is already open under #1273.

As far as importing goes, I'll likely not officially support other file formats such as docx due to their complexity and likelyhood to raise many more issues. Ideally, once we have expanded the BookStack API, people will create scripts to import from various formats.
