### ISSUE TITLE
Beginner with Laravel

### ISSUE THREAD

**Issue by demoqb1** [BookStackApp/BookStack#2148]
I'm beginer laravel, now I want to learn about the architectural model of App BookStack and I want to rebuild it to better understand laravel, I hope to receive helpful advice from you!!
Thank you!!

**Comment by ssddanbrown** [comment]
Hi @demoqb1,

What kind of advice are you after exactly? Do you have any specific questions you'd like me to answer?

**Comment by demoqb1** [comment]
> Hi @demoqb1,
> 
> What kind of advice are you after exactly? Do you have any specific questions you'd like me to answer?

Can you help me more clearly about the Bookstack project architecture !!
I am trying to fix the css and add some options to the homepage but I cannot find the file that contains it, maybe I do not understand the workflow of the project yet

**Comment by demoqb1** [comment]
> Hi @demoqb1,
> 
> What kind of advice are you after exactly? Do you have any specific questions you'd like me to answer?

Can you help me more clearly about the Bookstack project architecture !!
I am trying to fix the css and add some options to the homepage but I can't find the file that contains it, maybe I don't  understand the workflow of the project!! 
thank u!!

**Comment by ssddanbrown** [comment]
Hi @demoqb1,
It's quite a large subject to be honest and it will take a long time to document each part of the architecture. 

Most things follow Laravel convention. 
CSS is done via SCSS, and the root file for the styles is this one:
https://github.com/BookStackApp/BookStack/blob/master/resources/sass/styles.scss

More details, and instructions for building css/js, can be found in the readme here:
https://github.com/BookStackApp/BookStack#%EF%B8%8F-development--testing

The homepage is served through this method here:
https://github.com/BookStackApp/BookStack/blob/master/app/Http/Controllers/HomeController.php#L19
It's one of the messiest controller routes, due to the different homepage options available. 

By default, this is the view that would be served:
https://github.com/BookStackApp/BookStack/blob/master/resources/views/common/home.blade.php

Knowing the Laravel basics will really help understand how a request goes through an application until the point of response.  

Laracasts has a great free video guide on the basics: https://laracasts.com/series/laravel-6-from-scratch

**Comment by demoqb1** [comment]
Thank you for the very useful sharing !!
