### ISSUE TITLE
Accesskey navigation between Chapters (and Pages) within a Book 

### ISSUE THREAD

**Issue by GreatestFool** [BookStackApp/BookStack#2149]
**Describe the feature you'd like:**
Since you've already gone for the Bookshelf > Book > Chapter > Pages approach, I think it would be really nice to be able to go to the next page or chapter by pressing an arrow key. Left arrow goes to the previous chapter (or page) behind it, right arrow goes to the next chapter (or page) in front of it.

**Describe the benefits this feature would bring to BookStack users:**
While not exactly useful for editing or the like, I think it is pretty useful if you're gonna be reading through something, either for proofreading, checking the flow of the text or simply for reading through it just because. It's a convenience thing mostly, less interruptions to take you out of the content.

**Comment by ssddanbrown** [comment]
Hi @GreatestFool,
Thanks for your suggestion. The idea non-editor keyboard shortcuts is already open under #1216 so I'll likely close this off to cut-down on duplicates.

I think I'd be apprehensive to take over the arrow keys directly, since users may use them for navigational purposes, but perhaps some other keys or a modifier key with the arrow keys could work.
