### ISSUE TITLE
External Authentication ID stopped working

### ISSUE THREAD

**Issue by kabaga** [BookStackApp/BookStack#2155]
**Describe the bug**
When LDAP has been enabled, LDAP users are able to login. However, the local admin account with External Authentication ID configured, cannot login.

**Steps To Reproduce**
1. Enabled ldap by editing .env (AUTH_METHOD=ldap)
2. Login to the web UI using the local admin account
3. Will get an error message stating "These credentials do not match our records."

**Expected behavior**
Step 3 should allow the local admin account to login to the system.

**Screenshots**
n/a

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): 0.29.3
 - PHP Version: PHP 7.3.18
 - Hosting Method (Nginx/Apache/Docker): not sure. I am using the linuxserver/docker-bookstack 

**Additional context**
n/a

**Comment by ssddanbrown** [comment]
Hi @kabaga,
Just so I understand, On step 2 where you mention a "local admin account", is this an account that exists in your LDAP system?

**Comment by kabaga** [comment]
No, the admin account locally created in Bookstack

**Comment by Dayflare** [comment]
to login with the standard bookstack authentication system you need to change AUTH_METHOD=standard
if you set it to ldap it always tries to authenticate with the ldap server.

**Comment by kabaga** [comment]
> to login with the standard bookstack authentication system you need to change AUTH_METHOD=standard
> if you set it to ldap it always tries to authenticate with the ldap server.

I should be able to use the local account because it has admin privilege. To get the local account to work with ldap, the External Authentication ID should be enabled. https://www.bookstackapp.com/docs/admin/ldap-auth/

**Comment by ssddanbrown** [comment]
Hi @kabaga,
Since you're getting ""These credentials do not match our records." I'd imagine one of the following is true:

- The credentials you're using to login are wrong.
- The configured LDAP user search does not match any users for the username you're giving.
- A user is being matched but the details are already in use (Maybe email) for a user that does not have a matching external auth id.

Does LDAP login work for other LDAP accounts?
If so, and it's only this admin account you're having issues with, You could try removing any common details, with the LDAP user, from the BookStack admin user, including clearing the "External Auth ID". Then, with LDAP enabled, login as the intended LDAP account to create the account with the right settings, then log back in with `standard` authentication to promote that new "admin" LDAP user.

**Comment by kabaga** [comment]
Hi,
Sorry for the late reply. In the Bookstack settings, I was using the email login when it was failing. Everything seems to be working as intended. The problem is more of a user error.

Thanks!
