### ISSUE TITLE
Recommended to consider supporting epub file import

### ISSUE THREAD

**Issue by yoyomule** [BookStackApp/BookStack#2167]
Hello, it is recommended that bookstack can support epub file import,  so that  can quickly import a large number of existing resources. I know there is an open source solution https://github.com/futurepress/epub.js, the author sees if they can consider integration. In addition, it is even better if the import of docx files is also supported.
Thanks.

**Comment by ssddanbrown** [comment]
Hi @yoyomule, 
I general won't look to support importing of different formats, like epub or docx, within the core project due to the complexities and side-effects involved but we will continue to work on the API to allow import scripts to be created in the future. 

In regards to the library linked to, I generally will try to stay away from having file "viewers" in BookStack since it discourages the actual content being inserted as normal documentation content, instead leaving it embedded in a more complex attached format that's much harder to parse out.
