### ISSUE TITLE
Cursor Speed refresh speed issue on Editing Page content

### ISSUE THREAD

**Issue by chyeteck** [BookStackApp/BookStack#2178]
**Describe the bug**
Edit Page becomes slow when the page content is large(with images and tables) compare to updating a fresh page with little content.

**Steps To Reproduce**
1. Go to 'Page'
2. Click on 'Edit'
3. Scroll down to 'Editor' content
4. See slow page response when editing text in editor area

**Expected behavior**
Same speed cursor refresh rate as editing a fresh page.

**Screenshots**

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): 0.24
 - PHP Version: 7.1
 - Hosting Method (Nginx): 

**Additional context**

**Comment by ssddanbrown** [comment]
Hi @chyeteck,
Version v0.24 is a considerably old BookStack version, at almost 2 years old.  There's been a major design update since then which could affect this issue.

That said, This may just come down to your system & browser and there might not be much we can do here unless you're able to pinpoint an exact problem.
Details of your system and browser would help us may look into this, but really we'd only look to support if this is found on the latest version of BookStack.

**Comment by ssddanbrown** [comment]
Since no further detail has been provided I'll close this off.
