### ISSUE TITLE
Export pdf file, Chinese characters disappear

### ISSUE THREAD

**Issue by yoyomule** [BookStackApp/BookStack#2182]
When exporting the page, I found that when exporting the pdf file, the Chinese will be lost.
Another optimization suggestion: when searching, the results obtained did not locate the specific location of the page.Is it possible to optimize here?Thanks.

**Comment by ssddanbrown** [comment]
Hi @yoyomule,
Non-ascii character sets having issues on PDF exports is a known issue and is open under a few other issues such as #719. Generally, Changing the PDF rendered to WKHTML will allow for better results: https://www.bookstackapp.com/docs/admin/pdf-rendering/

The search query is somewhat related to the existing issue #997.

Therefore I'm going to close this off since there are existing issues covering this.
