### ISSUE TITLE
Multilanguage support

### ISSUE THREAD

**Issue by robbash** [BookStackApp/BookStack#219]
Desired Feature:
Do you intend to/would you add multilanguage support?
I saw some texts in the `lang` resources, but not all texts are in there so currently would make much sense for me to translate. I'm quite busy atm but could maybe help to move texts from blades to the resources when I find some time.

**Comment by ssddanbrown** [comment]
Hi @robbash,
Yes, I am intending to add multi-translation support. At the moment, any big bulky features are a priority but every so often I am trying to move more of the text into the `lang` resources. Help in doing so would be great.

Since this has already been requested under issue #115 I will close this duplicate.

**Comment by robbash** [comment]
@ssddanbrown, excellent!

Sorry about duplicating, was just filtering by `lang` not `translation`... ;)
