### ISSUE TITLE
Change shelf owner

### ISSUE THREAD

**Issue by grootsys24** [BookStackApp/BookStack#2204]
Hello,

I created a shelf whose owner I am through. Is there an easy way to give such a shelf to someone else or hand over a group role as owner?

**Comment by ssddanbrown** [comment]
Hi @grootsys24,
There's no way to do this as of yet but I've seen some similar requests before from others.

I've opened #2246 to propose a solution as a way to achieve these requests, which would allow this logic on all items instead of just shelves. I'm going to therefore close this off. Feel free to provide any feedback on #2246.
