### ISSUE TITLE
Allow author to delete page

### ISSUE THREAD

**Issue by kshitijsharma97** [BookStackApp/BookStack#2213]
**Describe the feature you'd like**
Currently only admin have the permission to delete a page, My idea for new feature is to allow user to request for deleting the page.

**Steps:**
1. User will request to delete the page with a reason.
2. Admin will review the request and perform the operation accordingly.

**note: User can only request for the page if he/she is the author of the page.**

**Describe the benefits this feature would bring to BookStack users**
User can give the request to delete instead of mailing the admin to delete the page. Also, there are multiple instances where accidentally multiple page get created so it will give an option to users to delete unnecessary pages.

**Comment by ssddanbrown** [comment]
Hi @kshitijsharma97,
Thanks for your suggestion.

The feature is based on the statement that only admins have permission to delete a page. This is not full true, You can create any roles you want with the permission to delete a page, and you can even allow permissions for users to only have the power to delete their own content instead of all. These options can been seen on the right-hand-side of this screenshot from a role page:

![image](https://user-images.githubusercontent.com/8343178/89582807-2bea6480-d831-11ea-8a63-ee80bd7dccfa.png)

With the above, do you still feel the need for your requested feature?

**Comment by ssddanbrown** [comment]
Will close this since there has been no further response.
