### ISSUE TITLE
Can't save draft - Error 405

### ISSUE THREAD

**Issue by navvienna** [BookStackApp/BookStack#2218]
**Describe the bug**
When a draft is saved, a green checkmark will appear next to the text "undefined 0NaN:0NaN". On reopening the page, no draft is loaded.

Chrome Webconsole shows the error "PUT http://SERVERNAME:8081/ajax/page/55/save-draft 405 (Method Not Allowed)"

**Steps To Reproduce**
1. Open any page in edit mode and press CTRL + S
2. See error

**Expected behavior**
A draft should be saved on CTRL+S - when the same user reopens the page later, the saved draft should be loaded again to give the user the option to resume previous work.

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): BookStack v0.29.3
 - PHP Version: 7.4
 - Hosting Method (Nginx/Apache/Docker): Windows Server 2016 + IIS 10

**Additional context**
.env Value APP_URL=http://SERVERNAME:8081
Every other feature other than saving draft seem to work

**Comment by ssddanbrown** [comment]
Hi @navvienna,
Sorry to hear you're experiencing this issue.

Just to confirm, can you successfully upload images & files to a page without issue? Just trying to determine if this is maybe an issue with all background requests on your instance.

**Comment by navvienna** [comment]
Hi @ssddanbrown 
uploading files / images works without issue. As far as I can see, every other feature is working fine for us.

**Comment by navvienna** [comment]
Hi @ssddanbrown 
apparently we are also unable to delete attachments - I'm not sure if this is linked to this problem, I just wanted to mention it. After the confirmation dialog, I see a green checkmark without text, but the attachment doesnt get deleted.

Thank you for your help and best regards

**Comment by navvienna** [comment]
Any chance to get help with this issue?

**Comment by ssddanbrown** [comment]
Hi @navvienna,
Sorry for the lack of help, I generally feel a bit clueless when it comes to IIS specific issues.

The operations you describe, that are failing, are some of the only PUT/DELETE HTTP requests in the app, all others are GET/POST or only pretend to be PUT/DELETE.
A search of ISS along with the response message seems to pick up quite a few results: https://www.google.com/search?q=iis+method+not+allowed

Many of these point to the WebDAV module interfering with these kinds of requests. Do you have that installed and is that something you can try disabling to test? 

Otherwise we'll need to dig to see if this fails at IIS level or BookStack level.

**Comment by navvienna** [comment]
Hi @ssddanbrown 
I checked the installed roles on the server and the WebDAV module is neither activated nor installed. 

Attached you can find the google chrome webconsole error which appears when saving a draft - maybe it helps? I tried googling the error, but couldnt find anything useful to be honest.

![Uploading 2020-10-06 10_47_46-Meeting 06.10.2020 - OneNote.png…]()

**Comment by navvienna** [comment]
Uploading here doesnt work, here is a link: https://ibb.co/0QW64mY

**Comment by ssddanbrown** [comment]
Thanks @navvienna, 
Unfortunately that does not provide much extra detail.

If you can, Can you open the chrome devtools, re-create the error, go to the "Network" tab, Click on the last red line, Then view the "preview" tab as see what the response looks like (If any)?

![image](https://user-images.githubusercontent.com/8343178/95796520-fc4e5180-0ce4-11eb-9e76-a4513686e480.png)

Also, Do you have anywhere to configure HTTP verbs for requests to the application as per this guide?: https://support.deskpro.com/en/kb/articles/configuring-http-verbs-on-windows-iis

**Comment by navvienna** [comment]
Hi @ssddanbrown 
thank you so much - apparently the HTTP verbs for request were the problem. I followed the article (although you have to set it for both php handlers), restarted IIS and now everything works as it should.

Best regards

**Comment by ssddanbrown** [comment]
@navvienna That's awesome to hear, Glad that got things working. Will try to remember if I see issues for other IIS users. Will therefore close this off.

**Comment by awarre** [comment]
In addition to enabling **All verbs** in the PHP Handler Mappings in IIS (noted above), I needed to do the following:

1. Internet Information Services (IIS) Manager
2. Select your BookStack site
3. WebDAV Authoring Rules feature menu
4. **Disable WebDAV** from the Action Menu on the right
5. Modules feature menu
6. Remove **WebDAV Module**
7. Handler Mappings feature menu
8. Remove **WebDAV**
9. Restart BookStack website

**Reference**
https://stackoverflow.com/a/29415149/860698

Apologies for responding to a closed issue. This is the top Google result on this issue so hopefully IIS folks will see this.

**Comment by valentinkang** [comment]
Hi everyone, I have 403 error for the automatic save draft action
![image](https://github.com/BookStackApp/BookStack/assets/138471496/1d0dad48-4a1b-49d0-b501-f38e494333f3)
![image](https://github.com/BookStackApp/BookStack/assets/138471496/e17cbecc-f3b1-4f43-816b-ddcdbbff80df)
![image](https://github.com/BookStackApp/BookStack/assets/138471496/0924ec8c-cd0e-4065-929a-502a47c12efa)

My server is hosted on OVH (french web host). It is a shared server
Is it because of the HTTP PUT verb which will not be accepted by my host?

**Comment by navvienna** [comment]
Did you follow the steps mentioned in the previous posts?

**Comment by valentinkang** [comment]
> Did you follow the steps mentioned in the previous posts?

It's for IIS Microsoft server, mine is a LAMP and I just checked my Laravel applications, they also use the PUT verb as well as DELETE and it works fine so that's ultimately not the problem.

**Comment by ssddanbrown** [comment]
@valentinkang I'd be very surprised if OVH were blocking specific HTTP verbs, especially since I don't think that'd be visible to them over HTTPS traffic anyway (without sketchy goings on).
Since your scenario and environment is different to one discussed here please open a new support issue so you can detail out your specific case/environment.
