### ISSUE TITLE
imprint

### ISSUE THREAD

**Issue by xiaoveiti** [BookStackApp/BookStack#2221]
Any chance to get the option for in imprint? Or maybe I'm not seeing it? 
But at least here in Germany you need an imprint for nearly everything which is accessable by public. So a simple wiki page would count as journalistic research, ... which requires an imprint. 

would be nice if there would be the option to just add a simple/lean page with the basic imprint information and add a link to the footer or the navigation bar on top. 

I guess this would be very useful for all German users, who run a public bookstack :)

**Comment by gxf0** [comment]
seems there is at least some workaround - https://github.com/BookStackApp/BookStack/issues/854

**Comment by Silverlan** [comment]
I'm from Germany as well and I have the same issue. Having an imprint on your site is required by law for most use-cases, which makes bookstack unusable without modifications... It also needs to be accessible from all pages, so just putting it into a book is not an option.

**Comment by Tastaturberuf** [comment]
You can make update safe views https://www.bookstackapp.com/docs/admin/hacking-bookstack/

**Comment by ssddanbrown** [comment]
[As of v21.04](https://www.bookstackapp.com/blog/bookstack-release-v21-04/) it's now possible to define custom footer links which are shown on almost every (Just not the content editor pages) view. Using this you could link to a page within your BookStack instance or an external page.

I wouldn't really want to define some kind of separate "Imprint" page/option within the system itself since that's very use-case specific and would likely lead to several other similar requests for various one-off specific pages. 

Hopefully the additions in v21.04 cover the core requirement requested here so I'll close this off.
