### ISSUE TITLE
Update the upgrade docs to include dotenv changes

### ISSUE THREAD

**Issue by n0nag0n** [BookStackApp/BookStack#2224]
**Describe the bug**
Just upgraded our wiki from an older version (possibly from Jan-Feb this year). In my `.env` file, I had a `DB_PASSWORD` value that had a `@` and `#` character in it. After performing the upgrade my user suddenly didn't have privileges to the db (and the migration wouldn't work either)

**Steps To Reproduce**
Create a user/pass for MySQL and include the `@` and/or `#` characters in it. I suspect it's probably `#`.
Try to migrate, or load the site. It'll fail with perms issues.

**Expected behavior**
Shouldn't blow up :)

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): 0.29.3
 - PHP Version: 7.2
 - Hosting Method (Nginx/Apache/Docker): nginx

**Additional context**
I've already fixed this. I simply changed the password to something without those characters. I imagine that if I had put quotes around the password for `DB_PASSWORD` it would have fixed it as well now that I think about it.

**Comment by ryanc-me** [comment]
See [#27850](https://github.com/laravel/framework/issues/27850) on Laravel - it looks like strings need to be `SETTING="quoted#"` if they have hashtags in them.

Perhaps the Bookstack docs should be updated with a reference to this?

**Comment by alexmannuk** [comment]
This is default behaviour from the php dotenv library which was updated in between Laravel versions 5.7 and 5.8 where # is treated as a comment unless quoted. This should definitely be in the doc, will aim to make a PR for the doc later

**Comment by ssddanbrown** [comment]
Thanks for raising and reporting @n0nag0n; And thanks for supporting @ryanc-me and @alexmannuk.

In September I updated the default `.env.example` file to include a note about this case: https://github.com/BookStackApp/BookStack/blob/00308ad4ab9302293afd0a65f815feeaca06b626/.env.example#L6-L7

Really, I should have included this in the v0.28 update notes but it got missed. Missed the boat on that one by this point. Since I added the note to the `.env` for future users I'll close this off.
