### ISSUE TITLE
Latex support Tinymce

### ISSUE THREAD

**Issue by brechtgijsens** [BookStackApp/BookStack#2231]
Latex code integration is a subject that's already discussed a few times, I think i found a nice way to integrate this although I am not very familiar with the code structure of this project. If I'm right the tinymce editor is used in the project. 

[This link](https://gitlab.com/francoisjacquet/TinyMCE_Formula/-/tree/master/tinymce-formula) links to a project which integrates equations and formulas. I tried to connect it with my version but I can't find it to work.

Would it be possible to integrate this? I think it would be a handy feature instead of using the drawio method.

**Comment by ssddanbrown** [comment]
Thanks for the recommendation @brechtgijsens. It appears the official repository for the linked code [can be found here](https://github.com/iCAPLyon1/tinymce-formula).

Ultimately, while we could quickly add a plugin to tinyMCE, the hard part is considering all other areas of the application. How the syntax is rendered elsewhere, how it's used in the MarkDown editor, how usable the stored format is used if people want to migrate away from BookStack etc...

Additionally, we may be looking to move away from TinyMCE depending on a future evaluation of available editors. 

My review of fully implementing such a feature can be found here: https://github.com/BookStackApp/BookStack/issues/495#issuecomment-628919106

I'm going to close off this issue since there are already various other issues open for latex or similar support.
