### ISSUE TITLE
Some questions about the search function

### ISSUE THREAD

**Issue by BarryBooder** [BookStackApp/BookStack#2232]
**Describe the bug**
Hello, I am a Chinese user. Bookstack's search feature is less friendly to Chinese search support. For example, I have a book called "I want to swim" (In Chinese), but if I search for "swim" in Chinese, the search will be unsuccessful. After testing, it is found that Chinese search can only match words from left to right, and cannot span words on the left, or extract some parts of words from the whole sentence for searching.

**Steps To Reproduce**
1. Build a book
2. Fill in book contents
3. After saving the contents of the book, return to the home page
4. Search the search bar for Chinese words

**Expected behavior**
The Chinese search function should be the same as the English search function

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings):0.29.3
 - PHP Version:7.2
 - Hosting Method (Nginx/Apache/Docker): Nginx

Thanks！

**Comment by ssddanbrown** [comment]
Hi @BarryBooder,
Thanks for the request. Yeah, This is an unfortunate result of how I implemented in indexing for the search system, It will split indexed tokens on punctuation and spaces then left-match them when searching which does not work for chinese text.

Since this is already open under #778 I'm going to close this off as a duplicate.
