### ISSUE TITLE
Change default editor to SimpleMDE

### ISSUE THREAD

**Issue by nguyenrom** [BookStackApp/BookStack#2251]
I have used both https://www.notion.so/ and http://coda.io/ . The featured keep continues to use it is a Block Editor, the way to make docs is powerful and smooth.

With https://simplemde.com/, you don't need to make the end-user choose WYSIWYG, SimpleMDE has both in one screen.

![image](https://user-images.githubusercontent.com/7044465/92563097-3c16b900-f2a1-11ea-87ac-9bbd2e5a5318.png)

**P/s**: I see BookStack used Laravel, https://github.com/VanOns/laraberg do you think it's a good idea?

**Comment by ssddanbrown** [comment]
Thanks for the suggestion @nguyenrom.

I don't see SimpleMDE being a suitable replacement to the current WYSIWYG editor since it does not directly provide a WYSIWYG view but an enhanced markdown view with preview. There is still markdown syntax shown in the content which would make it confusing to those unfamiliar with markdown. BookStack is intended to be usable and friendly to those that are not overly technically inclined, Maybe only familiar with word processing apps.

**Comment by kayvanaarssen** [comment]
As i suggested before I love to write in markdown it much faster.
Others prefer normal writeups.
But instant on the fly conversion would be so good!!

Changing it in the settings is mot the way to go.

If I want to markup a code line or codeblock.

Now I have to type the code highlite and set it to a code line or codeblock.
More work more clicks not a nice experience...

I've seen more than one request for simular things like this post. So people want it. Please provide the options/ best solution there are many out there.

**Comment by ssddanbrown** [comment]
@kayvanaarssen Just as a tip, it's worth looking at the [WYSWIYG shortcuts](https://www.bookstackapp.com/docs/user/wysiwyg-editor/) as they can speed up some of your pain-points, I think we even keyboard-optimised the code-block flow a release or two ago. 

I understand that people want to be able to change editor, I will be keeping this in mind when reviewing the editors as the next [upcoming stage on the roadmap](https://github.com/BookStackApp/BookStack/#%EF%B8%8F-road-map). 

I'm going to close off this issue due to the reasons in my previous comment above from September.
