### ISSUE TITLE
Search Features

### ISSUE THREAD

**Issue by javadevelopment4** [BookStackApp/BookStack#2252]
#1 Able to preview the searched results in a small window
#2 The keyword searched for, should be higlighted in all places when we open the search results windows and it's subsequent pages
#3 Type-ahead search with the number of matches found if possible for the entered keyword with auto-suggestios
#4 Previous, Next and exact match count should be accessible easily

**Comment by fklappan** [comment]
Due to the GitHub issue referencing feature, all your points link to unrelated tickets. You could use 1. 2. 3. instead.

**Comment by ssddanbrown** [comment]
Thanks for your suggestions @javadevelopment4 but I'm going to close this off due to the combined effects of the following:

1. Issues that contain a list of requests are hard to manage on here.
2. Some of your requested features have already been requested.
3. This does not follow the feature request template where the measurable benefits for existing BookStack users would be specified.

**Comment by passionate2023** [comment]
is the above search features are available in the latest release?
