### ISSUE TITLE
Updated to 0.12.2 - settings still stated 0.12.1

### ISSUE THREAD

**Issue by jsreynolds** [BookStackApp/BookStack#227]
Expected Behavior:
Settings page would show updated version.

Actual Behavior:
Still looks like the older 12.1 version

See http://imgur.com/CkYtU4m  for update results.

**Comment by ssddanbrown** [comment]
Hi @jsreynolds,

Thank you for reporting this. I think this may be the same issue as #108 (Which has been fixed, ready for the next release). It's due to your local BookStack git repository not being up-to-date. If you run `git fetch --tags` and then re-check the settings it should show the latest actual version. 

The next version of BookStack uses a non-git way to determine versioning so should not have the same issue.

Let me know if the above works or if the issue appears to be something else.

**Comment by jsreynolds** [comment]
Oh I feel dumb about not trying that. Sorry!

Thanks again.

Best,

John

**Comment by ssddanbrown** [comment]
@jsreynolds No worries, Too me a while to find this same issue 😄.

I'll close this since it's fixed in the upcoming release.
