### ISSUE TITLE
Whoops, looks like something went wrong. (No update was made)

### ISSUE THREAD

**Issue by geekedtv** [BookStackApp/BookStack#2281]
When trying to save or edit a page, it fails and gives this error. "Whoops, looks like something went wrong." I have not updated at all since I began using Bookstack. All I did was reboot my server and this began happening.

Tried restarting the container and even rolled back to a backup from yesterday when I know it was working and it still breaks when I edit pages. tried disabling dark mode too as some have suggested and still does it.

This is the first time I've had issues and I saw people were getting this after updating but I haven't updated...

Installed on Ubuntu.

**Comment by ssddanbrown** [comment]
Hi @nashosted, There was an issue in a previous version of the linuxserver.io image where a faulty PHP config file would be written out which would cause this. This config file would then only get picked up after a restart. I believe it has been fixed but, after upgrading the container, you may need to restart the fresh one so that it updates the config file on first run then uses it from second run.

**Comment by ssddanbrown** [comment]
Since there's been no follow-up I'm going to close this. If the issue remains and is something you still require to be fixed please open a new issue, referencing this one.
