### ISSUE TITLE
Text editor on Demo Instance not working

### ISSUE THREAD

**Issue by ezzra** [BookStackApp/BookStack#2282]
It looks like the Demo instance is not working correctly, the text editor for new pages or editing is not loading (just grew)

https://demo.bookstackapp.com/books/dummy-content-book/page/face-without-dont-abundantly-had-dont-living/edit

for example

**Comment by ssddanbrown** [comment]
Hi @ezzra,
Can you provide any detail in regards to browser version in use and operating system?
I've had another report of this via discord but I have not been able to replicate as of yet, It loads fine for me.

**Comment by mdangers-DE** [comment]
Hi @ssddanbrown ,

I'm seeing this issue on Linux Mint 19.3 Cinnamon running Firefox 71.0 (64 Bit).

**Comment by ezzra** [comment]
I had the problem with Linux Firefox ESR 68 which was outdated for a few days now, console error was:

`SyntaxError: expected expression, got '?' app.js:1:7518`

**Comment by ssddanbrown** [comment]
Thanks both for confirming browser versions.

@ezzra Got to admit, this is my first time coming across Firefox ESR versions, It's not something I've previously thought to test against and, to be honest, not something I'd probably look to officially support/test-within. That said, I'd be happy to fix any issues that specifically arise in `ESR78` for a while. I think `ESR 68` is just a tad too old to make changes to support since we're beyond the cross-over period between ESR releases at this point.

**Comment by ssddanbrown** [comment]
@ezzra Might be worth trying things again. I've just published a new release with a tweak to the build system since the aggressive use of modern JS was causing issues on current mobile browser versions that were using lagging-version engines, so things might work now. 

I'll close this off now due to my previous post but if you do have any issues in ESR78 please feel free to raise them here.
