### ISSUE TITLE
Editor can't escape link in same line

### ISSUE THREAD

**Issue by Zyzto** [BookStackApp/BookStack#2308]
**Describe the bug**
link function can't be escaped in same line for normal paragraph

**Steps To Reproduce**
1.Create page
2.insert url/link using built in function
3.try to enter anything after the link

**Expected behavior**
for the link/url function to not take over unless I click on it so it's doesn't lock normal text like inline code if you click the right arrow two times it will escape it

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings):0.30.2v
 - PHP Version:7.2.24
 - Hosting Method (Nginx/Apache/Docker): nginx

**Additional context**

**Comment by ssddanbrown** [comment]
Just done some testing on the following:

- Chrome 96.0.4664.45 
- FireFox 94.0

Using BookStack v21.11 and running the browsers on Fedora 35.
In both browsers I could escape the link quite easily by pressing right arrow. This was tested with both a fully linked section and with linked text within a greater block. 

Will therefore assume this issue has since been resolved.
