### ISSUE TITLE
Bookstack keeps returning 403 forbidden errors

### ISSUE THREAD

**Issue by hwittenborn** [BookStackApp/BookStack#2326]
I recently installed Bookstack through the [manual method](https://www.bookstackapp.com/docs/admin/installation/#manual) on an Ubuntu 20.04.1 install, but every time I try to visit the site for it, it gives out a 403 forbidden error on Nginx.

I check file/folder perms and ownership several times as well as making sure the root was set correctly in nginx, but it makes no difference.

What should I check next? I'm trying to look around for a good nginx config for Bookstack to see if that would help at all, but I can't find any.

**Comment by ssddanbrown** [comment]
Hi @hwittenborn,
Sorry to hear your are having problems.
We have a simple example of an nginx config in the devops repo:
https://github.com/BookStackApp/devops/blob/master/config/nginx
I think this config should work on Ubuntu 20.04 since 20.04 comes with php7.4 by standard, which that config is intended for.

Upon that, are you getting any clues in your access or error logs for nginx?  (In `/var/log/nginx/`)

**Comment by hwittenborn** [comment]
That config did the trick, thanks!

I always forget to check logs, sorry for any trouble on that -- php7.4-fpm wasn't installed, installing it did the trick though.

Again, thanks for the help, it's appreciated!

**Comment by ssddanbrown** [comment]
No problem, Glad to hear you got things working.
