### ISSUE TITLE
Add option to manually sort chapter contents from chapter view

### ISSUE THREAD

**Issue by Rumcajsev** [BookStackApp/BookStack#2335]
**Describe the feature you'd like**
An option to manually sort pages inside the chapter view. This could be limited to sorting only the contents of given chapter.

**Describe the benefits this feature would bring to BookStack users**
Corrently if I enter the chapter and decide I want to sort its content (pages) I gave to go back to book view, and there I can access manual sorting tool. This is sometimes annoying as I need to go to previous screen, search through the chapters in the book again and only then can I sort the paged inside specific chapter.

By being able to sort the chapter contets directly it would make it quicker and more user friendly to make a quick edit to order of pages inside a chapter.

**Comment by Wookbert** [comment]
+1

It's really annoying that one has to leave the chapter view and change to the book view, in order to sort the chapter one is looking at. Every time I need to sort a chapter I'm confused by that and click on "Move", just to realize then, that this is "Sort". So, this is what we need:

![image](https://user-images.githubusercontent.com/3104762/104781339-9a3d3680-5782-11eb-80b7-0220e629f1bd.png)

**Comment by nightsparc** [comment]
I was just about to write a new feature request for this :see_no_evil:

So, yes, please! 

It would be real useful to be able to sort chapters individually! The current state (sorting only on book level) only works for smaller books, but gets really cumbersome once the number of pages exceed a certain limit (i.e. if the page list is longer than your vertical screen size).

For example, we' re using bookstack to record minutes of meetings, both internally and externally. For that, we're using an iso-date prefixed page title and we prefer to have the most recent MoM on top of the stack. Thus, every time we add a new MoM page we have to manually move the page to the top. Which is really annoying :D

I mean, we're really happy with the automatic sorting functions on the book level, however, they sort everything, which would require us to prefix our chapters with ugly 00,01,02,10... - I mean, yes real books have chapter numbers, but, c'mon :D

**Comment by singleseeker** [comment]
very useful, wait for new update.

**Comment by superojla** [comment]
Any update on this? It would be very useful - we tend to have lots of pages in chapters in my company, and the possibility to sort them manually would really make our lives easier.

**Comment by ssddanbrown** [comment]
@superojla no update but you should still be able to manually sort chapter contents at a book level, via the sort action when viewing a book.

**Comment by ssddanbrown** [comment]
Within  #3598 I've added a "Sort Book" option to the actions list when viewing a chapter. This will take you to the same view as the "Book" sort view.
This will be part of the next feature release. 

Since I believe this covers the fundamental request of this issue, I'll go ahead and close this off.
