### ISSUE TITLE
[Feature Request] extension of the export function

### ISSUE THREAD

**Issue by wtfbaxxter** [BookStackApp/BookStack#2351]
**Hello :)**
At first thank you all for making these software. Im using BookStack for my informatic study and its makes everything better. After working some weeks with this software, i have 2 ideas that really improve BookStack. I will cluster them in 1 request, cause they all related to the export function:

**1 Export sites to Microsoft word (docx)**
A page can currently be exported to html, pdf and txt. I would like to convert the page to word (docx). The possibility should be listed under export. 

Maybe we can discuss about more types.

**1 Benefits**
Sometimes you work at school, university, work, freetime with people you can't or don't want to give write permission to. Therefore a clean export to word would be a good idea to pass on the file. I have read the "workaround" in https://github.com/BookStackApp/BookStack/issues/1273 , but i not really like it :(. Maybe its usefull enough to spend time on this feature :).

------------------------
**2 posibility to add page numbers**
Im really want the posibility to add page numbers, especially for exporting to pdf (or word :)).

**2 Benefits**
If you writing books or stuff for university page numbers are really usefull.

**Comment by ssddanbrown** [comment]
Hi @wtfbaxxter,
Thanks for the feedback. 

The request for PDF page numbers on the export is already open under #1811 and the request for docx export is already open under #1273. 

You can add a thumbs-up reaction to the original posts in those issues to show support, or add comments if you have something to add.

Good to hear about the use-case from a study perspective. 
Since both of the requested features are already open under existing issues I’m going to close this off as a duplicate.
