### ISSUE TITLE
Support links in Shelf/Book descriptions

### ISSUE THREAD

**Issue by qwertyuu** [BookStackApp/BookStack#2354]
**Describe the feature you'd like**
Right now the "Description" part of a shelf or a book is only plaintext. I would like, at least, for it to support links... if not markdown

**Describe the benefits this feature would bring to BookStack users**
We use Bookshelf to document a project and having "post-it" links would be beneficial to everyone in my opinion 

**Additional context**
Here is an example of a link in a description
![image](https://user-images.githubusercontent.com/3145639/98205208-b9f3eb00-1f05-11eb-9d7b-bc163e763225.png)

**Comment by bennyandresen** [comment]
I hope I'm not breaking etiquette but I looked for an already existing issue about markdown in the description and I can only confirm that I'm also looking forward to that feature for the exact same reason.

**Comment by axelsimon** [comment]
I'm also surprised that while book pages can contain markdown, the "cover" of a book cannot, so you just end up with unclickable links.

Any plans to fix this?

**Comment by ssddanbrown** [comment]
> Any plans to fix this?

It's not really something I see to "fix" since it's not really a bug IMO.
Probably won't support markdown in these boxes, as that doesn't really work to the target audience/UX I aim for, and I don't want to support multiple implementations for different audiences like with the page editor.

As per the ["Next Steps" of our latest release post](https://www.bookstackapp.com/blog/bookstack-release-v23-08/#next-steps), I may look to align a few areas with a simplified WYSIWYG editor, which could include description boxes to bring simple formatting.

**Comment by bennyandresen** [comment]
If a simplified WYSIWYG editor is introduced that converts a subset of formatting to html including `a` and can, as the current description can, be set via the API, then my use case would be satisfied.

**Comment by nikkilocke** [comment]
I can't understand what the objection is to allowing markdown. It appears to be easy to implement, it wouldn't affect users who don't need it (they are unlikely to use markdown here by accident), and it allows cross-referencing between books (for example).
If voting counts, I vote for the change.

**Comment by ssddanbrown** [comment]
> I can't understand what the objection is to allowing markdown.

@nikkilocke One of my core focuses for BookStack has been to create a platform suitable for mixed-skill environments, to the general idea of it being comfortable to anyone that is comfortable using a word processor. 
I'm not keen on adding abilities to core content functionality that may be less accessible & intuitive to that target audience, especially as this could be used in that mixed-skill environment leaving less-technical users to come across markdown provided by other more technical users.

> It appears to be easy to implement

Ease of implementation is rarely a reason for me to consider something to be honest.
It's easy to add things, but they all have a cost so I'm relatively strict on anything added to the platform, however small.
Purpose, functional benefit, existing-audience desire, fit with other platform features/functions, and platform suitability relative to our intended audience are usually larger factors I consider.

> If voting counts, 

I do consider the :+1: reactions on the original post in the thread. Not really needed here though since, as per my last comment, I am intent in working towards this.

**Comment by ssddanbrown** [comment]
A WYSWIYG for description inputs, with the ability to use links upon some other simple formatting options, has now been added via PR #4729 and will be part of the next feature release. Therefore I'll close this off.

Thanks @qwertyuu for the original request here.
