### ISSUE TITLE
Don't allow 2 users edit 1 page at the same time

### ISSUE THREAD

**Issue by lealka** [BookStackApp/BookStack#2355]
When 2 users edit 1 page at the same time, the content of the previous editor will be replaced by the last editor.

So, We can put a flag if someone is editing a page and disallow another one edit it.

Problem:
[1] Someone is editing a page and S/He logout without clicking the `Save Page` button. The flag is existing forever.

The `test mock` string (first save action) was replaced by `test` string (last save action)
![image](https://user-images.githubusercontent.com/8043284/98210732-96678980-1f73-11eb-9860-b30cfb26aeb2.png)

**Comment by boonduck** [comment]
Bookstack is a client/server web application and therefor inherently multi-user. So ideally, Bookstack should support modifications by multiple users of the same resource at the same time, very much like Google Apps. The real question is how to implement this. I have seen people editing the same cell in Google Sheet in real-time without any modification being lost. In fact, all my colleagues at work use Google Sheets this way.

**Comment by Supergamerx3000** [comment]
Yes I think so too. There should be an official collaborative function. Since I work in a company and we have documentation teams, we currently also work with office 365 and create collaborative documentation. I am a big fan of OpenSource and would like to use Bookstack for it. An alternative is Nextcloud with Onlyoffice or Collabora, but there the organization is not as nicely solved as in Bookstack. Maybe there will be a bookstack integration in Nextcloud at some point.

**Comment by ssddanbrown** [comment]
Thank you for your request @lealka.

Since this request is already open under #395 I'm going to close this off as a duplicate.
