### ISSUE TITLE
Code block frame hide its content

### ISSUE THREAD

**Issue by v1rals** [BookStackApp/BookStack#2370]
**Describe the bug**
Code block became gray and does not show content of page in edit mode. 
![image](https://user-images.githubusercontent.com/59255336/99241381-d994e880-280e-11eb-83f0-b7f3af6c56f1.png)

**Steps To Reproduce**
1. Go to any empty page
2. Add 50+ code block of JSON with one string 
![image](https://user-images.githubusercontent.com/59255336/99241628-28db1900-280f-11eb-958d-692221a00461.png)
3. Save page.
4. Exit edit mode and enter it again
![image](https://user-images.githubusercontent.com/59255336/99241946-94bd8180-280f-11eb-9975-d42e4f42d5dc.png)

**Expected behavior**
Open the saved page in edit mode and see the code in blocks.

**Your Configuration (please complete the following information):**
 - Exact BookStack Version: BookStack v0.30.4
 - PHP Version: PHP 7.3.24 (cli) (built: Oct 30 2020 13:32:21) ( NTS )
 - Hosting Method: docker/linuxserver

**Additional context**
If we press 'undo' button on page with gray code blocks - they will magically begin to shows its content.
![image](https://user-images.githubusercontent.com/59255336/99243193-60e35b80-2811-11eb-856c-f25891d00207.png)

**Comment by ssddanbrown** [comment]
Thanks for reporting @v1rals.

This could occur in some scenarios as the code block rendering update has been done on a timer which could be fired sooner than the content is ready in some cases, especially when there's many code blocks.

As part of the work in #2518 I've changed how code blocks are rendered to a page to make things more efficient and more event-based rather than timer based. 

These changes will be part of the future v0.32 release. If you still have issues after that release feel free to open a new issue referencing this one.
