### ISSUE TITLE
[Feature Request] Multi Attachment Uploads

### ISSUE THREAD

**Issue by athornfam2** [BookStackApp/BookStack#2372]
**Describe the feature you'd like**
I'd like to request multi attachment uploads under the "chapters" section

**Describe the benefits this feature would bring to BookStack users**
I recently converted over from Confluence *PAID* to BookStack and found it lacking an option to drag and drop multiple files into a chapter. This prolonged my transition over to BookStack and will take more of my time to upload other attached items later on when I make more documents.

**Comment by ssddanbrown** [comment]
Thanks for the request @athornfam2.

I'm a little confused on the fundamental request for issue. What of the following do you desire?:

1. The ability to upload attachments to chapters.
2. The ability to upload multiple attachments in a single operation on pages.

In regards to the listed benefits, these are usually intended to be focused on what the feature would bring to general existing BookStack users rather than personal benefits. I prefer to prioritise features that benefit existing users over attracting new users, and knowing the benefits to existing users can help assess if a feature is worthwhile to implement and maintain since it's likely not if it only benefits a single instance.

**Comment by athornfam2** [comment]
I'm requesting, as a feature, to add multi-attachment support on a per chapter level. I don't know "who" wouldn't want this function  especially if you need to upload a manual, reference pictures rather than injecting them into the document, raw files, etc...

**Comment by ssddanbrown** [comment]
Okay, So you're after any ability to upload an attachment to a chapter, whereas BookStack only currently offers attaching files to a page.

I'd rather keep chapters as an organisational element, rather than an element that contains content (including attachments) itself, since that's focused on pages currently. I like the currently focused simple nature of the chapter, and adding more content options to chapters may just lead to more confusion as to where content should lie. 

To consider supporting such a change in the future, I'd need to hear good reasoning why attachments at the chapter level would be a benefit over the current page-only implementation.

**Comment by ssddanbrown** [comment]
Since there's been no further discussion or reasoning in the past year I'll close this off.
