### ISSUE TITLE
LDAP Group synchronization: memberUid attribute

### ISSUE THREAD

**Issue by das-kaesebrot** [BookStackApp/BookStack#2380]
**Describe the feature you'd like**
LDAP Group synchronization by the `memberUid` attribute

**Describe the benefits this feature would bring to BookStack users**
Implementing this feature would make it possible to use Bookstack in conjunction with an OpenLDAP server using posixGroups for authorization and Bookstack permissions management.

As of right now, it is only possible to synchronize user groups from an LDAP server to Bookstack using the `memberOf` attribute (or another group attribute written to the LDAP user him/herself). Considering that there are quite a few OpenLDAP servers using the `posixGroup` group type which does not support `memberOf` attributes ([See here, for example](https://tylersguides.com/guides/openldap-memberof-overlay/)) it would be a great enhancement to implement group synchronization by `memberUid`.
The main difference between `memberOf` and `memberUid` is that there is no membership attribute written to the user him/herself, the membership is instead stored only as a `memberUid` attribute in the posixGroup, containing the uids of all group members.
(Please excuse my formatting, this is my first time posting an Issue on GitHub...)

**Comment by tiredofit** [comment]
`memberUid` has been deprecated for a long time now with people moving onto RFC2307bis `memberOf` overlays. I get the feeling the dev does not want to invest much more time in authentication functionality as its working for the majority of users and wants to focus on improving the overall application.

**Comment by ssddanbrown** [comment]
Thanks for the request @das-kaesebrot.

As @tiredofit has pointed out I would not want to dedicate too much additional time or expand out the auth system features unless there's significant benefit in doing so, to ensure the maintenance burden does not grow much greater. Since noone else has previously or since requested `memberUid` it appears the demand is very much limited and outside that which I'd deem worthwhile. This is especially so for this case where it is possible to work around the limitation by using a `memberOf` overlay on the LDAP system. Therefore I'm going to close this off.
