### ISSUE TITLE
Page template

### ISSUE THREAD

**Issue by ateliermedia** [BookStackApp/BookStack#240]
### For Feature Requests
Would it be possible to have page templates?

### For Bug Reports
PHP Version:

MySQL Version:

Expected Behavior:

Actual Behavior:

**Comment by Shackelford-Arden** [comment]
Is this similar to #129 ? @ateliermedia

**Comment by ateliermedia** [comment]
@Shackelford-Arden I guess so. I am speaking about content templates, the possibility to create pages with some pre-filled content (some headers, paragraphs).  In the long run, will save a lot of time and would be extremely useful for consistency (e.g. all documentation pages having the same structure, meeting minutes pre-filled with section titles and participants). Templates could be created in the settings section and propose a new link on top "New page from template" next to "New page". Maybe rename it "New blank page"? (a modal to serve the templates list with a short description bellow each template title?). If it is in the sidebar, I guess most of the users will forget about the existence of this feature or they will realize it exists when they've already worked a part of the page and they will maybe lose the work upon template apply and page refresh. Just some ideas.

**Comment by ssddanbrown** [comment]
Hi @ateliermedia, Since this is very similar to #129 I will close this issue.

I get what you're saying about the template system needing to be obvious so thank you for your ideas. At the same time, I don't want it to get in the way to those who won't use it.

After that feature has been implemented, If you think it's not obvious enough just open a new issue at that time and we'll discuss what we could do then.

@Shackelford-Arden Thanks for noticing the similar issue.
