### ISSUE TITLE
Give more power to the WYSIWYG Editor.

### ISSUE THREAD

**Issue by asiamaster2** [BookStackApp/BookStack#2402]
**Describe the feature you'd like**
A tool bar menu like an adding macros 
 - task list
 - date
 - markup
 - ETC

Choose the color for the background of table and cell instead of typing.
 - I think it's a good idea to make the first row bold and colored automatically.

**Describe the benefits this feature would bring to BookStack users**
 - Easy to draw a table, easy to use BookStack as a documentation tool.

**Additional context**
 - Thank you so much for your effort and providing this quite good tool, I appreciate.
 By the way, I'm having the problem that editor pasting an image instead of table when I copy and paste it from excel.  
 Bookstack version is 0.30.5/ windows 10 and MS office 2016.

Thanks

**Comment by ssddanbrown** [comment]
> Thank you so much for your effort and providing this quite good tool, I appreciate.

Thanks @asiamaster2!

- Checkboxes are already open under issue #4 which I believe would meet the "task list" request.
- Date is a little tricky as you can quickly delve into conversations about localisation and format.
- Not really sure what is meant by "markup". Like a code block? Those are available under the formats menu.

> Choose the color for the background of table and cell instead of typing.

I can get how a color picker would be easier but I'd imagine table colouring is going to be fairly uncommon in popularity to deem it worth spending time improving the user-experience in that small area.

>  I think it's a good idea to make the first row bold and colored automatically.

Maybe, I'd often agree it would in most cases where I use tables, but it's a little dangerous to assume this would work for the vast majority. This could actually be added right now with a little custom CSS added via the "Custom HTML Head Content" setting:

```html
<style>
.page-content table > tbody > tr:first-child td {
    font-weight: bold;
   background-color: #eee;
}
</style>
```

I'm going to close this issue off due to the above reasons/workarounds and since issues listing multiple desired features are really hard to manage. Within the next year we'll be reviewing the page editors so things may change up anyway.

> By the way, I'm having the problem that editor pasting an image instead of table when I copy and paste it from excel.
Bookstack version is 0.30.5/ windows 10 and MS office 2016.

Darn, I've seen this before but thought we had worked around it. Since excel adds both an image and text (In different formats) to the clipboard it can be tricky to detect the right format. Feel free to open this as it's own issue, where you could also provide details of the internet browser you use and ideally an example of spreadsheet content that causes this to occur (A single cell could act differently to multiple cells for example).
