### ISSUE TITLE
Select a language when creating a new user

### ISSUE THREAD

**Issue by Baptistou** [BookStackApp/BookStack#2408]
**Describe the feature you'd like**
I've set my account language to French. When I create a new user, he receives an invitation email in French. I expected that he receives an invitation email according to the .env variable [APP_LANG](https://www.bookstackapp.com/docs/admin/language-config/) which is set to ```en```. Still, his account language is effectively set to English, which is inconsistent with the invitation email.
Could it be possible to add language selector in the user creation form.

**Describe the benefits this feature would bring to BookStack users**
Improve user administration, make language setting consistent.

**Comment by ssddanbrown** [comment]
Thanks for the suggestion @Baptistou.

To be honest, I'd prefer to avoid needing another option in this flow unless very much demanded. 
I'd also expect new users to be sent their invites based on the configured `APP_LANG` rather than the admin's preference.

Would this be solved for you if we focused on testing and ensuring the email sent adheres to the configured `APP_LANG`?

**Comment by Baptistou** [comment]
> Would this be solved for you if we focused on testing and ensuring the email sent adheres to the configured APP_LANG?

The language selector is already present in the user edit form, I thought it would be easy to add it to the user creation form.
But yes, this solution is good enough.

**Comment by ssddanbrown** [comment]
Hi @Baptistou,
I've now applied 6eadf3efb3c460cc450b0c8b67220a5d00125ff7 which adds your original request of a language select box on user create. By default this should reflect the system default language instead of the admin/current-user configured language.

This will be part of the next patch release so will therefore close this off.
Thanks again for your request!
