### ISSUE TITLE
Pages are incorrectly displayed inside a chapter at the book overview

### ISSUE THREAD

**Issue by cdrfun** [BookStackApp/BookStack#2414]
**Describe the bug**
A chapter is readable for Role1 and Role2, but all pages of this chapter are only readable for Role1. When you open **the chapter** for Role2, no pages are displayed. But when you open **the book** for Role2, the pages are displayed under the chapter and the first line of content is shown. 

**Steps To Reproduce**
1. Create a chapter with individual Read rights for Role1 and Role2
2. Create two pages under this chapter with individual Read rights for Role1
3. Open book overview with a user who is in Role2 only 
4. The pages are displayed under the chapter and the first line of content is shown.

**Expected behavior**
When you open the book for Role2, the chapter should be empty.

**Screenshots**
Role2 book view:
![grafik](https://user-images.githubusercontent.com/146877/102345209-4aa9f600-3f9d-11eb-8e8b-70c0dea96798.png)

Role2 chapter view:
![grafik](https://user-images.githubusercontent.com/146877/102345256-5bf30280-3f9d-11eb-8c62-366bb2157cdc.png)

**Your Configuration (please complete the following information):**
 - BookStack v0.30.4 
 - latest Linuxserver Docker image

**Comment by ssddanbrown** [comment]
Thanks for reporting @cdrfun.

Have marked this to be tested and patched as a priority.

**Comment by ssddanbrown** [comment]
Thanks again for reporting @cdrfun, This has now been addressed in v0.30.6: https://github.com/BookStackApp/BookStack/releases/tag/v0.30.6

Some notes from my testing and fixing:

- If the restricted page sat alongside other non-restricted pages within the chapter then this issue would not be apparent. This only occurred when none of the pages within a chapter were visible.
- This applied to a few different areas of BookStack including the sidebar tree views. The biggest concern was book exports since this would include the entire page content in the export. 

Apologies if this issue caused you, or any others, problems.

**Comment by cdrfun** [comment]
I'm glad I was able to help, as I really love bookstack. I've tested the update and the reported behavior is correct now. Furthermore, I tested the export and the plaintext export still is shaky. This is the chapter export result from my test setup:
![grafik](https://user-images.githubusercontent.com/146877/102595981-cb413180-4118-11eb-9e79-8ee161ec525f.png)

But the same error happens when exporting the book.
Shall I create a new issue @ssddanbrown or will the export issue also be handeled here?

**Comment by ssddanbrown** [comment]
Thanks so much once again for reporting that @cdrfun, Was part of the same thing but made worse with the changes in v0.30.6.

Have now deployed a new release to cover this: https://github.com/BookStackApp/BookStack/releases/tag/v0.30.7
Have added these cases along with some additional ones in our automated test to cover for future releases.

**Comment by cdrfun** [comment]
I did a retest and everything seems fine now. Thanks for your fast response, your way of managing Bookstack is great!
