### ISSUE TITLE
[Feature Request] Snippet/Card-like post or pages

### ISSUE THREAD

**Issue by wx-Yao** [BookStackApp/BookStack#2417]
**Describe the feature you'd like**

Hey there, great thanks for making such an extraordinary project! And i can't believe you've been working on it since 2015, that's super long! :) Thank you again!

One thing that had been in my mind when I was searching for personal knowledge base style software, is that it'd be great if i can have the ability to create some card-like or snippet style post, to quickly (in 15 ~ 30 mins) summarize a specific topic I've researched today and put it there properly. 

I understand that the original intention of the project is to build some wiki, or book stack, as the name indicated, style software but honestly many people, at least for me, couldn't allocate big portion of time sitting at a table and write some serious blogs or books. I mean if I'm determined to write a book or long post I'll definitely schedule a plan but most of the time I don't write a book. Instead, I'll spend a day learning something and those processed, multi-source integrated knowledge went through my mind and I really like a place to write them down in 100 ~ 200 words, which doesn't fit into a "page" (some people are fine with those "short post" but I'm not).

One possible demonstration of my idea is [this project](https://github.com/kormyen/memex). It has a [demo](https://kormyen.github.io/memex/).

**Describe the benefits this feature would bring to BookStack users**

Well, as I mentioned above, some people just don't have enough, consecutive time to sit down to write a long post. I'm not sure how big the number is but one fun fact is that most (serious) bloggers just don't update a lot, like a handful of articles per year :).  I think this idea might benefit them and encourage them to express ideas in an easier non-pressure way.

Finally, I totally understand that this idea might (somewhat) contradict the intention of this project and if you disagree with it, I'm totally cool. I just wanna put it here and see the possibilities.

btw, are you willing to accept Github Sponsors? To clarify, It definitely doesn't mean "I pay you to add a new feature" loool. It's just, the first time I saw the demo of this project, I was like "shit this project can't die". And I'll for sure recommend it to my boss as a team documentation tool, majorly because it has Azure AD Auth and, again, it's an amazing tool.

Thanks.

**Comment by ssddanbrown** [comment]
> Hey there, great thanks for making such an extraordinary project! And i can't believe you've been working on it since 2015, that's super long! :) Thank you again!

Thank you so much!

> Finally, I totally understand that this idea might (somewhat) contradict the intention of this project and if you disagree with it, I'm totally cool. I just wanna put it here and see the possibilities.

Thanks for your understanding and the detailed explanation of the benefits you see this bringing.

My thoughts would be that this kind of thing is essentially the management of notes. I don't really want to get deep into fully supporting a shared "notes" system as it'd make it unclear if something should be a page or a note. Additionally I wouldn't want to get deep into the note-taking space especially as there are already many note-taking focused apps out there.

That said, I could possibly see value in having quick-notes at a personal user-level (Not visible to others). We could keep this purposefully simplified so a page is used for anything more complex. They could be called scraps (As in scraps of paper) to fit the theme. This would only really work though if the smaller "scrap" ideas are eventually written into a page otherwise you'd just be using the system as a weak note-taking system. From the sounds of your use-case, you don't have that intention.

I guess a question is, what's wrong with creating pages for the shorter form content? You could just contain all these up in a book so they're all in one place.

**Comment by wx-Yao** [comment]
> My thoughts would be that this kind of thing is essentially the management of notes. I don't really want to get deep into fully supporting a shared "notes" system as it'd make it unclear if something should be a page or a note.

Yeah exactly I get it. That's where I felt might somewhat contradict to this tool. Never mind I'll keep this issue open till 30th Jan. and if nobody really cares I'll close it willingly :) how does that sound to you?

> what's wrong with creating pages for the shorter form content?

Um I don't know, I just feel like short content shouldn't be a "blog" or "post", it should be like "sticky notes" or sth, where they all have their places and values. Not sure how other people think about it. Maybe it's just my problem.

But this

> You could just contain all these up in a book so they're all in one place.

sounds like a tolerable idea. I can have those short "sticky notes" in one place. Sounds ok. I'll use this approach when the issue is closed. Thanks! :)

**Comment by wx-Yao** [comment]
Sounds like this isn't an popular idea :). I'll close this issue.
