### ISSUE TITLE
Search learning improvement

### ISSUE THREAD

**Issue by Di2g10** [BookStackApp/BookStack#242]
### Desired Feature:
Search learning improvement

For each search used store the search term then the article selected and the articles position in the search result list. Once data begins to be collected a priority between search terms can be established to priorities articles appropriately. Also could track the article popularity by number of times selected by search and show these higher in the list.

**Comment by tmikaeld** [comment]
I think this would work best with a Full Text Search engine that has Taxonomy included. 
(Like Rubedo CMS)

And not something that is suitable for a structured thing like a Knowledge Base.

I don't really like the idea of user-optimized search results, because that lowers the priority for the relevance of finding new articles that actually contain what you're looking for.

**Comment by ssddanbrown** [comment]
Thanks for the original request here @Di2g10.

I'm going to close this though as out of scope as I think any effort should be focused on the core search system itself rather than spending time implementing optimization on user-based-selection. Maybe this can be revived in the future, but for now just trying to implement an efficient search system that works for both latin-based and asian languages is tricky enough.
