### ISSUE TITLE
Donate?

### ISSUE THREAD

**Issue by tmikaeld** [BookStackApp/BookStack#243]
### For Feature Requests
Desired Feature:

Just like with other Open Source Projects, I would like to be able to donate to the project so that it has a more probable future with maintenance.

**Comment by ssddanbrown** [comment]
Hi @tmikaeld, Currently there's no donation system set up. Personally, unless I can live of the donations it doesn't make too much of a difference to me as I just work on BookStack when I get some free time (And am not playing Battlefield).

Maybe something like [BountySource](https://www.bountysource.com/) will be better? It would tempt others to get involved and people could donate to features they want. I'll have a further look into it soon and set up an account for BookStack if I don't see any issues with it.

**Comment by tmikaeld** [comment]
@ssddanbrown 

Don't underestimate cashing in on Open Source, you just need to have the right payment/incentive model for it to work. Look at Proxmox, Group Office and even Froala.

In the case of Knowledge bases, there is a huge hole to fill. I was planning on building this myself until I found Bookstack, it fills the hole I currently have even though it's lacking features.

Yeah, BountySource would work fine and make it easier for people to find it.

**Comment by Shackelford-Arden** [comment]
If there was an option to donate, I'd be sure to do so :) This is an app that I'd love to see held onto through the years.

**Comment by JtheBAB** [comment]
I would also like to donate. I guess a simple paypal donation link like https://www.screentogif.com/donate.html is enough. If you get something why not :)

**Comment by partoneoftwo** [comment]
Hi

I now use Bookstack in a corporate setting and for my own personal project documentation needs. Everyone is amazed at "what I do" but it is really Bookstack that makes me shine. I want to give back, and give donations to you from me personally.
It's not about bounty donation, but a spend-it-on-beer-and-have-fun donation.

See the Linux Mint Project and how successful their donation drive is and has been.
https://linuxmint.com/donors.php

**Comment by solus-hq** [comment]
I would like to donate as well, it's a wonderful app and simply leaving your BTC address would be simple and efficient enough.

**Comment by Cave-Johnson** [comment]
Would love to have the option to donate even if its just to buy you a coffee / beer to show appreciation for your continued support of this great piece of software!

**Comment by kauesena** [comment]
I would really like to donate to the project.  (Even though the values would be small since I'm just a student and USD is worth over 5 times BRL these days. =| ) I'm a recent user but I feel that I'll rely on this tool for years and years. Thank you so much, @ssddanbrown, for creating such a wonderful tool. Wonderfully _opinionated_ tool!  And thanks to everyone who's ever contributed.

**Comment by Wookbert** [comment]
@ssddanbrown

After using BookStack for a bit over a year now, I've just realized (again) how good the decision was to leave Edgewall’s Trac behind. (I know, Trac is mainly a bug tracking solution, but I've first and foremost used its Wiki for my knowledge base ... required heavy use of markup language, which just feel outdated and is very time-consuming).

Just had the desire to donate, when I noticed that there is no donation button. Had to search a moment to come across the [sponsorship page](https://github.com/sponsors/ssddanbrown). Problem is: I'm absolutely no fan of subscription models and recurring payments, so I urge you to add other Donation buttons (PayPal, et. al.) to the BookStack website.

**Comment by ssddanbrown** [comment]
Thanks @Wookbert! Yeah, Just been testing out GitHub sponsors since the holidays. I totally understand about recurring payments so will think about setting something else up. I think you might be able to use GitHub sponsors and cancel the sub immediately afterwards. Again, no real need though, I'm living comfortably and there are more worthy causes out there.

**Comment by Wookbert** [comment]
Monthly payment w/ cancelation reminder is exactly what I did after my comment.

(Occasional) donations: I consider it more as a way of saying „Thank you!“ and an acknowledgement of your great work.

Make sure to make the DONATE button prominent, even if you are no dependent on this money. You have a serious product here IMO, which deserves some gratification.

**Comment by ssddanbrown** [comment]
Thanks for your support and continued feedback @Wookbert! Also, thanks to eveyone else that's donated so far!

A note on the GitHub sponsors, GitHub now allow one-off donations and custom monthly amounts. I have enabled both of these as options on my profile.

I'm going to close this off since there's now an official method for donations with a variety of options. As recommended above, I'll probably start to make these links more prominent on the site page and project readmes. 

As said on my original 2016 comment, I don't specifically need the donation income but since then I've realised it allows me to do the following:
1. Pass on the support to the projects & people that BookStack is built upon.
2. Gauge the feasibility of using the income to potentially one day work on open source full time.
