### ISSUE TITLE
Kudos to the move away from Google Analytics

### ISSUE THREAD

**Issue by FMCUSystemAdmins** [BookStackApp/BookStack#2476]
@ssddanbrown, not technically an "issue", but just wanted to shout-out kudos to the decision to move away from Google Analytics. You highlighted something key in the article: "it’s available without paying". That's because the users of the product pay Google with their data!

Also kudos by association for one open-source project leveraging/supporting another :)

**Comment by ssddanbrown** [comment]
Thanks @FMCUSystemAdmins, As said in the article, I was anonymising IP addresses and using domain-based local storage instead of cookies but that still requires some trust in google, and while I personally mostly trust that they probably will respect the privacy of my data, it felt a bit wrong for me to infer the same of my visitors.
