### ISSUE TITLE
UI Not Displaying Correctly

### ISSUE THREAD

**Issue by henryp007** [BookStackApp/BookStack#250]
Expected Behavior:
UI Interface displays correctly.
This could just be a config issue but i don't know how to fix this - Thanks

Actual Behavior:
![image](https://cloud.githubusercontent.com/assets/20864879/20880306/5c7df14e-bacf-11e6-839d-3c9cc5f2d97d.png)

**Comment by ssddanbrown** [comment]
Hi @henryp007,

This is how BookStack would appear if no styles are loaded. I'd guess this is due to one of two things:

1. During installation the `master` branch has been cloned instead of the `release` branch. The master branch does not include compiled CSS or JS content. You can check your version by going to `/settings` and looking for the version number or you can open the `VERSION` file at root of the installation.
2. Something like a browser extension is blocking the request to the CSS/JS files. This could also be due to a mis-configured server setup.

If the issue is not 1 let me know the version you're on and the web server you're using (Apache/Nginx/Something else) and we can go from there.

**Comment by ssddanbrown** [comment]
Closing due to lack of response, Feel free to still comment if you want to respond to the above.

**Comment by theAkito** [comment]
@ssddanbrown 

I got the same issue, [as explained here](https://discourse.linuxserver.io/t/reverse-proxy-for-bookstack-docker-version/1191).

I assume I need a special configuration for NGINX, though I'm not familiar with advanced PHP setups.

**Comment by ssddanbrown** [comment]
@theAkito Do you have the `APP_URL` env option set?

Feel free to open a new issue for this since this one is quite old and closed, hence any responses could be missed.
