### ISSUE TITLE
Feature Request: Option to upload dark mode alternative cover images

### ISSUE THREAD

**Issue by Swoy** [BookStackApp/BookStack#2502]
**Describe the feature you'd like**
A feature that allows us to choose a dark mode equivalent for the cover images on shelves and books (and potentially also on pages)

**Describe the benefits this feature would bring to BookStack users**
This will allow us to create a uniform experience for our readers and more refined customization for our editors. It will also allow us to use light images for the lightmode and darker versions of these for the dark mode.

**Comment by ssddanbrown** [comment]
Thanks for the suggestion @Swoy.

Really I'd prefer to avoid introducing something like this, since this is effectively introducing options to accommodate other options at this point.

One thing you can do that might help is to use CSS filters, in some "HTML Custom Head Content" styles, to alter these images to make them more suitable for dark mode. This was something we included in dark mode, to reduce contrast and brightness of cover images, upon release of the feature but had to revert as it could cause issues in certain cases.

**Comment by ssddanbrown** [comment]
Closing this off due to my reasoning above.
