### ISSUE TITLE
Sort books not possible

### ISSUE THREAD

**Issue by Tealk** [BookStackApp/BookStack#2520]
**Describe the bug**
The book display is missing when editing a shelf

**Steps To Reproduce**
1. Open a shelf
2. Click on Edit

**Expected behavior**
Display of the books that are in the shelf and sorting of them

**Screenshots**
![CleanShot 2021-01-31 at 01 03 03](https://user-images.githubusercontent.com/12276250/106371023-2002d980-6360-11eb-9cc1-8c9a4fc81cb8.jpg)

**Your Configuration (please complete the following information):**
- Exact BookStack Version (Found in settings): BookStack v0.31.4
- PHP Version: 7.4.14
- Hosting Method (Nginx/Apache/Docker): nginx

**Comment by ssddanbrown** [comment]
Hi @Tealk,

That's really odd to see, Even if something on the JavaScript side was to break and no books were found to use you'd still see this:

![image](https://user-images.githubusercontent.com/8343178/106371708-63a91380-635f-11eb-9288-65924e514776.png)

From your screenshot it looks like you're on MacOS? Could you confirm your browser in use?
I've given it a quick test on Safari via my iPad to be sure and all appeared to work there.

Might also be worth testing this [on our demo site](https://demo.bookstackapp.com/books/bookstack-user-guide/page/logging-in-to-the-demo-site) to see if you get the same thing there.

**Comment by Tealk** [comment]
Apparently this can somehow be blocked by adblockers.
I use Safari and Adguard and actually have that turned off on my website.
After turning it on and off again I see the books on the shelf.
It was the same on the demo site.

**Comment by ssddanbrown** [comment]
Thanks for confirming @Tealk.

I could not re-produce with the Firefox extension so could not see exactly why this was being blocked, Possibly due to `.scroll-box` class used, or maybe adguard is suspecting it to be an ad since the sections are scroll-able.

Either way, I don't really want to start changing our code base just to suit the over-reaching filters of a single ad-blocking solution so I'm going to close this off. It does look like the adguard team are fairly responsive upon reported false positives so you could report this there if it's causing you trouble: https://forum.adguard.com/index.php?forums/false-positives.68/
