### ISSUE TITLE
Divide HTML exports into separate pages

### ISSUE THREAD

**Issue by maggie0002** [BookStackApp/BookStack#2537]
**Describe the feature you'd like**
At the moment, when exporting a HTML book all the pages are included in one continuous scroll. In keeping with the book theme of BookStack, an export where there is a separate HTML page for each BookStack page, with a link at the bottom of each to go backwards and forwards. 

**Describe the benefits this feature would bring to BookStack users**
Would provide improved readability and better alignment with the book theme that shapes BookStack.

**Comment by ssddanbrown** [comment]
Hi @maggie0002,
My thinking here very my mirrors [my comments on your PR here](https://github.com/BookStackApp/BookStack/pull/2524#issuecomment-773648822).

I'd rather leave specific use-cases to the API otherwise we can easily get dragged into need to support a variety of further customizations on the output. 

This might possibly be of interest: https://github.com/BookStackApp/api-scripts/tree/main/php-book-to-static-site
It's a very simplistic, quickly created example but creates a little static site of a book using the API.

**Comment by maggie0002** [comment]
> I'd rather leave specific use-cases to the API otherwise we can easily get dragged into need to support a variety of further customizations on the output.

Indeed, this is one I hesitated on posting as I probably would have said the same thing. Glad I posted though as that referral link to the static site generator is of great help.

Thanks
