### ISSUE TITLE
Automatic Start with Webserver

### ISSUE THREAD

**Issue by Screamy86** [BookStackApp/BookStack#2538]
Hi,

i got bookstack finaly installed on a Windows 2016 Server, its running with a WAMP. Now i always have to be logged on the Server remote and open a command-line in the bockstack directory for this particular command "php artisan serve --host 0.0.0.0 --port 8080". With this bookstack is working in our company network. Can anyone tell me how i can setup the server, so bookstack will be automaticaly started without any remotesession on it? I Tryed already like its written in this post https://stackoverflow.com/questions/55087585/how-to-autostart-xampp-and-laravel-project-in-windows . But unfortunally this is not working. For the notes only "php artisan serve" is not working outside the server, so i got only successful with full command like written above. 
Thanks for any help!

**Comment by ssddanbrown** [comment]
Hi @Screamy86,
Ideally you'd be running it on a webserver; WAMP should include Apache. Running via `php artisan serve` instead using PHP's built-in development server instead of Apache. If you can get it running on Apache you might have better luck with the stackoverflow solution.

**Comment by Screamy86** [comment]
Hi,
thanks for the reply. So that i understand you right. Its normal to run bookstack with php artisan serve command? Or can you tell me whats the best way to run bookstack automatically and how to set it up? Like i wrothe, at the moment i need to have an active remote session to the server and run it with the command in command line. I like it to run it without any actions needed, so when the server restart, I would not need to do anything and can open bookstack within our company network.

**Comment by ssddanbrown** [comment]
> Its normal to run bookstack with php artisan serve command?

No, The command is really just for development purposes. 

I don't really use windows for production level web hosting so my knowledge in that area is limited. As said above, WAMP includes Apache so you'd typically use that to host BookStack. 

BookStack is based on Laravel, so that might help you find some guies, You'd likely need to setup a "VirtualHost" for the bookstack site, pointing to your BookStack install's `public` folder.  You could try searching for "WAMP Laravel Setup Guides" or "WAMP VirtualHost Setup".

I could attempt to help further but I'm not often on a Windows machine, and I'd need to know what version of WAMP you have, where you've got BookStack installed and where you have WAMP installed.

**Comment by Screamy86** [comment]
Hi, 
thanks alot. You pointed out that i need to set the path of apache to the "public" folder. That helped alot. Now it works with apache, only on the server with localhost, but its a start :). Now try to figure out how to make it accesible in company network, but this is not a bookstack topic i think. Nice work with the bookstack, i like it!

**Comment by ssddanbrown** [comment]
@Screamy86 Cool! Will therefore close this but just shout if further help is needed.
