### ISSUE TITLE
BookStack MetaSearch Browser Extension – Search the web (e.g. Google) & BookStack at once

### ISSUE THREAD

**Issue by Wookbert** [BookStackApp/BookStack#2540]
Boy, here comes an insane one, but it would be so great and helpful...

**Describe the benefits this feature would bring to BookStack users**

Well, the problem is that I have so much stuff and so many projects going on, that I quickly (after a few months) forget which information in detail I've written down/archived in BookStack. So there is a good chance, that after three quarters of a year or so, I'm confronted with a certain technical issue, a problem, a bit of missing knowledge, which I'd actually sorted out before, but forgot that I took the effort to write it down in BookStack.

So instead of simply looking it up in my BookStack knowledge base, I start from scratch doing a Google search on the web. Chances are that the Google result includes sites still marked in purple which I've previously visited in search for a solution, but still it’s a time consuming process to start from scratch ... and stupid if the answer is already there/here in my BookStack.

**Describe the feature you'd like**

It would be awesome if there’d be a BookStack browser extension (I'm using the latest Chrome on mac OS Big Sur), which when you do a web search through the browser’s URL bar takes the search string and searches your (previously defined, personal) BookStack account for that string too (so in addition to Google searching the web) and then lists any results found somehow above the Google search results. Get the point?

**I mean that’s the big, big problem: Remembering which information you put where.**

**Comment by ssddanbrown** [comment]
Hi @Wookbert,

Sorry for the late response on this. I've been meaning to provide at least some guidance on this but never got round to it.
I don't really want to be officially supporting external components such as this myself since it would quickly grow in scope to other browsers and search engines and they'd be moving targets to support, and would result in another significant element to support. 

That said, it's all possible to do. I have put together a demo MVP of such extension and added it to our api-scripts repo here:
https://github.com/BookStackApp/api-scripts/tree/main/chrome-extension-google-search-results

This is a very barebones example, I just worked to get a minimal example to the point of functioning. Below is a preview of it in usage.

Since I don't intend to develop this further I'm going to close off this issue but hopefully the fundamental work done in my example can be developed and built upon by yourself and/or others.

### Preview

![Screenshot from 2022-05-09 18-16-41](https://user-images.githubusercontent.com/8343178/167462851-7758d74b-746e-4173-83d3-b8af0c5c8f28.png)
