### ISSUE TITLE
Add search endpoint for Books

### ISSUE THREAD

**Issue by come2thecabaret** [BookStackApp/BookStack#2554]
#### API Endpoint or Feature

It would be very useful to have a search endpoint in the REST API.

#### Use-Case

Exploring using Bookstack as a user guide for an application, but we plan to develop a context-sensitive-help feature which will allow users to search help docs from within the application. A search endpoint in the REST API would be essential for this. Thanks!

#### Additional Context

If required, add any other context about the feature request here.

**Comment by ssddanbrown** [comment]
Thanks for the request @come2thecabaret.

I've just come across #909, which was opened before we finished, or even started, work on the API. Since that covers the same request I'll close this off as a duplicate.

You can do some level of searching via the current API endpoints. Please [see my comment in #909 ](https://github.com/BookStackApp/BookStack/issues/909#issuecomment-608753323)to see how this would be done.
