### ISSUE TITLE
Stable Release

### ISSUE THREAD

**Issue by Haboubi92** [BookStackApp/BookStack#2564]
**Describe the feature you'd like**
when will a stable version would be released?

**Describe the benefits this feature would bring to BookStack users**
I've just read a forum thread in [softaculous forum](https://www.softaculous.com/board/index.php?tid=13625)
in which someone suggest adding BookStack to softaculous list of one click installation apps
but Softaculous Team refused to add BookStack because of unavailability of a stable version (only beta versions exist)

**Comment by ssddanbrown** [comment]
Thanks for the request @Haboubi92,
I would likely not look to change the stability of the project itself, since I'm happy with the stability we are able to offer. That said, This is primarily about dropping the beta status from releases. I've opened #2570 as a starting point for discussions to eventually achieve this. Since #2570 would cover the core request here I'm going to close this off.

**Comment by Haboubi92** [comment]
@ssddanbrown thanks ♥
