### ISSUE TITLE
Include the app logo in emails sent by BookStack

### ISSUE THREAD

**Issue by digitall-it** [BookStackApp/BookStack#2577]
**Describe the feature you'd like**
Our site header has my logo and the word "docs" after it. However, on sending a password init email, only the word "docs" appears, without the logo, so the user isn't sure it comes from me.  I suggest separating the site and the email headers in two different fields in the ```/settings``` form in the customization section.

**Describe the benefits this feature would bring to BookStack users**
Better recognition of BookStack legit emails.

**Additional context**
Attached a screenshot of a test email.
<img width="605" alt="Schermata 2021-02-21 alle 14 53 19" src="https://user-images.githubusercontent.com/3578378/108627207-9d4bd680-7454-11eb-88d3-6ef7c60cb936.png">

**Comment by ssddanbrown** [comment]
Thanks for the request @digitall-it.

I'd prefer not to have additional settings simply to account for an edge-case scenario if possible.
Would you feel that the core issue would be solved here if we added the logo image into the header of the emails sent by the platform, alongside the text as per the web interface header?

**Comment by digitall-it** [comment]
That would be even better, but it is important to have alt text on the image if it is not base 64 encoded in the message.

**Comment by ssddanbrown** [comment]
@digitall-it Thanks for confirming. I'll therefore update the issue title to focus on the above mentioned alternative.

**Comment by ssddanbrown** [comment]
Patch applied for this now, Will be part of the next feature release.

**Comment by ssddanbrown** [comment]
Hi @digitall-it,
After further thinking and reviewing of the options I've just reverted the inclusion of this.

This would be adding an additional bit of complexity to emails which would likely raise more issues, and you requested this having good alt text which would not currently be possible without another input, which this solution was attempting to avoid.

We use the app name in a few places, Even with this added there'd still be oddities in your setup due to this combination of app name and logo.

Next to the name input within the setttings there's a "Show name in header" checkbox. Quite honestly I think your situation would work best, and this would be solved, if you included the "docs" text within your app logo image. That way you can make the full name descriptive and readable for emails and other potential locations.
