### ISSUE TITLE
A way to make each user's books private, but able to share common books?

### ISSUE THREAD

**Issue by LavaTiger99** [BookStackApp/BookStack#2605]
Hi,
We are using this as an evernote/onenote replacement. Ideally each user's login would show them private books, but also have access to any shared books by any other user. Is there a way to do this?
Thanks

**Comment by ssddanbrown** [comment]
Hi @LavaTiger99,

It's not the primary focus of BookStack, to fit in that permission structure, since the platform is really intended to be fairly open across an instance. That said, You can kind of do this via the permission system.

When creating/editing a role you'll see a bunch of "own" permission options, that alter the permissions based on their ownership of an item. You'd need to take advantage of those & remove many of the "all" permissions. For shared books you'd need to specifically update the permissions of those books to enable the "view" permission for applicable books.

**Comment by LavaTiger99** [comment]
Ok, thank you. Have confirmed this works.

I know this is not what it is meant for, but I haven't found a solution that has as nice an interface & easy user experience as bookstack for notetaking.

I created a user and a group (role) for each user:
user: person1 role: person1
Then I went through the books I wanted to share, and selected person1 (read/write/edit), person2 (read/write/edit), etc
