### ISSUE TITLE
More Markdown Features

### ISSUE THREAD

**Issue by Y0ngg4n** [BookStackApp/BookStack#2622]
Hey there it would be nice if the Bookstack Community could implement more Markdown Features like Checkboxes, Tabs and Keyboard Keys like in [Wiki JS](https://docs.requarks.io/en/editors/markdown)

This would be very nice and would improve the Workflow.

**Comment by ssddanbrown** [comment]
Thanks for the request @Y0ngg4n. Checkboxes should be possible in the current release via the `- [ ]` syntax

That said, For BookStack I stick to commonmark in an effort to keep to a standard. We have expose some [editor hooks](https://www.bookstackapp.com/docs/admin/hacking-bookstack/#bookstack-editor-events) for customization of the underlying markdown-it front-end rendering and I'm currently working how to expose the back-end markdown renderer for more customization, otherwise I don't want to expand out support much further than commonmark in the core project.

**Comment by ssddanbrown** [comment]
Will therefore close this off.

In regards to the checkboxes, You'd just need some content after the square brackets:

![Screenshot from 2021-03-09 22-08-30](https://user-images.githubusercontent.com/8343178/110544700-166d4e00-8124-11eb-8b47-96694df7b8d3.png)

**Comment by Y0ngg4n** [comment]
@ssddanbrown ah ok nice thank you :)
