### ISSUE TITLE
Undefined index: start_tls after upgrading to v21.04

### ISSUE THREAD

**Issue by irefuse** [BookStackApp/BookStack#2676]
**Describe the bug**
Receiving "Undefined index: start_tls" after upgrading to v21.04

**Steps To Reproduce**
1. Upgrade from v0.31.8 to v21.04
2. login after upgrade using ldap credentials
3. see error message in screenshot

**Expected behavior**
i should be able to login

**Screenshots**
![image](https://user-images.githubusercontent.com/2688319/114405894-b75c8800-9b6c-11eb-90a0-2717b85e086d.png)

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): v21.04
 - PHP Version: 7.3.22
 - Hosting Method (Nginx/Apache/Docker): Microsoft IIS

**Additional context**

**Comment by irefuse** [comment]
This seems to have resolved itself with a `php artisan config:cache` command. For reference, I had already run the 2 recommended commands in the update instructions documentation `php artisan cache:clear` and `php artisan view:clear` but those did not resolve this issue.

It may be worth notating in the 'Updating to v21.04 or higher' section that a `php artisan config:cache` command may be necessary due to the addition for the start_tls settings.

**Comment by ssddanbrown** [comment]
Thanks for confirming the solution for you @irefuse, I will therefore close this off since you found a resolution.

You should also be able to use `php artisan config:clear`, `config:cache` runs `config:clear` hence why that cleared things up. The config would only be cached if you've previously run `config:cache` before, which I generally don't document. You'd need to re-cache or clear this config-cache after each update, if the command has never been ran its not needed. Did you follow a guide that advised running this or did you find this command yourself? Or did you run this being familiar with the framework used (Laravel)?

**Comment by irefuse** [comment]
I am actually lightly familiar with Laravel from other web applications I use. I had found the config:cache command as a recommendation previously (not for BookStack), and have typically used it on any Laravel deployment. Should I not be using the config:cache? These configs are pretty light weight so I don't see any reason to continue to cache them if it's not specifically recommended.

**Comment by ssddanbrown** [comment]
> Should I not be using the config:cache? 

It's typically good practice for most Laravel deployments to be fair, the free performance gain is generally worth it; It's just that I've not recommended it to BookStack users due to the caching becoming "sticky" (Especially when permissions are involved) and causing maintenance burden. 

I've added the `config:clear` command to the update suggested commands in the docs now, just for when similar scenarios occur in the future.
