### ISSUE TITLE
Laravel 419 error when logging, after reinstall

### ISSUE THREAD

**Issue by leopendas** [BookStackApp/BookStack#2707]
**Describe the bug**

**Steps To Reproduce**
I took a backup from version mentioned, and when trying to restore get this error.(how could I check which version the script installed?)
It loads home page properly, but when trying to access this error happens. Tried to install libmemcache and set up on the .env file. Also tried to add login page to CSRF exception file, and now it does not throw 419, but does not allow to login. Nothing happens.
Any advice in where to look, would be really useful, as I do not see any error or log file in where to check.
thanks in advance.

**Expected behavior**

**Screenshots**

**Your Configuration (please complete the following information):**
 - BookStack v0.30.4
 - PHP Version: 7.4.3
 - Hosting Method (Nginx/Apache/Docker): Apache

**Additional context**

-

**Comment by ssddanbrown** [comment]
Hi @leopendas,
Debugging information can be found here: https://www.bookstackapp.com/docs/admin/debugging/

This usually happens when there's issues this cookies or when things are occurring across different hosts. 
Can you check you have an `APP_URL` value set in your `.env` file and that it matches the base URL that you're accessing BookStack on? The start of the URL (`http://` or `https://`) must exactly match how it's being accessed.

**Comment by ssddanbrown** [comment]
Since there's been no follow-up I'm going to close this. If the issue remains and is something you still require to be fixed please open a new issue, referencing this one.
