### ISSUE TITLE
Bookstack installation in Cpanel 

### ISSUE THREAD

**Issue by farooqtahir333** [BookStackApp/BookStack#2729]
I would like to know that is it possible to install and setup new version of Bookstack in Cpanel?
I have tried to install it on Cpanel but facing HTTP ERROR 500 on page after installation is completed. 
Can anyone share guideline?

**Comment by ssddanbrown** [comment]
Hi @farooqtahir333,
cPanel is not something I can offer support for since I don't use it at all. I'll leave this open for a few days in the hope someone familiar with cPanel might be able to help. The BookStack debugging page may help to solve errors: https://www.bookstackapp.com/docs/admin/debugging/

Other than that, BookStack is based on Laravel so has some similar install requirements. You can try searching for "Laravel cPanel" guides instead. Be wary though, if you're not able to use the mechanisms within the BookStack install instructions you may have trouble upgrading in the future. In addition, if you're ever editing any of the BookStack core PHP files, or end up with `/public` in the URL for access, I'd advise against using that setup as you'll likely just have issues down the line.

**Comment by bridgeyuwa** [comment]
@ssddanbrown A request can be made to **Softaculous** to add bookstack to their Cpanel Auto installer.

A request was made in 2017 but they were reluctant to add bookstack since it was still tagged as being in its Beta stage.

[https://www.softaculous.com/board/index.php?tid=13625](https://www.softaculous.com/board/index.php?tid=13625)

**Comment by connectedbusiness-gary** [comment]
We were able to get it installed on CPanel following the instructions...

**Comment by Haboubi92** [comment]
> @ssddanbrown A request can be made to **Softaculous** to add bookstack to their Cpanel Auto installer.
> 
> A request was made in 2017 but they were reluctant to add bookstack since it was still tagged as being in its Beta stage.
> 
> https://www.softaculous.com/board/index.php?tid=13625

I made another request last month to add Bookstack to Softaculous, since Bookstack have dropped the [beta status](https://www.bookstackapp.com/blog/bookstack-release-v21-04/)

they told me "We have forwarded the request to our scripts team. They will check and let you know if it is possible to add the script in Softaculous or not."

**Comment by Haboubi92** [comment]
> @ssddanbrown A request can be made to **Softaculous** to add bookstack to their Cpanel Auto installer.
> 
> A request was made in 2017 but they were reluctant to add bookstack since it was still tagged as being in its Beta stage.
> 
> https://www.softaculous.com/board/index.php?tid=13625

@bridgeyuwa 
I made a new request to add Bookstack to Softaculous last month 
Bookstack now is on their task list, but it takes time to be added 

Softaculous Support told me today:

> 
> "Sure we have escalated this to our team.
> They have this listed on their task list. However our developers are already working on daily updates and many other suggestions provided by other users too.
> Please give us few weeks time and we shall check the feasibility of this script at Softaculous. If we find this going as expected, > then we shall start the process of integration for the same at Softaculous.
> However this entire process may take upto few weeks and provide any exact ETA shall not be possible for now.
> As and when we have any updated OR need any further assistance from us, we shall definitely keep you posted here."

**Comment by ssddanbrown** [comment]
Thanks @Haboubi92. I'll therefore close this off since there's not much I can do and since noone else has been able to provide steps of any kind for a CPanel environment.

**Comment by shashinasiri** [comment]
I was abled to get it installed on cPanel following their instructions -> https://www.bookstackapp.com/docs/admin/installation/#shared
