### ISSUE TITLE
RTL language Support

### ISSUE THREAD

**Issue by Haboubi92** [BookStackApp/BookStack#2744]
I'd like to suggest some features to make Bookstack more suitable for RTL (Right-to-left) languages like Arabic, Hebrew, Persian.. etc.

1. I'd like to see a dedicated button in wysiwyg editor to change writing direction
currently only shortcuts are supported to change writing direction (ctrl + left shift for left direction and ctrl + right shift for right direction), most users are not aware of such shortcuts so a dedicated button would be more user friendly

2. I couldn't change header direction, for an RTL language the header should be in the right text alignment.

Currently I don't have my own installation of bookstack, I'm relying on the bookstack demo for testing but if you provide an option for changing language in the demo setting, then I will make more in-depth RTL testing.

**Comment by ssddanbrown** [comment]
Hi @Haboubi92,
Text direction controls will appear in the editor one your language is set to a RTL language, and the whole UI (Including the header) will be shown in an RTL format:

![Screenshot from 2021-05-15 11-27-03](https://user-images.githubusercontent.com/8343178/118357146-8955d380-b570-11eb-8f6c-842a0d7370d6.png)

> if you provide an option for changing language in the demo setting, then I will make more in-depth RTL testing.

Unfortunately I can't really easily allow setting edits in the demo since it opens up security/spam issues. If you access the demo site, without logging in, with `ar` set as your default browser language choice then the demo will show in Arabic but you won't be able to test the editor in this mode.

**Comment by Haboubi92** [comment]
aha
thank you so much ❤ that's very nice
