### ISSUE TITLE
Sizing of Tables

### ISSUE THREAD

**Issue by pboatone** [BookStackApp/BookStack#2757]
If there is a table with more than 5 Heads the sizing of the table looks bad. Like this:
![2021-05-20 20_38_16-Window](https://user-images.githubusercontent.com/67209365/119031714-b01a6c80-b9ab-11eb-9614-7f1b9e3b5ed5.png)

It would be nice to to set the sizing of a table on our own or improve the sizing

**Comment by ssddanbrown** [comment]
This is a general limitation of the flexibility of tables when working to a certain width. Often using headings (Per row) with a series of bullet points (Or similar) for the detail can be a much more flexible way to lay-out data. You could even use the page template feature to template each entry out.

Since there are already existing issues #1387 and #2126 referencing the various issues with tables being non-adaptive, I'll close this off.
