### ISSUE TITLE
Error no vendor files

### ISSUE THREAD

**Issue by planesticud** [BookStackApp/BookStack#2763]
Regards

I'm installing BookStack in a EC2 instance, when i pulled the git, i do not found a vendor carpet and in the step "php artisan key:generate" it show this error

[ec2-user@ip-172-29-0-181 BookStack-release]$ php artisan key:generate
PHP Warning:  require(/var/www/html/BookStack-release/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/BookStack-release/artisan on line 18
PHP Fatal error:  require(): Failed opening required '/var/www/html/BookStack-release/vendor/autoload.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/html/BookStack-release/artisan on line 18
[ec2-user@ip-172-29-0-181 BookStack-release]$ 

What could i do to solve this error if the git don't have this files?

![image](https://user-images.githubusercontent.com/38005888/119240495-74031b00-bb15-11eb-8711-9755f2821d80.png)

**Comment by ssddanbrown** [comment]
Hi @planesticud,
You'll need to get a copy of [composer](https://getcomposer.org/download/) then use it to install the dependencies. 

Assuming a Ubuntu machine (May work on other linux systems):

```bash
# Install composer globally
wget https://getcomposer.org/download/2.0.14/composer.phar
chmod +x composer.phar
sudo mv composer.phar /usr/local/bin/composer

# Run composer from within your BookStack install dir
composer install --no-dev
```

I see that you've put the files within `/var/www/html`. Be sure that nothing it setup on the machine to serve `/var/www/html` by default, You only want to expose the BookStack's `public` folder as the web-root otherwise you could end up with an insecure setup.

**Comment by ssddanbrown** [comment]
Will therefore close this off.
