### ISSUE TITLE
Request for adding Croatian language

### ISSUE THREAD

**Issue by ffranchina** [BookStackApp/BookStack#2772]
### Croatian

Hello, I would like to kindly request to add Croatian language.
I have tried to contact you (@ssddanbrown) by email to ask you about the possibility of opening a PR will all the files already translated.
I hope you can accept this condition due to my peculiar situation and since I already have the files almost ready :)

Thank you in advance for your understanding and for this well crafted project :)

----

_This issue template is to request a new language be added to our [Crowdin translation management project](https://crowdin.com/project/bookstack). Please don't use this template to request a new language that you are not prepared to provide translations for._

**Comment by ssddanbrown** [comment]
Hi @ffranchina,
Sorry, I'm can be pretty bad about replying to emails.

Sure, that would be great, feel free to provide a new language by PR. I do prefer Crowdin being used for minor changes since it keeps things manageable and it's simpler to use for most people but happy to accept PRs if that's not possible or if bulk providing a new language.

Note, Files may end up being re-commited during syncing within Crowdin. Nothing to functionally worry about but it just may end looking like my user has changed/updated all files.

**Comment by ffranchina** [comment]
Hi @ssddanbrown!
Thanks for your reply. Don't worry at all about the email, what matters is that I could reach you!

Thanks a lot for your understanding and willingness, it's very much appreciated! So I will open soon a PR with the complete Croatian translation :)

:rocket:
