### ISSUE TITLE
Is it possible to hide "Recent Activity" and "Recently Updated Pages" in public view?

### ISSUE THREAD

**Issue by wayne-cec** [BookStackApp/BookStack#2786]
Hi,
Is it possible to hide "Recent Activity" and "Recently Updated Pages" in public view?

thanks

**Comment by ChrisB101** [comment]
Hello,

I'd like to add to that, can you hide the timestamps (like "created before" or "updated") and the users who created/updated content?

Thanks.

**Comment by ssddanbrown** [comment]
There is no way to do these via settings or options provided within BookStack.

The Hacking BookStack page does provide some ways you could customize the UI though: https://www.bookstackapp.com/docs/admin/hacking-bookstack/

The "Custom HTML Head Content" setting allows you to add custom CSS to control the UI where needed otherwise you could use the Theme system to do some more advanced overriding of view content. 
If you're attempting to hide these things in just the public view, instead of for all users, then that will be more challenging.
