### ISSUE TITLE
Audit log in mobile mode

### ISSUE THREAD

**Issue by candrews67** [BookStackApp/BookStack#2793]
When viewing on a mobile device, the audit log appears as desktop

Bookstack version: v21.01.4
Mobile device: Samsung Note 9 
Browser: Samsung Internet and Chrome

Thanks!!!!

**Comment by ssddanbrown** [comment]
Thanks @candrews67 for raising.

Is using the audit log on mobile a legitimate desire you have or are you filing this more as an advisory of something you noticed? This would apply for many of the tabular views and hence it would take a fair undertaking to change these up to use alternative responsive methods. Many of these views are admin/power-user views though so I have not previously seen an ideal responsive as a primary concern.

**Comment by candrews67** [comment]
Hi!
This was more of an FYI. Not a issue, problem or bug. I did not know if it might be a simple theme or CSS fix.

Thanks again and i love the software!!

**Comment by ssddanbrown** [comment]
@candrews67 Ah, Okay, thanks for confirming. In that case I'll close this off since it'll require a fair amount of effort to adapt these table style views in their current form but I'll keep this in mind if I see similar requests pop up in the future, in the event people start to have important mobile format use-cases around these views.
