### ISSUE TITLE
Change current list of groups on book custom permissions to autocomplete dropdown 

### ISSUE THREAD

**Issue by Rumcajsev** [BookStackApp/BookStack#2800]
**Describe the feature you'd like**
Currently, when adding custom group permissions to the book, all of the groups are listed. This makes it cluttered and hard to find a correct group. Usually most of the groups don't have any permissions.

Autocomplete dropdown could be used to add individual groups to context of customer permissions. This way only groups with actual permission are visible.

**Describe the benefits this feature would bring to BookStack users**
This would remove the clutter on custom permissions screen when larger numbers of groups are added.

**Comment by ssddanbrown** [comment]
Thanks for the suggestion @Rumcajsev.

While this could technically be implemented as a UI change now, It could result in some confusion into how permissions work since activating custom item permissions will still affect all groups.

I have  #410 open as a point to change how the permissions are handled in the future with the intention of providing the proposed approach. I'll therefore close this off as a duplicate.
