### ISSUE TITLE
Cannot access BookStack from outside home network with domain name

### ISSUE THREAD

**Issue by vtallen** [BookStackApp/BookStack#2900]
**Describe the bug**
When trying to access BookStack from a domain outside the network the server is hosted on, the page does not show up. If I change the APP_URL, and the virtual host back to the internal ip, it connects fine while in the home network. I have correctly port forwarded my router to allow port 80 and 443.

**Steps To Reproduce**
1. Start with a fresh Ubuntu Install
2. Install with the install script
3. Set domain to internal IP
4. Connect to internal ip with web browser to see it is working fine
5. Edit the .env from 192.168.1.93 to mydomain.com
6. run sudo php artisan bookstack:update-url http://192.168.1.93 http://mydomain.com
7. update the virtual hosts file to point to mydomain.com
8. Connect with web browser to mydomain.com to see "This site cannot be reached."

**Expected behavior**
When changing the app URL and virtual host to a publicly accessible domain, I should be able to access BookStack from outside my home network.

**Your Configuration (please complete the following information):**
 - Exact BookStack Version: 21.05.4
 - PHP Version: 7.4.3
 - Hosting Method: Apache install script

**Comment by ssddanbrown** [comment]
Hi @vtallen,
Do you have any evidence that the requests are hitting your server? If not does the browser provide any additional context for the error?

It sounds like this may be a networking issue rather than a BookStack specific issue. You'll can usually refer to the access log (For example, maybe at `/var/log/apache2/access.log` or similar file) to see if the requests are even getting to your server.

**Comment by vtallen** [comment]
It looks like it was, I reset my router and remade my portfowards and it worked. Odd but I'll take it.

Thanks for your time!

Vincent Allen
