### ISSUE TITLE
Permalink in details of a page view

### ISSUE THREAD

**Issue by jhrdt** [BookStackApp/BookStack#2917]
**Describe the feature you'd like**
Permalink link inside the details panel of a page view. A action button would be also a solution (something like the *Code* button on GitHub where you get the ssh or http links).

**Describe the benefits this feature would bring to BookStack users**
This would be an easy way for get a permalink for a page. 
The BookStack way of getting a permalink is the select content pop-up, but this context menu is a unknown mechanism (and somehow un-intuitive) for non IT users.

**Ref**

* https://www.bookstackapp.com/docs/user/reusing-page-content/

**Comment by ssddanbrown** [comment]
Thanks for the request @jhrdt but I'm going to close this off since this is just over the line of what I'd like to show the user by default within the interface. The old `/link/#` permalink feature is intended for power users and hence currently not shown in the default UI (Until a selection is made to get the popup to appear).

I see it as a failing of the system if you'd even have to guide users to copy a permalink from under the details, or via a button, as is proposed, instead of simply using the current webpage URL. I eventually want to move to a different URL scheme that acts as a better permalink but that move needs to be a slower and considered process.

If this feature was important to you right now you could make use of [our visual theme system](https://github.com/BookStackApp/BookStack/blob/development/dev/docs/visual-theme-system.md) to override the view that holds the item details, to add the url as desired. The view you'd be overriding would be this one:
https://github.com/BookStackApp/BookStack/blob/55af22b487f10c9efbeb0a2444da45016ac537d0/resources/views/entities/meta.blade.php
