### ISSUE TITLE
Better Tag Manipulation and Display, Intelligent Tag Suggestions

### ISSUE THREAD

**Issue by Salvora** [BookStackApp/BookStack#2938]
**Describe the feature you'd like**

**1- Display the tags under the page, book, chapter titles like in the search results by default:**
It is a simple display issue. It would be nice to see the tags without going into shelf, book, chapter or page itself.

**2- A separate page to see all the tags (This has been requested before.):**
I will not explain this for this has been suggested before.

**3- Easily remove and add multiple tags without going into edit mode:**
Just an idea but if no 1 is implemented, a small X can be added to remove the tags without actually going into the edit mode of the shelf, book, chapter or page itself.
For adding a tag, a small text box could be implemented. I am not sure how to go about it though.

**4- Suggest tags based on the page content or auto fill the tags (user can delete some or add more during page creation, can be turned on and off):**
I am not sure how other web sites of applications do this. When creating a new shelf, book, chapter or page, the content can be parsed and specific key words can be used to create tag suggestions.

**5- Mark specific tags viewable or hidden by assigned users:**
It is not that important but a nice to have feature.

**Describe the benefits this feature would bring to BookStack users**
For two years, I have been using this app and a big fan of it. It has really made a big difference for me.
I have put together this tag feature improvement suggestions based on what is normally available for other applications and web apps and what I felt missing during my use of it.
Tags are not important for small libraries but when things get big, they are absolutely essential to organize your stuff.
Currently, BookStack offers very basic features in terms of tags and it is open to many improvements.

**Additional context**
Is it possible to add some approved suggestions to the Road Map?
And again, thanks for the great work.

**Comment by ssddanbrown** [comment]
Thanks for the suggestions and feedback @Salvora. Just some quickfire feedback from my perspective:

1. My issue with this is that it starts littering up the listing views with tags and I'm cautious about overwhelming the user with what is essentially levels of metadata in such listings. Somewhat related to #2528.
2. This has been requested (#738) as mentioned but has always fallen down at describing the actual use-case and layout of such a view, in terms of what it enables/achieves for a user. 
3. This quickly adds complexity, and blurs the line between edit and display modes of content. Maybe there'd be some half-way solution. Has already somewhat been requested in #571.
4. Can't see this being something worth implementing, since "auto-suggestion" kind of things like this can quickly get into opinion and control would be desired. It also has a dependency on certain work flows such as the content needing to exist before the tags can be suggested, but I'd imagine tags would be applied early on within an asset's lifecycle.
5. Not sure if the "Hidden" aspect applies to the tags themselves or the tagged content. Either way, Is probably a layer of permission level I'd prefer to avoid. 

To be honest, multi-request issues like this are hard to manage. Is there any specific feature you'd desire above others, that's not already covered by another issue?

**Comment by Salvora** [comment]
Yeah, I get what you are coming from with multi-request issues. It is hard to keep track of them. Sorry about that.
It is just that, recently I had to tag all my shelves, books, chapters, pages recently. It was a painful process to tag hundreds of entries. That is why I made those suggestions. 
Apparently, I didn't do my research well before opening this request. Most of what I suggested had already been asked. This issue can be closed if you wish.
I would just put my support behind the already open requests for 1,2, and 3.
Other than that, there is nothing more I have in mind that would be helpful to the project. Again, thanks for the awesome work.

**Comment by ssddanbrown** [comment]
@Salvora Yeah, I understand. The tag system does need some attention at some-point soon.

Just another option to consider, if you're handy with databases and SQL you could always view/manage via the database. Not ideal, I know, but can be useful for bulk work at times where platform implementation lacks. The tag table structure isn't too complex to work with.

As advised, Will therefore close this off.
Thanks again for your feedback.
