### ISSUE TITLE
Restrict Registration to Some Social Integrations

### ISSUE THREAD

**Issue by csicar** [BookStackApp/BookStack#2940]
**Describe the feature you'd like**
As a admin of a BookStack installation, I would like to have the option to restrict registration to just Slack, but not via e-mail.

**Describe the benefits this feature would bring to BookStack users**
I would be only allow slack users with access to a specific workspace to register an account, but disallow users to register via email.

**Additional context**
If the development team agrees, that this is a feature worth implementing, I would be willing to put the work in to get it implemented

**Comment by ssddanbrown** [comment]
Thanks for the suggestion @csicar.
This would probably be a level of configuration I would be apprehensive to go down to. 
Might be okay if it can be implemented in a simple manner via just one `.env` configuration option.

To implement in the required format though, this may be dependant of #1090 since we don't currently provide the mechanisms to properly independently disable to primary auth method. 

For your specific scenario, are you sure the "Automatic Registration" option [described on this page](https://www.bookstackapp.com/docs/admin/third-party-auth/) doesn't already provide the required functionality? Enabling this for should allow auto-registration via the slack option on the login page, while leaving registrations disabled for email sign-up.
