### ISSUE TITLE
Better Search in the Site-Content

### ISSUE THREAD

**Issue by reddexx** [BookStackApp/BookStack#2989]
Would it be possible to improve the search a little? Since the search only returns links or titles.

It would be better that you can get a result after a text or similar text

**Comment by ssddanbrown** [comment]
Hi @reddexx,

We'd need some specifics in regards to what needs to change from a user perspective as this request is very general.
Since there are already a [range of issues open](https://github.com/BookStackApp/BookStack/issues?q=is%3Aissue+is%3Aopen+search+in%3Atitle) relating to improving the search system I'm going to close this off as a duplicate.
