### ISSUE TITLE
Random Tags in the Left-Site-Box

### ISSUE THREAD

**Issue by reddexx** [BookStackApp/BookStack#2992]
Random tags (10-15 tags) in the left side box

Would the menu navigation improve this should correspond to rights based.

**Comment by ssddanbrown** [comment]
Thanks for the clarification.

I don't really want to introduce any level of randomness into the user-interface, since randomness can often lead to frustration, so this is not an approach I'd look to take. I do appreciate tag-based discoverability needs to be improved. I think something like that described in https://github.com/BookStackApp/BookStack/issues/738#issuecomment-928278273 would be a better and less intrusive initial approach to improving tag usage.
