### ISSUE TITLE
[Feature Request]: wysiwyg emoticons

### ISSUE THREAD

**Issue by reddexx** [BookStackApp/BookStack#3017]
### Describe the feature you'd like

Please Aktiviate the wysiwyg (TinyMCE) emoticons Plugin in the wysiwyg (TinyMCE) Editor

### Describe the benefits this feature would bring to BookStack users

Emojis 😁

**Comment by ssddanbrown** [comment]
Okay, Thanks for confirming. Again, I don't really think there's enough reason to implement and maintain a full emoji picker within the application since operating systems already fill this gap in a way that would handle various issues much better than we'd be able to handle (Internationalization, Unicode updates/changes etc...). So will therefore close this off as out of scope.
