### ISSUE TITLE
[API Request]: Ability to upload and attach files

### ISSUE THREAD

**Issue by aydwi** [BookStackApp/BookStack#3031]
### API Endpoint or Feature

The ability to upload and attach arbitrary files via the API. If such an endpoint already exists, then my sincere apologies for missing it in the documentation; I haven't encountered one yet.

### Use-Case

File uploads are considered one of the core functionalities of a wiki software. Addition of an API endpoint for the same would add significant value to Bookstack in that it allow its users to manipulate files externally for a variety of use cases.

### Additional context

I am maintaining a fork of Bookstack for my employer for use as a closed knowledge base. We plan on setting up a CI-CD pipeline for out binary releases, the endpoint for which would be a Bookstack instance.

**Comment by aydwi** [comment]
Upon some searching, I've discovered that my issue is redundant/duplicate since it has been discussed in #2981 and #2942, and seems to have been addressed by #2986.

I will update my instance (it is somewhat out of date). You may close the issue unless there is something you would like to add.

P.S. My humble regards to you for building Bookstack to this high standard. Over the past few weeks, I've pored over many of your discussions with the community over issues or the general direction of the project, and your efforts and sincerity is truly commendable. Thank you @ssddanbrown.

**Comment by ssddanbrown** [comment]
Yeah, Should be all implemented within #2986 which was included as of BookStack v21.10. Feel free to raise any issues with that system if you come across any problems. Will therefore close this off.

> P.S. My humble regards to you for building Bookstack to this high standard. Over the past few weeks, I've pored over many of your discussions with the community over issues or the general direction of the project, and your efforts and sincerity is truly commendable.

Thank you for saying that! It means a lot to know it doesn't go unnoticed. 

By the way, since you're working with the API, just want to point out we have the api-scripts repo if you havn't already come across it:
https://github.com/BookStackApp/api-scripts

Nothing in there fore attachments yet, but still might be some useful bits and pieces.
