### ISSUE TITLE
[Support Request]: Saving drafts / unpublished content

### ISSUE THREAD

**Issue by sarah-arrrgh** [BookStackApp/BookStack#3062]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [x] I have searched GitHub for the issue.

### Describe the Scenario

I am building out help docs using BookStack, and want to be able to use drafts to get content proofed / updated / edited before publishing for public viewing.

e.g.
Some published content needs updating - the current content is no longer relevant. I want to be able to 
1) Unpublish that page but keep its page id and place in the book.
2) Remove reference to the page from the book on the public site, but allow it to be viewable via the url for others to view and give feedback on.
3) (dreamy dream) be alerted where that page or its content is being referenced on other pages, so I can update them too
4) Once it's ready to go live again, publish the page back to its existing position in the book

Is there a way to do this? It seems that if I go to an existing published page and click "Save draft", it remains visible to the public. 

### Exact BookStack Version

v21.05.3

### Hosting Environment

Unsure and likely irrelevant for this question

**Comment by ssddanbrown** [comment]
Hi @sarah-arrrgh,
We don't really follow a publish/unpublish model so much in BookStack. The initial draft state is really just to keep the content private to the creator up until that initial point of saving.

You could emulate something via the permission system. So in this case set permissions on the specific page so that the public role does not have visibility but those needing to review/edit to keep visibility.  Upon this, you could utilise the organisation structure to make this a bit smoother, Where you'd maybe have a "Pending Review" book that you could move pages in/out of, where that book has the correct permission set upon it already.

**Comment by ssddanbrown** [comment]
Since this was answered and since there has not since been a response I'll close this off.
