### ISSUE TITLE
[Feature Request]:  Office Formats Support for prewiev

### ISSUE THREAD

**Issue by GamerClassN7** [BookStackApp/BookStack#3064]
### Describe the feature you'd like

Hello would be possible to implement some sort of Prewiev for most used Microsoft Office Formats Like Excel,Word,Vision,Poverpoint ?

### Describe the benefits this feature would bring to BookStack users

in our company we have a lot of legacy documentation writen in Upper mentioned formats, ant they are really long and most of time unused, so amount of work rewriting it into BookStack would be to big.

### Additional context

Onyl Easy solution i OFund is to use GOOGLE DOC and iframe

iframe1.Attributes.Add("Src", "http://docs.google.com/gview?url=http://YOUR_FILE_PATH&embedded=true");
Ho ever for use with company docs this dont seem secure enought. some local library or parser would be aprichiated.
on additional note it would be great to work same way like PDF Prewev :) an last feature would be also index the files for search. this would be totaly awesome. i think mos of the peope using this software would benefit from this change :)

**Comment by ssddanbrown** [comment]
Hi @GamerClassN7,
Thanks for the request but the support of such file formats, especially in respect to showing previews and supporting indexing, would take a lot of work and likely spawn a series of issues when it comes to supporting the feature on an ongoing basis.

I'd much rather keep out time focused upon the simplified, open format(s) of what we support by default instead of having to also keep track of the moving target that is Office file formats. 

For the import of content the BookStack API can be utilised if you have some scripting skills available. I have an example of import docx files as pages here: https://github.com/BookStackApp/api-scripts/tree/main/node-docx-to-page

Otherwise I'm going to close this off as out of scope.
