### ISSUE TITLE
[Feature Request]: subscription + mail notification

### ISSUE THREAD

**Issue by pboatone** [BookStackApp/BookStack#3088]
### Describe the feature you'd like

Hi,
unfortunately I have to ask again because it is an important function for us ...

Is it possible or upcoming that you will subscribe to an article and then receive a change email. We have users who do not log into Bookstack every day and these users do not receive changes.

### Describe the benefits this feature would bring to BookStack users

Users who do not login every day receive an e-mail when a subscribed contribution is changed. As an example, a critical process in purchasing or something similar. With this function, the users would receive an email and thus a change information

**Comment by ssddanbrown** [comment]
Hi @pboatone,
As per your other issue (#2580) I'm going to close this off as a duplicate due to already being covered by existing issues.

If desperate for this, and familiar with Laravel, it may be possible to hack such a feature together using the logical theme system:
https://github.com/BookStackApp/BookStack/blob/master/dev/docs/logical-theme-system.md
