### ISSUE TITLE
[Support Request]: Emoji Support clarified?

### ISSUE THREAD

**Issue by southeasterntech** [BookStackApp/BookStack#3125]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

Was tinkering around today, and while at it, decided to enable emoji support.  I followed the guide on this page:
https://www.bookstackapp.com/docs/admin/ut8mb4-support/

Afterwards, I expected to be able to input characters such as ;) and then get some emoji icons appearing within the text.  I then looked for emoji icons in the menu and there aren't any either.

This doesn't seem to work.  Am I misunderstanding the usage?  

How is this used?
Thanks much!

### Exact BookStack Version

BookStack v21.12

### Hosting Environment

Ubuntu 20.04 self hosted

**Comment by ssddanbrown** [comment]
That documentation page is only really intended for much older instances upgrading their database to be able to support emoji characters (Emoji characters would break old database formats).

We currently don't have any user-interface support for emoji selection or conversion since it'd be another significant element to package in and maintain. `:smile:` style emoji support (As supported here on GitHub) has been requested but this format is not really a standard and is quite fixed to the english language which makes me hesitant.

As time goes on most operating systems have very good native emoji picker support so I've usually advised using those instead (Windows Key + `.` on Windows for example) since they are kept up-to-date by the Operating System and should work fine in our editors.

**Comment by southeasterntech** [comment]
I see!  I just tried the Windows Key + . method and it works great.  So there's basically no current use for that page except for upgrading old databases?  Is that to say that I really didn't need to do that procedure to allow UTF8mb4/Emoji Support since it would have already been supported in v21?  
Thanks

**Comment by ssddanbrown** [comment]
> So there's basically no current use for that page except for upgrading old databases? Is that to say that I really didn't need to do that procedure to allow UTF8mb4/Emoji Support since it would have already been supported in v21?

Yeah, That is correct. Shouldn't have done any harm though.

**Comment by southeasterntech** [comment]
thanks!! clears it up!
