### ISSUE TITLE
[Support Request]: S3 configuration is unclear in docs

### ISSUE THREAD

**Issue by chrisaalid** [BookStackApp/BookStack#3126]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

Hello — I'm trying to configure Bookstack to use S3 for image uploads, [per the documentation](https://www.bookstackapp.com/docs/admin/upload-config/).

I cannot get it to work and I suspect I'm not providing the right values for bucket & region, but the format of the value Bookstack expects is unclear from the documentation.

- Is `bucket` supposed to be the full `https://<bucket-name>.s3.us-east-2.amazonaws.com`? or just `<bucket-name>`?
- Is `region` supposed to be a full `us-east-2.amazonaws.com` or just `us-east-2`?

Could someone provide insight into the expected format for those? An update to the docs with an example configuration would be helpful as well.

### Exact BookStack Version

v21.08.3

### Hosting Environment

Ubuntu 20.04 (LTS) x64, installed via official installation script

**Comment by ssddanbrown** [comment]
Hi @chrisaalid,

- Bucket is just `<bucket-name>`.
- Region is just `us-east-2`.

I won't update the docs yet with an example, as I don't want to complicate them where this has not been previously reported as an issue, since I don't think there's any suggestion these values would be urls, but I'll keep this in mind in the event it becomes a common question.

Since the question has been answered I'll close this off but just shout if further clarification is needed.
