### ISSUE TITLE
[Feature Request]: Add custom shelves ordering

### ISSUE THREAD

**Issue by tautvilis** [BookStackApp/BookStack#3132]
### Describe the feature you'd like

It would be nice to have custom shelve ordering like you can do it with books.

### Describe the benefits this feature would bring to BookStack users

Customization of the main page.

**Comment by ssddanbrown** [comment]
Hi @tautvilis, thanks for the request. 

> It would be nice to have custom shelve ordering like you can do it with books.

Currently the `/shelves` sorting functionality matches that of the `/books` sorting functionality. Both are aligned and do not have custom sorting since they can both act as top-level items within the content hierarchy. 

> Customization of the main page.

Customization alone is not really a definition of benefit to users. There'd need to be some considerable & tangible benefits to be worth implementing and maintaining another type of sort view for top-level items, especially since there's been little demand for such feature so far.

**Comment by ssddanbrown** [comment]
Since there's been no follow-up I'll close this off.
