### ISSUE TITLE
[Feature Request]: APNG Support

### ISSUE THREAD

**Issue by paviro** [BookStackApp/BookStack#3136]
### Describe the feature you'd like

It would be amazing if Bookstack could support animated PNG graphics. 

### Describe the benefits this feature would bring to BookStack users

Another supported format for animated graphics that has better color etc. than gif is useful IMHO.

### Additional context

Currently the generated scaled version of uploaded images looses the animation when using apng.

**Comment by mecco86** [comment]
hello i've a problem with this modules after update a last version MagicMirror with node.

**Comment by ssddanbrown** [comment]
Thanks for the request @paviro, I've made some changes in 31f1dca8a81e70aa8b5598fdaf4af772a28ac9c9 to better support apng images. The generated "display" thumbnails will now be bypassed for files detected as apng to serve the originally uploaded image. This is what we do already for GIFs although APNGs proved trickier due to having the same extension and mime as normal png images.

Note: this may not work with already-upload apng images, only new ones.

This will be part of the next patch release, v21.12.1 so will therefore close this off.

@mecco86 To be honest I'm not sure what you're referring to in regards to node or MagicMirror. Neither of those terms are in discussion here. Feel free to open a new support/bug-report issue if you're having a BookStack specific issue.

**Comment by paviro** [comment]
Awesome thank you very much @ssddanbrown for the quick addition!
