### ISSUE TITLE
[Feature Request]: add the possibility to generate charts

### ISSUE THREAD

**Issue by AC-WhiteGlint** [BookStackApp/BookStack#3145]
### Describe the feature you'd like

Hi,

Could you implement https://www.chartjs.org/ into bookstack to help generate any kind of charts?

### Describe the benefits this feature would bring to BookStack users

Generating chart easely without requiring an external application

**Comment by ssddanbrown** [comment]
Thanks for the request @AC-WhiteGlint. 

This request is asking quite a lot in reality, since we'd need to build in the systems and interfaces to support data input, chart configuration, display handling, editor integration and export support. In addition, I try to keep user content away from proprietary formats which chart.js would effectively be unless we support another intermediary format.

The advised benefit if not "requiring an external application" is fairly weak since that could apply to almost any feature request, it's not really clear how this would fit into the system or how the build and maintenance effort would be worthwhile. Note, I think you could technically draw out a chart in the diagrams.net/draw.io integration, never tried myself though.

Due to the above I'll likely close this off as out of scope unless I've misunderstood something or there's further discussion to be had.

**Comment by AC-WhiteGlint** [comment]
Maybe you can have a look at this : https://github.com/highcharts/highcharts 

https://www.highcharts.com/blog/tutorials/how-to-integrate-highcharts-editor-into-tinymce-editor/

This should be doable.

My idea was wo only use bookstack editor and not change windows/tab to do the charts keeping the focus on the same window.

**Comment by AC-WhiteGlint** [comment]
Btw good work on bookstack it is really great!

**Comment by ssddanbrown** [comment]
Thanks @AC-WhiteGlint!

> This should be doable.

It's definitely doable, just not feasible in my opinion at this stage of the project. 

I do have a fair amount of experience with both highcharts and chart.js.  
Although highcharts offers some level of configuratiuon UI, and TinyMCE integration, that still doesn't solve all the concerns and we'd likely be moving away from TinyMCE soon anyway. In addition, highcharts is not free/open-source so not something we can include.

**Comment by AC-WhiteGlint** [comment]
Got it! Do you know which editor you will be using to replace TinyMCE?

**Comment by ssddanbrown** [comment]
Will likely be prosemirror, Done some scoping in this issue: #2738

As per the above, will therefore close this as out of scope.
