### ISSUE TITLE
[Bug Report]: 

### ISSUE THREAD

**Issue by madsmka** [BookStackApp/BookStack#3165]
### Describe the Bug

After upgrading to version v21.12.1 our site returns HTTP error 500. Under the upgrade there was no errors.

Our bookstack shows the following errors.

[Bookstack Log.txt](https://github.com/BookStackApp/BookStack/files/7869197/Bookstack.Log.txt)

### Steps to Reproduce

1. Run command "git pull origin release && composer install --no-dev && php artisan migrate"
2. Run command "php artisan cache:clear"
3. Run command "php artisan config:clear"
4. Run command "php artisan view:clear"

### Expected Behaviour

I expected our Bookstack to be upgraded to version v21.12.1.

### Exact BookStack Version

v21.08.6

### PHP Version

7.3.33

### Hosting Environment

Ubuntu 18.04.6, VMware Virutal Machine, installed using official script.

**Comment by ssddanbrown** [comment]
Hi @madsmka,
My guess at the issue here would be that you're running BookStack on PHP 7.2, which is what the default would have been for your Ubuntu 18.04 setup.

Quite often the command line and server PHP versions can be mis-aligned. 
If possible, could you attempt to remove all instance of PHP7.2 and restart apache afterwards?

As an added note, We'll soon be dropping support for PHP7.3 so, if possible, it might be beneficial to upgrade to PHP8 at this stage.

**Comment by madsmka** [comment]
> 

Hello ssddanbrown,

I tried removing PHP7.2 completely and that seems to have solved the problem. Thank you.

We will be looking into upgrading to PHP8 soon.

**Comment by ssddanbrown** [comment]
Awesome, Happy to hear it's solved!
