### ISSUE TITLE
[Bug Report]: Grammarly does not render when editing articles

### ISSUE THREAD

**Issue by escnmueller** [BookStackApp/BookStack#3168]
### Describe the Bug

Grammarly does not render when editing articles.

When using Grammarly it does not highlight any spelling or grammar mistakes or load the little circle. if you know there is a mistake you can click on it (the word) and it will load the Grammarly and you can fix the said mistake. Tired multiple browsers 

### Steps to Reproduce

install the Grammarly plugin
enable it for the site
edit any article

### Expected Behaviour

To be able to use Grammarly. 

### Screenshots or Additional Context

![image](https://user-images.githubusercontent.com/61297484/149592711-00c59a16-bda9-488d-a70b-e6b836c3694a.png)
![image](https://user-images.githubusercontent.com/61297484/149592790-f403b04a-5673-47bd-b527-d26dceee4f28.png)

### Exact BookStack Version

21.12.2

### Hosting Environment

Docker via the LinuxServer.io install

**Comment by ssddanbrown** [comment]
Hi @escnmueller,
We don't really promise support with grammarly, nor any third party browser extensions, hence I wouldn't really consider this a bug in our core platform and will close this off. 

If there's a known tweak in the platform, or an actual bug that's affecting usage, that could be reasonably made to achieve support feel free to specifically raise that otherwise we won't look to take the burden of support for a third-party service.
