### ISSUE TITLE
[Feature Request]: Show page parent context on recently updated list

### ISSUE THREAD

**Issue by mlipok** [BookStackApp/BookStack#3183]
### Describe the feature you'd like
In https://MYURL/pages/recently-updated
could you add a feature to provide more precise localization something like "Shelf / Book / Chapter / Page"

As you can see in the following screenshot this shows only "Page" name for example "TYMCZASOWE" or "Screenshoty"
![image](https://user-images.githubusercontent.com/11089482/150359132-3758f3b2-5f14-4995-bdb9-aceba04c2dfa.png)

### Describe the benefits this feature would bring to BookStack users

BookStack local manager will know not only what but also exactly where was changed.
@Julesdevops thinks that this is `useful enhancement`

### Additional context

It was mentioned here:
https://github.com/BookStackApp/BookStack/pull/3177
Exactly here: https://github.com/BookStackApp/BookStack/pull/3177#issuecomment-1017296759

**Comment by ssddanbrown** [comment]
Thanks @mlipok,
Already had much of the logic in place from the search system which shows this.
Makes sense to have it here also since we're showing them as large list items and there's no existing context for the path.

Note: No shelves will be shown in the path since there's no singular shelf that acts as an owner, since books can be on multiples shelves. 

Added in 7b4086107cb1ae461a4af1dfff5e1ef98cc8b6ad to be part of the next patch release.
