### ISSUE TITLE
[Feature Request]: public access

### ISSUE THREAD

**Issue by Statium** [BookStackApp/BookStack#3194]
### Describe the feature you'd like

When public access is enabled and an unregistered user goes to pages for which public access is closed, an error occurs stating that the page was not found and it is clearly not clear that authorization is needed to view it. Would it be possible to add a feature so that when you go to such pages, the authorization page opens? 

### Describe the benefits this feature would bring to BookStack users

A cleaner interface for inexperienced users.

**Comment by ssddanbrown** [comment]
Hi @Statium, This has already been requested in #2606. Please see that conversation chain for the reasoning we don't auto-redirect, and for potential workarounds.

Since that issue was closed I did make it easier to customize the not found wording, via the theme system, by extracting the text to its own view: https://github.com/BookStackApp/BookStack/blob/master/resources/views/errors/parts/not-found-text.blade.php

**Comment by ssddanbrown** [comment]
Will therefore close this off as a duplicate.

**Comment by Statium** [comment]
In #2606 the method is not working. I don't use ldap auth. Can you tell me how to make a 404 redirect when hitting such a page?

**Comment by ssddanbrown** [comment]
@Statium How far did you get with it? Did you get the theme system working?
