### ISSUE TITLE
[Bug Report]: Update to v21.12.3 from most recent release fails

### ISSUE THREAD

**Issue by jsreynolds** [BookStackApp/BookStack#3196]
### Describe the Bug

- Installation request for doctrine/dbal 3.3.0 -> satisfiable by doctrine/dbal[3.3.0].
- doctrine/dbal 3.3.0 requires composer-runtime-api ^2 -> no matching package found.

### Steps to Reproduce

Applying the update per instructions on [https://www.bookstackapp.com/docs/admin/updates/](https://www.bookstackapp.com/docs/admin/updates/)

### Expected Behaviour

Update without issues

### Screenshots or Additional Context

![image](https://user-images.githubusercontent.com/5440012/150881311-eb0348bd-fbdb-4ca5-90ed-cdbdcd7958af.png)

### Exact BookStack Version

v21.12.3

### PHP Version

7.4.3

### Hosting Environment

Ubuntu 20.04.03 LTS

**Comment by ssddanbrown** [comment]
Hi @jsreynolds,
Could you confirm the output of running the below (To get your composer version)?:

```bash
composer -V
```

**Comment by jsreynolds** [comment]
Sure thing!

`
Composer 1.10.1 2020-03-13 20:34:27
`

**Comment by ssddanbrown** [comment]
Thanks for confirming @jsreynolds,
Apologies, I did not expect this change for the updates made, but looks like composer version >= 2 is required.
If using the originally installed version of composer (Via script) you should be able to just run:

```bash
sudo composer self-update
```

Otherwise, if you're using the system-installed-package you may need to run `sudo apt remove composer` and then follow the composer install instructions: https://getcomposer.org/download/

Let me know if that works for you and, if so, I'll update our update notes to warn others about this.

**Comment by jsreynolds** [comment]
Will do - will take me a few min.

**Comment by ssddanbrown** [comment]
@jsreynolds Just been testing this, The self update command might need to be:

```bash
sudo composer self-update --2
```

**Comment by jsreynolds** [comment]
Mine is a stock Linux install (not a Digital Ocean drop) but after uninstalling the apt composer package as mentioned, I just followed the steps to the letter in the Digital Ocean how-to and all is working again. I went ahead and upgraded as well - all is working and I'm successfully on v21.12.3.

Link: [https://www.digitalocean.com/community/tutorials/how-to-install-and-use-composer-on-ubuntu-20-04](https://www.digitalocean.com/community/tutorials/how-to-install-and-use-composer-on-ubuntu-20-04)

Thank you so much!

-J

**Comment by ssddanbrown** [comment]
@jsreynolds Awesome, Thanks for confirming. I'll update our update notes!

**Comment by Meth0d007** [comment]
Are you planning on fixing this ? Kinda dont want to move from Ubuntu 20.04.3 LTS Packages ..
composer/focal,now 1.10.1-1 all [installed]

**Comment by ssddanbrown** [comment]
Hi @Meth0d007,
I don't see this as a bug to fix.
Although being a bit unexpected to us, and something I'd prefer to leave to a feature release if known beforehand, we'd just go ahead with composer >= v2 being a requirement.

Composer doesn't usually prove as a difficult non-system-package to handle since it's really contained within a single file. Composer v2 brings a lot of improvements anyway, while v1 was often causing issues for people as it grows lesser supported.

Sticking to Ubuntu LTS packages isn't a reason to hold things back. You'll likely need to use a non-Ubuntu PHP package in a year or so time when we require PHP 8 or greater, if still on 20.04.
