### ISSUE TITLE
[Bug Report]: Shelf / Books title images disappear after cache change

### ISSUE THREAD

**Issue by christianhz01** [BookStackApp/BookStack#3242]
### Describe the Bug

Hi Dan,

after I set the cahe to database cache in my instance, all the title images of the shelves and books disappeared. I have put this in the .env:
CACHE_DRIVER=database
SESSION_DRIVER=database

I don't know what's behind this, but at least a note in the documentation wouldn't be bad.

Christian

### Steps to Reproduce

1. Insert this Points in to the .env: CACHE_DRIVER=database and SESSION_DRIVER=database
2. all titel pictures are gone now

### Expected Behaviour

That no pictures are lost :)

### Exact BookStack Version

21.12.4

### PHP Version

7.3

### Hosting Environment

Ubuntu20, PHP7.3, MYSQl, Apache2

**Comment by christianhz01** [comment]
Profile pictures also affected...

**Comment by ssddanbrown** [comment]
Hi @christianhz01,
A change of these values alone should not cause a loss of the described images.
Changing the cache can cause BookStack to look to the storage mechanism, instead of the cache, for image thumbnail information. If this errors then images may fail to show.

- Have you attempted changing any of the file storage locations?
  -  (A change of folders or changing the `STORAGE_TYPE`, `STORAGE_IMAGE_TYPE` or `STORAGE_ATTACHMENT_TYPE` options)
- Do you get any errors logged when loading a page with these images?
   - Error log location described on this page: https://www.bookstackapp.com/docs/admin/debugging/

**Comment by christianhz01** [comment]
Hi @ssddanbrown,

yes, I changed STORAGE_TYPE, STORAGE_IMAGE_TYPE,STORAGE_ATTACHMENT_TYPE.

I found this logs, but I dont think that there are relevant:

[2022-02-04 09:22:02] production.ERROR:  {"exception":"[object] (BookStack\\Exceptions\\StoppedAuthenticationException(code: 0):  at /var/www/html/BookStack/app/Auth/Access/LoginService.php:40)
[stacktrace]

[2022-02-04 09:38:02] production.ERROR:  {"exception":"[object] (BookStack\\Exceptions\\StoppedAuthenticationException(code: 0):  at /var/www/html/BookStack/app/Auth/Access/LoginService.php:40)
[stacktrace]

Christian

**Comment by ssddanbrown** [comment]
@christianhz01 Okay, In that case it sounds like the images cannot be found in their expected locations.
What changes to the `STORAGE_*` options did you make and what did you do with the original image files?

**Comment by christianhz01** [comment]
@ssddanbrown  This are my "STORAGE*" Settings:

STORAGE_TYPE=local_secure
STORAGE_IMAGE_TYPE=local_secure
STORAGE_ATTACHMENT_TYPE=local_secure

Christian

**Comment by ssddanbrown** [comment]
@christianhz01 Did you move the existing image files when changing this option, as per the documentation?:

> If you’d like to switch to this option from the default local storage system you’ll first need to migrate existing image uploads to the image folder listed above.

**Comment by christianhz01** [comment]
Okay, that was the mistake... Who can read is clearly at an advantage :) Thanks for the quick help anyway.
