### ISSUE TITLE
[Feature Request]: Add direct `Ctrl+Shift+K` entity selector popup shortcut in WYSIWYG editor

### ISSUE THREAD

**Issue by dc31xx** [BookStackApp/BookStack#3244]
_Note by @ssddanbrown_ 

This request thread resulted in focusing on adding the `Ctrl+Shift+K` shortcut to the WYSIWYG editor, to show the entity select popup for quick cross-linking. This aligns in shortcut and functionality with the existing markdown shortcut. 

---

### Describe the feature you'd like

I would like to be able to link to other pages within my bookstack without knowing the exact URL or PageId. I would start typing:

1.  `[` 
2. Then some search term to find the exact page withing my BookStack. 
3. Upon selecting the correct page it would close with `]`

Like in tagging people with `@`: [Confluence example](https://www.atlassian.com/blog/confluence/four-fast-ways-to-link-to-content-in-confluence)

### Describe the benefits this feature would bring to BookStack users

Links between content makes for a better experience and prevents DRY. If I can easily link to another page I will do it, if it takes to much effort I wont.

### Additional context

I just love the way BookStack works. IMHO this is the only mature feature missing (or available without me knowing).

**Comment by ssddanbrown** [comment]
Thanks for the request @dc31xx,
This runs very close to issue  #441. I may close this off as a duplicate once any discourse here runs dry.

I'm not really looking to support certain methods/syntax just to align with another platform.
I am however open to addressing the fundamental benefit/feature of easier access to cross linking.
We have to keep a couple of things in mind:
- Usability for our core audience (Including the less technical).
- Portability of content.

I don't really want to be introducing certain type characters that cause actions/popups (`[`) as I don't feel that's a good route for usability, especially since square brackets are not a highly unlikely character for actual content. 

As it stands you can get to a link selector, without using the mouse, via the following in the WYSIWYG editor:
- Select content > `Ctrl + K` > Tab > Enter. 

Perhaps we just need to private a more directly accessible route. In the markdown editor we have `Ctrl+Shift+K` to directly access the same popup box that shows. Maybe step 1 is brining that shortcut to the WYSIWYG editor.

**Comment by dc31xx** [comment]
Thank you for your response. 

> I'm not really looking to support certain methods/syntax just to align with another platform.
I get that. Keep in mind that Confluence

> We have to keep a couple of things in mind:
 Usability for our core audience (Including the less technical).

I have to remark that Confluence is not (only) for technical people. I do get that mimicking other platforms is not a goal. The funny thing is that as a technical person I found it obvious that one could link via a certain syntax. This way I discovered the `[`-syntax in Confluence just by trying. On the other hand I didn't even notice the little folder icon in the Link (<kbd>Ctrl</kbd>+<kbd>K</kbd>) window! So actually, the way of linking that I was looking for (via UI) was already implemented, but I just couldn't find it.

> I don't really want to be introducing certain type characters that cause actions/popups ([) as I don't feel that's a good route for usability, especially since square brackets are not a highly unlikely character for actual content.

I get this. I have to admit it can be annoying if you do want to enter `[` in actual content, but this behaves the same way as suggestions on your iPhone. Escape will remove the popup.

> Perhaps we just need to private a more directly accessible route. In the markdown editor we have Ctrl+Shift+K to directly access the same popup box that shows. Maybe step 1 is brining that shortcut to the WYSIWYG editor.

Already quite happy to find out that the feature I was looking for is not actually missing. I do think however that this might be an improvement.

**Comment by ssddanbrown** [comment]
Yeah, We could do better at making the shortcuts more discoverable. Maybe by adding a possible overlay popup from link, that's where I wanted to get to when I get around to more general interface shortcuts.

I get that content-base auto-formatting is used elsewhere, but I really don't want to go down that road if we can have less intrusive alternatives, especially since introduction content-input-based actions would be introducing a potential annoyance to those that really don't want them (In which case we then have to add controls to allow disabling/reverting of behaviour). 

Are you using the WYSIWYG editor and, if so, are you happy for me to re-focus this issue for `Ctrl+Shift+K` link selection input to move us closer to fundamental described benefits?

**Comment by martijnhazebroek** [comment]
Yes and yes 🙂

**Comment by dc31xx** [comment]
Yes and yes 🙂

**Comment by ssddanbrown** [comment]
Required change applied in #3298, awaiting scheduling into a release.

**Comment by ssddanbrown** [comment]
This has now been merged and will be part of the next feature release.
