### ISSUE TITLE
iOS Mobile Compatibility

### ISSUE THREAD

**Issue by thecek** [BookStackApp/BookStack#326]
### For Feature Requests

Desired Feature: iOS Mobile Compatibility

First of all, what a great and exciting project. Congratulations!

I tried to use it with an iPhone 5S and the responsiveness wont work well. I dont know if it should works however it would great to have it working on small screens like 4inches or greater. Also tinymce wont respond well at ios.

What do you think?

### For Bug Reports

* BookStack Version:
* PHP Version:
* MySQL Version:

**Comment by ssddanbrown** [comment]
Hi @thecek, Sorry for my late reply. Thanks for your compliments and your enthusiasm regarding BookStack.

During development I've always tried to build things to be vaguely responsive but desktop based environments has been the primary focus for a platform such as this. I would like to get all viewing/discovery based activities working well on mobile (Page viewing, searching etc..) but editing and admin tasks are a bit harder to accommodate for. Things like TinyMCE may always be an dodgy experience on mobile but we'll try to make it better. 

If there's any specific things that are bad to view on mobile feel free to open a specific issue otherwise I'm thinking about having a bit of a design update soon, at which point more focus will be put on mobile.

**Comment by thecek** [comment]
Hello @ssddanbrown, thanks for replying. 

I´ll let some thoughts here regarding this subject of mobile responsiveness.
While researching, I found TinyMCE very limited on mobiles, and found a project LGPL called [AlloyEditor](http://alloyeditor.com/), very interesting.

It seems to work great on editing while using safari on iOS, algo seems to have a great ux at desktop browser too. 

It is built upon CKEDITOR, perhaps it has all the stuff needed for customizing and replace TinyMCE.

Appreciate to hear your thoughts on that whenever you get time for it.

Best,

**Comment by david-zaletanski** [comment]
I’d like to second this. I really love Bookstack but was very disappointed to see how it functions on iPhone, for all intents and purposes the glitchy, crowded UI makes it unusable. For someone who always has their phone on them and needs to write ideas down when they come to them, it’s kind of a necessity.

**Comment by zhdenny** [comment]
I would VERY much appreciate seeing much better mobile viewing. I'm on Android and it is basically impossible to actually add/edit......and just barely manageable for viewing.

**Comment by ssddanbrown** [comment]
Just come across this. Since this issue was opened we've made some massive improvements to mobile usage, especially in [v0.26](https://www.bookstackapp.com/blog/beta-release-v0-26-0/) released last may, including a focus on iOS.

I'm therefore going to close this off since the platform is very different now. If you notice any particular issues feel free to open new, focused issues for them here on GitHub.
