### ISSUE TITLE
[Feature Request]: "Similar pages" instead of "Next page"

### ISSUE THREAD

**Issue by christianhz01** [BookStackApp/BookStack#3268]
### Describe the feature you'd like

Hi @ssddanbrown ,

there is the feature "next page" or "last page" when you are on a book page. This is logical if you actually compare BookStack with a bookshelf-book-page constellation. But I think a "Similar Pages" or "Similar Articles" would make more sense for most users, since BookStack is (I think) mainly used for documenting. There it would be simply practical e.g. to the same topic, pages to get displayed. Alternatively, I can imagine this as an item in the server settings or in the book settings.

### Describe the benefits this feature would bring to BookStack users

Better transition to similar topics or easier search for related topics

**Comment by ssddanbrown** [comment]
Thanks for the request.

I think this really comes down to opinion, and I'd prefer to stick with the option we've already implemented, especially since next/previous navigation was strongly requested wheras "similar pages" was not so much.
I don't want to expand options to cover this, especially since the control requested is toggling between two fairly distinct features. "Similar Pages" would probably be an addition rather than a toggled setting tied to next/previous navigation.

Similar page functionality has already been requested in  #982 so I'm going to therefore close this off to reduce duplicates.
