### ISSUE TITLE
Good afternoon, please tell me the possibility of implementing a preview of documents before downloading Excel and Word

### ISSUE THREAD

**Issue by vpnwe912** [BookStackApp/BookStack#3269]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

Good afternoon, please tell me the possibility of implementing a preview of documents before downloading Excel and Word

### Exact BookStack Version

21.12.2

### PHP Version

7.4

### Hosting Environment

Good afternoon, please tell me the possibility of implementing a preview of documents before downloading Excel and Word

**Comment by ssddanbrown** [comment]
Hi @vpnwe912,

> please tell me the possibility of implementing a preview of documents before downloading Excel and Word

The possibility, of something directly built in, is very unlikely. Supporting these formats would require a great deal of effort which we don't have at this time.
Our focus is instead on the core page content within BookStack.

**Comment by ssddanbrown** [comment]
Since the original question has been answered and there's been no follow up I'll close this off.

**Comment by sdhadi** [comment]
This is our problem/request too. This feature could be so useful because there are too many documents already exist in data warehouse of companies which they trying to implement in their Bookstack portal. 
Viewing and even ability to search in the Word and Excel document with native Bookstack's search module  would be very useful. Some other DMSs and Wikis already has this feature. Copping contents  from Word to Bookstack's editor is easy but copping and transferring info and content from Excel document to Bookstack's editor is time consuming, tedious and some times impossible because the Bookstack's editor is not natively a spreadsheet.
@ssddanbrown do you think it is worth it I raise a new feature by this explanations?
