### ISSUE TITLE
[Support Request]: KeyCloak Auth Support

### ISSUE THREAD

**Issue by zhangxiaokang** [BookStackApp/BookStack#3270]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

bookstack login with keycloak

### Exact BookStack Version

v21.12.5

### Hosting Environment

docker

**Comment by ssddanbrown** [comment]
Hi @zhangxiaokang,

Unfortunately there's much information here for us to understand the issue.
- What have you attempted so far?
- Are you getting specific errors?

If it helps, some users have shared details of their Keycloak setup in this following thread: #1157

**Comment by zhangxiaokang** [comment]
OIDC_ISSUER  must start with 'https://'? why not 'http://'?

**Comment by ssddanbrown** [comment]
@zhangxiaokang Because that's part of the spec to ensure security of the authentication method. From the OIDC spec:

> An Issuer Identifier is a case sensitive URL using the https scheme that contains scheme, host, and optionally, port number and path components and no query or fragment components. 

Taken from here, section 1.2: https://openid.net/specs/openid-connect-core-1_0.html

**Comment by ssddanbrown** [comment]
Since there's been no further follow-up I'll close this off.

**Comment by gugigunawan** [comment]
Hello, 

i working to integrate Keycloak and Bookstack right now at My Office but have issue to login from Keycloak to BookStack and APP_DEBUG set to TRUE not help so much.

Any suggestions ? because the error only "**ID token validate failed with error: Token issue at time is not recent or is invalid**" 

Bookstack Version : v23.10.2

Keycloak Version : v23.0.4

**Comment by ssddanbrown** [comment]
@gugigunawan Please ensure both systems/hosts/containers have the correct time set.
If you need further help, please open a new support issue.

**Comment by gugigunawan** [comment]
Hello,

i already have correct set time zone between Docker Image & Hosts System by adding this at docker-compose.yaml
<img width="272" alt="image" src="https://github.com/BookStackApp/BookStack/assets/9584750/a5766900-a0c2-495f-995d-096b2760f1e8">

but when i change .env file for AUTH_METHOD from standard and oidc still have the same error
any suggestion ? 

Thank's and Best Regards.

**Comment by ssddanbrown** [comment]
@gugigunawan That reflects the timezone config, not that the actual time is correct. Check that the time is correct in the BookStack container (for example, by going inside the container and using the `date` command) and for the keycloak system/container.

**_If you need further help, please open a new support issue rather than commenting in this closed thread._**
