### ISSUE TITLE
[Feature Request]: Support for laravel 9

### ISSUE THREAD

**Issue by chyeteck** [BookStackApp/BookStack#3273]
### Describe the feature you'd like

Laravel 9 and php 8 is available now. I would like to use upgrade and use them.

### Describe the benefits this feature would bring to BookStack users

users will be able to use laravel 9 on bookstack with php 8.0

**Comment by ssddanbrown** [comment]
Hi @chyeteck,
We have had support for PHP8.0 for a while now, and support for PHP8.1 since release v21.11.

Is there any reason why upgrading to Laravel 9 would bring any significant benefit for us at this stage?
I'd generally be planning to upgrade quite late in the Laravel 8 lifecycle to manage lower-end PHP version requirement changes.

**Comment by ssddanbrown** [comment]
Will therefore close this off since there is no clear benefit of this request at this time.

**Comment by Cave-Johnson** [comment]
I realise this is closed due to no response from the original poster. The benefits I can see to upgrading to Laravel 9 would be:
- Its the new LTS and is supported until Feb 2025
- Fulltext indexes and where clauses
- New scout database engine for Eloquent models

**Comment by ssddanbrown** [comment]
Thanks @Cave-Johnson,

Yeah, so there's no significant need to upgrade at this time as we're not in current demand of any of those features.
Note, Laravel 9 is no longer LTS and has a lesser support lifetime. Again, we will upgrade to this but at a time that fits into the project.
