### ISSUE TITLE
[Feature Request]: Video scrubbing

### ISSUE THREAD

**Issue by alexphillips-dev** [BookStackApp/BookStack#3274]
### Describe the feature you'd like

Scrubbing in the video player to allow moving the slider along the timeline back and forth in order to get the needed point right away, without waiting when the track reaches this moment “in a natural way”.

### Describe the benefits this feature would bring to BookStack users

Our use case is uploading videos recorded from Teams to a Bookstack page with multiple video files for our training chapter. Would be nice if when users return to the page they don't have to wait for the video to slowly play again back to where they were, they could just move the slider forward and pick up where they left off.

**Comment by s00500** [comment]
There also seems a bug involved here: in Firefox one can at least jump to places in a video, but in chrome based browsers the bar just jumps back and the video continues where it was... seems to be a chrome thing with the video tag... have not found a nice way around it yet

**Comment by ssddanbrown** [comment]
Related to #882, May close/merge this into that in the future.

If you host the video somewhere that can properly support range requests (Most webservers can do this) then scrubbing should work fine. BookStack's attachment serving does not currently support range requests hence the lack of scrubbing.

**Comment by jennso** [comment]
Has anyone found a workaround for this or has it been implemented, my goal is to have embedded mp4 videos that can be scrubbed and skip while playing.

Thank You!

**Comment by LHBL2003** [comment]
I would also be happy if it works in Chrome.  in Firefox, fast forwarding it still works.

**Comment by ssddanbrown** [comment]
Range request support has been added in PR #4758, to be part of the next feature release.
This allows video scrubbing. There are some limitations for this, if using cloud (s3) storage but those concerns could be raised separately if an issue, otherwise should work for most cases.
That PR also eases adding videos from attachments by adding them as a video embed automatically when dragged in from the attachments bar (or when the link button is used).

Note though, browsers can treat videos in different ways, likely depending on a number of factors. Worked fine in my testing although Safari could act strange and often still want to download the whole video in a single big chunk, although this may change depending on network conditions and other factors.
