### ISSUE TITLE
[Feature Request]: [WYSIWYG] Toggle on insert link for perma link rather than generated link

### ISSUE THREAD

**Issue by robertfshort** [BookStackApp/BookStack#3283]
### Describe the feature you'd like

When inserting a link to a page, browsing to find an internal link is great, but, knowing that my users like to rename things it would be handy if there was a way to have it insert the perma link instead of the current name of the document.

### Describe the benefits this feature would bring to BookStack users

Some users like to change page names... frequently... Inserting a perma link removes any need for the system to try to figure out what page it's referring to.

**Comment by ssddanbrown** [comment]
Thanks for your request @robertfshort,
But as per #3277, I'm going to close this off under the same reasoning as I've put forward in #2917.
I don't want to build features around the permalink system since the primary goal would be to move to links that are permalinks by default, but this will take a little more time to get to.
