### ISSUE TITLE
[Bug Report]: When you click anywhere in the editor, the content will jump to the top

### ISSUE THREAD

**Issue by JoshuaChoi819** [BookStackApp/BookStack#3287]
### Describe the Bug

When you click anywhere in the editor, the content will jump to the top

![933fb52106ca9a71b0f9e4b087388b3f](https://user-images.githubusercontent.com/100438364/155767439-51a82249-1cf9-4a3d-b88a-bb9f16754958.gif)

### Steps to Reproduce

1. Insert a long text

2. Drag the text to the bottom

3. Click the text or button

### Expected Behaviour

-

### Exact BookStack Version

 v21.12.5

### Hosting Environment

-

**Comment by ssddanbrown** [comment]
Thanks for reporting @JoshuaChoi819, with clear video guidance.
Likely related to #2692.
Can confirm this occurs on the latest release version, but we've made substantial changes to the editor for the next release and the same testing on the development branch does not cause this to occur so will likely be fixed in the next release. Will therefore close this off but if you still experience issues after upgrading to v22.02 (due to release soon) feel free to comment back here and this can be re-opened.
