### ISSUE TITLE
Internal Domain Certificate authority for Webhooks and other SSL-Stuff

### ISSUE THREAD

**Issue by crpb** [BookStackApp/BookStack#3294]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

Hi there,
i have an installation in which we implemented the Webhooks to send Updates to the Intranet-Webserver.
Both the Bookstack and the Intranet-Site are accessible via SSL-Certificates from the internal Microsoft Certtificate Authority and so the verification from an Docker-Installation ( we used the [linuxserver/bookstack](https://github.com/linuxserver/docker-bookstack) release ) is throwing an SSL-Cert-Error.

So to be able to do as less as possible when i Update the Image ( Change the Numbers ) and just using one simple Docker-Compose-File I whipped up a script which will be run in the Docker-Guest from the `/etc/periodic` Folder. The script itself does an reboot which i just used out of laziness as the Guest does that within seconds...
And as it checks for the presence of the local Certificate in `/etc/ssl/cert.pem` it will only reboot once every update.

Here is my additional line in the `docker-compose.yaml`
```
...
    volumes:
...
      - ./bookstack/periodic/ca-add:/etc/periodic/hourly/ca-add
...
```

The Script with the relative Path
`./bookstack/periodic/ca-add`
```
#!/bin/bash

COMMPARED="$(comm -13 <(sort -u /etc/ssl/cert.pem) <(sort -u /config/keys/ca.crt))"
if [[ ! -z $COMMPARED ]]; then
  cp /config/keys/ca.crt /usr/local/share/ca-certificates/MYCA.crt
  update-ca-certificates
  reboot
else
  exit 0
fi
```

And the `ca.crt` i just throw in the `config/keys`-Folder.

It worked for couple of Updates so far.

I just wanted to share that solution for anyone out there who need's SSL-Verification with Non-Globally-Published Certificates from Mozilla :-)

Cheers.

### Exact BookStack Version

22.02.1

### Hosting Environment

Docker with an [Compose-File.](https://github.com/linuxserver/docker-bookstack#docker-compose-recommended-click-here-for-more-info)

**Comment by MarcBollmann** [comment]
I also had the issue with Open-ID-Connect that my Identity Provider was in the intranet. While logging in I got also an SSL Error because ther cert of my intranet Identity Provider was not trusted. Thats why I had to build my own docker-image:
```
FROM linuxserver/bookstack:23.02.3
ADD ./MTG+CA.crt  /usr/local/share/ca-certificates/CERT_TO_BE_TRUSTED.crt
RUN chmod 644 /usr/local/share/ca-certificates/CERT_TO_BE_TRUSTED.crt && update-ca-certificates
```

built the docker-image with `docker build . -t linuxserver/bookstack:mtg`

**Comment by MarcBollmann** [comment]
In case anyone has also issues with Open-ID-Connect and an identity provider which is located in the intranet:

While logging in I got also an SSL error because the certificate of my intranet identity provider was not trusted. That's why I had to build my own Dockerfile and docker-image with a small modification:
```
FROM linuxserver/bookstack:23.02.3
ADD ./CERT_TO_BE_TRUSTED.crt  /usr/local/share/ca-certificates/CERT_TO_BE_TRUSTED.crt
RUN chmod 644 /usr/local/share/ca-certificates/CERT_TO_BE_TRUSTED.crt && update-ca-certificates
```

Build the docker-image with `docker build . -t linuxserver/bookstack:YOUR_CUSTOM_TAG_NAME` and reference it in the docker-compose file.
