### ISSUE TITLE
Book names are not sorted by name in shelves overview, when sorting by name

### ISSUE THREAD

**Issue by jhrdt** [BookStackApp/BookStack#3309]
### Describe the Bug

The book names in the shelves overview are sorted by creation date instead of name (when sorting shelves by name).

### Steps to Reproduce

1. Create a shelf s
2. Create a book Z in s
3. Create another book A in s
4. Go to shelves

### Expected Behaviour

* When looking at the shelves overview (in "List View" and "Sort by Name" is selected)
  * The book names should be sorted by name 

### Screenshots or Additional Context

![grafik](https://user-images.githubusercontent.com/22557140/156568315-57969a62-6da0-4f0a-9910-0e082c1b4504.png)

### Exact BookStack Version

BookStack v22.02.1 

### PHP Version

7.4

### Hosting Environment

Ubuntu LTS

**Comment by ssddanbrown** [comment]
Hi @jhrdt,

> The book names in the shelves overview are sorted by creation date instead of name

I don't think this is the case. Books within a shelf are generally sorted by their manually managed ordering. 

I think expected behaviour here is a matter of opinion and expectations; Should the ordering of the shelves affect their contents or should the curated ordering be respected? I'm tempted to side upon the latter since that's the current functionality and otherwise the existing curation becomes tricky to achieve or becomes more redundant.

**Comment by jhrdt** [comment]
Hi @ssddanbrown ,

OK, this was as misunderstanding on my side. It wasn't obvious to me where the ordering comes from. Thank you.
