### ISSUE TITLE
Tab indentation 

### ISSUE THREAD

**Issue by Ismael034** [BookStackApp/BookStack#3316]
### Describe the Bug

When editing a page in WYSIWYG, the Tab key is being used as a browser navigation key therefore, there is not an option to have tab indentation in the text.

### Steps to Reproduce

1. Edit a page
2. Use Tab, the cursor will disappear and it wont create a tab indentation

### Expected Behaviour

When the cursor is in the editing page and when the tab key is pressed the cursor dissapears and instead it navigates to the next browser control.

It should instead keep the indentation like any other text editor would do.

It works fine with bulleted lists for some reason but not if I want to create a single tab

### Exact BookStack Version

v22.02.3

### Hosting Environment

Ubuntu Server installed using the Docker image

**Comment by ssddanbrown** [comment]
Thanks for the request @Ismael034,

I think this is really a matter of expectations and opinion instead of a bug.
We support tabs within code blocks which is the common primary use-case for them.
Outside of that tabs are not so common in the content formats we support and can act inconsistently. In addition we'd need to consider how we're affecting accessibility and current user flows in changing the behaviour.

Due to the above, and since this has not been strongly requested in the last 6 years, I'd look to keep the existing functionality instead of changing to your expected behaviour. 

Note, there is an option to indent an entire block if that's what you need. This can be found in the editor toolbar overflow within the same sections as the list blocks.

**Comment by Ismael034** [comment]
Hi @ssddanbrown 

Thanks for the quick and derailed answer! It's indeed more like a request depending of what you are expecting when writing. 

So my main issue is when I want to structure my writting. For example, sometimes I just want tabs instead of bulleted list and it would be more comfortable for me to have tabs but I completely understand that you want to keep the existing behavior as this is what most users are expecting to be.

Also I didn't know about the block indenting feature. Haven't tried it yet but it seems to more less solve my issue

As of this I think I am closing this issue if you are ok with it and also, thank you for creating such an amazing tool!
