### ISSUE TITLE
Update updated_at field when tags are changed

### ISSUE THREAD

**Issue by FooB4r** [BookStackApp/BookStack#3319]
### Describe the Bug

The *updated_at* date in the json response (i.e. `/api/pages`) is not modified when the last update modifies only tags.
I think it would be more coherent to change this date when the tags are updated.
Moreover the tags are not listed in the list of elements queried (see #2680), therefore we cannot test for modified tags directly.

### Steps to Reproduce

1. Create a page
2. Change only the tags (in a different commit)
3. Request the list of pages
The updated_at date is the creation date instead of the tag modification date.

### Expected Behaviour

I expect to have every actions listed in the commits to change the updated_at date. That is : 
- Every content modification
- Every tag modification

### Screenshots or Additional Context

I am using Bookstack v21.05.3.
I found the following related issues
- #2680 which would in a way solver the problem.
- #1777, focuses on sorting pages and updating the date but does not mention tags

### Exact BookStack Version

v21.05.3

### Hosting Environment

I unfortunnately do not know any information on the hosting environement.

**Comment by ssddanbrown** [comment]
Thanks for reporting @FooB4r.

I was on the fence with this once, since this behaviour may come down to opinion due to tags maybe being considered a separate entity in themselves. Could choose either way, update or not update.
That said, since we're now updating the search index for content based on tags, tags could now be considered part of the content hence I agreed It makes sense to update timestamps on tag change.

The functionality has been added in c30a9d35643da526f5ea6299d053b6f0dea3bcb1, with testing to cover. This will be part of the next patch release.
