### ISSUE TITLE
Font choice ?

### ISSUE THREAD

**Issue by NinjaAway** [BookStackApp/BookStack#3330]
### Describe the feature you'd like

Hello! 
First things first, thank's for your tool, it's a really great one!

And for the feature, is it possible to add some font customisation on the page ? Not only on the global website.
Maybe juste a few could be nice ! Example : 
- Arial
- Calibri
- Perpetua
- Segoe UI
- Times New Roman

For naming the most "wanted".

Thank's ! :) 

### Describe the benefits this would bring to existing BookStack users

More versatility ! 

### Can the goal of this request already be achieved via other means?

Except changing the CSS of the whole site, I dunno.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

0 to 6 months

**Comment by ssddanbrown** [comment]
Thanks for the request and your kind feedback @NinjaAway.

The benefit provided of "More versatility !" is not really a strong benefit since it could apply to any feature request that adds more options. There needs to be strong reasoning why this specific feature would provide unique benefit.

Based upon the lack of request so far, I don't think this would be worth adding to the core project. We'd have to make it optional, since many environments would probably not want this feature, and we'd need to allow configuration of the font list since even those listed in your request are not available on every machine. Then we get into complications of having to communicate font availability to the person configurating that list, and potential provide ways to load additional fonts efficiently? Then we have things like export formats to consider and editor support. Overall it'll be a fair amount of effort/maintenence for an optional feature that would have its own options/configuration, which I am not a fan of.

**Comment by ssddanbrown** [comment]
Since there's been no follow-up or further discussion to prove benefits or requirement I'll close this off.

**Comment by BloodyIron** [comment]
Hi @ssddanbrown I want to throw my hat into the ring for this topic a bit.

So I am not necessarily saying I want to match the exact ask that @NinjaAway speaks to here. However, I think it would be worthwhile at times to have a very short list of fonts (a default list) that can be switched between. In my particular case, the default font cannot tell between an upper case i and a lower case l. And I don't always want to use code blocks to have that visual distinction. So if in that case I could use a basic-af terminal-ish font which would have more distinction between lower/upper case letters (I can only speak for Latin/English mind you) that would be worthwhile at time.

In my use-case its describing CLI commands I'm documenting, so details like that are very important. And one of the reasons a code block doesn't _necessarily_ work for me is that in this case I am creating a numbered list showing the commands. So if that is in a single code block instead, the copy function copies _all_ lines, instead of each line one at a time. So I am motivated to instead not use a code block.

At the end of the day this isn't a deal-breaker for me to not have this function. But it would be nice to have instead of having to crack the hood and do some CSS changes. I'm not scared of CSS changes, but a short list of some common fonts to select could fill the functional void here.

If in the end you still feel this is not sufficiently warranted, no worries. I just wanted to share the functional difference when issuing a CLI command and using the correct parameter vs the incorrect parameter, all because capital i looks like lowercase l (and the command being described uses uppercase i).

As always, thanks for hearing me out, keep on being awesome!
