### ISSUE TITLE
Adding Grammarly or something similar

### ISSUE THREAD

**Issue by AuthorShin** [BookStackApp/BookStack#3336]
### Describe the feature you'd like

Hello
I really like to see Grammarly or something similar (better to be local and self hosted) checking my writing when I'm editing and writing a page inside the BookStack (E.g. at the top or right toolbar) for grammatical mistakes and misspellings.

### Describe the benefits this would bring to existing BookStack users

It will decrease the time and effort one have to spend for proof reading a page after writing it.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

0 to 6 months

**Comment by ssddanbrown** [comment]
Hi @AuthorShin,
As stated in other issues, I'm not really willing to provide official support for a third-party closed commercial service such as grammarly in any manner, unless there's an established open means for doing so. I'd consider our own development of any such grammar checking functionality out of scope due to the vast complexities involved.

The WYSIWYG editor will already handle some level of spelling and grammar via the browser's own functionality. This generally works well for us to keep the responsibility and complexity out of project, while remaining flexible to user's preferences and language.

If you needed something a bit more powerful, then I just tested the [languagetool](https://languagetool.org/) extension with the BookStack demo. Seems to work as expected in the WYSIWYG editor.

**Comment by AuthorShin** [comment]
@ssddanbrown 
Thanks for your clarification and suggestion, I gave [languagetool](https://languagetool.org/) extension a try but it had too many false positive signals and since in order to work it need to send all of the texts and data to their servers I just remove it.
I wonder if there is any self hosted solution out there that can be add to BookStack.

**Comment by ssddanbrown** [comment]
@AuthorShin Languagetool can be selfhosted: https://github.com/languagetool-org/languagetool
Their extension has options to point it at your own server instance.

---

I'm going to close this off as the build of such as tool, or implementation of a specific service, is not something I'd consider in scope. As said above though, if there are ways we can look to adhere to certain open standards I'd be happy to see what's possible there. Based upon languagetool's functionality, it seems that this kind of thing is possible via browser extension without us making changes, at least for the WYSWIYG editor.
