### ISSUE TITLE
Ctrl+F to focus search-bar

### ISSUE THREAD

**Issue by xam-ps** [BookStackApp/BookStack#3348]
### Describe the feature you'd like

It would be great to have a shortcut (Ctrl+F) that focuses the search bar (in non edit mode). That would make it easier to keep the hands on the keyboard. 

E. g. open new tab -> go to bookstack -> search for what I need
That all could be done without touching the mouse.

### Describe the benefits this would bring to existing BookStack users

Speed!

### Can the goal of this request already be achieved via other means?

Tampermonkey etc. but it's not built in (as far as I know).

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

1 to 5 years

**Comment by ssddanbrown** [comment]
Thanks for the request @xam-ps, but I'm going to close this off in favour of the more general existing issue #1216 to reduce on duplicates. 

I probably wouldn't look to bind `Ctrl+F` due to its existing popular usage; I think interfering with a popular browser shortcut may just lead to frustration. I do agree that a search shortcut would be useful though. Many modern sites, including GitHub, seem to use `/` as the search shortcut.

> Can the goal of this request already be achieved via other means?
> Tampermonkey etc. but it's not built in (as far as I know).

Just a note on this in case it helps, the search bar is quite early in the focus order of a bookstack page, meaning that most of the time, before any other interaction, it's possible to get to the search bar by pressing tab four times.
Additionally, if really desperate right now, a script could be added to achieve this on your instance in the "Custom HTML Head Content" setting. Let me know if you'd want guidance for adding that.

**Comment by xam-ps** [comment]
Makes sense, thank you. But please be careful with `/`. This only works on the english keyboard layout. On my german layout I can't use this shortcut (on github) as `/` = `Shift+7` which is not working.

In the OS I have both layouts activated, so I can switch quite fast with `Win+space`. It's annoying anyway.
