### ISSUE TITLE
Hosted version?

### ISSUE THREAD

**Issue by drreen** [BookStackApp/BookStack#336]
Hey guys

do you plan to offer a paid hosted version like Gitbook?

Kind regards

**Comment by ssddanbrown** [comment]
Hi @drreen, There are currently no plans (At least that I'm aware of) to offer a hosted version of BookStack. Personally I don't have the free time nor the experience as a SaaS provider to be able to provide any level of guaranteed support that I'd with. 

Since BookStack is open source someone else could offer such a service but I don't know of such an offering at this time.
