### ISSUE TITLE
Feature Request: Add Categories for Books.

### ISSUE THREAD

**Issue by muramasatheninja** [BookStackApp/BookStack#337]
### For Feature Requests

Desired Feature: Categorize Books.

It would be nice to have a way to divide books into different cateories. For example I would like to have a Personal Category as well as a computer category to view them all seperately. Also i would suggest a name 'Book Shelf'.

Thanks for the great work on this app. I'm looking forward to digging into it more.

**Comment by ssddanbrown** [comment]
Ooh, I like the use of the name 'Book Shelf'. I think this ties closely into #95.

**Comment by nvnvnvnvn** [comment]
I think the application is great. One more level would be nice (though I'm sure after that many will say one more level sure would be nice).  But it would seem to me you would have a "volume" first above book. Then a bookshelf would be above that.  If you just do one level and you call it bookshelf instead of volume, it is the same difference (doesn't really matter).  But volume seems more fitting and would then allow even another level for the bookshelf.  
Thanks so much for all you put into this. I'm so amazed! It is working great for us.

**Comment by darkmoon2** [comment]
I second having Volume
