### ISSUE TITLE
Setting Page Orientation, Landscape or Portrait 

### ISSUE THREAD

**Issue by HalfAssProgammer** [BookStackApp/BookStack#3371]
### Describe the feature you'd like

I would like the ability to change the layout to either landscape or portrait while editing a page.

### Describe the benefits this would bring to existing BookStack users

This would provide the ability to use larger tables with more columns while still staying between the page margins.

### Can the goal of this request already be achieved via other means?

Not to my knowledge, while you can change the page orientation while printing, this does not expand the table. 

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

6 months to 1 year

**Comment by ssddanbrown** [comment]
Thanks for the request @TT0ps,

I'm not fully sure what "Lanscape" would look like in the context of BookStack. Right now, a page is infinitely long which doesn't really work on a horizontal basis for writing content. The fixed-maxed-width "Portrait" view is nice since it somewhat aligns with common print widths and has a read length that most find comfortable, while working to the "Page" paradigm and giving us a fixed with to work to in other aspects (Such as generating full-width image sizes).

In regards to the given benefit:

> This would provide the ability to use larger tables with more columns while still staying between the page margins.

I feel this only applies until we're limited by something else, such as window size, then we're at the same scenario but now more variable. It would not solve anything, just provide a different potential upper bound.

If the intent is just wider pages, a previous discussion with potential non-official workarounds can be found in #1757.
If the intent is primarily for supporting wider tables, I'm aware these could do with support and we have a range of existing issues to cover these: #2126, #2381, #1387

**Comment by ssddanbrown** [comment]
Since there's been no follow-up or further discussion I'm going to close this.
