### ISSUE TITLE
IP Address based guest user auth

### ISSUE THREAD

**Issue by kaylahynes** [BookStackApp/BookStack#3374]
### Describe the feature you'd like

Hello! I was curious if it would be possible to add an independent guest user role with additional permissions based on which IP address the guest is accessing the wiki database from. We were hoping to allow users on our local network to access the application's content without authentication, while still having a login barrier in place for public non-local requests.

### Describe the benefits this would bring to existing BookStack users

A more comprehensive feature set.

### Can the goal of this request already be achieved via other means?

Not that I know of.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

1 to 5 years

**Comment by ssddanbrown** [comment]
Hi @meepmeep22, Thanks for the request.

This would not be something I'd look to add to the core project, due to the specific nature of the request, lack of demand and the cost of maintaining authentication options.

We do however provide extension options, which may help here, via the [logical theme system](https://github.com/BookStackApp/BookStack/blob/development/dev/docs/logical-theme-system.md) - [Video Guide](https://www.youtube.com/watch?v=YVbpm_35crQ).

Using this you could hook into the `WEB_MIDDLEWARE_BEFORE` event then, if the user is not authenticated but coming from a specific IP address, authenticate them as a chosen existing user account.

Let me know if you'd need additional guidance in setting this up if desired.

**Comment by ssddanbrown** [comment]
Since there's been no follow-up I'm going to close this. If you need further assistance with the above feel free to still comment here.

**Comment by newmedicine** [comment]
This is absolutely something which we'd really like too. The usecase is hosting medical guidelines - would be great for intranet users to be able to access them without password, keeping things locked down for external users.

**Comment by AuthorShin** [comment]
@ssddanbrown Hello, Thanks for building BookStack.
Just open the same issue and them saw this.
It can be/is very critical option in my office. so, please tell me how to set it up or is there any chance it might find it's way into future builds?

**Comment by ssddanbrown** [comment]
> is there any chance it might find it's way into future builds?

Probably not, as per my reasoning above, especially so with the added granularity in your request.

I'll re-purpose your fresher issue to request an example, and I'll try to come back to it soon.

**Comment by kaylahynes** [comment]
Hey All,

I've been able to secure development approval from my company to create this feature, and have created a fork of the project in which I will be implementing the functionality myself for our own internal use.

**Comment by ssddanbrown** [comment]
An example of achieving the above, using the logical theme system as suggested above, can be seen here:
https://github.com/BookStackApp/BookStack/issues/3464#issuecomment-1149761763
