### ISSUE TITLE
Unable to Center Videos 

### ISSUE THREAD

**Issue by WavedirectTel** [BookStackApp/BookStack#3378]
### Describe the Bug

When you select an embedded video.  Using the left/right/center formatting buttons will not center the video. 

Wrapping it with html with <center></center> will center it and work.

### Steps to Reproduce

Embed the video using the media button. 
Highlight the video
Click on Center / Left / Right. 
Nothing happens.  

### Expected Behaviour

The video should shift left/right/center. 

### Screenshots or Additional Context

Disabled all browser extensions to be sure. 

### Browser Details

Brave, Firefox. 

### Exact BookStack Version

v22.0.3.1

### PHP Version

7.4.3

### Hosting Environment

Ubuntu 20.04

**Comment by ssddanbrown** [comment]
Thanks @WavedirectTel for raising.
I have now implemented better video alignment, copying that of images, via PR  #4727 although the implementation works around complications from the editor, so the fix was tricker than hoped and may be somewhat brittle, but it will be part of the next feature release so I'll therefore close this off.
