### ISSUE TITLE
Bookstack vs OneNote

### ISSUE THREAD

**Issue by hasankaracayir** [BookStackApp/BookStack#3379]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

Hi Bookstack,

I am an intern at a Dutch insurance company. My internship assignment is to centralize all information on 1 platform. Currently I am experimenting this by using OneNote, where all IT teams have their own OneNote for documentation. OneNote meets the needs of the employees by, for example, being able to search easily and very fast for documented information and simply being able to find back who has modified what in which place. However, all information is still not fully centralized when each team works within its own OneNote.  I wondered if Bookstack as an open source platform could offer a solution here. 

I myself don't know exactly what the differences are between OneNote and Bookstack. Are there certain functionalities what OneNote does not offer and Bookstack does and vice versa? The integrations of programming software is not accessible through OneNote for example.

I hope you can inform me with this! 

Yours sincerely,

Hasan Karacayir

### Exact BookStack Version

x

### Hosting Environment

x

**Comment by ssddanbrown** [comment]
Hi @hasankaracayir,
I'm not really able to provide a full breakdown, as I don't personally use OneNote.
Here are some large high level differences:

- OneNote has good pen support which many users enjoy (At least in certain versions); BookStack does not have any specific pen support.
- OneNote has much more flexible content and formatting options, BookStack is purposefully quite limited in this manner. Limitations can help with standardisation and portability but it can mean a higher chance of things not being possible.
- OneNote has good offline/desktop/app support, BookStack does not specifically/directly have any app or offline options, it's a centralised web application.
- BookStack is free and open-source, and keeps to simpler/more-common open standards where possible.

Your best bet would be to try them both out first-hand, to assess what works best for your needs. You can play in our demo instance, without any setup needed, here: https://demo.bookstackapp.com/
Otherwise, you could spin up your own test instance of BookStack to trial.
