### ISSUE TITLE
My first impressions

### ISSUE THREAD

**Issue by ChangePlaces** [BookStackApp/BookStack#339]
Just tried out the demo on the site and wanted to give a bit of feedback with maybe bugs / features included.

First like the idea - it's a novel way of collecting information. However, it's realistically unusable in it's present form:

- features: 
   - need to be able to drag page / chapter order around around, maybe the Chapter / Page could have a property int Order that's mutable. There are tons of jquery plugins that allow things to be sortable. on each "drop" you'd need to update the order of the chapter/page thta's been dragged.
   - having the order on the right in bright colours is distracting, please the right-side menu it foldable / minimisable at least when creating content
    - why such big lettering on book creation - it looks unprofessional. 
    - what about setting a cover image when declaring a book as well,
    - meta data like author/s, keywords/tags would be appreciated for better search and categorising, and an icon maybe for when listing the books, 
    - we need "subchapters" - online / pdf books are not real books, and it's possible for chapters to need grouping of sub-related data - this is urgent! - so Chapter can have a property SubChapters.
    - i see no theme in the settings, 
    - please don't choose those slidey checkboxes over a normal checkbox - it scares users. 
    - please present the chapters and pages in a smaller font, it can get unruly for big books beyond a few pages you make for testing, 
    - new pages / chapters are more common than export, so move the export link to the far right, not the far left as the hand has to travel further to click it. 
    - also when entering a book, <tab> should then move focus to the save button, not the cancel button (you can then 'press it' with the space bar so it allows you to create content without touching the mouse.) 
    - search by author / category would be nice once the metadata is implemented. all relatively simple features on top of what you have! opening attachments on page breaks the toolbox for wysiwyg

- bugs: 
    - clicking on cancel in the edit book redirectss to translation.js, 
    - exporting to pdf is nasty - code of long lines  aren't wrapped and vanish - i assume an issue of whatever pdf converter you're using.

looking forward to see what this grows into. I'm not too confident with laravel, but it'd make most of the above changes fairly simple from what I remember.

**Comment by domainzero** [comment]
Note: not affiliated with Bookstack development - just a user of Bookstack.

> need to be able to drag page / chapter order around around, maybe the Chapter / Page could have a property int Order that's mutable. There are tons of jquery plugins that allow things to be sortable. on each "drop" you'd need to update the order of the chapter/page thta's been dragged.

Page and chapter order can be reordered from the "Book" page. The sort option is hidden in the 3-dot menu on the right hand side.

> i see no theme in the settings,

Currently there are no additional themes. There is the option to implement your own style via authoring a custom stylesheet and injecting it into the head of the page via the "custom html head" section in the settings. This would also allow you to fix your text size complaints. If you wanted per-user themes or toggle-able themes this could be a valid feature request.

That being said, you should probably break out your feature requests into individual issues so they are manageable and trackable.

> clicking on cancel in the edit book redirectss to translation.js,

Clicking on cancel in the edit book section does not redirect me to translation.js using the hosted demo. What browser are you using and what version is it?

**Comment by ChangePlaces** [comment]
hi, thanks for the feedback. using firefox 52 windows.

**Comment by ssddanbrown** [comment]
Hi @ChangePlaces, Thanks for your feedback. Sorry to hear it's unusable for you at the moment.

In regards to the 'cancel' button, It was set up to direct you back to the last page you were on. I've updated this behaviour for the next release to go to the correct page.

Thanks @domainzero for your answers above, All the information there is good so I won't go over the same points.

---

> having the order on the right in bright colours is distracting, please the right-side menu it foldable / minimisable at least when creating content

I have some plans to renovate the sidebar a little as its feature set is growing and will grow in the future. I agree that making it collapsible would be nice for those who want a clean reading experience.

---

> why such big lettering on book creation - it looks unprofessional.

A matter of opinion but I understand what you mean. Really it was to best utilise the space and to emulate the importance of writing the title of a new book. I'll consider this when I come to the next design update.

---

> what about setting a cover image when declaring a book as well

This could lead to views becoming messy. The use of cover images is great in an ideal world where everyone would upload consistent and correct art but the world is not ideal. This can be discussed further under #181.

---

> meta data like author/s, keywords/tags would be appreciated for better search and categorising, and an icon maybe for when listing the books,

> search by author / category would be nice once the metadata is implemented. all relatively simple features on top of what you have! 

I agree. I plan to open up the ability to search on database columns as part of #64 and #271.

---

> we need "subchapters" - online / pdf books are not real books, and it's possible for chapters to need grouping of sub-related data - this is urgent! - so Chapter can have a property SubChapters.

I'm aware BookStack books are not real books. The system and analogy used is to make the structure easily and instantly relate-able to users. This can be discussed further in #95.

---

> please don't choose those slidey checkboxes over a normal checkbox - it scares users.

[citation needed]

To me they are good at representing binary options. When there's multiple related options I use check boxes instead.

---

> please present the chapters and pages in a smaller font, it can get unruly for big books beyond a few pages you make for testing,

I don't only use BookStack for testing. You can override font sizes via custom CSS as @domainzero has described.

---

> new pages / chapters are more common than export, so move the export link to the far right, not the far left as the hand has to travel further to click it.

That's going to depend on how people use BookStack but that area does need a little cleanup after the exports options were added recently so I'll have a look when I'm next editing around that area.

---

> also when entering a book, should then move focus to the save button, not the cancel button (you can then 'press it' with the space bar so it allows you to create content without touching the mouse.)

Yeah, That's a good idea. I think all the tab-focus paths need a check over and also the focus css states.

---
 
> opening attachments on page breaks the toolbox for wysiwyg.

Could you confirm the steps to replicate this? On Firefox/Ubuntu I could not get this to happen.

---

> exporting to pdf is nasty - code of long lines aren't wrapped and vanish - i assume an issue of whatever pdf converter you're using.

Yeah, clean PDF generation from HTML appears to be a difficult task. There are two different PDF rendering libraries supported by BookStack so switching to the WKHTML engine may prove better results:

https://www.bookstackapp.com/docs/admin/pdf-rendering/

---

Since this is a long list I'm going to close this issue for now since it's a bit unmanageable from a issue tracking point of view. Please refer to the linked issues for discussion on individual points.
