### ISSUE TITLE
Search API filters

### ISSUE THREAD

**Issue by danbuntu** [BookStackApp/BookStack#3399]
### API Endpoint or Feature

Hello

The search API returns all books, shelves and pages that are matched by the search. This can be a bit on an issue when integrating the results form the search with other products.

It would be extremely helpful to be able to only tell it to return pages.  

### Use-Case

We are looking at integrating bookstack results with an AI chatbot.
We want the bot to be able to search and display results from bookstack. 
Currently the API returns shelves and books in it's results and this it confusing for end users. We would like it just to return pages.

**Comment by ssddanbrown** [comment]
Hi @danbuntu,
As mentioned in the description of this endpoint, this search endpoint can use any of the search options described here:
https://www.bookstackapp.com/docs/user/searching/

Therefore, you could achieve what you need by passing `{type:page}` within the query.

**Comment by danbuntu** [comment]
Excellent thank you very much - I'd missed that bit

**Comment by adamreading** [comment]
I would be really interested to know if anyone has successfully integrated Bookstack with a search AI Chatbot - and if they managed to do it at a reasonable cost - what the steps look like? I don't write code - and ideally am looking for something that can be implemented in the Custom HTML Head Content as a script. I've investigated KorticalChat -- but because it needs to access bookstack behind a secure login - they would charge for customisation etc and takes it out of budget. Any advice appreciated.

**Comment by ssddanbrown** [comment]
Hi @adamreading, I'm not really sure what you mean by "integrated Bookstack with a search API". How do you see that working? Is there a particular API you have in mind?

**Comment by adamreading** [comment]
> Hi @adamreading, I'm not really sure what you mean by "integrated Bookstack with a search API". How do you see that working? Is there a particular API you have in mind?

Hi Dan - That's my bad for typing too quick and not noticing it had autocorrected. What I am trying to do is use Bookstack as a knowledgebase for our users to quickly find information they need whilst on the phone to customers and make sure they are following all sorts of financial rules and processes. So I want a more natural language based "AI/ ChatGPT" style search function where they can type a question explaining what they are trying to find out - and then it searches the Wiki and responds with either some links or an actual thought out answer. We have a lot of jargon in Car Leasing - and I'm monitoring the Google Analytics that's coming back and seeing a lot of failed searches because they don't know how to ask the questions in a way that exactly matches the written text. So I need the search to be more intelligent / elastic and the cleverer the better I guess.

Does that make more sense? @danbuntu above said he was implementing something like this - and I was hoping someone has done it and doesn't mind sharing what they did / what worked and what didn't etc.

**Comment by ssddanbrown** [comment]
@adamreading 

> So I want a more natural language based "AI/ ChatGPT" style search function where they can type a question explaining what they are trying to find out - and then it searches the Wiki and responds with either some links or an actual thought out answer.

I played around with this a few months back. You can see my video here from about 4:28:
https://foss.video/w/mB67n8JBBHb9mSMYUM5DED?start=4m28s
In that I share my thoughts about AI usage, and show an example integration.
In the video I use [danswer](https://github.com/danswer-ai/danswer), which uses ChatGPT (and other models I think now).
I [created the connector](https://github.com/danswer-ai/danswer/pull/139) between BookStack and danswer for this. The integration just uses the normal BookStack REST API though. All existing content from BookStack gets read in, then refreshed every so often.

If needed, you could use the integration code I wrote for other similar platforms. 
Keep in mind the integration is quite simplistic, It just scrapes all from the core content as plain text and feeds it in. Trying to take things like permissions, or format types, can make things much more complex quite quickly.

**Comment by adamreading** [comment]
Thanks for that Dan, it was a great watch! - I would have to get our IT department involved as Danswer needs to be installed on a server etc - which reduces the likelihood of me being able to get it over the line. Ideally I need something which runs in the cloud and only needs me to add some script to the custom header, but I'll raise this option with my manager and it may fly.

I really appreciate your assistance - and massively impressed with Bookstack itself - it's a real Gem!
