### ISSUE TITLE
Thread-like comment

### ISSUE THREAD

**Issue by EnvironmentalBit3940** [BookStackApp/BookStack#3400]
### Describe the feature you'd like

Thread-like comment, like in Confluence

### Describe the benefits this would bring to existing BookStack users

More convenient presentation of the discussion

### Can the goal of this request already be achieved via other means?

No

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

0 to 6 months

**Comment by ssddanbrown** [comment]
Hi @sergey27564,

> Thread-like comment, like in Confluence
> More convenient presentation of the discussion

It would be useful to provide more detail in regards to what would need to change upon the current comment system, and why/how this would offer a "more convenient presentation of the discussion".

I'm not familiar with Confluence's formatting of comments, nor is it our goal to fully replicate the functionality of Confluence.

**Comment by EnvironmentalBit3940** [comment]
Okey, it's hard for me to describe in text, so i'll do it in presentation in few days

**Comment by EnvironmentalBit3940** [comment]
Okay, sorry for long time, but that's what i'm talking about:
![изображение](https://user-images.githubusercontent.com/16984827/170246788-9acaa2dd-3f00-4bae-85cc-f8ee821f08f2.png)

Answer to comment would locate like tree under the master-comment, so it will be easier to read discussion about one problem

**Comment by bendem** [comment]
Agreed, I just tried the comment system today (always had it disabled), and it's absolutely impossible to follow a large conversation with multiple people answering different comments.

One thing I did, which allows going back up (not down sadly) and seeing more easily what someone responds to is this tiny css (obviously has to be adapted to theming and such) which allows seeing clearly which comment someone is referring to when clicking on "in reply to" link:

```css
<style>
  .comment-box:target {
    background-color: lightblue !important;
    transition: background-color 0.3s linear 0.1s;
  }
</style>
```

![image](https://user-images.githubusercontent.com/2681677/218050234-ab68b647-1420-42d5-85a8-2b7093dd23f9.png)

The feature seem to be implemented already, but it just flashes the comment for a split second, which makes it very hard to identify the comment since the page jumps at the same time.

**Comment by ssddanbrown** [comment]
I've been working on improving the comments display within  #4286.
That work has been merged, to be in the next feature release, so I will therefore close this off.

Here's a preview:

![image](https://github.com/BookStackApp/BookStack/assets/8343178/c121a9f1-ab73-4aac-aa85-b3318529426d)

**Comment by bendem** [comment]
You are absolutely awesome! This is great! ❤️
