### ISSUE TITLE
I hope to add a more friendly editor for Chinese, such as angEditor 

### ISSUE THREAD

**Issue by zhenjieyun** [BookStackApp/BookStack#3420]
### Describe the feature you'd like

我希望增加一个对中文等更友好的编辑器，比如开源的[wangEditor](https://www.wangeditor.com)
I hope to add a more friendly editor for Chinese, such as open source [wangEditor](https://www.wangeditor.com)

### Describe the benefits this would bring to existing BookStack users

Wechat is popular in China and many people will write articles on it, similar to a blog, but its editor requires special support to work, if I create a page on BookStack, when I want to copy it to WeChat, I get an error that causes me to need to schedule it all over again, which is very annoying

### Can the goal of this request already be achieved via other means?

NO

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

6 months to 1 year

**Comment by ssddanbrown** [comment]
Thanks for the request @zhenjieyun but I would not look to implement such an editor for the reasoning of avoiding an error on a specific external application. The effort would be be far to great on us for limited benefit.
If there's something specific in our handling, that does not meet an open standard that would help make things compatible, I'd be happy to consider an improvement, but I will otherwise close this off as out of scope.
