### ISSUE TITLE
API Error: Too Many Attempts

### ISSUE THREAD

**Issue by IceWreck** [BookStackApp/BookStack#3423]
### Describe the Bug

So I made a program which uses the API to periodically download my entire wiki as markdown, change URLs in pages to preserve interlinking, save it with git and generate a static site of the wiki with Hugo.

It downloads less than half the wiki and then all page downloads start erroring out with:

```json
{"error":{"message":"Too Many Attempts.","code":429}}
```
I limited my concurrency to 10 page downloads at a time but its still happening. Any slower than that and it'll take hours to download my wiki. 

Can I tweak the rate limiter ?

### Steps to Reproduce

I'll put the entire code on github after cleaning it up but basically its downloading pages using `/api/pages/<pageid>/export/markdown` 10 at a time

### Expected Behaviour

No rate limits when using the API, especially for admin users.

### Exact BookStack Version

 BookStack v22.04.1 

### Hosting Environment

Linuxserver container image running on rootless Podman + mariadb from Rocky Linux repos

**Comment by ssddanbrown** [comment]
Hi @IceWreck,
You should be able to configure this rate limit by using adding the following options to your `.env` file then tweaking:

https://github.com/BookStackApp/BookStack/blob/ca09ed916f73ae53998703bfe0e3489798485971/.env.example.complete#L346-L347

It does look like we need to add this option to our documentation though since it's quite hidden right now.

**Comment by IceWreck** [comment]
Thanks. Its working now.

**Comment by ssddanbrown** [comment]
The in-built API docs have now been updated with a new "Rate Limits" section. This will be part of the next release.
