### ISSUE TITLE
Insecure password in POST request

### ISSUE THREAD

**Issue by KarelWintersky** [BookStackApp/BookStack#3432]
### Describe the Bug

![изображение](https://user-images.githubusercontent.com/2164874/168266647-7ef9f197-66e9-437e-a571-ba409fdcad90.png)

### Steps to Reproduce

Goto: https://demo.bookstackapp.com/login
Enter login & password
Click "Вход"

### Expected Behaviour

Hashed or crypted password

### Browser Details

Any

### Exact BookStack Version

22.04.2 (may be)

### Hosting Environment

Demo

**Comment by ssddanbrown** [comment]
@KarelWintersky You may also need to report this one to google, since their login does the same.

Passwords are hashed in storage in BookStack. Hashing/encrypting client side doesn't really add much security, just adds complexity. Sure, it may slightly help in non-HTTPS cases, but it still won't protect access to the BookStack account and those cases are already open to a wider array of security concerns.

**Comment by KarelWintersky** [comment]
> You may also need to report this one to google,  

appealing to the errors of a third-party resource cannot be an excuse

**Comment by ssddanbrown** [comment]
@KarelWintersky Sure, It was a joke though,  hence why I justified our existing methods in my comment above.
Happy to hear why we're insecure though if you believe this to be a legitimate vulnerability.
