### ISSUE TITLE
The head of table sticks to top when scroll down

### ISSUE THREAD

**Issue by starsang1995** [BookStackApp/BookStack#3448]
### Describe the feature you'd like

Sometimes we have long forms, and when scrolling down the head of the table is long disappeared and people may not understand the nature of a particular cell. Maybe it is possible to have the head of the table stick to top of the page when scrolling down until the table itself is not visible anymore?

### Describe the benefits this would bring to existing BookStack users

It would benefit to UX for pages have long tables, especially when cells containing only "yes" and "no" values or something like that.

### Can the goal of this request already be achieved via other means?

Not sure.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

0 to 6 months

**Comment by ssddanbrown** [comment]
Thanks for the suggestion @apsonandtesla.

This is probably not something I'd look to include by default, due to varied use of tables and opinion of sticky headers, but this can easily be added via some custom CSS styles in the "Custom HTML Head" content setting. Here are a couple of different examples, depending on desired usage:

```html
<style>
    /* Specifically makes table headers sticky
       You can make a table row into a header via the table
       editor button > "Row" > "Row Properties"  > "Row Type" dropdown
       > Select "Header" option.  
    */
    .page-content table thead {
        position: sticky;
        top: 0;
    }
</style>

<style>
    /* Makes the first row of any table sticky.
       More general than the above and will always apply, without marking
       a header row.
    */
    .page-content table tbody tr:first-child {
        position: sticky;
        top: 0;
    }
</style>
```

I'll therefore close this off but feel free to still comment if you need help with the above.
