### ISSUE TITLE
Point Home page to Books index instead of Recently Viewed?

### ISSUE THREAD

**Issue by lxtv** [BookStackApp/BookStack#345]
Hi; about to unleash Bookstack on my users as a Knowledge Base. I think they will find it more useful if they are presented with the list of available Books when visiting the home page, as opposed to Recently Viewed/Updated/Created etc. What's my best bet for making that happen? I tried swapping code from the books index blade to the home blade, but that broke the home page, so I know it's more complicated than that! Thanks for your assistance.

**Comment by nh-mike** [comment]
+1, I would like to see this too even if it is something that needs to be configured manually.

I too am using Bookstack as a Knowledge Base.

**Comment by lxtv** [comment]
I don't even want to admit how much trial and error it took me to figure this out, but it's actually pretty simple:

In /var/www/bookstack/routes/web.php, change:

```    // Other Pages
    Route::get('/', 'HomeController@index');
```
to

```    // Other Pages
    Route::get('/', 'BookController@index');
```

So far it doesn't seem to have broken anything, but I'll chime in again if I find any gotchas.

**Comment by ssddanbrown** [comment]
Hi @lxtv, I like the solution you have found, Simple and clean. Just be wary when it comes to updating as it may either cause issues or be wiped. 

I'm aware the home page could do with some improvement. There is already an [issue open about impoving the homepage which can be found here](https://github.com/BookStackApp/BookStack/issues/126). Since this issues overlaps that one I will close this issue but feel free to continue the discussion on #126.
