### ISSUE TITLE
Overriding styles using the Visual Theme System

### ISSUE THREAD

**Issue by stevenmasci** [BookStackApp/BookStack#3486]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

Hi, is it possible to override styles using the Visual Theme System? I have attempted to place scss files are various folders under my custom theme folder but it has no effect.

Or do I have to override individual blade.php files and use inline styles?

Thanks for your help!

### Exact BookStack Version

v22.06-dev

### PHP Version

8.1.6

### Hosting Environment

Docker

**Comment by ssddanbrown** [comment]
Hi @stevenmasci,
It's not possible to override SCSS (Or JavaScript) files using the visual theme system since these require a build/transpile step for their final formats and I don't really want to complicate the theme system with such additional requirements.

You can however just add custom inline styles via template overrides or use the "Custom HTML Head Content" setting in the settings of BookStack to directly add some inline style HTML.
If you did go the template override route via the visual theme system, [then this template](https://github.com/BookStackApp/BookStack/blob/a61c9c5e98b0a411b081543e3eaf1994d12919b3/resources/views/common/custom-styles.blade.php#L1-L11) is probably a good candidate for override since it's used in most non-export views.

**Comment by stevenmasci** [comment]
Hi @ssddanbrown, overriding the `custom-styles.blade.php` file works great!

Thanks for the prompt response and pointing me in the right direction.
