### ISSUE TITLE
Make a linked file for windows explorer 

### ISSUE THREAD

**Issue by michaelortnersanube** [BookStackApp/BookStack#3488]
### Describe the feature you'd like

Hello,

We have some colleagues who work in a network drive (Windows) and would like to have a direct link to their files in the wiki. This means you want to click on it like on a link and then the file, folder etc. should open. 

### Describe the benefits this would bring to existing BookStack users

Many companies need such possibilities to work faster and more efficiently. This way, you don't have to spend a lot of time looking for the file, but go directly to the link, press it and the corresponding file opens in Windows Explorer etc.

### Can the goal of this request already be achieved via other means?

I don't know.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

0 to 6 months

### Additional context

![image](https://user-images.githubusercontent.com/96595501/172847393-de258c29-6946-402f-9451-4ca2476a2846.png)

**Comment by ssddanbrown** [comment]
Thanks for the request @michaelortnersanube, although this has been previously discussed. Please see #1669.
Nothing should stop you from using `file://` links within BookStack, but you'll find they're blocked in most cases due to security concerns. 

I'll therefore close this off but feel free to still comment if there is a feasible solution we could offer for this. As far as I'm aware, achieving this would require external out-of-browser components which I would consider out of scope for the core project.
