### ISSUE TITLE
Auto Scale/Resize Cover art

### ISSUE THREAD

**Issue by uprightcarrion** [BookStackApp/BookStack#3524]
### Describe the feature you'd like

When uploading an image it would be nice if it was automatically scaled appropriately for the display.   You can see below this is a 48x48 image, this could be scaled down so the entire image is visible.
![image](https://user-images.githubusercontent.com/7152455/175554836-9af1b159-f157-4f93-b7b4-9dd1bf02d608.png)

### Describe the benefits this would bring to existing BookStack users

This feature will help with visual aesthetics.  Editors of the site may not always use appropriately sized images, which then don't render nicely.

### Can the goal of this request already be achieved via other means?

There may be solutions through CSS, I'm not sure.  The current solution is to use an appropriate image, 24x24 I think?

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

0 to 6 months

**Comment by ssddanbrown** [comment]
Hi @uprightcarrion,

Images by default are set to cover the area of the image display area, while maintaining aspect ratio.
There's no set image size for these areas since the display size may change depending on display screen size.
If you instead wanted images to be scaled to fit within the box, you could use the following CSS:

```html
<style>
.entity-list-item-image {
    background-size: cover;
    background-repeat: no-repeat;
}
</style>
```

Though, with this approach, you may get horizontal or vertical bars from the background area.
Alternatively you could use the following to stretch the image:

```html
<style>
.entity-list-item-image {
    background-size: 100% 100%;
    background-repeat: no-repeat;
}
</style>
```

**Comment by uprightcarrion** [comment]
@ssddanbrown Thanks, I understand.  I'll look at implementing your suggestions.  Great project!

**Comment by ssddanbrown** [comment]
Since a workaround was provided I'll close this off.
