### ISSUE TITLE
Add spellchecker

### ISSUE THREAD

**Issue by mayrmartin** [BookStackApp/BookStack#354]
It would be great if you could add a spellchecker to avoid spelling errors in documents.
[https://www.tinymce.com/docs/plugins/spellchecker/](
https://www.tinymce.com/docs/plugins/spellchecker/)

**Comment by AbijeetP** [comment]
Although I'd like to see this too, this will have to be a configurable option, since we don't want people with other languages having a red underline under every word they type.

**Comment by AbijeetP** [comment]
In addition, certain languages seem to be supported here - https://www.tinymce.com/docs/plugins/spellchecker/#spellchecker_languages

**Comment by ssddanbrown** [comment]
Totally agree with this, Spellchecking is kind of crucial to a documentation platform like this and I've been annoyed with some of my simple spelling mistakes while using BookStack.

I think the best, and also easiest, option here is to use the browser's spellchecking abilities. That way we don't have to worry about languages or saved words as it's all handled by the browser. Luckily, This looks like it's really easy to add to TinyMCE, Just one line to add:
https://www.tinymce.com/docs/configure/spelling/ 

I've marked this in for the next release. I'll add this in after the search system updates otherwise, until then, if anyone wants an easy pull request go right ahead.

**Comment by AbijeetP** [comment]
@ssddanbrown  - I agree, going with the browser's spellchecker is likely to have the lowest complaints.

**Comment by Abijeet** [comment]
Added a fix for this. 

![bookstack-354](https://cloud.githubusercontent.com/assets/1685517/25018816/06f58056-20a6-11e7-9cf2-0cfabd03a371.png)

**Comment by ssddanbrown** [comment]
Thank @Abijeet for this addition. Will be in the next release.
