### ISSUE TITLE
Code Editor: Language Select Usability

### ISSUE THREAD

**Issue by gitget0** [BookStackApp/BookStack#3542]
### Describe the feature you'd like

The new code selection interface seems less intuitive and forces the user to have to scroll through a list, which provides no UX benefit over the previous layout.

_**Feature:**_ An option to be able to display the various languages at the top of the dialog, listed horizontally (as they were previously).

### Describe the benefits this would bring to existing BookStack users

It was beautifully easy prior to 22.06 to document masses of code. Cmd+ E and one simple click to select the language - all the languages were listed at the top and visible without scrolling, especially 'shell/bash'.

Since 22.06 we have to scroll to the bottom of the list in order to select Shell/Bash for a code block. This is an additional step which complicates a previously excellent, and straight-forward process (which I felt made Bookstack superior to all other alternatives I tried).

### Can the goal of this request already be achieved via other means?

Yes, but with an added layer of complexity.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

6 months to 1 year

### Additional context

I am aware that the scroll position is saved, however it is only saved per 'page'. If you create/edit a different page, then you have to scroll and select the language again.

New layout:
![image](https://user-images.githubusercontent.com/92808564/176255331-59cd6f65-fe5f-4378-b0f4-feb143215777.png)

Previous layout:
![image](https://user-images.githubusercontent.com/92808564/176326657-a7705442-16e0-46d9-98b0-10df388d5027.png)

**Comment by ssddanbrown** [comment]
Hi @gitget0, Thanks for your input.

My goals with the new design were generally as follows:

- Improve on the design so it's much less dis-jointed. The old language list, input and code editor didn't really fit together and there's a lot of odd space within the popup window. The new design intended to better maximise the code editor working space and fit the language list into the design.
- Organise the language list to be more readable and continue to feel organised as we add more options. In this updated the list was added with quite a few additions. While the horizontal list worked okay to start with, I feel it gets more awkward as we expand the language list since now the user has to scan across multiple lines to find the language they want.

I do understand though your issue in that it's now less efficient to use when your desired language is not near the top of the list. I don't want to add an option for horizontal display though. That level of option is something I try to avoid in the system.

Instead, How about the ability to favourite languages (User-level preferences), to bring them to the top of the list?
That would potentially make things more efficient than before, since you could prioritize your common set of 5 or so languages then you would hardly ever need to scan the list far at all, they'd always be to hand.

As an added note, if easier you can directly enter `shell` or `bash` into the input at the top of the language list instead of scrolling and clicking.

**Comment by gitget0** [comment]
Hi @ssddanbrown and thanks so much for getting back to me. You are awesome, and Bookstack is incredible.

I totally understand your point about maximising the code editor working space, and I seek exactly the sort of functionality you describe in an interface _where I am programming first-hand_ (i.e. vscode, jetbrains, eclipse, visual studio, etc).

However, I happen to use Bookstack as a documentation tool - I usually come to Bookstack after I have significant amounts of code (9/10 times written somewhere else) and I paste it over to Bookstack in chunks so that I can begin documenting it.

It is indeed possible to enter `shell` or `bash` directly in the inputbox, and had I only had a couple of code blocks it wouldn't be a problem, but an average page contains 30-50 code blocks.
At this point, even something as simple as scrolling through the same list 50 times becomes a bit tedious (which is a big part of why I loved Bookstack over any other wiki, because the entire interface is clearly designed to be a pleasure to use and not tedious and repetitive).

- When documenting a more complex process, I sometimes need to switch between about 5 languages (and they're not always the same 5 across all pages). So having a top 5 list would help, but still slightly inferior compared to the ease of use of the previous layout.
- How about mitigating the downside of the horizontal list by having a setting to 'show/hide (each) language' checkbox per user? That way the width and the height of the languages list is up to the user's discretion (and use case), without compromising on the previous rock-solid ease of use? The chances that any one person needs to use all 35 languages currently available are probably quite slim..

**Comment by ssddanbrown** [comment]
Thanks @gitget0 

Just to confirm, my mention of 5 languages was just an example. I'd probably implement this, for ease of implementation and maintenance, as favourite as many as needed, where favourites will float to the top of the list alphabetically sorted. Based upon your screenshot above this could be as many as 19 favourites within initial view.

With a show/hide options in a horizontal list would complicate implementation a tad more, since we'd still have to design around a list of both dynamic width and height as before, while also having a separate view for this control, with UX issues such as "The expectations of new languages added" while likely adding friction for scenarios where a lesser-used language is desired as a one-off.

**Comment by ssddanbrown** [comment]
Within #3593 I have implemented the favourites system as discussed above.
At the same time, I adjusted the code editor window styling to make it a little greedier with vertical space.  It's now quite possible that, depending on screen configuration, you may have all current languages in view. Preview of this functionality:

![Screenshot 2022-07-25 at 19-19-01 Editing Page Code Editor Favorites BookStack](https://user-images.githubusercontent.com/8343178/180847093-38e0d6b3-1ad2-43a7-b81e-3e02b2480ea5.png)

This will be part of the next feature release. I'm going to therefore close this off as I think the core usability issues have been addressed, even if not in the preferred configuration.
