### ISSUE TITLE
Integrate Google Docs

### ISSUE THREAD

**Issue by conserve-cgn** [BookStackApp/BookStack#3543]
### Describe the feature you'd like

Hello,

Can Google Docs be integrated into Book Stack? I would like to include a document from Google Docs (at least read-only / better optionally even read & write) in bookstack. 

### Describe the benefits this would bring to existing BookStack users

I would like to include a document from Google Docs (at least read-only / better optionally even read & write) in bookstack. 

### Can the goal of this request already be achieved via other means?

Yes, Is similar but not the same request.

https://github.com/BookStackApp/BookStack/issues/916

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

6 months to 1 year

**Comment by ssddanbrown** [comment]
Hi @conserve-cgn,
My response would remain as it was in  #916, so this is something I'd consider out of scope in respect to our responsibilities within the core project.

I believe google docs may provide some form of embed links, these could be used within BookStack although you may need to tweak [some settings](https://www.bookstackapp.com/docs/admin/security/#iframe-src-control) to allow embeds from google. Of course embedding would not allow many features of your google doc content in BookStack, for example the content won't be searchable.

Our [platform extension options](https://www.bookstackapp.com/docs/admin/hacking-bookstack/) have grown significantly since 2018 though, so if you have the skills to hack around then that may provide some other opportunities.

**Comment by conserve-cgn** [comment]
Many thanks, that's it, it works.

I have edited the .env file with:

ALLOWED_IFRAME_SOURCES="https://*.draw.io https://*.youtube.com https://*.youtube-nocookie.com https://*.vimeo.com https://*.google.com"

**Comment by conserve-cgn** [comment]
Many thanks, that's it, it works.

I have edited the .env file with:

ALLOWED_IFRAME_SOURCES="https://.draw.io https://.youtube.com https://.youtube-nocookie.com https://.vimeo.com https://*.google.com"

Kind regards

**Comment by Doctor-Macintosh** [comment]
I would love to see BookStack be able to export the integrated Google Docs (like Sheets) when exporting to PDF. The integration in the web-interface (HTML) works fine and one can browse the embedded Google Docs in the BookStack page, but when exporting the page to PDF the embedded (and fully visible) Google Doc gets converted to a link.

So, I think it's just the PDF rendering engine that should be updated to fetch the Google Doc and embed it properly, just like the BookStack page does with an iFrame I guess, isn't it?

**Comment by ssddanbrown** [comment]
@Doctor-Macintosh Thread #5618 is relevant for your desire.
