### ISSUE TITLE
Instructions import to Bookstack

### ISSUE THREAD

**Issue by kentavar** [BookStackApp/BookStack#3547]
### Describe the feature you'd like

Hello Dan,
I have just installed on VMware server Bookstack and I saw that there is an option to export page or Book to PDF file
but there is no import function there. When I create an article it is easy for me to copy and paste the text there but there are
also screenshots in my instructions which doesn't copy and I have to import them manually while creating the article instead of just importing the Word, Excel, PDF file and the file to be converted and uploaded as text including the photos in it (if there are any).
Where in the source code I can try to add import function which will do the same as the export function but reversed so I can upload documents. Because downloading the photos from the Word, PDF files and then uploading them and put them in the correct places is very time consuming and if that feature is able to be created it will be awesome :) 

### Describe the benefits this would bring to existing BookStack users

This will save them a lot of time

### Can the goal of this request already be achieved via other means?

As far as I know no.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

0 to 6 months

### Additional context

Yes but unfortunately I was not able to find the exact same feature request.

**Comment by ssddanbrown** [comment]
Hi @kentavar,
There are no such import options for those formats, nor will there likely be for all of those formats due to the variation and complexities involved.
The issue of copying images with text has been discussed before in #449.

> Where in the source code I can try to add import function

It would be a fairly intensive operation to add something in the same manner as our import options. Do you have experience of the technologies used? 

If it helps you achieve what you need, I have an example API script for converting docx pages to BookStack pages here: https://github.com/BookStackApp/api-scripts/tree/main/node-docx-to-page

**Comment by kentavar** [comment]
Hi Dan,
I don't have any programing experience and I don't know if my request is simple or hard to achieve.
I looked at other articles and found that one: https://github.com/BookStackApp/BookStack/issues/449
It seems the same request as mine. Will this feature be added in the new version?

**Comment by ssddanbrown** [comment]
Hi @kentavar,

> Will this feature be added in the new version?

It is not currently planned. Maybe I will re-visit that issue soon but I cannot make any assurances.

> It seems the same request as mine. 

Thanks for confirming, I will therefore close this off as a duplicate.
