### ISSUE TITLE
Import Pages from another wiki software

### ISSUE THREAD

**Issue by SwiftRedline** [BookStackApp/BookStack#3567]
### Describe the feature you'd like

Hello! 

I would like to have an import function from other wiki tools. Like HTML Import or something like that. 

### Describe the benefits this would bring to existing BookStack users

So u need less time to implement this software fully

### Can the goal of this request already be achieved via other means?

I think not

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

0 to 6 months

**Comment by ssddanbrown** [comment]
Thanks for the request @SwiftRedline, but I'm not looking to support the handling and import of other application formats into BookStack since such functionality would require a fair amount of effort that would need active maintenance.

The REST API would probably be best for these kind of import tasks. If support is needed I can provide pointers via our discord chat upon request.
