### ISSUE TITLE
Mediwiki XML Import

### ISSUE THREAD

**Issue by gabviv73** [BookStackApp/BookStack#3585]
### Describe the feature you'd like

Hello,
started using BookStack, and I think it's a very good piece of code.
I have a big mediawiki instance that contains my notes: it would be nice to be able to import it's XML dump, as explained here: 
[https://www.mediawiki.org/wiki/Help:Export](https://www.mediawiki.org/wiki/Help:Export)

### Describe the benefits this would bring to existing BookStack users

Tools for migrating from other platforms will encourage adoption of BookStack

### Can the goal of this request already be achieved via other means?

Database import

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

0 to 6 months

**Comment by ssddanbrown** [comment]
Thanks for the request @GabrieleV, but I'm not looking to support the handling and import of other application formats into BookStack since such functionality would require a fair amount of effort that would need active maintenance.

You have listed database import as an alternative, but this can be dangerous. The REST API would probably be best for these kind of import tasks. If support is needed I can provide pointers via our discord chat upon request.
