### ISSUE TITLE
Changing Bookstack URL with php artisan

### ISSUE THREAD

**Issue by EctoBoggan** [BookStackApp/BookStack#3603]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

Hey,

I've installed Composer and I'm able to do things such as : 
```
$ composer --version
Composer version 2.3.10 2022-07-13 15:48:23
```
But I really don't understand how to use the 'artisan' php command.
When i do : 
```
$ php artisan bookstack:update-url https://old.com https://new.com
Could not open input file: artisan
```
There are no questions about that and it really makes me believe it's a basic thing.
After some researches I might need to install/create a laravel project, do I really need to do it ?
Sorry if it's consider as a non-related Bookstack Support Request and sorry for my poor english.

### Exact BookStack Version

BookStack v22.06.2

### PHP Version

PHP 7.3.3

### Hosting Environment

Docker for Synology NAS, using docker-compose and the LinuxServer.io's image.

**Comment by ssddanbrown** [comment]
Hi @EctoBoggan,
Since you're running via docker, everything you need is within the container, and that's where you need to run commands.
You don't need to install anything outside the container.

I've never used docker on Synology before, but from looking at some guides:

1. Go to the running bookstack container in the Synology docker app.
2. Open the "Terminal" tab of the container.
3. Create a new shell terminal, I think via the "Create" button, you should be provided a command-line window.
4. Within the command line, type `cd /var/www/html` and press enter. You could be taken to the BookStack install files within the container.
5. Here you should be able to run any required `php artisan` commands as required. To test this you could run `php artisan list bookstack`, which simply lists out the available artisan commands.

**Comment by EctoBoggan** [comment]
It works thanks a lot.
It makes me feel stupid because I'm doing exactly that to install bc-math inside the docker (in order to send mail with bookstack).

To go inside a container directly from shell (Synology docker app can be painfull) : 
`sudo docker exec -it CONTAINER_NAME bash`

Thank you very much and thank you for this amazing app

**Comment by whattheschnell** [comment]
Just stumbled across this.  Have the same issue, but still can't run php artisan from that folder with the Linuxserver IO docker image

**Comment by ssddanbrown** [comment]
@whattheschnell The linuxserver.io image has recently changed so directories may be different on a very recent image.
Based upon my reading of their changes, The old `/var/www/html` directory can now be found at `/app/www`

**Comment by EctoBoggan** [comment]
Here to confirm it is now located in `/app/www` for linuxserver.io's image, otherwise using `/var/www/html` gives :

`Could not open input file: artisan`

Thank you again for your help !
