### ISSUE TITLE
Change port 

### ISSUE THREAD

**Issue by catweis** [BookStackApp/BookStack#3620]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

Dear Sir or Madam,
how can I change the port during or after installation?
The issue is that on my machine, port 80 is not available.
Thank you in advance.
With kind regards.

### Exact BookStack Version

v21. 08.5

### Log Content

-

### Hosting Environment

Ubuntu 20.04

**Comment by ciphermenial** [comment]
Change the port your webserver is running on.

**Comment by ssddanbrown** [comment]
As @ciphermenial has said above, the port is managed by your web-server. 
For any further assistance we'd ideally need to know what web-server you are using, or the method used to install BookStack.

**Comment by ssddanbrown** [comment]
Since there's been no follow-up I'm going to close this. If the issue remains and is something you still require to be fixed respond to my previous comment and this can then be re-opened.

**Comment by albjeremias** [comment]
Hi! 🙂 
i've been getting crazy while setting up bookstack using docker-compose... right now my issue is that i can't start the frontend..
because i don't known which port is it using. where is the frontend port configured? which is the default port if u run it localhost for development? thank you

when i finish i will propose some PR to make the docker-compose more easy..
