### ISSUE TITLE
Deploy Bookstack without composer

### ISSUE THREAD

**Issue by bridgeyuwa** [BookStackApp/BookStack#3649]
### Describe the feature you'd like

Installation & Deployment Process Revamp
Creation of a streamlined & secure process for users to deploy & update BookStack with reduced development requirements (No git or composer requirement)

Please how soon will this be implemented.
Some of us are fed up with composer

### Describe the benefits this would bring to existing BookStack users

It would make it easier for the less tech knowledgeable.

### Can the goal of this request already be achieved via other means?

No

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

Over 5 years

**Comment by ssddanbrown** [comment]
> Please how soon will this be implemented.
> Some of us are fed up with composer

No sure to be honest. It is the next item on the roadmap after permissions, so I could roughly estimate first half of next year, but I'm not sure it'd be that worthwhile and I'd probably consider changing up the roadmap and removing that phase, or alter it to something different.

This is because I haven't seen much complaint about the current install and update processes, and the current process has worked well (In my opinion) for 7 years now, so I'm not sure on the value of removing composer. I can only envision it being a problem in environments with limited access/functionality, which I don't think we should be going out our way to accommodate anyway. 

Feel free to put forward reasons why composer is a problem.

The fundamental request here is already open in  #161, so this will be closed off as a duplicate, but I'll leave this open a small while for discussion.

**Comment by BloodyIron** [comment]
Perhaps use the docker images to streamline deployment and updates? That's the route I've gone down. Might work for you @bridgeyuwa

**Comment by ssddanbrown** [comment]
Since there's not been much further discussion I'll close this off.

**Comment by bridgeyuwa** [comment]
I discovered October CMS use Laravel and have a script they use for their install wizard

https://github.com/octobercms/install/tree/master/install_files

I dunno if it will benefit bookstack.
