### ISSUE TITLE
SSO/SAML Avatar Sync

### ISSUE THREAD

**Issue by BloodyIron** [BookStackApp/BookStack#3662]
### Describe the feature you'd like

LDAP has Avatar sync, and that's nice. But I'm not seeing that as a thing for SSO/SAML for Bookstack, but I believe it is technically possible. Can we please get Bookstack SSO/SAML to support Avatar sync from the IdP? I think it would be appreciated by users.

### Describe the benefits this would bring to existing BookStack users

A consistent experience for rapidly identifying authors based on the avatar they use. With the LDAP method this is possible (Bookstack) but the SSO/SAML documentation page doesn't mention Avatar sync. When many staff members switch between tools, they often notice the avatars people use, and can recognise that avatar more rapidly than the name, giving context to the author. It also adds a positive effect to pride in staff.

### Can the goal of this request already be achieved via other means?

Well right now I am aiming to use LDAP to achieve this, but SSO/SAML being able to do this would make authentication likely more convenient.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

0 to 6 months

**Comment by ssddanbrown** [comment]
Hi @BloodyIron, Thanks for the request.

When you mention `SSO/SAML`, Do you specifically mean something other that SAML when stating `SSO`? 

When it comes to SAML, do you know of a widely agreed upon standard for avatar images? I remember looking before but not finding anything, but I'm not much of a SAML pro.

**Comment by BloodyIron** [comment]
I'm really talking about the method on this page : https://www.bookstackapp.com/docs/admin/saml2-auth/

I am not familiar with the options from a technical perspective here, but in similar vein to how LDAP pulls the Avatar attribute from user-sync, I suspect that same property is reachable via SAML. In my particular case, pulling from Google Workspace.

Not sure how to answer your question better than that, hope it helps!

**Comment by ssddanbrown** [comment]
Thanks for confirming those points.

Just done another quick search, for avatar data in SAML responses for Google and came up empty. I don't think image data in SAML responses is a common thing.

It would be possible to import an avatar from Google, by querying a seperate Google API (With a different kind of auth), but I wouldn't want to add anything that vendor-specific or additional-in-scope to the existing SAML work.

This technically could be added using our [logical theme system](https://github.com/BookStackApp/BookStack/blob/development/dev/docs/logical-theme-system.md), with some hackery, since we do emit login/registration specific events that could be hooked into.

**Comment by BloodyIron** [comment]
Yeah I myself would rather use a platform-agnostic method instead of one specific to Google, so I hear your concern on that. I'm probably just going to use LDAP then since that seems to be "standard" or so.

Before opening this ticket I did some cursory searches on the topic of SAML + Avatar sync, and it _seemed_ to be "standard"-ish, so it's a bummer that you couldn't find any way to do it with Google Workspace SAML. I just now (as I'm typing this) did a cursory look-up on Google Workspace SAML avatar/image sync (or of similar nature) and could not find anything. Looks like maybe Google hasn't made this feature a "thing" in their SAML ecosystem.

Would this feature be possible for other SAML providers (authentik?) as some sort of "standard" feature thinggy? The current scope I'm working with is Google Workspace, but I'm likely to implement Bookstack in another scope that may be using authentik for SAML/SSO.

I think the PHP extension with logical theme might not be the direction we want to head at this time, but I appreciate you mentioning it as an option! :)

Thanks for looking into this! Yay! :D

**Comment by ssddanbrown** [comment]
I'm going to close this off since I don't see this moving forward without clear indication of a current user need that is possible for that environment and aligns with a standard or is common across SAML providers. I did search again but came up relatively empty. 

Happy for further input to be provided and this can be re-opened if needed, otherwise don't want an extra issue hanging around if there's not much we can do about it.

**Comment by BloodyIron** [comment]
@ssddanbrown I thought you might like to know that user Avatars seem to be passed through SAML from Google Workspace without any real effort! But... only some of the time (unsure why, probably Googly issues).

As you mentioned, you didn't really see Avatar data from Google Workspace SAML. So that's why I mention this. I haven't done anything special so far as I can tell!

My user doesn't get the Avatar, but I've seen 3x users get their avatars, so it's ^.WoRkInG.^ ish, yay!

Just thought you might benefit from knowing this hidden gem ;) Thanks again for your help!

**Comment by ssddanbrown** [comment]
@BloodyIron Unless disabled, or configured to use another service, BookStack will use [gravatar](https://en.gravatar.com/) by default to get user avatars based upon email address. I'd guess it's likely this at play, with those specific users having configured gravatar for their email.

**Comment by BloodyIron** [comment]
ohhhh you might be right, thanks! I'll have to check that aspect :)
