### ISSUE TITLE
could user login， when user‘s group is in the LDAP_BASE_DN，but user outside the LDAP_BASE_DN？

### ISSUE THREAD

**Issue by Zhengyueewee2e** [BookStackApp/BookStack#3675]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

BookStack Version: v22.07

my .env profille
![image](https://user-images.githubusercontent.com/40627010/186552545-60bc9a46-843a-4690-8950-4b2611f1f92a.png)

I have created role
![image](https://user-images.githubusercontent.com/40627010/186552674-22620749-8971-4fee-bdc5-78398878cf81.png)

my user：
CN=azheng，OU=test,DC=test,DC=com
CN=azheng3，OU=test2,DC=test,DC=com
my group
CN=test,OU=test,DC=test,DC=com
azheng and azheng3 are in the group
when LDAP_BASE_DN="ou=test,dc=test,dc=com"
azheng can login
azheng3 can't login error messages:user or password wrong

when LDAP_BASE_DN="dc=test,dc=com"
azheng and azheng3 can login both,and two user are in this test role
![image](https://user-images.githubusercontent.com/40627010/186552711-441c4d91-6075-44c9-aa43-16a1c097c807.png)

could user login， when user‘s group is in the LDAP_BASE_DN，but user outside the LDAP_BASE_DN？

### Exact BookStack Version

v22.07

### PHP Version

7.4.30

### Hosting Environment

centos 7.9

**Comment by ssddanbrown** [comment]
Copying my response from the same issue posted on [the website repo](https://github.com/BookStackApp/website/issues/126#issuecomment-1225500837):

> the ldap group sync can't let user log through users are not in the LDAP_BASE_DN?

The group sync does not control user access to login, it's somewhat unrelated although group discovery may be affected by `LDAP_BASE_DN`. 

`LDAP_BASE_DN` will affect the discovery of users and groups since searchers will be performed using this DN as the base.

Group sync is performed on returned `memberOf` style returned properties only. Groups within the `LDAP_BASE_DN` setting are not used directly as part of group sync.

**Comment by ssddanbrown** [comment]
Since there's been no follow-up I'm going to close this off.
