### ISSUE TITLE
Documentation Improvement : Link to LDAP for Avatar/image fetching as second method

### ISSUE THREAD

**Issue by BloodyIron** [BookStackApp/BookStack#3676]
### Describe the feature you'd like

On this page : https://www.bookstackapp.com/docs/admin/other-config/

I think it would be worthwhile to mention that an alternative method for Avatar/image fetching is the LDAP method (and link to it) that is already documented elsewhere for Bookstack. I think this would help inform those looking to use Bookstack that may not realise this is a feature of LDAP.

### Describe the benefits this would bring to existing BookStack users

Expose admins/users to features that already exist.

### Can the goal of this request already be achieved via other means?

Um... no?

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

Not using yet, just scoping

**Comment by ssddanbrown** [comment]
Thanks for the request, but I won't add this to the docs just yet. 
The usage of LDAP avatars would already likely be noted when reading through the LDAP docs, and auth method is usually driven be auth preferences rather than avatar existence. 

I'll therefore close this but keep it in mind, and we can always add the additional note/tanget to the docs if it becomes a common query.
