### ISSUE TITLE
Changing translation of a word in search section [Persian language]

### ISSUE THREAD

**Issue by sdhadi** [BookStackApp/BookStack#3689]
### Describe the Bug

I'm not sure where reporting of  an inaccurate translation should be reported, so I raised it as a bug report. 
Translation of the word "Shelf" in Persian language is "قفسه" which have been used in every section of the software but not in the search menu.
Below the search bar are four checkboxes that limit search phrase to shelf/book/chapter and page. In the Persian language, "shelf" translated to "تاقچه" which is not wrong but it's inaccurate and not consistent through out of the software as mentioned above and it's better changed to "قفسه".
thanks  

### Steps to Reproduce

This picture shows the location of target word in English language:
![22](https://user-images.githubusercontent.com/110716039/187367205-a97a97e6-b240-45d3-b2bf-276c097594d8.jpg)

### Expected Behaviour

This picture shows the same category (shelf) in Persian language:
![11](https://user-images.githubusercontent.com/110716039/187399152-78691f3e-09bd-4ca4-bcb6-4863bf22e4dc.jpg)
which would be better to be changed to "قفسه"

### Exact BookStack Version

v22.07.3

### Hosting Environment

Ubuntu Server 22.04
The software is currently deployed via Docker & Docker Compose.

**Comment by 10935336** [comment]
Translations are maintained by the community, you can participate in maintaining translations at https://crowdin.com/project/bookstack

**Comment by ssddanbrown** [comment]
Hi @sdhadi, Thanks for raising but as @10935336 has mentioned, translations can be managed via Crowdin. More details can be found in the [translations section of the readme](https://github.com/BookStackApp/BookStack#-translations). 

Feel free to contribute changes via Crowdin, but it may be worth waiting a week or so since I'll soon be updated some of the shelf translations texts to address #3553.

I'll therefore close this off.
