### ISSUE TITLE
Restriction on viewing recent changes

### ISSUE THREAD

**Issue by whoami-ru** [BookStackApp/BookStack#3696]
### Describe the feature you'd like

Hi. A feature that allows enabling or disabling the view of recent changes for unauthenticated users. For example, we use a central authentication server and external users can view some of the existing logins. It can be used through OSINT to perform some attacks on companies. Also, it applies to information about books that are available for external users.

### Describe the benefits this would bring to existing BookStack users

Improve security

### Can the goal of this request already be achieved via other means?

No

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

6 months to 1 year

**Comment by ssddanbrown** [comment]
Hi @whoami-ru,
Based upon your description, your real fundamental request here is the ability to not show user names due to their potential use against your auth system?

In BookStack we only show user display names and user url slugs, neither of these have a direct connection (unless mapped so in your auth configuration) to authentication login fields. Therefore, if this is a problem, you could update user names to be different to logins used for your auth system?

I don't really want to make the permission system more granular, with controls for user detail visibility, if it only serves to achieve a vague sense of security through obscurity in some environments.

**Comment by grugel-maintro** [comment]
It is not just an issue with displaying the user name it is unnecessary information about the internal workings of the company also without the user names displayed. 
I'm also looking for a solution to hide the recent activity panel  panel for users without login.

**Comment by whoami-ru** [comment]
@ssddanbrown yes, it's not possible to change logins names in this case. As you can see not only me interested in with this issue. I think many companies use BookStack as a knowledge base with the need to make some books public. 
So you can decide by yourself what to do with this issue close or move it to backlog =).

**Comment by ssddanbrown** [comment]
I'm going to close this off since I don't want to add additional permission controls to handle user visibility in the name of a tangential reference to security.

It is possible to customize views as required, with a little hacking knowlege, using the [visual theme syste](https://github.com/BookStackApp/BookStack/blob/development/dev/docs/visual-theme-system.md) or via some custom CSS in the "Custom HTML Head Content" setting.
