### ISSUE TITLE
[Feature request]  comments and imports

### ISSUE THREAD

**Issue by turbotankist** [BookStackApp/BookStack#371]
### Feature Requests:
1. Opportunity to comment on articles.

2. Also need some kind of import. 

Thank you! Great program!

**Comment by AbijeetP** [comment]
For (1), we already have something mentioned here - #47 

I'm currently working on it, and you can track the progress here - https://github.com/BookStackApp/BookStack/pull/261

**Comment by Shackelford-Arden** [comment]
@turbotankist I'm just curious... what do you mean by *imports*?

**Comment by turbotankist** [comment]
@Shackelford-Arden  
I mean  what I've using confluence and there are many articles. How can I import it to bookstack?
So, I've already resovle it. I'm python-user and used it. I downloaded over Conluence Rest API all spaces and inserted direct into mysql.

**Comment by ssddanbrown** [comment]
Hi @turbotankist, Thanks for providing your thoughts and I'm happy to hear you found a way to import your existing data.

As mentioned above, the request for comments is already open on #47. Open issues for imports can be found at #149 and #43. Feel free to add your comments or thoughts to those.

Since this issue overlaps others I'll close this one to keep things focused.
