### ISSUE TITLE
Enable chunked uploads for Dropzone.js

### ISSUE THREAD

**Issue by saschabrockel** [BookStackApp/BookStack#3717]
### Describe the feature you'd like

It would be very nice if Bookstack implemented Dropzone.js, which is used for file uploads so that the uploads use chunks. This way problems like an upload limit from Cloudflare can be circumvented. Otherwise, no matter what settings you make, only a maximum of 100MB can be uploaded. Even changes to php.ini or nginx.conf won't help.

### Describe the benefits this would bring to existing BookStack users

You could upload more than 100MB files with providers like Cloudflare and you wouldn't be restricted anymore, because some providers allow a maximum of 100-500MB per file upload (500MB even as an enterprise version) and you shouldn't be so restricted there. If one would use chunking, the problem could be circumvented. The functionality already exists in dropzone.js.

### Can the goal of this request already be achieved via other means?

Yes, the goal can already be achieved. And it can be achieved through an implementation like the one here: https://stackoverflow.com/questions/50397023/how-do-you-use-dropzone-js-with-chunked-file-uploads-php-only

There are certainly a few changes needed in the code, but since dropzone.js is already used anyway, there probably shouldn't be a problem.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

6 months to 1 year

**Comment by ssddanbrown** [comment]
Thanks for the suggestion @saschabrockel.

To be honest though, I'm not fond of complicating upload handling within our project/codebase because of limitations applied by third-party services, of which are optional to the instance hoster. 
It seems like we're taking the burden from the choices of others. 

If BookStack was a service to specifically handle large files uploads, I might see some value in adding this, but the only value reflected here is circumvention of security controls and hosting limitations.

**Comment by ssddanbrown** [comment]
Due to the above, I'm going to go ahead and close this off.
