### ISSUE TITLE
Searching strings in attachments and uploaded files 

### ISSUE THREAD

**Issue by merrime-n** [BookStackApp/BookStack#3719]
### Describe the feature you'd like

In order to improve the ease of access and content navigation, it would be great if one could search for strings in attachments (mostly MS Office Word files or even PDFs).
 

### Describe the benefits this would bring to existing BookStack users

When the amount of books and shelves rises, the number of attachments increases consequently. As a result, navigating specific files may become an issue. One is likely to remember some parts of a text file but does not recall the name of the file or where the file is uploaded. So if the user can search for strings in files, they can find the file easily.

### Can the goal of this request already be achieved via other means?

The answer is no.
That is because the feature should be accessible along with other BookStack features; So it can be beneficial.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

0 to 6 months

**Comment by ssddanbrown** [comment]
Thanks for the suggestion @okaeiz,

Personally I'm not too keen on this, since it would expand the scope of what we consider as main documentation content to attachments, which provides a sliding scope to different attachment types.
Behavior may be confusing here as indexing will depend on supported formats, and the structure of content within those formats. In addition, extra work would be needed to make it clear where content lies upon seeing search results. 
Also, users can currently upload supporting attachments without altering the search index, so keeping that ability would require further controls which I'd be hesitant to add.

Generally, my view is that if it's considered core documentation content it should be added as page content.
BookStack is not a file/document management system, and I'm hesitant to widen the scope to more become one.

**Comment by ssddanbrown** [comment]
With my above considerations/concerns in mind, I'm going to go ahead and close this off.
