### ISSUE TITLE
Excessive Row Padding in Tables

### ISSUE THREAD

**Issue by david-burleigh** [BookStackApp/BookStack#3761]
### Describe the Bug

I have a large table -- two columns but many rows -- and no matter what I do BookStack adds enormous amounts of padding below the cell contents. There must be a way to make it minimize the row height to just accommodate the contents of the cells. 

### Steps to Reproduce

1. Create a table (mine is 2 x many)
2. Add a little text to each cell
3. Save
4. Edit and add more rows, with a little text in each cell
5. Keep repeating steps 3 and 4.
6. Rows will start getting excessively padded.

### Expected Behaviour

Just make a table (mine is 2 x many) and add a little text in each cell. Then save it and edit it again and add more rows with a little text in them, and keep doing that. The cells will grow way beyond the text within them.

### Screenshots or Additional Context

![Screenshot from 2022-10-02 15-43-08](https://user-images.githubusercontent.com/5530825/193473172-adb57a4e-72e4-4a32-914e-223c27e927fd.png)

### Browser Details

Firefox 102.3.0esr (64-bit)

### Exact BookStack Version

v22.09.1

### Hosting Environment

Linux Mint 21 Cinnamon

**Comment by ssddanbrown** [comment]
From some quick testing, I think this is maybe due to variance in width when in and out of the editor, after making adjustments to row heights which would start fixing table sizes. The fixed row heights will then present empty spacing if the table becomes wider. It is possible to reset heights back to be automatically adjusting to content by selecting all cells in the table then using the "table > cell properties", "table > row properties" and "table > table properties" menu options (accessed via the dropdown icon on the table toolbar item) and then removing any height values or by setting a value of "auto". 

TBH though, if you need content to be flexible, I'd advise against tables, and instead recommend maybe using using additional header levels for each of your shown left-hand cell items, with right-hand cell items as normal paragraphs below.

**Comment by david-burleigh** [comment]
Thank you, but that didn't change anything. The table cell width does not vary. I expect the row height to conform to the contents. That does not seem unreasonable.

**Comment by ssddanbrown** [comment]
> Thank you, but that didn't change anything.

Did you reset it for all three? (Table, row and cell?) 

>  I expect the row height to conform to the contents. That does not seem unreasonable.

It does by default, but upon any manual tweak to table dimensions sizes will start to become fixed which is what I believe is causing the additional spacing here.

**Comment by david-burleigh** [comment]
Ok, yes, that works. I thought I had selected all cells, but I had not scrolled to the end of the table. Thank you.

**Comment by ssddanbrown** [comment]
Happy to help, Will therefore close this off.
