### ISSUE TITLE
deactivate redirect for certain folders

### ISSUE THREAD

**Issue by helson22** [BookStackApp/BookStack#3766]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

Bookstack runs on Ubuntu 22.04 with newest Apache for Ubuntu on local network.

I'd like to track user interaction with a analytics software which must be located in /var/www/bookstack/{{SUBDIR}}

If I navigate to this subfolder bookstack catches this and says it can't find anything (redirecting). So I'm not able to install the analytics app and if installed I can't access it even if I type http://my.localdomain.net/{{SUBDIR}}/index.php.

Maybe this is just a case for .htaccess but I'm not so familiar with it or may there is a separate config-option to exclude redirects for such use-cases?

### Exact BookStack Version

v22.09

### Log Content

-

### PHP Version

7.4

### Hosting Environment

Ubuntu 22.04

**Comment by ssddanbrown** [comment]
@helson22 Do you have any details on the analytics software?

> I'd like to track user interaction with a analytics software which must be located in /var/www/bookstack/{{SUBDIR}}
> If I navigate to this subfolder bookstack catches this and says it can't find anything (redirecting). So I'm not able to install the analytics app and if installed I can't access it even if I type [http://my.localdomain.net/{{SUBDIR}}/index.php](http://my.localdomain.net/%7B%7BSUBDIR%7D%7D/index.php).

BookStack's root web directory is the public folder so, as an example, the following (fictional) URL maps to the following file, assuming `http://my.localdomain.net/` is your main BookStack root url:

- URL: `http://my.localdomain.net/cats/index.php`
- File `/var/www/bookstack/public/cats/index.php`

Note, BookStack does generally not expect files to be added to its `public` directory. These may affect BookStack updates since BookStack may detect unfamiliar directories/files.

As an alternative, you can look to use an Apache `Alias` definition with the BookStack apache config to serve the analytics software from a different directory on the server filesystem.

**Comment by ssddanbrown** [comment]
Since there's been no follow-up I'm going to close this. If the issue remains and is something you still require to be fixed respond to my previous comment and this can then be re-opened.
