### ISSUE TITLE
There is not option to choose relative links 

### ISSUE THREAD

**Issue by jrmiller82** [BookStackApp/BookStack#3785]
### Describe the Bug

When inserting a link it is putting in an absolute link i.e. `http://[IP address]/books/[bookname]/[pagename]`. This makes a demo/production workflow difficult, makes migrating domains difficult to impossible, and makes markdown code otherwise really messy.  

### Steps to Reproduce

Insert any link even for an **internal link** and you'll have an absolute path instead of a relative path. 

### Expected Behaviour

I expect the software to allow either relative links or absolute links, like practically all (all?) other wiki or CMS software. 

### Screenshots or Additional Context

This is pretty much a deal killer bug / oversight. It's like having a word processor that doesn't have a forward delete option, and then being told you can only use backwards delete. 

If this is an intentional design pattern I truly don't understand that position. 

### Exact BookStack Version

22.09.1

### Hosting Environment

docker image from linuxserver.io

**Comment by ssddanbrown** [comment]
Hi @jrmiller82,
Not so much a bug, since it's not a break or issue with existing functionality, but instead functionality that does not align with your expectations or desires.

> This makes a demo/production workflow difficult, makes migrating domains difficult to impossible

We have a [built-in command](https://www.bookstackapp.com/docs/admin/commands/#update-system-url) to update database references when desired.

I'm going to close this off as a duplicate as I feel the fundamental request is already covered by #1342. My thoughts and some historical context can be found within my comments on that issue, in addition to my comments in PR #1275.

**Comment by jrmiller82** [comment]
I am not understanding why you want users to be running commands to update urls in the database, when you should be using relative links like every other wiki/cms out there?

**Comment by ssddanbrown** [comment]
> I am not understanding why you want users to be running commands to update urls in the database

This is only required when changing the domain/base-url used, so I only expect it to be used in infrequent scenarios.

> when you should be using relative links

In your opinion. Absolute links provide some benefits such as less side affects and generally better stability & portability, along with better identification potential. 

>  like every other wiki/cms out there

Not all. Pretty sure wordpress still sticks to absolute links also. 

Either way, relative or absolute, they'd bring their own challenges or limitations. I used absolute early on to prevent some in-editor issues, and have since leant further into using absolute links. I don't see switching or supporting both as worth the effort at this time.
