### ISSUE TITLE
Installing on a shared host

### ISSUE THREAD

**Issue by kwa11ace** [BookStackApp/BookStack#379]
Hi, sorry if I have posted this in the wrong area. 

I don't have a dedicated server and am on shared hosting.  Is there a way to install this via FTP and CPanel?

**Comment by lommes** [comment]
You can install this locally and upload the whole folder to your webroot. For the database you need to create a dump and import later.

I did not test this, but it should work without problems. On updates you have to apply the update locally and repeat these steps. You should download all files and the database apply the updates and reupload.

**Comment by ssddanbrown** [comment]
@kwa11ace You may be able to find a guide for installing a 'Laravel' app on your shared hosting. BookStack is based on Laravel so the steps will be roughly the same.

Please be careful though, Normally on a BookStack/Laravel install, only the `public/index.php` PHP file would be accessible to the internet. On shared hosting, since you have limited options where to place files, it's easy to make all PHP/Config files accessible. If possible you want to set the 'Root' web directory to the `public` folder.

**Comment by ssddanbrown** [comment]
Closing due to issue age and the fact the conversation came to a close, Feel free to comment if you want to discuss further though and this issue can be re-opened.
