### ISSUE TITLE
Multiple Levels of Shelves

### ISSUE THREAD

**Issue by MrNerdversum** [BookStackApp/BookStack#3790]
### Describe the feature you'd like

I would like to request to have have hte option to have shelves inside of shelves. So if you open a shelves u can have subshelves for sup topics of the main shelve.

### Describe the benefits this would bring to existing BookStack users

I think it would be easier to sort things if u could sort books of the same main topic in different sub topics. E.g. like the main Topic "IT-Department" with the Sub-Topics "Software" and "Hardware"  etc.

### Can the goal of this request already be achieved via other means?

No

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

0 to 6 months

**Comment by ssddanbrown** [comment]
Thanks the request @MrNerdversum, but please see issue #95 for a history in regards to additional levels. 
I feel especially adverse to additional shelf layers, since their relation with books already causes confusion, Plus you don't really have shelves on shelves to align with the real-world analogy. 
I'm going to close off this request since additional levels have been previously discussed, and particularly since I don't see nesting shelves to be a way forward.

**Comment by jmmoreu** [comment]
I know this feature has been discussed already a couple of times and I agree with Dan that we could be asking for more levels forever (#1353, #95 ) . However, I must say that I do see the real-world analogy, although I would have chosen different words. In the real-world you do have a Bookcase with different shelves. Each shelf would contain the books which may be on multiple shelves (just as you can do right now on bookstack) or bookcases. 

As this will probably not convince Dan, I do believe though that it would be nice to have a way to organise the books within a shelf (perhaps using book tags in a more appealing way?). If we could see all the books grouped by tags or sorted by tags when possible it would provide that extra level, without having to develop that extra level (perhaps this requires something way more complicated that I am missing). For the real-world analogy, you could have books organised by topic such as "Romance", "Historical", "Thrillers"... I guess that the current approach would require the user to create a different shelf for each topic. But then again, it would not be possible to have a the books of a specific author within a shelf organised by topics.

This kind of feature was also suggested in #3708 , but it was closed since it was linked to the sub-chapter feature in #95 (which I think it is conceptually different since you shouldn't reorganise sub-chapters within a book). I do believe this is asking for something different. No extra levels, but a way to sort or group books within a shelf (right now you can sort them manually, but using the book tags would be much more useful when you have a high number of books).

I know feature requests may sound a bit rude for the developers (specially when the request implies a huge workaround), but please be sure that Bookstack is great!
