### ISSUE TITLE
Feature:  Switch the HtmlDiff package

### ISSUE THREAD

**Issue by mlantz** [BookStackApp/BookStack#381]
### Switch the HtmlDiff package:

Switch to https://github.com/caxy/php-htmldiff rather than `gathercontent/htmldiff` which requires the Tidy extension. Currently homestead doesn't work out of the box nor does anything built with forge, without having to install further extensions.

**Comment by ssddanbrown** [comment]
@mlantz Thanks for opening this issue and creating a pull request but unfortunately the alternative library used is under a GPL-v2 license which is incompatible with this project. I am open to removing the tidy extension requirement if a good alternative option is provided but for now, due to the license issue, I will close this issue and the pull request.
