### ISSUE TITLE
Editors not loading when the domain is behind Cloudflare DNS proxy

### ISSUE THREAD

**Issue by AuthorShin** [BookStackApp/BookStack#3814]
### Describe the Bug

Hello
When the domain is behind Cloudflare DNS proxy page editors are not working (WYSIWYG not working at all but Markdown is still working for some pages).
When I turn off the Cloudflare DNS proxy editors start loading and working as expected.
P.S. I tested this on all versions starting from v22.06.1 till the v22.10.1 and took me awhile to find out it was caused by Cloudflare DNS proxy because in the past it used to work just fine (since 1 year ago).

### Steps to Reproduce

Have a instance with a domain behind Cloudflare DNS proxy and install the Bookstack on docker (haven't tested it on other environments).

### Expected Behaviour

When logged in and click on edit to edit a page I expect the editor to load normally and be able to edit the page contents.

### Screenshots or Additional Context

<img src="https://i.ibb.co/1XGpQj2/Screenshot-2022-10-27-023316.png" alt="Screenshot-of-problem">

### Exact BookStack Version

v22.10.1

### Hosting Environment

Debian 11 (Docker)(Domain is behind Cloudflare proxy)

**Comment by ssddanbrown** [comment]
Hi @AuthorShin,
From previous cloudflare-based issues,  I remember Cloudlfare attempts to inject its own scripts.
One is something like "Rocket Loader" and the other is some email obfuscation script.
There should be settings in Cloudflare to disable these. Disable these injected scripts and things should work again.

Otherwise, if that's not the case, it would help to see any errors in the browser development tools "Console" table.
If you need guidance on this, just let me know what browser you're using.

**Comment by AuthorShin** [comment]
Hi @ssddanbrown 
Thanks a lot for the help turning "Rocket Loader" off fixed the problem.
