### ISSUE TITLE
Backup method bookstack

### ISSUE THREAD

**Issue by cevinov** [BookStackApp/BookStack#3820]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

Hello sir,

I have my own method to back up my data in bookstack app. The method is that I'm navigate to the volume of my bookstack container and after that I zip it. So if I run into a problem, I just need to create a new bookstack container and unzip my previous bookstack volume, and map it with portainer.

Is my method correct sir ?.

### Exact BookStack Version

v22.07

### Hosting Environment

Oracle Cloud

**Comment by ssddanbrown** [comment]
> Is my method correct sir ?.

There's no way to ensure a backup process works until you attempt to restore.
Try to create a separate running instance of your BookStack system, from your backup data, to be sure.

You only mention zipping of the bookstack container volume, you'll also need the data from the database container.
Zipping live database data can be a little risky since you're working with active data. Ideally you'd create a mysqldump of the data. We [have details on creating a database dump here](https://www.bookstackapp.com/docs/admin/backup-restore/) but the approach may differ if attempting via a container.

**Comment by cevinov** [comment]
Hi sir, I tried and it worked.

Thank you
