### ISSUE TITLE
Month export date error

### ISSUE THREAD

**Issue by Statium** [BookStackApp/BookStack#3825]
### Describe the Bug

Problem recurs in version 22.10.1
https://github.com/BookStackApp/BookStack/issues/3650

### Steps to Reproduce

1. Export to PDF

### Expected Behaviour

-

### Browser Details

Chrome

### Exact BookStack Version

22.10.1

### PHP Version

8.1

### Hosting Environment

WinServer

**Comment by ssddanbrown** [comment]
As far as I'm aware, I've made no additional changes upon those in #3650 to the locale system. 
Not really sure why this differ now. 
Were you ever using the changes I applied in #3650 or were you only using your own changes?

**Comment by Statium** [comment]
> As far as I'm aware, I've made no additional changes upon those in #3650 to the locale system. Not really sure why this differ now. Were you ever using the changes I applied in #3650 or were you only using your own changes?

I used my own fix (manual change in the code), on the new version 22.10.1 the problem persists out of the box.

**Comment by Statium** [comment]
![image](https://user-images.githubusercontent.com/4026090/199560525-36e96c0e-c27c-4e18-8c26-558c84778607.png)
Adding UTF-8 to the line in the screenshot still solves the problem for me.

**Comment by Statium** [comment]
I think the problem is that all languages have a prefix _ but in Russian it is not, this function does not work correctly for the Russian language.
![image](https://user-images.githubusercontent.com/4026090/199561154-01c82a1b-1f56-4a2c-a096-86a391a1cdd7.png)
![image](https://user-images.githubusercontent.com/4026090/199561255-118a50c7-db17-4aa9-90e9-cc8ce0cee722.png)
Could this be a problem?

**Comment by ssddanbrown** [comment]
Just been doing a lot of testing on this in a Windows 10 VM. 
From [changes back in Jan](https://github.com/BookStackApp/BookStack/commit/78ebcb6f38ee7a984b26cd56dff882ae9d7e9f95#diff-d2eb5dba3f36e9494a1167c348e4ed001c8fd32225b678d81c278751a5164a6b), introduced in v23.01, system-locale based details are not used so this should not longer be an issue since then.

Additionally, with the old date formatting methods this still was working fine for me.
The lack of underscore/two-components within the `iso` value for `ru` shouldn't have been an issue, and just resulted in `ru.UTF-8` being applied as suggested as the working value.

I'll therefore close this off.
