### ISSUE TITLE
User count on Users page (admin settings section)

### ISSUE THREAD

**Issue by BloodyIron** [BookStackApp/BookStack#3838]
### Describe the feature you'd like

A count of the number of users on the users page (in settings).

### Describe the benefits this would bring to existing BookStack users

Make it so we can count how many active users there are, for administrative decisions.

### Can the goal of this request already be achieved via other means?

Not that I know of.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

0 to 6 months

### Additional context

Please? :)

**Comment by ssddanbrown** [comment]
> Can the goal of this request already be achieved via other means?
> Not that I know of.

You could count them? 20 per page if you have many pages, then just count last page.
Alternatively, look at `users` page of the database.
If it's a common requirement, you could also hack this into the view using the [visual theme system](https://github.com/BookStackApp/BookStack/blob/development/dev/docs/visual-theme-system.md).

TBH, I'm not too keen on adding this since it'd then be expected in all similar listing views in the application, and it's an extra thing to complicate views and question expectations upon (For example, does the count change during a search? etc...). Especially not keen since I have not had a previous request for this.

Think I'd prefer to maybe have stats listed within a separate maintenance view, but I'm not too comfortable adding that without understanding exactly the value of what questions they're answering, or what administration questions are being asked here. 

I know some business environments will just hook-up a business intelligence tool (PowerBI, tableau, etc..) to the bookstack database so they can dashboard up any views they need as required.

**Comment by BloodyIron** [comment]
Having to go into the database to count number of users seems onerous and time costly when I'm really asking for a simple user count, and having that number change based on search filter isn't a priority for me. With hundreds of users counting pages and such is also onerous. Knowing how many have actually ever logged in helps determine usage level and who _isn't_ using Bookstack. I think you're making this bigger of an ask than it really is ;)

**Comment by ssddanbrown** [comment]
> With hundreds of users counting pages and such is also onerous.

The number of pages is always reflected in the pagination. You can just do `((page_count - 1) * 20) + number_of_users_on_last_page`.

> Knowing how many have actually ever logged in

Okay, but that's already potentially something different that simply reflecting the numbers of users in the list, hence the questioning around the questions being answered by this.

> I think you're making this bigger of an ask than it really is ;)

For sure relative to raw implementation effort, it'll be a very simple thing to add in. Just a case of adding `<p>{{ $users->total() }} Users</p>`  to [somewhere around here](https://github.com/BookStackApp/BookStack/blob/ec4cbbd0041122f30d13afc016f8a5fac72e0754/resources/views/users/index.blade.php#L34-L33).

That said I can't just add in every minor detail requested otherwise things would be a confusing mess, so I try to evaluate everyone on value, desire and platform fit. This count has not been previously requested and can be easily worked out, so has minimal value/desire. Implementation requires working it into the design and thinking about ux, in which case we'd have to think about the expectations of other list views if we're showing a count on this one.

**Comment by ssddanbrown** [comment]
For the reasoning provided above, I'm going to go ahead and close this off.
