### ISSUE TITLE
Simplify creation / editing of books / chapters / pages by removing unnecessary clicks

### ISSUE THREAD

**Issue by Rene-Auberger** [BookStackApp/BookStack#3839]
### Describe the feature you'd like

Improve creation of new pages by adding additional elements to the UI:

- "Save & create new [chapter|book|page]" button
- "Create new page" button when viewing a page (currently users must go back to chapter view when they want to create a new page)
- hover-icons for editing books / chapters / pages that are displayed eg right of the title. Currently users must click to open eg the page and then click edit.

### Describe the benefits this would bring to existing BookStack users

Adding these "shortcuts" to create or edit new elements within Bookstack would save the users time, simplify their workflow when editing or creating content. At the same it will time reduce workload from the server as no more unnecessary pages need to be served. Some exmaples:

- currenlty page must be opened in view mode before it can be edited
- when editing a page and the user wants to add a new page he needs to save the page, the page is displayed in view mode, user needs to switch back to chapter, chapter is displayed, user creates new page

New approach:

- user clicks "edit" icon next to a page title in the chapter view and page is directly opened in edit mode
- user clicks "save & create new page", page is saved and a new one is directly opened in edit mode

### Can the goal of this request already be achieved via other means?

Yes - because this feature request describes an improvement in workflow for users that reduces the number of necessary clicks and time to achieve a goal.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

0 to 6 months

**Comment by ssddanbrown** [comment]
Thanks for the input @Rene-Auberger.

The trouble is that such additions are not without cost. I don't want to add item-level hover controls in list views, since this would add visual distraction & noise. I don't see exposing item actions an additional depth layer, as worth it for the listed benefits. I want to keep actions relatively contextually tight to the current view. If really desired, you could tweak the list views used in your instance via our [visual theme system](https://github.com/BookStackApp/BookStack/blob/development/dev/docs/visual-theme-system.md).

Adding actions for sibling page creation is already covered by #1267.

As an additional note, I'm looking to [add interface shortcuts](https://github.com/BookStackApp/BookStack/pull/3830) to the next release which should help lessen clicks in certain cases for power users.
