### ISSUE TITLE
Issues is Still There in markdown-it html tags

### ISSUE THREAD

**Issue by yoginth** [BookStackApp/BookStack#386]
### Error in Markdown

* BookStack Version: 0.61.1
* PHP Version: PHP 5.6.4
* MySQL Version: 5.14

According the issue #378. I have enabled The HTML option `const md = new MarkdownIt({html: true});` but it seems the HTML Markdown is not working.

![screenshot from 2017-05-06 12 09 01](https://cloud.githubusercontent.com/assets/10177861/25770507/d726b212-3254-11e7-9575-c242b3cfa946.png)

**Comment by ssddanbrown** [comment]
Hi @yoginth,
Making that code work will require it to be placed in the correct place. Refer to this commit: 92108d710dc8e2c9626d61e17fc4ee5e4f15979e.

Also, The JS will need to be built using gulp afterwards.

It should work by default, Without the requirement of modifications as of v0.16.1. I can only assume it doesn't due to large modifications made. Since I can't really support custom modifications I will close this issue but if you can prove HTML does not work on a vanilla instance let me know and I can re-open this issue.

**Comment by yoginth** [comment]
No i have modified the particular line in **BookStack v0.16**
