### ISSUE TITLE
Sorting pages between chapters does not work

### ISSUE THREAD

**Issue by Eichiwolf** [BookStackApp/BookStack#3860]
### Describe the Bug

Trying to move pages from one chapter to another within a book fails without error for every user other than the global administrator. 

However sorting pages within a chapter does work just fine

### Steps to Reproduce

Enter Sort mode as user.
Drag page to another chapter.  
Click 'Save'  
BookStack reports "Book successfully re-sorted"  

-> Changes are not saved

### Expected Behaviour

Pages are moved to another chapter or outside a chapter

### Screenshots or Additional Context

Permissions given to the user role on book level:

- [x]  View
- [x] Create
- [x] Update

System Permissions: none
Asset Permissions:

![Bildschirmfoto vom 2022-11-17 10-36-18](https://user-images.githubusercontent.com/118433751/202410202-6614f59c-7782-45d1-949a-b3e19b3a333a.png)

Tried on production environment with NGINX proxy and fresh install without proxy

### Exact BookStack Version

v22.10.2

### PHP Version

8.0.25

### Hosting Environment

Docker Compose from Linuxserver.io
MariaDB 10.6.10

**Comment by ssddanbrown** [comment]
Hi @Eichiwolf, This is likely related to [#1200](https://github.com/BookStackApp/BookStack/issues/1200#issuecomment-450385751) and #3813.

The permissions involved in sorting are quite complex, and changes are assessed on a per-items basis, where the changes are allowed or not on per-item permissions.

Therefore, I'd imagine you're not seeing changes due to lacking permissions right now. 
Based on the shared permissions, I'm guessing is lack of "Delete" permissions. Moving an item out of its original location currently requires "Delete" permission for that item.

**Comment by Eichiwolf** [comment]
Oh that was it, thanks.
I think i tried granting every permission other than that before opening the issue.
A bit unfortunate since we planned on not giving every user delete permissions, but it'll do for now.
