### ISSUE TITLE
Create Book and add to Shelf

### ISSUE THREAD

**Issue by McHill007** [BookStackApp/BookStack#3886]
### API Endpoint or Feature

It would be great to have an optional parameter in create/update book api endpoint to directly assign the book to a shelf.

`{
  "name": "My own book",
  "description": "This is my own little book",
   "shelf_id" 1
}`

### Use-Case

We are creating books out of github automatically and would like to assign them to a specific shelf directly. 
We need to get the shelf , parse the books and update shelf with new assignment. 

I think it would reduce the work if the assignment can be done directly while creating or updating a book.

**Comment by ssddanbrown** [comment]
Thanks for the request, but I'm not sure if the use-case is significant enough to make this worthwhile.
I generally want to avoid adding tangential features, or optional abilities to endpoints, in the name of optimizing specific use-cases since needing to handling such elements creeps the scope of the specific endpoints and adds technical dept.

I'd maybe be a little more open about the addition of specific add/remove book endpoints for shelves, so would still require an extra request to put the book on a shelf but would avoid having to get & parse the shelf first.

**Comment by ssddanbrown** [comment]
As per my previous message, I would not want to add the specific implementation requested here, and there's been no follow-up conversation, so I'll therefore close this off.
