### ISSUE TITLE
Exclude Shelfs/Books/Pages from Search

### ISSUE THREAD

**Issue by bionemesis** [BookStackApp/BookStack#3917]
### Describe the feature you'd like

The ability to flag a Shelf/Book/Page to not show up in search results. Perhaps being able to exclude based on tags would be easiest?

### Describe the benefits this would bring to existing BookStack users

We have a dedicated Book called "Work in Progress" where we keep chapters and pages that we are working on before moving them to the appropriate book/chapter. By definition, these are documents that are not ready for consumption but were already saved (not as a draft). As there is no way to take a saved page back to draft status, keeping the page as a draft may not always be an option (mistakes happen).

### Can the goal of this request already be achieved via other means?

For new content, yes. As long as the page is saved as a draft, it won't show up in search results (I believe). But for existing content, or if someone accidentally saves the page, it's not possible.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

6 months to 1 year

### Additional context

There is a more narrowly focused and somewhat similar issue in #3657, but it is specific to shelf membership.

**Comment by ssddanbrown** [comment]
Thanks for the request @bionemesis,

I quite like the idea of being able to exclude based on tags, since it's quite a generic solution that could have many use-cases, but would that for sure suit your use-case? Considering:

- These would have to be applied when searching.
- The tags would need to be applied to content.

A request like #1691 sounds may actually suit your use-case better (So you could archive the book but keep it in favourites) but that kind of thing has a much more significant scope for platform fit and implementation, whereas adding a new search ability for tag terms is much more feasible in the short-term.

**Comment by ssddanbrown** [comment]
Since there's been no further follow up I'm going to close this off.
If it's something you'd still desire please respond to my comment above and this can be re-opened.

**Comment by Saturo78** [comment]
It would be very helpful to have the ability to exclude certain shelves or books from the global search results by setting a flag or property on them.

The reason for this request: In a diary or journal, terms often appear only as brief mentions without any relevant context. When searching for a topic, these entries show up as false positives and clutter the search results. Being able to exclude such content would make the search much more accurate and useful.

This could be implemented, for example, as a checkbox or a setting in the shelf/book configuration (“Exclude from search”), so that content marked this way is ignored by the search index.

**Comment by mattexxino** [comment]
Very helpful if you need to keep an archive of old posts without them appearing in the search results.
