### ISSUE TITLE
Export Audit Logs

### ISSUE THREAD

**Issue by IMAG0D** [BookStackApp/BookStack#3957]
### Describe the feature you'd like

The ability to export Audit Logs to CSV

### Describe the benefits this would bring to existing BookStack users

Main benefit will be the ability to 'stock take' your bookstack contents. 

Secondary benefits:
- faster content maintenance
- added log sorting ability

### Can the goal of this request already be achieved via other means?

Yes: You can copy and paste audit log results into a csv. This becomes troublesome when you have more than 1 page of Logs.

This gives rise to a secondary component to this feature:
The ability to filter which columns of data you want to export

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

6 months to 1 year

**Comment by ssddanbrown** [comment]
Hi @IMAG0D,

In regards to the main benefit:

> Main benefit will be the ability to 'stock take' your bookstack contents.

I don't understand what that actually functionally achieves. What does this 'stock take' actually allow or achieve and how does this benefit users? How is the CSV data being used/consumed?

In regards to the request in general, it would be a fairly niche addition since it has not had prior request, and I especially can't see it being worthwhile to build sub-features/options around this such as the requested column filtering. 

My main thought to this feature is: If you need this level of audit and control of the format, why not access the database directly? That way you gain ultimate control and can join the data to other tables/details as required.

**Comment by IMAG0D** [comment]
The situation that lead me to this request was when I tried to grab the following info:
- Total number of pages created
- List of all Page titles and the creator of each Page

I ultimately wanted that information to help figure out a more efficient way to keep our page information up to date
I did end up in the database eventually but I just thought the feature would be useful to get that info more quickly. 

So yeah definitely not a necessary feature but I really appreciate the reply anyway,

@ssddanbrown

**Comment by ssddanbrown** [comment]
Okay, even for those use-cases the audit log would not be ideal. The audit log primarily reflects use actions instead of database state. The database will really be the best and most flexible solution for those kinds of metrics (and especially useful if you have business intelligence tools to connect the database up with).
Otherwise, for high-level detail, something like the existing request in #3204 would probably be a better approach. 
Will therefore close this off but may consider something simplistic or API-based if it becomes more requested in the future.
