### ISSUE TITLE
 A way to automatically transfer rights from shelves to books

### ISSUE THREAD

**Issue by CptGroot** [BookStackApp/BookStack#3959]
### Describe the feature you'd like

It would be nice if there was a switch on the shelves under Permissions that would allow you to automatically transfer permissions to books.

### Describe the benefits this would bring to existing BookStack users

Users can create new books on the affected shelves without having to worry about permissions. In addition, the administrators no longer have to search for new books and click on copy permissions

### Can the goal of this request already be achieved via other means?

No

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

1 to 5 years

**Comment by ssddanbrown** [comment]
Thanks for the request @CptGroot but this has been discussed many times before (#1091, #2652, #1455).
There is also an existing request in #1596 to add an option to copy permissions on book create from shelf.
There also is a [built-in command](https://www.bookstackapp.com/docs/admin/commands/#copy-shelf-permission) to help copy shelf permissions.
Since this has already been covered, or at least touched upon, by existing open & closed issues I'm going to close this off.
