### ISSUE TITLE
HHVM support

### ISSUE THREAD

**Issue by yoginth** [BookStackApp/BookStack#396]
Does bookstackapp runs on HHVM server?

**Comment by Shackelford-Arden** [comment]
@yoginth Can you clarify?

Are you asking if it's compatible with running on HHVM or are you asking something else?

**Comment by ssddanbrown** [comment]
Hey @yoginth, I think BookStack should generally run on HHVM, I've ran similar Laravel based apps on HHVM before with no problem. That said, HHVM is not directly supported and tested against. If there specific things that break feel free to open an issue for those.

Since the original issue is a question which should be answered in the above I will close this but feel free to comment further if you don't feel your question has been answered.
