### ISSUE TITLE
Ignore search words

### ISSUE THREAD

**Issue by Daru-man** [BookStackApp/BookStack#3967]
### Describe the feature you'd like

Dear ssddanbrown,

If it is possible, we need a tool to ignore some words in search. For instance, in Spanish the word "de" is very used. When someone makes a search with this word all go slow, because boockstack search all pages with this word.

Thanks for your time

Capture: time to response search with "de"
![vivaldi_2023-01-13_15-54-15](https://user-images.githubusercontent.com/97914522/212350111-b08e3dd6-e215-4004-a218-6584412038bd.png)

### Describe the benefits this would bring to existing BookStack users

Quick search

### Can the goal of this request already be achieved via other means?

No

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

6 months to 1 year

**Comment by ssddanbrown** [comment]
Thanks for the suggestion @juan-f-rico. This can be discussed before in #2894.
My feelings remain the same as [my comment here](https://github.com/BookStackApp/BookStack/issues/2894#issuecomment-904935342).

Ultimately, I think this is choosing a complex/specific solution to a problem rather than dealing with the problem head-on, which is fundamentally the performance issue. 
70 seconds is of course a very long time for a search.

Can you provide any insight in regards to the BookStack instance and host machine specs? Just want to know how powerful the host system is and the general database size (Estimate amount of pages and roles).

**Comment by ssddanbrown** [comment]
Since there's been no follow-up I'm going to close this. If the issue remains and is something you still require to be looked at, please respond to my previous comment and this can then be re-opened.
