### ISSUE TITLE
Current shelf of book

### ISSUE THREAD

**Issue by GenTexX** [BookStackApp/BookStack#3968]
### API Endpoint or Feature

If i get my list of Books, it would be nice to know in what shlef they currently are.

### Use-Case

Yes, Books should be unique by name, but for in my case, I have a few books with the same name in different shelves. Would be nice to differentiate them by shelf.

**Comment by ssddanbrown** [comment]
Thanks for the suggestion.
I'm not sure on where we should expand the scope for the `books - list` endpoint, showing assigned shelves seems like it would be a bit out of scope since it's one-to-many parental detail. This is not a format we ever have in the interface itself at all. 

It would make more sense to add a list of assigned shelves to the `books - get` endpoint, which would achieve the same thing but may require additional API calls. 

You technically could already achieve this via pre-fetching the details of each shelf in the system, which lists assigned books, but I can see that's not ideal.

**Comment by ssddanbrown** [comment]
I'm going to therefore close this off as I do feel that a many-parent relation is out of scope for a listing endpoint, but if the alternative `books - get` option as mentioned above would suffice feel free to re-request for that.
