### ISSUE TITLE
Internal LAN Works, Tailscale Broken

### ISSUE THREAD

**Issue by Insan0** [BookStackApp/BookStack#3972]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

I am able to access Bookstack locally by going to 172.16.0.100:6000.  The APP_URL is `http://172.16.0.100`  

I'm on CGNAT, and so I'm using Tailscale to access my network when away from home.  

However, when I'm remote and try to access Bookstack through the Tailscale domain (machine.tailunique.ts.net:6000) or the Tailscale IP (10.xxx.xxx.xxx:6000) it doesn't work.  When trying on my iPhone, the address bar switches to show 172.16.0.100, and eventually says the server stopped responding.  

Access to my other apps works fine using Tailscale this way (e.g. plex, photoprism, etc.).  I tried Wiki.js, and that works also with this method, but I really much prefer the structure, intuitiveness of Bookstack.  

I suspect this is related to open issue 1342, but not sure.  

### Exact BookStack Version

v22.11.1

### Hosting Environment

Synology NAS through docker.

**Comment by ssddanbrown** [comment]
Hi @Insan0,
BookStack only supports being hosted on one hostname/IP at a time. Since you mention:

> When trying on my iPhone, the address bar switches to show 172.16.0.100

It sounds like the request is resolving but BookStack, with the APP_URL set to `http://172.16.0.100/`, will redirect to that local IP.

I'd advise standardizing on a single domain/scheme for usage, so the tailscale domain I'd guess in this case since that should be accessible for everything?

**Comment by Insan0** [comment]
Hi @ssddanbrown  ,
Thanks for the quick reply.  Yes, i suppose I'll need an internal DNS server to route the tailscale domain when used internally to the correct IP?   The tailscale domain is only available if the device is on the tailscale tunnel.  Local devices (e.g. desktops) wouldn't need to be on the tailscale tunnel.  Am I understanding this right?  Thanks again.

**Comment by ssddanbrown** [comment]
Ah, Yeah, Sorry, I'm not too familiar with tailscale, have only quickly used it once before.
I had it in mind they provide some way to expose a public domain/IP though, might be an add-on service of sorts?

**Comment by Insan0** [comment]
Great thanks, I'll look into it.  Am I right that this is the same as issue 1342?  If so, I'll keep my eye on that to see if things might change on Bookstack end, and you can close this one.  

By the way, I was so happy and excited to use Bookstack, I created a Github account just for this.  Great work!

**Comment by ssddanbrown** [comment]
Thanks!

> Am I right that this is the same as issue 1342? If so, I'll keep my eye on that to see if things might change on Bookstack end, and you can close this one.

If your intention is to use the system on multiple IPs/hosts, yes. To be honest though, I don't see the status of that issue changing anytime soon. The current system is based upon decisions I made early on and have since reinforced usage of. It would be a painful process to make changes to that and one I don't see being relatively worthwhile right now.
