### ISSUE TITLE
Dictation (speech to text) on Bookstack through OpenAI Whisper

### ISSUE THREAD

**Issue by rounakdatta** [BookStackApp/BookStack#3990]
### Describe the feature you'd like

Dictation would be a much loved feature on Bookstack. What if there would be a mic button pressing which the dictation module is activated. Many folks must be using Bookstack for mind dumps and hence such a feature would be pretty interesting. [OpenAI Whisper](https://github.com/openai/whisper) is open-source and with community development like [whisper.cpp](https://github.com/ggerganov/whisper.cpp), I feel self-hosting Whisper isn't that big of a deal. Connecting Bookstack to the self-hosted Whisper API can help us achieve the feature.

Bonus: If the dictation service is able to take into account meta things like - "insert a joy emoji", "start a newline with Large Header", "quote ... unquote" etc, that would be pretty awesome. If our custom server which processes these meta instructions, that improves QoL much more.

### Describe the benefits this would bring to existing BookStack users

- A lot of folks must be using Bookstack for diary-writing or even for mind dumps. It might be very helpful in such situations.
- Often tools like [Otter](https://otter.ai/) are used to take meeting notes and transcriptions. Imagine where we just turn on the mic button on Bookstack and the entire meeting transcription gets recorded there itself on a page.

### Can the goal of this request already be achieved via other means?

The base feature doesn't exist as of today. Whether or not we decide to use OpenAI Whisper is a thing to discuss.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

1 to 5 years

**Comment by ssddanbrown** [comment]
Thanks for the request @rounakdatta.
To be honest, this is not something I'd be particularly keen on including myself. While you say it would be a much loved feature, this is the first request I've had for such a feature. Therefore I don't think there'd be enough benefit to warrant the build, maintenance, support and reliance on external libraries/technologies (Whisper or otherwise). 
I think this would be something better served at an operating system or browser extension level, like many existing speech-to-text systems.

**Comment by rounakdatta** [comment]
Yup, on re-thinking, this might better be implemented as a browser extension to allow more applications to benefit from it. I'm hence closing this issue.
