### ISSUE TITLE
Feature Request: Email to document

### ISSUE THREAD

**Issue by mojoaar** [BookStackApp/BookStack#402]
### Feature Requests

Desired Feature: Email to document

Wanted to propose a feature that would allow you to email into the platform and get that email converted to a page. Maybe having like a doc inbox where you could sort the stuff coming in.

Would make it easier to create documents from your email inbox (copy/paste is so old school) where some knowledge will end up. 

/ Morten

**Comment by s0n-** [comment]
This is a great feature for indexing mass email chains, would be useful for our deployment as well.

**Comment by Nebucatnetzer** [comment]
I would love to have this. It would make capturing things on the go much easier. Especially in a scenario where one wouldn't have a reliable connection.

**Comment by ssddanbrown** [comment]
Thanks for the request but I'm going to close this off since there's been little desire/request for this since opened, while it'd be a technical pain to achieve and support.

You may find this possible to achieve via automation platforms such as Zapier, using such as platform to recieve email, format as desired, then feed into BookStack using the REST API.
