### ISSUE TITLE
Document stats

### ISSUE THREAD

**Issue by athornfam2** [BookStackApp/BookStack#4020]
### Describe the feature you'd like

I'd like to see more stats for each document such as upvote and view count. In correlation to that would be nice to add a overall stats page (views over days, weeks, months, keyword searches, most popular upvoted docs, etc).

### Describe the benefits this would bring to existing BookStack users

This would help overall give bookstack admins and contributors more insight to how the articles are benefiting others and where improvements are needed.

### Can the goal of this request already be achieved via other means?

No

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

1 to 5 years

**Comment by ssddanbrown** [comment]
Thanks for the request but this does have overlap or is already covered by existing issues #1000, #518, #505, #1772 and #1524 and therefore I'm going to close this off. Please see those for more specific thoughts.
As will be generally seen in those, my general advisory is just make use of an analytics system if that's what you need since that would be more extensive and purposefully built for analytical data.
