### ISSUE TITLE
Function Anchor in WYSIWYG

### ISSUE THREAD

**Issue by thelmosantos** [BookStackApp/BookStack#403]
### For Feature Requests

Desired Feature: Function Anchor in WYSIWYG

Hi!,

Is it possible con create anchors using the page editor mode WYSIWYG? I saw that it's possible to do when we use the Markdown mode. I think it could be very usefull  if we could define anchors with a button.
Right now, to define a Anchor in a title I need to put this code in the line that I want to use this functionality:

for example:
` <h1><a name="Top" id="Top"></a> put a Title here....</h1>`

And than, at the hyperlink button (insert/edit link) I c`an choose the Anchor option and select the title with the code that I inserted.

So, it would be awesome if I could define a Anchor without need to put html codes.

I hope you could add this functionality soon.

Thanks and best regards,

Thelmo Henrique

**Comment by samgoode** [comment]
To add to this, how about on the settings page when WYSIWYG is selected, you get two text fields appear in which you can specify the plugins and toolbar parameters for TinyMCE?

This way if you want anchor links available, simply add it to the plugins list and to toolbar wherever you want.

Then when the WYSIWYG editor is loaded it pulls the settings from here.

**Comment by samgoode** [comment]
@ssddanbrown is this something that would be easy enough to add to the next release?

**Comment by ssddanbrown** [comment]
Sorry for the late reply :grimacing: 
The WYSIWYG editor does have some in-built anchor linking which detects and provides headers within the page to link to:

![image](https://user-images.githubusercontent.com/8343178/167824881-fdd91eb5-bec2-43df-ab1a-ac37404afe96.png)

I think that probable suits most use-cases, I wouldn't really expand on that existing functionality since there's been relatively so little demand in the last 5 years so will hence close this off.
