### ISSUE TITLE
Custom application icon not showing on uploaded images

### ISSUE THREAD

**Issue by JK1198** [BookStackApp/BookStack#4030]
### Describe the Bug

I set a custom application icon with the new setting. For most sites the icon is used as the favicon. But when I open an image in an new tab it will use the default bookstack favicon.
It seems like that /uploads doesn't use the custom application icon.

### Steps to Reproduce

1. Set custom application icon
2. Open any site with a image in the text
3. Click on that image
4. In the new tab the favicon should be the default bookstack icon

### Expected Behaviour

The custom application icon should be used as the favicon.

### Exact BookStack Version

v23.01.1

### PHP Version

8.2

### Hosting Environment

Installed on AlmaLinux 9, Apache httpd as webserver

**Comment by ssddanbrown** [comment]
Thanks @JK1198 for reporting.
BookStack sets the icon via meta tags, so it will be only used on BookStack-rendered HTML pages.
Images won't go through BookStack at all in most cases. 

We'd need to set the `public/favicon.ico` file directly for that but that's a little bit of a pain since `.ico` format support is limited and that's not a directory we advise to be writeable, so would need some extra file permission checks around that.

**Comment by ssddanbrown** [comment]
Have started on this in #4032, having some fun byte-level hacking the fairly-well supported `bmp` image format into `ico` format. Seems to work from a quick test.

**Comment by ssddanbrown** [comment]
Now addressed as part of  #4032, to be part of the next feature release.
