### ISSUE TITLE
Logo in Login Form

### ISSUE THREAD

**Issue by reddexx** [BookStackApp/BookStack#4070]
### Describe the feature you'd like

As well as uploading the application logo and the icon for the login form

example:
Settings:
![image](https://user-images.githubusercontent.com/6242840/221517787-3df8bd84-9007-4a6c-bda6-0f21a841e031.png)

Login form
![image](https://user-images.githubusercontent.com/6242840/221518162-8011f827-dc5f-4612-ad7a-f132c04e51b1.png)

i have this manually over CSS inserted

   .my-l {
    margin-top: 10px !important;
    margin-bottom: 0px !important;
    background-image: url(➡️LOGO URL HERE⬅️);
    height: 250px;
    background-size: 100%;
}

### Describe the benefits this would bring to existing BookStack users

You don't have to enter it manually

### Can the goal of this request already be achieved via other means?

  .my-l {
    margin-top: 10px !important;
    margin-bottom: 0px !important;
    background-image: url(➡️LOGO URL HERE⬅️);
    height: 250px;
    background-size: 100%;
}

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

Not using yet, just scoping

**Comment by ssddanbrown** [comment]
Thanks for the request @reddexx, but this is a customization that'd be well-suited for the [visual theme system](https://github.com/BookStackApp/BookStack/blob/development/dev/docs/visual-theme-system.md). I don't see it being worthwhile to add as another official option, since this would only be used on one view, which may already show a logo, and since there's been no strong prior request for this feature.

Therefore I'll close this off.
