### ISSUE TITLE
Increase book description character limit

### ISSUE THREAD

**Issue by KevinMaatman** [BookStackApp/BookStack#4085]
### Describe the feature you'd like

When writing the description of a book, we face a **1000** characters limit.

The error: _The description may not be greater than 1000 characters._ appears

 I would like to increase this limit. 1000 characters is not always sufficient for us and currently a limitation.

### Describe the benefits this would bring to existing BookStack users

Being able to write descriptions longer than 1000 characters for books

### Can the goal of this request already be achieved via other means?

No

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

0 to 6 months

**Comment by ssddanbrown** [comment]
Hi @KevinMaatman, Thanks for the request but I'd need to understand why the described benefit:

> Being able to write descriptions longer than 1000 characters for books

would actually be a benefit. What fundamental value does it provide? What would allowing more that 1000 characters allow? 

This has not really been an issue for the last 7 years, so understanding that there's a significant benefit (primarily to our existing user base) is important to considering changes here. 

Personally I see a limit to this field as somewhat important, since it avoids the description being abused as content instead of a summary/description, and provides an indication that it should be succinct (Especially since most uses of the description will be in a length-limited truncated format).

**Comment by Swoy** [comment]
We've had this issue in our organisation as well, where some editors have expressed the need to describe books more indepth. This has always concluded with creating separate books for parts of the content as opposed to including it all in one book. There is also a possibility to divide the books into chapters and describe each chapter instead.

Personally I see the limit to this field as a feature that prevents us from creating a mess we don't really want.

**Comment by KevinMaatman** [comment]
Hi,

Well the reason we needed it is because we use books as "Customers". So we want the description of the "Customer" to contain a short introduction about what they do. And the "pages" to be specific information about the customer. Sometimes the introduction we fill is longer than 1000 characters. I do not expect "Unlimited" characters, but a higher amount (2.000) for example would be useful sometimes.

**Comment by ajh0912** [comment]
I agree with @Swoy in that 1,000 characters is quite reasonable for a description.

@KevinMaatman would making a page inside the book and sorting it to the top of the book not be a better solution?

**Comment by ssddanbrown** [comment]
Via the changes in PR #4729, the limit has somewhat been increased, although this is primarily to support the use of more complex HTML content, but generally this allows almost double as much simple content where desired.
Those changes will be part of the next feature release, so I'll therefore close this off.
