### ISSUE TITLE
"new line" in comments does not have any effect

### ISSUE THREAD

**Issue by Stephen-9445** [BookStackApp/BookStack#4097]
### Describe the Bug

When writing a comment and entering a new line, the two lines appear in one single line after the comment is saved.
If the comment is edited again, it appears in two lines.

### Steps to Reproduce

Go to a page.
Add a comment
Write some text
press "Enter"
Write some more text
press "Save Comment"

### Expected Behaviour

The comment should appear in two seperated lines

### Browser Details

Firefox

### Exact BookStack Version

BookStack v23.02 

### Hosting Environment

Docker on Synology DSM7

**Comment by ssddanbrown** [comment]
Thanks for reporting. 
This isn't so much of a technical bug, since it's more of a UX issue maybe. 

The comments input box is technically a mardown input box, and we follow commonmark conventions, so single newlines will be part of the same paragraph. If you separate content out with an empty line between, then they'd be considered two separate blocks paragraphs.

**Comment by Stephen-9445** [comment]
Ok. Understood. Thanks
