### ISSUE TITLE
I upgraded from 21.12.01 version to 23.02.01 version

### ISSUE THREAD

**Issue by Nick390** [BookStackApp/BookStack#4102]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

After I updated, I encountered several problems, the first of which is that there are many differences in the database, as there are tables that have been completely modified or tables that have been added, such as:

- joint_permissions
- permission_role
- role_permission
- role_user
and other

When I did the update, I did not expect this modification to exist, as there was no warning, anywhere as far as I know 
1- Before this process, I made a complete copy of the database and copies of the pictures and attachments folder.
2- I faced many other problems and was able to solve them with the help of documentation and videos I was able to make the system work, but I encountered two problems that I could not solve: 
   -    There is no folders with the name of `bootstrap/cache` or `storage` or `public/uploads`.
   - `/settings/recycle-bin` show `An unknown error occurred`.
   - I cannot upload any file to the system or any image.

### Here is what I try:
- Using the command from [Common Issues & Resolutions](https://www.bookstackapp.com/docs/admin/debugging/#common-issues--resolutions).
- Create folders manually.
- Even the error files are empty.

### System status
Everything works and the data was transferred from the old database to the new manually due to the conflict and everything else works except for what was mentioned above

### Exact BookStack Version

23.02.01

### PHP Version
8.1.16

#### OS
* Ubuntu 20.04.5 LTS 
    * Docker version 20.10.21, build 20.10.21-0ubuntu1~20.04.1
    * Docker-compose version 1.25.0, build unknown
        * BookStack 23.02.01.
        * [Nginx Proxy Manager](https://nginxproxymanager.com/).
        * [Mysql 10.6.12-MariaDB-log](https://mariadb.com/kb/en/mariadb-10-6-12-release-notes/).

#### Hosting
* [Linode](https://www.linode.com/).

For installation I used [docker-compose.yml](https://github.com/linuxserver/docker-bookstack#usage) + Additional lines for Nginx Proxy Manager.

**Comment by ssddanbrown** [comment]
Hi @Nick390,

> When I did the update, I did not expect this modification to exist, as there was no warning

Yeah, database changes are common upon update. We don't publish warnings/advisories for these unless the user specifically needs to know about them for any reason. The changes should be managed as part of the upgrade process, there should rarely ever be a reason to make manual database changes.

> Everything works and the data was transferred from the old database to the new manually 

Be aware, manual changes may impact and cause further issues, especially on future updates.

> There is no folders with the name of bootstrap/cache or storage or public/uploads

There won't be, since you're using a container. Those folders/files are in the container and the linuxserver team maps the required data into places within the `/config` directory that they advise to mount as a volume.

> /settings/recycle-bin show An unknown error occurred.
> I cannot upload any file to the system or any image.

Errors will be logged, Especially if you see the `An unknown error occurred` message.
I made an in-depth video regarding management of the linuxserver container setup here: https://www.youtube.com/watch?v=6A8hLuQTkKQ
This covers updates and other common tasks, showing you exactly what to expect and the steps to take.
Specifically look to around the `7:28` time of the video for details on finding log detail.

**Comment by Nick390** [comment]
From what it became clear to me that I can go back to the old version by do fresh install and then return the data as it is and then use the terminal to upgrade the system to the new version.

But how I go back to 21.12.01 there is no docker image with 21.12.01

**Comment by ssddanbrown** [comment]
I'm not really clear on the state of your instance/setup, it looks like things are getting a bit messy. I also don't really understand what the original issue was before you started making manual database changes.

> But how I go back to 21.12.01 there is no docker image with 21.12.01

You can often find [tagged container images here for various versions](https://github.com/linuxserver/docker-bookstack/pkgs/container/bookstack/versions?filters%5Bversion_type%5D=tagged). I would not continue to attempt to use a manually altered database though, or one that's ran on a more recent BookStack version.
Personally, if possible, I'd restore from a backup then try to upgrade again, assessing the actual errors without trying manual database changes unless absolutely required.

**Comment by ssddanbrown** [comment]
Since there's been no further follow-up I'm going to close this off.
