### ISSUE TITLE
collapsible sidebar sections / Visible scroll

### ISSUE THREAD

**Issue by Skydem** [BookStackApp/BookStack#4119]
### Describe the feature you'd like

On main page with all pages sidebar with “My Recently Viewed”, “Recently Updated Pages”, “Recent Activity” should be collapsible to not view whole list at once. Or maybe show scrollbar to scroll through sidebar. So users with no mouse (with touchpad) can access it easier. I thought about something like that (collapsed):
![obraz](https://user-images.githubusercontent.com/15656898/226336901-d0d5c921-7019-46e4-be64-998bbdcac8bc.png)

After clicking them they should expand:
![obraz](https://user-images.githubusercontent.com/15656898/226337653-148cbddc-9725-4462-b46b-dd78c285deaa.png)

### Describe the benefits this would bring to existing BookStack users

Website would be more accessible for those who can't scroll in different places of website (they are using scrollbar on the right of the screen etc) 

### Can the goal of this request already be achieved via other means?

Adding css to make scrollbar show would be the simplest solution. Collapsing list is also easy task with some JS i think.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

0 to 6 months

**Comment by ssddanbrown** [comment]
Hi @Skydem,
Please see #3789 for a previous discussion in relation to the scroll bar, and a possible workaround you can add to your instance if desired. 

Collapsing elements has been touched upon in #2277 although I'm not too keen for collapsible sections as a solution this described issue, since scroll could still be present with a single sidebar section. I'd stick to showing the scrollbar as above if you really to display it.

**Comment by Skydem** [comment]
Thank you, code mentioned in #3789 solves my problem.
