### ISSUE TITLE
Ability to hide Updated Date on Chapters & add new Date of Review value

### ISSUE THREAD

**Issue by pat-keeley-aurum** [BookStackApp/BookStack#4122]
### Describe the feature you'd like

I have had a request from upper management about some date values on Chapters (Though I am sure this could also be applied to Books/Pages)

More specifically, they were wondering if it's possible to hide the Updated Date value that shows against chapters. 

As well as this, (and a request that seems to already have been suggested at [https://github.com/BookStackApp/BookStack/issues/2123] a new date value that can be manually set called Date of Review which will always be a date in the future. 1st prize would also be to get a webhook or similar to fire off when the Date of Review value is met.

### Describe the benefits this would bring to existing BookStack users

Being able to hide the individual date values against the Books, Chapters and Pages would allow a cleaner UX for people that don't want/need to see it against particular content.

Additionally, as I am sure more firms are picking up Bookstack, an ability to track when we need to review the documentation contained within the platform seems like a good next step. Again, this has already been requested as far as I can tell.

### Can the goal of this request already be achieved via other means?

Unsure.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

1 to 5 years

**Comment by ssddanbrown** [comment]
Hi @patsyk1,
Thanks for the request.

> Being able to hide the individual date values against the Books, Chapters and Pages would allow a cleaner UX for people that don't want/need to see it against particular content.

Although I understand your desire, I can't really follow that benefit reasoning since it'd lead to adding settings to hide every bit of the UI. Instead we provide [a few methods of customization](https://www.bookstackapp.com/docs/admin/hacking-bookstack/).

This is quite a hack (and unsupported so may break on updates), but this may work to hide the updated date when viewing a chapter in the UI. Just add this to the "Custom HTML Head Content" customization setting:

```html
<style>
[option\:entity-search\:entity-type="chapter"] .entity-meta .entity-meta-item:nth-child(2) {
  display: none;  
}
</style>
```

> a new date value that can be manually set called Date of Review which will always be a date in the future.

As you point out, there are existing issues to cover this kind of request. You could just use a tag for this date. If you use integer-based dates (`2306` for June 23 for example) you're then able to filter/sort in [quite advanced ways](https://www.bookstackapp.com/docs/user/searching/#advanced-search-syntax).  

>  1st prize would also be to get a webhook or similar to fire off when the Date of Review value is met.

If you have some PHP skills, it would be possible to [create a custom command using our logical theme system](https://github.com/BookStackApp/BookStack/blob/development/dev/docs/logical-theme-system.md#custom-command-registration-example), to scan across those dates and alert as required, then schedule that command via cron on your system.

**Comment by pat-keeley-aurum** [comment]
Thanks @ssddanbrown - I'll use the hack above and have a play around for the alerting.

**Comment by pat-keeley-aurum** [comment]
Hi @ssddanbrown,

Hopefully a quick one that can also be completed using the Custom HTML Head Content, but is it possible to hide the Created & Updated date on the shelf/book UX?
![image](https://user-images.githubusercontent.com/94916225/231190211-f7d3d06d-e027-4932-bf98-8e7d11490fd1.png)

**Comment by ssddanbrown** [comment]
@patsyk1 

```html
<style>
.grid-card-footer { display: none; }
</style>
```

**Comment by pat-keeley-aurum** [comment]
Thanks @ssddanbrown - much appreciated.
