### ISSUE TITLE
Migrate ownership when deleting user not working

### ISSUE THREAD

**Issue by ChriFo** [BookStackApp/BookStack#4124]
### Describe the Bug

When deleting an (LDAP) user from within bookstack the ownership migration is not working.
After deletion the migrated pages/books/chapters have no owner.

### Steps to Reproduce

1. Select an user from the user list in settings.
2. Click delete.
3. Choose an other user from the dropdown "Migrate Ownership".
4. Click confirm.

### Expected Behaviour

The migrated pages are owned by the selected user.

### Exact BookStack Version

v23.02.1 

### PHP Version

8.1

### Hosting Environment

Alpine-based Docker setup inspired by https://github.com/linuxserver/docker-bookstack

**Comment by ssddanbrown** [comment]
Thanks for reporting @ChriFo.
Can confirm this, and looks like it may have been an issue for a while. 
Caused due to the migration user input not being part of the actual submitted form. Have fixed this, and tweaked our testing slightly to cover this scenario, within commit 0e43618dda5564da7b136c9c3d6b5ef3408dc494.

This will be part of the next feature release.
