### ISSUE TITLE
Won't Receive Email Confirmations or Test Emails from BookStack

### ISSUE THREAD

**Issue by carlossierra311** [BookStackApp/BookStack#4137]
### Describe the Bug

When users try to register to the app, they aren't getting the registration confirmation emails. When I try to Send a Test Email from the Maintenance section, I don't get the email either, even though I get a message saying that the email was sent successfully: 
![image](https://user-images.githubusercontent.com/23511373/228048793-3680092b-e96f-4760-8e72-9f6474679337.png)

There are no messages on BookStack's or Nginx's error logs. 

### Steps to Reproduce

1. Configure BookStack's .env file with the following values: 
```
MAIL_DRIVER=smtp
MAIL_FROM_NAME="BookStack Admin"
MAIL_FROM=from_email@mailserver.com
MAIL_HOST=smtp.mailserver.com
MAIL_PORT=587
MAIL_USERNAME=from_email@mailserver.com
MAIL_PASSWORD=my_password
MAIL_ENCRYPTION=tls
```
2. Try to register a new user or send a test email. 
3. Trying different combinations of values for MAIL_PORT (465 and 587) and MAIL_ENCRYPTION (tls, ssl or null) won't work either, no matter how I try to combine these values. 

### Expected Behaviour

Me and the users get BookStack's notification emails. 

### Screenshots or Additional Context

I can send an email with the same parameters, from the same server, using PowerShell: 
```
$EmailFrom = “from_email@mailserver.com”
$EmailTo = “to_email@mailserver.com”
$Subject = “BookStack Test”
$Body = “This is just a simple test... 1, 2, 3 :)”
$SMTPServer = “smtp.mailserver.com”
$SMTPClient = New-Object Net.Mail.SmtpClient($SmtpServer, 587)
$SMTPClient.EnableSsl = $true
$SMTPClient.Credentials = New-Object System.Net.NetworkCredential($EmailFrom, “my_password”);
$SMTPClient.Send($EmailFrom, $EmailTo, $Subject, $Body)
```

### Browser Details

Chrome 111.0.5563.65 (Build oficial) (64 bits) on Windows 10

### Exact BookStack Version

BookStack v23.02.2

### PHP Version

8.1.10

### Hosting Environment

Windows Server 2019 Standard v1809, OS build 17763.3406
32 GB Ram, Intel Xeon E3-1230 v5 @3.4GHz

BookStack installed manually by following [these steps](https://www.bookstackapp.com/docs/admin/installation/#manual), using the following components:
php-8.1.10
mysql-8.0.30
nginx-1.23.1

**Comment by ssddanbrown** [comment]
Hi @carlossierra311, 
There might be little I can address or do to diagnose from the BookStack side of things.
Every case I've seen before, where the test runs without error on the BookStack side, has been a mail-server-side issue (Spam filtering, faulty routing etc...). I would expect an error here if being completely rejected by the SMTP server, or if there's an issue in communication to that point.

Since you've done that powershell test, I can only think maybe the exact communication performed, or the difference of content (BookStack will use a multipart message with HTML and text) might be causing the message to be handled differently mail-server-side.

**Comment by carlossierra311** [comment]
I made some test with a Gmail account, and I was able to send notifications from BookStack. Seems like you are right. I'll keep looking for the problem. Thanks @ssddanbrown
