### ISSUE TITLE
No search result at \\Server-123\FolderA\Folder1\

### ISSUE THREAD

**Issue by LHBL2003** [BookStackApp/BookStack#4175]
### Describe the Bug

We have texts like

\\Server-123\FolderA\Folder1\ on some pages

If you search for \\\\Server-123 you get a result.

If you search for \\Server-123 or Server-123 or FolderA you get no result.

### Steps to Reproduce

- create a page with Text: \\Server-123\FolderA\FolderB\
- Search for this text or the components of the characters \ 
E.g. Server-123 or FolderA or \\Server-123

### Expected Behaviour

One finds what one seeks.

### Browser Details

Windows 10, Chrome

### Exact BookStack Version

23.02.1

### Hosting Environment

Ubuntu 22.04 LTS

**Comment by ssddanbrown** [comment]
Thanks for reporting @LHBL2003, Now addressed as part of #4202 and the subsequent work.
Will be part of the next release.

As mentioned in that thread, any non-prefix matching of words/strings will need to be done with quotes to use exact term matching (`\FolderA\` for example) since normal terms are prefix-only matching.
