### ISSUE TITLE
why is there no easy way to install

### ISSUE THREAD

**Issue by inikishev** [BookStackApp/BookStack#4183]
### Describe the feature you'd like

i want to install but I don't understand this page https://www.bookstackapp.com/docs/admin/installation/ and why can't there just be an exe file?

### Describe the benefits this would bring to existing BookStack users

it would make it so that actual people could use this as well

### Can the goal of this request already be achieved via other means?

No

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

Not using yet, just scoping

**Comment by ssddanbrown** [comment]
Hi @stunlocked1,

BookStack is primarily built as web/server software. We don't build it for any specific platforms, although we do provide Ubuntu LTS scripts to help install since that's a common environment.

BookStack itself is not written in a language that generally is compiled to an exe, and relies on other seperate applications.
While it may be possible to somehow bundle these to a single exe and distribute, I'd worry that could introduce licensing considerations, and it would be a complex process (especially to maintain) which I don't see as worthwhile to spend our time since Windows is a less popular target for this kind of software.

I've going to close off this request as out of scope.
