### ISSUE TITLE
LastPass preventing to access top right menu

### ISSUE THREAD

**Issue by crystalin** [BookStackApp/BookStack#4203]
### Describe the Bug

Just did my first installation.
On the main page, I cannot click on the top right buttons.

See the html element that seems to overlay the buttons preventing to click on them
<img width="1447" alt="image" src="https://user-images.githubusercontent.com/329248/234694576-4e70ecdc-2dba-4399-b4c6-3bfadc783abc.png">

(Removing this lastpass element in the console allows to click on the buttons again)

Refreshing the page doesn't help.
This is the first time (in years) I have such an issue on a website with LastPass so I'm reporting it here

### Steps to Reproduce

Install with the script on ubuntu 22
Add Google Project ID/Secret (not sure if this is needed)
Edit profile (name, image, connect Google)
Go back to main page

### Expected Behaviour

Being able to click on buttons

### Browser Details

Chrome

### Exact BookStack Version

v23.02.3

### Hosting Environment

Ubuntu 22.04

**Comment by ssddanbrown** [comment]
Hi @crystalin,
I suggest maybe disabling lastpass on your BookStack site/domain if possible.
Alternatively, you can add something like the below to the BookStack "Custom HTML Head Content" customization setting to prevent the element being active:

```html
<style>
[data-lastpass-root] {display:none !important;}
</style>
```

I'm guessing it's trying to show a view in an iframe but the [CSP rules](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-src) that BookStack enforces is blocking the lastpass frame from loading (Since it's rightfully seen as non-trusted content). 
As a third option, You could add the extension address to BookStack's `ALLOWED_IFRAME_SOURCES` option [as detailed here](https://www.bookstackapp.com/docs/admin/security/#iframe-source-control) which might let that load but I've never tested that with extensions.

Otherwise, I'm not really willing to build-in or maintain workarounds in the core system for plugins/extension that will try to inject their own content into a page in their own way.

**Comment by crystalin** [comment]
It makes sense, thank you for the quick response.
I reported it cause I've never seen such a behavior on another website and thought it could reflect a bad UI element on the page.

Using
```
<style>
[data-lastpass-root] {display:none !important;}
</style>
```
works
