### ISSUE TITLE
Login method selector when using third party authentication

### ISSUE THREAD

**Issue by mbsimulations** [BookStackApp/BookStack#4213]
### Describe the feature you'd like

When using third party authentication options like Azure AD the default login fields username and password shoul be hidden and a prompt should show up to choose which authentication method the user wants to use.

### Describe the benefits this would bring to existing BookStack users

Better user experience when users can select their preferred login method and not being misled by the integrated login option which would not work if the user is only registered via his specific login method. Also the admin still has the possibility to easily login via the builtin login.

### Can the goal of this request already be achieved via other means?

Partly by selecting the method to use but it can be misleading in environments where only third party logins are being used

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

6 months to 1 year

**Comment by ssddanbrown** [comment]
Closely related to #1090, may consider these close enough to be duplicate, since this kind of approach somewhat requires a change of design intent of the social providers essentially acting as primary options instead of additive to the primary auth option. 

@mb-simulations Based upon the information above, for your particular use-case, do you happen to use just the AzureAD provider alone?

**Comment by mbsimulations** [comment]
Yes, I enabled auto registration for the Azure AD provider which is the only method of authentication that is allowed to be used in this specific deployment. I have seen the issue you mentioned but did not consider it a duplicate because I still want to be able to select the default login provider as a fallback for the admin user. But it should not be the main thing advertised to the user that is trying to login.

**Comment by ssddanbrown** [comment]
Okay, I will close this off as already covered by #1090. I don't feel it's worth specifically supporting something for an admin fall-back as I'm sure whatever option added for #1090 would be revert-able, at least for temporary admin access. 

There are some CSS workarounds in that other thread, that could be used to hide the default auth method.

> Yes, I enabled auto registration for the Azure AD provider which is the only method of authentication that is allowed to be used in this specific deployment.

For this type of scenario, you might find [OIDC](https://www.bookstackapp.com/docs/admin/oidc-auth/) to be a much better fit, since you'll also get a single-click (Or no click/auto) login, group sync and no default login option.
I recently made a guide specifically for AzureAD here: https://www.youtube.com/watch?v=CL5kMFkopHY

**Comment by mbsimulations** [comment]
Thank you very much for the helpful advice. I tried OIDC today and it worked like a charm. Exactly what I was looking for!
