### ISSUE TITLE
How to get the number of pages in exported PDF?

### ISSUE THREAD

**Issue by Bouni** [BookStackApp/BookStack#4231]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

I already modified the PDF export with the help of a custom theme and the [gist](https://gist.github.com/ssddanbrown/bcc9d2e73ec8144a7f4807fd10ddc863) of @ssddanbrown as a starter.

He shows how to get the page number via CSS:

```css
.print-page-number:after {
        content: "Page "counter(page);
}
```

This gives just `Page 1` for example but I would like to have `Page 1 of 3` for example.

Any hints how to get the total number or where to look for examples?

### Exact BookStack Version

v23.02.3

### Hosting Environment

Docker container (lscr.io/linuxserver/bookstack)

**Comment by ssddanbrown** [comment]
From what I remember, there's no way to include the total as part of that, since it's being generated as the PDF rendering is going from start to finish, so there's no idea of total pages until the end. There might be some external ways to add such a number in, but nothing I know of that I can provide as a quick hack.

**Comment by Bouni** [comment]
OK, thank you for the quick reply anyway 👍🏽
