### ISSUE TITLE
Ability to hide "Details" including "Recently Viewed", "Popular Books", and "New Books"

### ISSUE THREAD

**Issue by travisfont** [BookStackApp/BookStack#4255]
### Describe the feature you'd like

Simply put, it would hide these sections from users. This can be controlled through user group permissions.

### Describe the benefits this would bring to existing BookStack users

**_Privacy_**

### Can the goal of this request already be achieved via other means?

With quite a bit of CSS tweaking (one could consider this hacking the layout), but this does not actually hide the information from users (specifically guest and search engines) through HTML source code.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

1 to 5 years

**Comment by ssddanbrown** [comment]
I generally try to avoid adding any kind of granular settings/options that relate specifically to UI elements such as this in the interest of maintainability. For this kind of thing, the [visual theme system](https://github.com/BookStackApp/BookStack/blob/development/dev/docs/visual-theme-system.md) is the advised approach.

I'm going to close this off due to the above, and since I feel this is generally already covered by #1291.
Feel free to comment though if you need any pointers in regards to the visual theme system.
