### ISSUE TITLE
Install BookStack on Synology NAS

### ISSUE THREAD

**Issue by techauthoruk** [BookStackApp/BookStack#4257]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

Hi

I am trying to create a backup install of my main BookStack install on a Synology DS414j NAS. I have two real questions:

+ 1. How to install BookStack on the NAS
+ 2. How to 'mirror' my server install to the NAS so they are synchronised

Question 1: I have updated the NAS to the latest allowed DSM version (DSM 7.1.1-42962 Update 5), and updated Web Station. I have also installed PHP 8.0. However, all the tutorials I have found say to install Docker or Portainer to get a working BookStack install.

My problem is that neither package are available (as far as I can see), so I can't even set up a container to install BookStack to! Has anyone recently managed to create a BookStack install on this NAS?

Question 2: Regardless of whether I get the NAs install working, what is the best way of synchronising two installs? Cani I rsync the install from one device to another? Can I restore an sql dump and restore the images, etc? I am mindful of the fact that the .env settings for the db may be different. I am no expert on this stuff, so would welcome some pointers.

Mark

### Exact BookStack Version

Latest version

### PHP Version

8.x

### Hosting Environment

Server - Ubuntu 22.04LTS
NAS....?

**Comment by ssddanbrown** [comment]
Hi @techauthoruk

> My problem is that neither package are available (as far as I can see), so I can't even set up a container to install BookStack to!

Yeah, the lower value range of Synology boxes (Which I think are those with `j` at the end of the model name) won't have certain packages due to system limitations.

> Has anyone recently managed to create a BookStack install on this NAS?

It likely is possible to get it running, but it might be messy to do outside of docker due to the requirements needed. It's not really what a Synology NAS is suited for tbh.

> Regardless of whether I get the NAs install working, what is the best way of synchronising two installs? Cani I rsync the install from one device to another?

What is your actual goal in this? There are methods but no easy way for a bi-directional sync. 
For a single-direction sync you can indeed dump the database and copy the files over.
Our [backup and restore](https://www.bookstackapp.com/docs/admin/backup-restore/) docs detail the mechanics of this.

As an easier potential option, The [latest release includes a system CLI](https://www.bookstackapp.com/blog/bookstack-release-v23-05/#new-system-cli-early-alpha) that allows potentially easier backup/restore. It's in early alpha and can still be subject to bugs/issues, but it automates and standardises a lot of the process in the docs linked above. 
I'm not confident it'd run without some pains on a Synology system though.

---

Personally, through experience I've found it's more hassle than it's worth to stretch the use-case of something like a Synology box, which ideally you'd want to remain reliable in it's primary purpose. You'd be going against the grain and there'd be little existing guidance/docs/experience to help when you run into issues (as you're finding now).
I have a separate little intel NUC box to run apps, running proxmox to separate/compartmentalise things via VMs or LXC containers. [I have a little overview of my setup here](https://danb.me/blog/my-2023-homelab-setup/).

If you just need to have a backup of your system though, you could maybe just look to use the new BookStack system CLI to create backups then store the resulting ZIP on your NAS like any other file.

**Comment by techauthoruk** [comment]
@ssddanbrown thank you for all your comments.

I have abandoned the idea of using the Synology now - there is just no reliable way to get Docker installed. My goal was actually to have a replica of my main bookstack instance installed elsewhere for reference. The sync would only ever be one way (main instance to backup).

The reason behind this - I keep all my notes and instructions for the management of my software apps in bookstack. My server went down a few days ago, and of course I couldn't access my notes to do reinstalls, etc! I wanted a backup on another machine/device so that I could see my notes while I sorted the issues. I do routinely back up the bookstack instance in line with the comments on your site, so it's not a problem restoring bookstack if needed.

I tried this morning restoring the sql backup from my main instance into a bookstack install on another machine, but this didn't work - I get a 419 error when trying to log in. I'm going to play around a little more to see if I can find out why.

Thank you again for your comments.

**Comment by techauthoruk** [comment]
OK, so resolved now.

My 419 issues seemed to be due to an incorrect database pasword. Changed the password, and everything is working as it should, so closing this.

**Comment by akahan989** [comment]
Well, I'm using Bookstack on Synology NAS, Using Docker(install at Synology Package Center), portainer(portainer/portainer-ce), nginx proxy manager(jc21/nginx-proxy-manager) and bookstack(linuxserver/bookstack). It works very well...

I don't have backup devices so I can't test mirror my bookstack(or NAS), but I think Synology High Availability can do it.
