### ISSUE TITLE
BookStack as a VM on Hyper-V, How Much Storage?

### ISSUE THREAD

**Issue by jimmie-jam** [BookStackApp/BookStack#4288]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

This is really a question rather than an issue. I watched @ssddanbrown tutorials on installing BookStack in Ubuntu 20.04 on a Linode server, and he chooses the lowest plan which is about 50GB of storage. I have created mine on a Hyper-V Server with 80GB of disk space? This is going to be used as a digital notebook for every project we do. We are a paint manufacturer and craft tons of specials for customers that require pages of documentation (including photos). We plan on using this year after year from here on out so that we can maintain historical data. Is 80GB enough? What does everyone recommend for something that could potentially grow pretty large?

Thanks in advance! BookStack is, without a doubt, the absolute best locally hosted solution out there for this. And Dan offers it for free! I am such a fan boy now!

### Exact BookStack Version

BookStack v23.05.2 

### PHP Version

8.2

### Hosting Environment

Ubuntu 20.04 
Dell PowerEdge Server using Hyper-V
Windows Server 2019

**Comment by ssddanbrown** [comment]
Hi @jimmie-jam, thanks for the kind comments!

> Is 80GB enough? What does everyone recommend for something that could potentially grow pretty large?

It massively depends on usage patterns, active users, and the files & images you upload.
80GB seems like a reasonable starting point. For any of my own previous use-cases of BookStack, that would take many years to get to.

My advice would be to start with that amount, record the current free disk space, then check on it again after a few months to see how things are scaling to get an idea of how fast you'd eat storage.

Since you're virtualizing, I'd have thought scaling up shouldn't be a significant problem if needed anyway? 
Will depend on your environment and hardware though.

**Comment by jimmie-jam** [comment]
@ssddanbrown,

You are the best!!! Thanks for the recommendations and best practices. It will be roughly 8 users, with 3-4 additional "viewers." I'm really going to limit the size of images and have some methods that the users can employ to keep photos light. But for the most part, text and table data would be the bulk of the content. 

I like your suggestion to check in every couple of months to gauge usage. Superb idea!

Thanks so much again!

**Comment by ssddanbrown** [comment]
Happy I could help! Will therefore close this off.
