### ISSUE TITLE
Support for proxy auth via env vars or use basic auth

### ISSUE THREAD

**Issue by buzzzo** [BookStackApp/BookStack#4295]
### Describe the feature you'd like

Would be useful to let user authenticate via env vars like REMOTE_AUTH (set by a reverse proxy).
This permits some sso products to be used with bookstack.

Also enable basic auth and not only via forms would be useful.

Thx

### Describe the benefits this would bring to existing BookStack users

Permit the usage of external auth setup by a sso manager like authelia or lemonldapng

### Can the goal of this request already be achieved via other means?

Not afaik

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

Not using yet, just scoping

**Comment by ssddanbrown** [comment]
I likely wouldn't look to add additional auth mechanisms at this point, as we already support a wide variety and auth systems have a relatively high cost. 

If you need just plain basic auth, you can often add this at the webserver/proxy level.

Otherwise, you might be able to achieve other options using our [logical theme system](https://github.com/BookStackApp/BookStack/blob/development/dev/docs/logical-theme-system.md).
I have an example of authenticating by HTTP header here:
https://github.com/BookStackApp/BookStack/pull/2289#issuecomment-857164663
That may be tweakable to your requirements.

**Comment by ssddanbrown** [comment]
Since I wouldn't look to specifically support the requested auth method, and since some alternatives have been posted above, with no further follow up, I'll go ahead and close this off.
