### ISSUE TITLE
Support for cloud version of diagrams.net

### ISSUE THREAD

**Issue by davidmlafuente** [BookStackApp/BookStack#4340]
### Describe the feature you'd like

It would be awesome if we can integrate de cloud version of diagrams.net (the one that integrates with google drive) with bookstack.

### Describe the benefits this would bring to existing BookStack users

Those users that has google workspace and uses google drive for storing diagrams, can attach and preview their existing diagrams inside bookstack.

### Can the goal of this request already be achieved via other means?

Yes, for now, we can use an external link to the diagram (without any kind of preview) or we can just copy the entire diagram into a new one (at this point, both diagrams starts to be different)

### Have you searched for an existing open/closed issue?

- [x] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

0 to 6 months

### Additional context

We are starting to use bookstack and we usually store this kind of files into google drive. We want to keep the diagrams stored in google drive, because there some people without access to bookstack that needs to see the diagrams, and these diagrams are in constant evolution.

**Comment by ssddanbrown** [comment]
Adding the below to your `.env` will enable some google-specific features in the embedded view (import/export via drive):

```bash
DRAWIO=https://embed.diagrams.net/?embed=1&proto=json&spin=1&configure=1&gapi=1
```

But this will still be awkward in terms of the integration with BookStack.

Otherwise, I'm not too sure how much more is possible, or how much more we'd be willing to do to specifically support a flow here. I don't really want to get into needing to support use of specific third-party proprietary storage platforms.

**Comment by ssddanbrown** [comment]
I'm going to go ahead and close this off as out of scope since, as explained above, I'm not sure how much more we can do without specifically supporting additional external services.
