### ISSUE TITLE
Irrelevant errors after successfully uploading a DOCX file using drag & drop 

### ISSUE THREAD

**Issue by merrime-n** [BookStackApp/BookStack#4388]
### Describe the Bug

As of the implementation of the [WYSIWYG Docx Import](https://www.bookstackapp.com/hacks/wysiwyg-docx-import/) which was launched in [v23.06.2](https://github.com/BookStackApp/BookStack/releases), working with DOCX files has been considerably easier; but there are still some issues.

In spite of being said that "_These hacks are unsupported customizations meant as unofficial workarounds_", I think fixing this issue can be a huge improvement.

After uploading the DOCX file, the contents of the file is migrated successfully but some irrelevant errors pops up. (screenshots included) 

### Steps to Reproduce

1. Open a new page.
2. Drag & drop a DOCX file.
3. The migration is successful but there are some errors shown on the screen that are frustrating.

### Expected Behaviour

I expect the migration to be clean and easy. After uploading the DOCX file, I don't want to encounter any errors.

### Screenshots or Additional Context

![photo_2_2023-07-18_15-37-29](https://github.com/BookStackApp/BookStack/assets/100111649/711ee0c1-76fc-4123-a5ab-d66ca4fdc136)

### Browser Details

Google Chrome Version 104.0.5112.102 (Official Build) (64-bit) On Windows 10

### Exact BookStack Version

v23.06.2

### Hosting Environment

Ubuntu 20.04 VPS, deployed on docker.

**Comment by ssddanbrown** [comment]
As per the warning you quoted from our hacks site, these things are not considered officially supported parts of BookStack and therefore I'm not looking to service issues for these in this repo.

The warnings are advised within the considerations for the hack. Additionally, there will always be issues and edge-cases in this kind of functionality. There are reasons this is provided as a hack instead of being built into the platform.
