### ISSUE TITLE
Reusing whole pages

### ISSUE THREAD

**Issue by grheine** [BookStackApp/BookStack#4392]
### Describe the feature you'd like

In bookstack it is possible to reuse books on multiple shelves. It would be helpful if this is also possible for pages, such that a page can be reused within multiple books. 

### Describe the benefits this would bring to existing BookStack users

Adding a feature to reuse page content within several places in Bookstack would bring several benefits:

1. **Consistency**: Reusing pages would ensure consistent information across multiple shelves, books, and chapters. Any updates or changes made to a page would automatically reflect in all instances where it is reused, reducing the risk of outdated or conflicting information.

2. **Time-saving**: Content creators and editors would save time by not having to duplicate content manually across different areas. They could create a central page for a specific topic and reuse it wherever necessary, streamlining the content creation process.

3. **Space-efficient**: Reusing pages reduces redundant storage of similar or identical information. This can be especially beneficial when dealing with large amounts of content, as it optimizes storage resources.

Overall, enabling the reuse of page content within Bookstack wikis would improve efficiency, maintainability, and consistency, making it a valuable feature for content creators and readers alike.

### Can the goal of this request already be achieved via other means?

Yes and no. There is the option to reuse page content. However, when copying a complete page via the page ID the preview in the book above does not show content.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

0 to 6 months

**Comment by ssddanbrown** [comment]
Thanks for the request @grheine, but I'd consider this to be already open in #182 so I'll close this off.

Please don't use LLMs/AI to fill any issue reports here in future (It's quite clear it has been used to generate the benefits). The question is there to make folks think about the actual user benefits in regards to BookStack and their own use-cases.

**Comment by grheine** [comment]
Hi Dan, 

Thank you for the fast reply. Since the original issue is from 2016 I assume you will not implement it? For our organisation (physics institute) it would be a crucial feature to use Bookstack for our wiki since we have a lot of articles that occur in different contexts such as an overview of our computing resources and accounts that should be found under onboarding but also in our book regarding the computing resources or pages containing onboarding specifics that are the same for Bachelor/Master students or PhDs which are different onboarding books. 
Since I am a physicist at the beginning of my PhD, I am unfamiliar with IT jargon. This is the reason I used ChatGPT to help me with the formulation of the points that I came up with by myself. If you want people to explain specific examples or use-cases maybe you should add this to the description of the text field instead of „measurable benefits“. But maybe I am the only one misinterpreting this field. 

Bests, Greta

**Comment by ssddanbrown** [comment]
> Since the original issue is from 2016 I assume you will not implement it?

I wouldn't say I will not implement it, but I have no current plans to move forward with that.

> For our organisation (physics institute) it would be a crucial feature to use Bookstack

Okay, in that case it sounds like BookStack, as provided, may not be suited for your organization.

> This is the reason I used ChatGPT to help me with the formulation of the points that I came up with by myself.

In that case I'd prefer you just provide your original points, otherwise in my view your points are just getting diluted in a mass of machine text.

**Comment by jlevitsk** [comment]
I also had a use for this if you ever were to implement it. I have a Book where I have recipes to install macOS software. I have another one for iOS and yet another for Windows. Sometimes there is a macOS/iOS article that would make sense to have as one article and sometimes a macOS/Windows one makes sense. Because I can't have 1 Page or 1 Chapter live in multiple Books I basically always split up the articles and then at the bottom have a link mentioning the other. Because my company makes a cross platform endpoint management system we frequently have topics that could exist in more than one Book. Where possible if a whole topic needs to be in multiple places I just make a Book of the topic and then put that in the different Shelves.

**Comment by robing29** [comment]
This feature is desirable for us as well. We use the wiki for manuals regarding processes in our ERP system. We want to use a book "Tutorials/Processes" that contains every process that we have defined. Then we want to use the pages in our different books, so that each unit can access these pages at the desired place.

This would make it easier for our Quality Assurance, as they can then follow the "Tutorials"-Book and see any change that is being made at a different place for a page. Basically, this would allow central management of pages that are useful in many different books and chapters, as we try to make these books as close to the process as possible.
