### ISSUE TITLE
Abillity to control the session duration when editing pages (due to session expiered when editing a graph in drawio)

### ISSUE THREAD

**Issue by alonohana627** [BookStackApp/BookStack#4441]
### Describe the feature you'd like

I would like to add a setting that is able to extend the duration of a session of creating a page/editing a page, due to session expiring when entering drawio. 

### Describe the benefits this would bring to existing BookStack users

This will make stupid people like me not losing their work if they've left their PC on drawio session without saving. I lost tons of work due to that :(

### Can the goal of this request already be achieved via other means?

I dont believe so.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundemental request

### How long have you been using BookStack?

0 to 6 months

**Comment by ssddanbrown** [comment]
Hi @alonohana627,
Please see the "Session Timeouts" part of our documentation here:
https://www.bookstackapp.com/docs/admin/cache-session-config/#session-timeouts
Additionally, as per #4421, I plan to soon add a browser-side backup mechanism to help prevent potential loss of drawing content.

Since we already provide an option, and since we also have #4421 to help the specific scenario, I'll close this off but feel free to still comment if required.
