### ISSUE TITLE
Translation: Norwegian Nynorsk

### ISSUE THREAD

**Issue by ghveem** [BookStackApp/BookStack#4447]
### Language to Add

Norwegian Nynorsk (nn-NO)

### Confirmation of Intent

- [X] I confirm I'm offering to help translate for this new language via Crowdin.

**Comment by ghveem** [comment]
Please clone https://crowdin.com/project/bookstack/nb to https://crowdin.com/project/bookstack/nn.

**Comment by ssddanbrown** [comment]
Thanks @ghveem for offering to translate,
I've now enabled Norwegian Nynorsk on Crowdin. 
If there's little activity on the language after a while I may remove it again rather than leave an incompletely langauge in our translations.

> Please clone https://crowdin.com/project/bookstack/nb to https://crowdin.com/project/bookstack/nn.

Are you saying you'd like this to start from the Bokmål translations? Is that better than the original English to start from?
I personally have no idea about these two languages. I can copy over the Bokmål text to Nynorsk to start with, but it may be more difficult to then see any text that has not been specific translated for Nynorsk. 

If you would like my to copy over the Bokmål text first, please let me know and wait before starting any translations, since it's likely I'd overwrite any changes in the process.

**Comment by ghveem** [comment]
Nn and nb are almost as British English related to American English. I think it will be most effective to start with a clone from nb.

**Comment by ssddanbrown** [comment]
@ghveem Okay, thanks for the info. I've now copied the existing nb translations for nn. Should now be ready to translate!
I'll therefore close this off.
