### ISSUE TITLE
Markdown export with API has HTML inside

### ISSUE THREAD

**Issue by andreapx** [BookStackApp/BookStack#4452]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

I have a page with a table in it. I've exported it in a markdown format (with the API) and I see that the table is in HTML format.
Why?
Thanks!

### Exact BookStack Version

v23.06.2

### Hosting Environment

Ubuntu 22.04 using the official Docker container image.

**Comment by ssddanbrown** [comment]
The conversion may fall back to HTML for a range of things that may not be supported by the converter or within markdown/commonmark.

Look like the underlying converter library we're using does have support for tables, but since HTML tables can be complex it cannot correctly handle more complex scenarios. If it was just a case of loosing formatting I'd probably look to add the conversion but loss can be structural here for table content, so I'd feel uneasy adding conversion in this case.

**Comment by ssddanbrown** [comment]
Just to add, if the page was written with markdown, and markdown tables are used while editing, then you should still get markdown tables in the export.

**Comment by andreapx** [comment]
> Just to add, if the page was written with markdown, and markdown tables are used while editing, then you should still get markdown tables in the export.

Thanks for your fast reply!
How can I select markdown instead of rich text? I'm using WYSIWYG.

**Comment by ssddanbrown** [comment]
You can switch via the draft controsl while editing a page, if you have permission. Or new pages will use the markdown editor if that's the default option set in app settings.

I show switching editors in my video here from about 1:42: https://youtu.be/R3RuxqV01yk?t=99

**Comment by andreapx** [comment]
Oh, I see, I thought that the WYSIWYG could write in markdown, not that I had to use markdown myself.
Thanks for the clarification.

**Comment by ssddanbrown** [comment]
Happy to clarify.
I'll therefore close this off.
