### ISSUE TITLE
Cannot send mails via MS365 with modern authentication

### ISSUE THREAD

**Issue by Man-in-Black** [BookStackApp/BookStack#4455]
### Describe the Bug

I wanted to use the email notifications to send updated to my mail if there are some changes.
But I wasn't able to get it to work with our MS365 accounts, where Microsoft disabled basic authentication.

### Steps to Reproduce

1. set the smtp setting in the .env file with the MS365 account
2. try to send a mail

### Expected Behaviour

After I added the setting the mail should be delivered

### Screenshots or Additional Context

error-notification:

`Error sending a test email: Failed to authenticate on SMTP server with username "x@y.com" using the following authenticators: "LOGIN", "XOAUTH2". Authenticator "LOGIN" returned "Expected response code "235" but got code "535", with message "535 5.7.139 Authentication unsuccessful, the request did not meet the criteria to be authenticated successfully. Contact your administrator. [FRxxx.DEUPxxx.PROD.OUTLOOK.COM 2023-08-22T11:44:59.154Z 08DBA260ED29A18C]".". Authenticator "XOAUTH2" returned "Expected response code "235" but got code "535", with message "535 5.7.3 Authentication unsuccessful [FRxxx.DEUPxxx.PROD.OUTLOOK.COM 2023-08-22T11:45:13.339Z 08DBA260ED29A18C]".".`

### Exact BookStack Version

v23.06.2

### Hosting Environment

Ubuntu 22.04, installed using official installation script

**Comment by ssddanbrown** [comment]
Thanks @Man-in-Black, but I'm going to recategorise this as a feature request rather than a bug since it's not really a bug in existing functionality we support, but a request for us to support a new authentication mechanism.

I haven't looked too deep into oauth & SMTP, but I'm worried it'd require per-service OAuth handling to properly support which is really not something I'd like to increase our scope to as it becomes a significant burden, I'd rather stick to complete standards. I may need to investigate further to confirm this is the case.

From helping folks in the past on this, I believe [there are ways](https://learn.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/authenticated-client-smtp-submission#enable-smtp-auth-for-specific-mailboxes) to enable SMTP auth for specific mailboxes depending on environment settings, which may be an option here.

**Comment by Man-in-Black** [comment]
Hi @ssddanbrown
Thanks for the hints, I already did this with the SmtpClientAuthenticationDisabled, but with no luck. The error I posted was generated after I set this.

I'm using another software which is making use of the Graph API vom Microsoft as described here:
https://community.lansweeper.com/t5/reporting/use-a-microsoft-cloud-services-application-to-send-helpdesk-and-email/ta-p/64540
With this settings I was able to send and receive mails over Microsoft 365 wihtout an interactive popup after and ignoring the MFA settings.
Maybe this helps in investigating this.

**Comment by ssddanbrown** [comment]
> Maybe this helps in investigating this.

Thanks. From that link, that service has specific documentation and uses a specific custom protocol/API for Microsoft, which is exactly the route I'd want to avoid as described above.

**Comment by AvrumFeldman** [comment]
@Man-in-Black to use SMTP auth with o365 you need to enable per user MFA and create an app password. 

You also need to make sure SMTP auth is enabled on the mailbox/tenant.

**Comment by Man-in-Black** [comment]
It was that simple... Thanks a lot @AvrumFeldman
I simply forgot the existence of the app passwords.

I will close this issue.
