### ISSUE TITLE
[Support] Adding other media uploads

### ISSUE THREAD

**Issue by spaceraccoon** [BookStackApp/BookStack#450]
Thanks for an amazing app, Dan! I've created an instance and am planning to modify Bookstacks by adding an audio upload function (e.g. audiobooks) to the page editor. I know there's already an attachments function, but I want something similar to the image upload. Before I begin modifying it, where would be a good place to start/duplicate?

**Comment by ssddanbrown** [comment]
Hi @spaceraccoon, Thanks for the kind words.

If you want something like the image uploader then copy things named `image-manger` would be a start. As a warning though, The JavaScript behind these systems is due to change a lot soon so changes you do now may become outdated soon and hard to integrate with updated versions of the app in the future.

Out of interest, What would the benefit be over the attachments feature?

**Comment by spaceraccoon** [comment]
Hi Dan,

Thank you, I just went with implementing Laravel File Manager and
integrating it with TinyMCE. I want to have the audio player within the
page itself.

**Comment by ssddanbrown** [comment]
Okay, Cool, I'll therefore close this issue.
