### ISSUE TITLE
Comment notification settings are visible even if comments are disabled

### ISSUE THREAD

**Issue by helmut72** [BookStackApp/BookStack#4508]
### Describe the Bug

Comment notification settings are visible even if comments are disabled:

> notify upon comments...
> notify upon replies to my comments...

### Steps to Reproduce

1. disable comments (admin user)
2. go to: preferences -> notifications -> manage

### Expected Behaviour

If comments are disabled, comment notification options should be invisible

### Exact BookStack Version

23.08

### PHP Version

PHP 8.1

### Hosting Environment

selfhosted Docker

**Comment by SirTwinkleberry** [comment]
Shouldn't the setting stay visible in case comments get enabled some time later?

**Comment by ssddanbrown** [comment]
Thanks for raising @helmut72.

> Shouldn't the setting stay visible in case comments get enabled some time later?

I'd say it's probably better UX to hide options for something if users don't have access to the features they interplay with, since this may lead to users questioning where how to use comments on a system that disables them.

I've categorized to a UX enhancement, since this isn't a break in existing functionality or a functional issue, mainly a UX improvement to be made, and I've assigned to the next feature release.

**Comment by tusharnain** [comment]
@helmut72 I have created a PR to fix it, please review it, i am new to open source.

**Comment by ssddanbrown** [comment]
This has now been addressed via #4552 thanks to @tusharnain4578, and will be part of the next feature release.

**Comment by helmut72** [comment]
@tusharnain4578 Thanks! Unfortunately I can test it earliest next week, but looks like it works if I understand Dan.

**Comment by ssddanbrown** [comment]
@helmut72 Yeah, it's all done, don't worry about spending time to test it.
