### ISSUE TITLE
Minimum DB User Privileges to run app

### ISSUE THREAD

**Issue by salimnanji** [BookStackApp/BookStack#451]
A question for you, potentially an update for your documentation as well. What are the minimum privileges granted to the main app DB user to use the application?

![image](https://user-images.githubusercontent.com/12036621/28584057-4b91d758-7139-11e7-80e7-2315f436b081.png)

**Comment by Shackelford-Arden** [comment]
@salimnanji Not sure if this is what you're looking for, but looking at the Ubuntu 16.04 script linked in the installation instructions, here is what I see for permissions granted to the user.

![image](https://user-images.githubusercontent.com/7362263/28585316-8d4d4b4a-7135-11e7-8658-518aabe9bb67.png)

Hope that helps!

**Comment by salimnanji** [comment]
Ah I see, so it looks like you are granting all privileges.

**Comment by ssddanbrown** [comment]
Since database migrations are done as part of the app I'd advise the user should have pretty much all permissions. Some are likely not needed, Such as 'views' or 'routines' but I cannot guarantee that for the future.

If you really wanted to limit access you could do that by using a different .env options when migrating which would limit the required permissions for general daily use.

**Comment by salimnanji** [comment]
Thanks for the explanation! Good to know.
