### ISSUE TITLE
Added exact term escaping and fixed breaking exact term behaviour

### ISSUE THREAD

**Issue by Civlac** [BookStackApp/BookStack#4535]
### Describe the Bug

Wrapping text in "double quotes" in the Advanced Search -> Search Terms field correctly identifies the user input styled as 'exact matches', but doesn't remove the double quotes when moving it to the other field. This causes 0 results to be shown.

### Steps to Reproduce

1. Go to the search page.
2. On the left 'Search Terms' field, enter text surrounded by double quotes.
3. It appears to detect this entry as Exact Search, so it moves the user input to that field, but it doesn't return any search results because the double quotes still exist.

Additionally, doubling quotes in the global search at the top of the page will cause the site to timeout, and return a 500 error after 30s.

### Expected Behaviour

If the website will auto detect the user input as an 'exact search', the double quotes should be removed.

#### Before searching:
![image](https://github.com/BookStackApp/BookStack/assets/42948607/f2d28d6d-1425-44ab-877e-dafab68c0453)

#### After searching:
![image](https://github.com/BookStackApp/BookStack/assets/42948607/83fef8ce-595d-4162-8fe9-3ad821640123)

Note in the global search at the top, the double quotes are duplicated.

### Browser Details

Microsoft Edge v116.0.1938.69 on Windows 10 (64 bit)

### Exact BookStack Version

v23.08.2

**Comment by ssddanbrown** [comment]
Thanks for raising @Civlac. Could confirm strange behaviour here.

It should be noted that the "Search Terms" box is only meant to represent standard query terms, and not anything more advanced, but some of our automatic promoting of standard term to exact terms (due for indexing reasons) make it seem like exact terms are attempting to be properly handled.

Within 89645759731bfd23cbaea3bb6d971f32579d5416, I've added some proper handling and testing for empty and escaped exact search terms, so that empty exact terms don't break loading (and instead just get filtered out) and so double-quotes can be used within an exact match term.

Now, if `"example"` was used in the "Search Terms" box, this will be converted to an exact search for `"example"`, reflected as `"\"example\""` in the top search bar. 
The new behaviour may still not always be as the user expects, but these kinds of cases are always going to be tricky, and it's probably more down to labelling/ux at this point, but at least things shouldn't break in these cases now.

This will be part of the next feature release.

**Comment by ssddanbrown** [comment]
Additional backslash handling added in f77bb01b514a0ae6a469ec33a40d0d053d804d40.

### Release Docs Updates

- [ ] Upgrade advisory, backslashes in exact match syntax now need to be escaped themselves to match a literal backslash.
- [ ] Update search docs to detail escaping for exact terms.
