### ISSUE TITLE
Give the possibility to choose between Markdown or TinyMCE at the page creation

### ISSUE THREAD

**Issue by hotgeart** [BookStackApp/BookStack#458]
We use BookStack to write the doc at the office and some people are developpers orthers aren't so ofc the dev want to write in MK and the others don't want to learn MK.

So the choose can be specific to the page and not a global option ?

**Comment by ssddanbrown** [comment]
Just for reference, Somewhat related to #119 and #369

**Comment by ssddanbrown** [comment]
PR #3387 has now been merged, which allows switching of editor type from within the editor.
The editor type is then saved against the page itself, and uses the system setting as a default.
[A preview can be seen here. ](https://user-images.githubusercontent.com/8343178/164977916-9c8beee1-8578-43cd-b877-accb55e97fb6.mp4)

The code for this has been merged and is targeted for the next feature release (Likely v22.04).
I'm going to close off this issue as being covered by this change. While this issue specifically states "at page creation", I wouldn't really want to prompt a user with this choice before page creation since it would add an additional barrier & step. Having this within the page edit view achieves the fundamental request of this issue with pretty much the same ease/speed from an end-user perspective.

@fredericmohr (If you're still using BookStack 5 years later :sweat_smile:) This addition does work at a book/chapter level but does come with permission control, A new role-permission has been added to control users that are able to switch the editor which I hope helps your scenario.

**Comment by fredericmohr** [comment]
I am still using and still loving BookStack. In fact, I just moved all my content from an old installation to a new server. Exciting to see this change happening. Thanks a ton for all your great work! 😊👍
________________________________

**Comment by ssddanbrown** [comment]
@fredericmohr Amazing! That's wonderful to hear.
