### ISSUE TITLE
Expired OIDC login button

### ISSUE THREAD

**Issue by thespad** [BookStackApp/BookStack#4600]
### Describe the Bug

If you leave a browser tab logged into Bookstack via OIDC and then close the browser and return later after the session has expired - say the next day - when the page loads it will display the login page, but following the login link will result in a 419 - Page Expired error.

Manually refreshing the login page *before* clicking the login button works as expected.

### Steps to Reproduce

Login to Bookstack via OIDC in a browser tab
Close browser
Reopen browser after login session has expired
Navigate to Bookstack tab
Click on OIDC Login button
See 419 error

### Expected Behaviour

Login button should work even if the page itself is stale, or at least fail in a more recoverable way than a full-page 419 error.

### Browser Details

Firefox 118.0.1 x64 on Windows 10

### Exact BookStack Version

v23.08.3

**Comment by ssddanbrown** [comment]
Thanks for reporting @thespad.

We [prevent caching when authenticated](https://github.com/BookStackApp/BookStack/blob/b90033a73032da8657f1bd3ec3687aa4426d8cc1/app/Http/Middleware/PreventAuthenticatedResponseCaching.php) since it was a security concern in that context, but maybe we need to do the same for all users.

Just need to double check potential implications but think it should be fine outside of minor performance hits in some (fairly uncommon) scenarios.

**Comment by ssddanbrown** [comment]
This has now been addressed via 7c4dc981cd049196971a663521da73aea2990490, and will be part of the next feature release.

Thanks again @thespad for reporting.
