### ISSUE TITLE
Unknown error Occured on creating new user

### ISSUE THREAD

**Issue by arshapsclock** [BookStackApp/BookStack#4602]
### Describe the Bug

While trying to create a new user from the admin account its showing unknown error occured and not able to create one.

### Steps to Reproduce

1. Go to settings
2. Click on users
3. Add newuser
4. add details and save

users are not getting created and throwing an error as "Unknown error occured"

### Expected Behaviour

User should be created and admin can enforce them to enable the MFA while login.

### Exact BookStack Version

v23.08.3

**Comment by arshapsclock** [comment]
103.179.230.63 - - [06/Oct/2023:03:09:20 +0000] "POST /settings/users/create HTTP/1.1" 500 18213 "http://34.219.34.103/settings/users/create" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36"

Please see the logs

**Comment by ssddanbrown** [comment]
Hi @arshapsclock,
Those webserver logs don't show a lot. You'll find more relevant information in the application logs as per our [debugging docs](https://www.bookstackapp.com/docs/admin/debugging/).

If you're sending an invite email when adding users, it's likely due to not being able to send email.
There's email test send functionality in the settings > maintenance part of the UI.

**Comment by ssddanbrown** [comment]
Since there's been no further discussion here I'll close this off. Feel free to respond to my last message if required to re-open and continue this thread.
