### ISSUE TITLE
Text size varies greatly

### ISSUE THREAD

**Issue by nat-418** [BookStackApp/BookStack#4613]
### Describe the Bug

Bookstack has a 39.55 pixel difference between text displayed, for example, here: https://demo.bookstackapp.com/shelves/demo-content .

The largest text is too large and the smallest text is too small. It seriously hampers legibility, and is very aesthetically unpleasing:

![image](https://github.com/BookStackApp/BookStack/assets/93013864/fd2b78d5-d57d-47f9-af18-f975ef6efebc)

For more detail on proper typography for the web, see:https://practicaltypography.com/websites.html

### Steps to Reproduce

1. Go to https://demo.bookstackapp.com/shelves/demo-content
2. Read the text.

### Expected Behaviour

Text should be sized between 15-25 pixels. Headers should be _slightly_ larger than the body text. For example, if we decide that the body text should be 15 pixels, a header could be 16 pixels. The smallest and largest sizes of text on a page should not be drastically different.

### Exact BookStack Version

whatever the demo is running

**Comment by otherjoel** [comment]
All of this is easy to adjust with custom CSS in the settings. Most BookStack admins are going to change the typography to suit their needs anyway.

While I also would tweak some things about BookStack’s typographic defaults, I don’t agree with a fellow typography nerd swooping in here and labeling this as a bug. I also know Matthew Butterick, and I don’t think he would be enthused about his work being used in service of drive-by nitpicking (see, e.g., [1], [2]). If you want to evangelize about good typography, do so through your own good typographic works 😉

[1]: https://forums.matthewbutterick.com/t/question-and-opinion-about-the-headings-practice/94/2
[2]: https://forums.matthewbutterick.com/t/first-line-indents-and-font-mixing/92/2

**Comment by ssddanbrown** [comment]
Thanks for the input @nat-418,
In my view, consistency of font sizes for sure could be improved.
In regards to range of font sizes, I don't doubt a tighter range could visually improve things, but I'm not sure I'd want to tighten things too much in the platform defaults. 

The example you're showing has a particularly large range due to the shelf heading.  
This heading is aligned with the sizes of that for books, chapters and pages so the names of these core items appear consistent as your travel down. 
Since the is a platform of user-content, and users have access to a range of headers, by default the main heading is quite large since we accommodate several options levels beneath this.
I like to ensure these are distinct without much additional opinionated design/style thrown in, and therefore sizing is used.

If you don't like the sizes/styles used, you can always customize/override the styles.

> For example, if we decide that the body text should be 15 pixels, a header could be 16 pixels.

A 1px difference is quite hard to see in my opinion. Of course you could use other methods of distinguishment, but as said above I like to keep the defaults fairly vanilla & free of much additional styling choices. 

I'm happy to take on this input, for choices I make going forward, but I don't expect to change things to work to the range you're requesting, and I may close this off as opionated change requests such as this can be hard to manage.

**Comment by nat-418** [comment]
> All of this is easy to adjust with custom CSS in the settings. Most BookStack admins are going to change the typography to suit their needs anyway.
> 
> While I also would tweak some things about BookStack’s typographic defaults, I don’t agree with a fellow typography nerd swooping in here and labeling this as a bug. I also know Matthew Butterick, and I don’t think he would be enthused about his work being used in service of drive-by nitpicking (see, e.g., [1](https://forums.matthewbutterick.com/t/question-and-opinion-about-the-headings-practice/94/2), [2](https://forums.matthewbutterick.com/t/first-line-indents-and-font-mixing/92/2)). If you want to evangelize about good typography, do so through your own good typographic works 😉

I don't care who you are or who you know. I tried out using Bookstack and found it hard to read. I don't think that is "drive-by nitpicking". If the maintainers of this project do not want user feedback in the form of issues, then they should restrict or close the ability of users to submit issues.

**Comment by nat-418** [comment]
> Thanks for the input @nat-418, In my view, consistency of font sizes for sure could be improved. In regards to range of font sizes, I don't doubt a tighter range could visually improve things, but I'm not sure I'd want to tighten things too much in the platform defaults.
> 
> The example you're showing has a particularly large range due to the shelf heading. This heading is aligned with the sizes of that for books, chapters and pages so the names of these core items appear consistent as your travel down. Since the is a platform of user-content, and users have access to a range of headers, by default the main heading is quite large since we accommodate several options levels beneath this. I like to ensure these are distinct without much additional opinionated design/style thrown in, and therefore sizing is used.
> 
> If you don't like the sizes/styles used, you can always customize/override the styles.
> 
> > For example, if we decide that the body text should be 15 pixels, a header could be 16 pixels.
> 
> A 1px difference is quite hard to see in my opinion. Of course you could use other methods of distinguishment, but as said above I like to keep the defaults fairly vanilla & free of much additional styling choices.
> 
> I'm happy to take on this input, for choices I make going forward, but I don't expect to change things to work to the range you're requesting, and I may close this off as opionated change requests such as this can be hard to manage.

Thanks for taking the time to respond. I checked out Bookstack because I saw your posts when looking for a good self-hosted wiki. I noticed you called it opinionated software. If you don't want to do such a small range that I suggested,  I respect your decision as the project maintainer. I think you could figure out a way to reduce the range between huge and tiny text, but if you don't want to do that, that's your free choice.

**Comment by ssddanbrown** [comment]
Thanks for your understanding. I'm going to close this off since I don't see enforcing a specific rule on the project, or a specific action to target right now, but I'll keep this feedback in mind when working on default design elements going forward.
