### ISSUE TITLE
Require email confirmation from Admin for new sign up

### ISSUE THREAD

**Issue by slimninja** [BookStackApp/BookStack#463]
### For Feature Requests

Desired Feature: Allow registration contingent on admin approval.

Flow:
1. User creates account, role is assigned as "Public"
2. Email sent out to designated admin
3. Admin approves account creation via email link
4. "Viewer" role is assigned to user

**Comment by Wachert** [comment]
Would be a nice feature, moderated registrations.

**Comment by Jab2870** [comment]
Has any progress been made on this? I'd like to see this feature too.

**Comment by ssddanbrown** [comment]
@Jab2870 no progress as of yet, and not too likely to be considered soon due to the low desire compared to the components that would need to be added and maintained.

**Comment by ssddanbrown** [comment]
I'm going to go ahead and close this off since it has such little desire while complicating authentication systems.
I've really desired I can think of a couple of workarounds:

- Use webhooks , listening to registration events, to trigger a communication to an admin/team.
- Use our [logical theme system](https://github.com/BookStackApp/BookStack/blob/development/dev/docs/logical-theme-system.md) to run custom logic on the [auth_register](https://github.com/BookStackApp/BookStack/blob/60014989f58bd96912278dd8c9320f8ff0184277/app/Theming/ThemeEvents.php#L70) event.
