### ISSUE TITLE
Domain or Group Based Roles

### ISSUE THREAD

**Issue by HoleInTheSeat** [BookStackApp/BookStack#4657]
### Describe the feature you'd like

A way to have a certain role applied to the user on registration based on either the email domain or the google group.

### Describe the benefits this would bring to existing BookStack users

This would allow easier user management by having the correct roles set to each user as intended, rather than manually changing the role after the user has registered.

### Can the goal of this request already be achieved via other means?

Not to my Knowledge.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

### How long have you been using BookStack?

1 to 5 years

**Comment by ssddanbrown** [comment]
We support group/role sync via OIDC/LDAP/SAML2, as long as the auth system can provide roles/groups in a fairly standard format.

Alternatively, I have a simplistic example in my comment here of using the logical theme system as a method to achieve this: https://github.com/BookStackApp/BookStack/issues/1904#issuecomment-848829004
This could be customized to apply any custom logic really.

Otherwise, this is not something I'd be too keen to implement since I'm hesitant to expand authentication features where there's little demand, especially where the desired logic may be quite specific or require extra in-app controls to maintain.

**Comment by HoleInTheSeat** [comment]
> We support group/role sync via OIDC/LDAP/SAML2, as long as the auth system can provide roles/groups in a fairly standard format.
> 
> Alternatively, I have a simplistic example in my comment here of using the logical theme system as a method to achieve this: [#1904 (comment)](https://github.com/BookStackApp/BookStack/issues/1904#issuecomment-848829004) This could be customized to apply any custom logic really.
> 
> Otherwise, this is not something I'd be too keen to implement since I'm hesitant to expand authentication features where there's little demand, especially where the desired logic may be quite specific or require extra in-app controls to maintain.

Thanks, Ill take a look at this and see if I can make it suite my needs. Much appreciated!
