### ISSUE TITLE
Ability to shorten URLs

### ISSUE THREAD

**Issue by mw-christensen** [BookStackApp/BookStack#4660]
### Describe the feature you'd like

I would like the ability to create and specify a shortened URL (similar to what bit.ly does).

### Describe the benefits this would bring to existing BookStack users

In instances where you need to have a URL listed on a printed page like a flier or printed documentation, it would be nice if you could specify a shortened URL so that people could easily type in the URL using their keyboard.

An example of this would be:
Original: myfunclub.com/events/2023/halloween/Come_join_us_for_our_fun_halloween_party
Shortened: myfunclub.com/2023halloween

The shortened URL would just be a redirect to the original longer URL.

### Can the goal of this request already be achieved via other means?

Possibly? You could have a main landing page with a simple name and put all other links on that page I suppose?

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

### How long have you been using BookStack?

1 to 5 years

### Additional context

Thanks! Bookstack is amazing!

**Comment by ssddanbrown** [comment]
Hi @mw-christensen, thanks for the request. 

> Can the goal of this request already be achieved via other means?
> Possibly? You could have a main landing page with a simple name and put all other links on that page I suppose?

To add some additional options:

- You can use the existing page permalinks (Applies to pages only).
  - To get the permalink, select the text of some page content, when viewing a page. You'll see a popup providing a link to that specific block. Remove everything after the `#` to generally link to that page, and shorten the link.
- You could set-up redirects via your webserver (Match on URL, redirect to desired path).
- You could use a separate external service like described.
  - A range of self-hostable options [can be seen here](https://github.com/awesome-selfhosted/awesome-selfhosted#url-shorteners).
- You could add redirects via our [logical theme system](https://github.com/BookStackApp/BookStack/blob/development/dev/docs/logical-theme-system.md).

With that last option, you could do something a bit smarter and dynamic, like redirect based on the URL matching certain tags. If you'd like an example of this, let me know although the logic would be considered unofficial/unsupported, but it might make a good addition [to our hacks site](https://www.bookstackapp.com/hacks/). 

Otherwise, while we could add in-built redirect management, I'm not too sure it'd be worthwhile maintaining that as a specific feature due the little demand of such a feature so far, and the existence of a range of alternative options.

**Comment by mw-christensen** [comment]
Thanks Dan for your response. I didn't know how to get a page permalink. I think that is probably the easiest and most logical workaround for what I am looking for. Thanks so much for pointing that out.

While I still think custom URLs would be nice, I think this workaround is totally sufficient to provide a link for printable media. Thanks so much!
