### ISSUE TITLE
Enable user tagging

### ISSUE THREAD

**Issue by jinjaghost** [BookStackApp/BookStack#4662]
### Describe the feature you'd like

Hi,

Could you please resolve #560  ? I've got a use case where a lot of users use (with success) Bookstack to exchange informations and that would be a HUGE enhencement and a perfect fit.

Regards,

### Describe the benefits this would bring to existing BookStack users

User time won't be wasted.

### Can the goal of this request already be achieved via other means?

Yes but this is for power user and not intuitive at all.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

### How long have you been using BookStack?

Not using yet, just scoping

**Comment by Skraal117** [comment]
+1 I think that this issue could have been solved in 5 years with the time spent responding to the other issues that the need had been declared in #560 :)

**Comment by ssddanbrown** [comment]
Please don't purposefully open duplicate issues like this, I'm going to close this off since the request is already covered.

I am moving toward adding user mentions, with elements like the notification system recently being added, but there's still some related bits I want to improve first before specifically tackling user mentions of any kind.

**Comment by otherjoel** [comment]
> +1 I think that this issue could have been solved in 5 years with the time spent responding to the other issues that the need had been declared in #560 :)

https://www.bookstackapp.com/donate/
