### ISSUE TITLE
Automatically add users to watch a specific book or add all users to shelves to send notifications

### ISSUE THREAD

**Issue by Manuel311290** [BookStackApp/BookStack#4676]
### Describe the feature you'd like

We are using bookstack also as an information plattform to store news and send them to our bookstack users.

the problem is, the users need to watch the book, to get the information. It would be realy nice if there was an option to automatically add a usergroup to watch the book, or even better the whole shelve. 

### Describe the benefits this would bring to existing BookStack users

Centralized adding users to watch pages, books and shelves

### Can the goal of this request already be achieved via other means?

as a work around I can manually add all users to the watch by searching the book id and adding all users to the watch table  by running sql statements in the database;

`INSERT INTO watches 
SELECT NULL,u.id, 26, 'book', 2, NOW(),NOW() 
FROM users u
where u.id not in (SELECT user_id from watches where watchable_id=26);
`

a even better work around would be to create a trigger which checks if the book is under a specific shelve and then automatically add all users to this book

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

### How long have you been using BookStack?

3 months to 1 year

**Comment by ssddanbrown** [comment]
Thanks for the request @Manuel311290 but I feel the fundamental request here is already covered by #4514, so I'm going to therefore close this off.

Instead of database usage, it is likely also possible to achieve this via the [logical theme system](https://github.com/BookStackApp/BookStack/blob/development/dev/docs/logical-theme-system.md), if comfortable getting into PHP, which can allow you to hook into certain system events to update the watch status as desired.
