### ISSUE TITLE
Use Callouts in Markdown Editor

### ISSUE THREAD

**Issue by Shackelford-Arden** [BookStackApp/BookStack#469]
So, I'm a big fan of the callouts that I can use in the WYSIWYG editor. Though, for simplicity in one of the wiki's I'm using, I've switched over to the Markdown Editor.

My only problem is I can't figure out how to use the Callouts (Info, Success, etc) while in the Markdown editor. Is there a way to do this or should I use the WYSIWYG editor if I really want them?

**Comment by ssddanbrown** [comment]
Hi again @Shackelford-Arden,

Since callouts are not a standard part of markdown there's no special syntax for them but you can add HTML into the markdown editor. Therefore you can add the HTML for callouts within the markdown editor without any issue. Here's an example with all callout types:

```
# My Markdown Page

<p class="callout info">A success message</p>
<p class="callout success">A success message</p>
<p class="callout warning">A success message</p>
<p class="callout danger">A success message</p>

Normal markdown text
```

Produces:

![image](https://user-images.githubusercontent.com/8343178/29251308-61f62948-804a-11e7-8a84-86b739cbc5f2.png)

---

In the last bugfix release, v0.17.4, I actually expanded the shortcuts for the markdown editor quite a lot including a callout shortcut `Ctrl+9` (Or `Cmd+9` on mac) which would insert the info callout syntax  for you but in writing out this message I realised this is currently a little broken (#470).

**Comment by Shackelford-Arden** [comment]
Hot dang. This does indeed work just fine for me. You can close this... Thanks! I'll look over the documentation.

**Comment by ssddanbrown** [comment]
Awesome, Glad to hear the above works for you 👍 . Will close.

**Comment by ZishanAdThandar** [comment]
# My Markdown Page
```html

<p class="callout info">A success message</p>
<p class="callout success">A success message</p>
<p class="callout warning">A success message</p>
<p class="callout danger">A success message</p>

```

Result below:
 
<p class="callout info">A success message</p>
<p class="callout success">A success message</p>
<p class="callout warning">A success message</p>
<p class="callout danger">A success message</p>
