### ISSUE TITLE
Collapsible Block with Warning, Error, Info and Solutions Style

### ISSUE THREAD

**Issue by Flo-Koenig** [BookStackApp/BookStack#4703]
### Describe the feature you'd like

Is it possible to create different styles of the collapsible block, such as an info, error, warning or solution design.
At my old employer we used Confluence, so here's a picture as an example of what exactly I mean.
![2023-11-29_18h02_50](https://github.com/BookStackApp/BookStack/assets/72582822/b17022c4-6df3-4e8c-a958-fec44915ac51)

### Describe the benefits this would bring to existing BookStack users

Ich denke hier mit wird es noch übersichtlicher Lösungen zu dokumentieren.
Man kann mit einem Error Block beginnen, bis hin zu einem Lösungsblock.

### Can the goal of this request already be achieved via other means?

i think no

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

### How long have you been using BookStack?

3 months to 1 year

**Comment by ssddanbrown** [comment]
Hi @Flo-Koenig,

> so here's a picture as an example of what exactly I mean.

Is that collapsible? If so, how does it look when collapsed?
Otherwise, we do support callout styles, and collapisble blocks, just not a combination of both.
Here's an example of the callout options:

![image](https://github.com/BookStackApp/BookStack/assets/8343178/1d74415e-7248-4946-926a-1d73c44644a2)

If some kind of combination was desired, I'd need to know what the benefit of having both combined into one should be.
In my view, an attention seeking callout like this should probably be something short and to-the-point, rather than being something that defines a section with extra text.

**Comment by ssddanbrown** [comment]
Since there's been no further follow up on this I'll go ahead and close this off.
