### ISSUE TITLE
file upload failure 

### ISSUE THREAD

**Issue by jonty-esterhuizen** [BookStackApp/BookStack#4757]
### Describe the Bug

when i want to paste or upload an image i get this error 

![image](https://github.com/BookStackApp/BookStack/assets/82042398/867e7af2-2172-4909-9b02-776c24e44aa8)

### Steps to Reproduce

create page paste image or upload image 

### Expected Behaviour

image should upload 

### Screenshots or Additional Context

![image](https://github.com/BookStackApp/BookStack/assets/82042398/3950c0af-1548-4fb7-860f-a0a9d4dddf59)

### Exact BookStack Version

BookStack v23.12

**Comment by jonty-esterhuizen** [comment]
just for added context 
this is the handler mapping on the *.php fast cgi
![image](https://github.com/BookStackApp/BookStack/assets/82042398/2088f26a-ca2d-4f38-bf60-4b5117213adc)
I also tried with All verbs

**Comment by ssddanbrown** [comment]
Hi @jonty-esterhuizen,
I'm afraid I'm not too familiar with IIS, so can't provide much insight.

The error message if fairly explicit though.
Are you sure there are not other "handlers" or things acting on the request?
Especially since your screenshot reflects a "request path" of "*.php", since these requests are not direct to PHP files (at least in terms of request path) I'm wonder if these requests are picked up by another handler first.

I'll re-categorize this as a support thread rather than a bug since there's nothing to indicate this is a bug in the core project here.

**Comment by ssddanbrown** [comment]
Since there's been no further follow-up I'll close this off.
