### ISSUE TITLE
New descriptions of books and chapters don't update with formatting if you have set a description before the update

### ISSUE THREAD

**Issue by Man-in-Black** [BookStackApp/BookStack#4798]
### Describe the Bug

I've set some description to my books since I've started using Bookstack.
Now with 23.12 the simple wysiwyg editor startet for the descriptions and I began on new books with it and all works fine.
But on the existing descriptions I cannot get it to work.

I got my book with the old description like this:
<img width="727" alt="image" src="https://github.com/BookStackApp/BookStack/assets/9048534/87aee64e-c57b-415d-8d0d-bae6049fb5ef">

But in the editor it shows up like this (what I wanted to have):
![image](https://github.com/BookStackApp/BookStack/assets/9048534/4ddf4363-6e1f-477e-a982-50149a3c0094)

I've tried it also with different browsers, it looks all the same.

### Steps to Reproduce

1. edit an old desciption with some formatting

### Expected Behaviour

the formatted text should appear on the old desciptions.

### Exact BookStack Version

23.12

**Comment by ssddanbrown** [comment]
Hi @Man-in-Black,
Do you have any visual theme system overrides that cover the areas where descriptions are shown (I think these are the `show.blade.php` views for books,chapters and pages in particular)
If not, are you able to reproduce this [on our demo site](https://demo.bookstackapp.com/books/bookstack-demo-site/page/logging-in-to-the-demo-site)? (I don't think I've updated any descriptions there since the recent changes to descriptions)

**Comment by Man-in-Black** [comment]
Thanks @ssddanbrown for pointing me to the right direction. I indeed did some changes to the `show.blade.php`.
I've changed line 29 to `<div class="text-muted break-text">{!! $book->descriptionHtml() !!}</div>` and now its working fine.

In the future I will check my modified files in the theme system in such cases.

Thanks again for your fast response.
