### ISSUE TITLE
[feature request]each book pages

### ISSUE THREAD

**Issue by msaus** [BookStackApp/BookStack#482]
### For Feature Requests

Desired Feature:
1. Changing defaualt book navigation location in setting.
Setting book navigation to right or left in admin setting screen.

2. Hiding Book navigation
If we can hide the book navigation by clicking button, it is great.

3. Folder style book navigation
If we can fold each book, it would be great.

4. Need more space for html editor
Currently, html editor is not fully expanded so that we can have more edit space.

**Comment by msaus** [comment]
![image](https://user-images.githubusercontent.com/3432876/29612093-01d0c39a-883b-11e7-8004-096b9527412e.png)

**Comment by msaus** [comment]
![image](https://user-images.githubusercontent.com/3432876/29612120-1ed6a0ea-883b-11e7-8918-474e31bc3be7.png)

**Comment by msaus** [comment]
![image](https://user-images.githubusercontent.com/3432876/29612181-512e79fa-883b-11e7-9727-083124fa32ff.png)

**Comment by msaus** [comment]
![image](https://user-images.githubusercontent.com/3432876/29612212-6df7271c-883b-11e7-9f6d-df6baddc9118.png)

**Comment by msaus** [comment]
![image](https://user-images.githubusercontent.com/3432876/29612236-85ea11c2-883b-11e7-85f7-5ddd2c1be589.png)

**Comment by msaus** [comment]
![image](https://user-images.githubusercontent.com/3432876/29612303-c420bfb8-883b-11e7-8e58-f61f1598769b.png)

**Comment by msaus** [comment]
I found why there is extra space on editor.
There is max-width defined as 840px in css.
When I remove that, it is fully expanded.
Possibly, this should go to issue list.

**Comment by ssddanbrown** [comment]
Hi @msaus, Thank you for your comments.

> Changing defaualt book navigation location in setting.
Setting book navigation to right or left in admin setting screen.

I'd prefer to not add an additional setting unless really required. As part of the upcoming redesign the navigation will be moving to the left.

> Hiding Book navigation
If we can hide the book navigation by clicking button, it is great.

Not sure about this as there's more than the book nav in the sidebar. I'd suggest waiting for the next release due to design changes.

> Folder style book navigation
If we can fold each book, it would be great.

Not sure how this fundamentally differs to the current setup.

> Need more space for html editor
Currently, html editor is not fully expanded so that we can have more edit space.

This is done very much so on purpose to emulate how the content will show on the page.

For future reference, issues like this with many requests are quick hard to manage. Separate, Well defined, issues allow each to be separately managed and discussed.

**Comment by msaus** [comment]
Thank you very much for your comment.
Then, I will wait for the new design and tell  you some feedback.
