### ISSUE TITLE
Probably wrong translation for button "Convert to book" / "In Buch umwandeln"

### ISSUE THREAD

**Issue by eldan0815** [BookStackApp/BookStack#4891]
### Describe the Bug

Hi Dan,
I am actually not sure if this is a bug or not. :)
Shouldn't the "In Buch umwandeln" button be called "Buch in Regal umwandeln" in this section (see attached screenshot)?
![book-to-shelf](https://github.com/BookStackApp/BookStack/assets/162973932/e3d4949b-cc1d-4fca-ba00-7cac78dfdc97)

Settings are in the german translation "Deutsch (Du)".

If I switch the language to english, the button also seems wrong. Shouldn't it be called "Convert book to shelf"?
<img width="758" alt="convert-to-shelf" src="https://github.com/BookStackApp/BookStack/assets/162973932/93ae5e92-973d-4c3e-a914-5e1bf3366107">

Thank you and cheers
Daniel

### Steps to Reproduce

1. Edit a book
2. See wrong translation or not (Maybe I'm misunderstanding the function here?) :)

### Expected Behaviour

Nothing, if I misunderstood the function. If not, little changes to the translation.

### Screenshots or Additional Context

Already provided above.

### Exact BookStack Version

v23.12.2

**Comment by ssddanbrown** [comment]
Hi @eldan0815,
The "Convert Book" English text seems fine to me, since pressing the button will convert the book to a shelf. 
Button text is usually short, and I don't see the need for the full "Convert book to shelf" text since the context is provided by the card/section that button sits within.

I don't know German well enough to have opinions there.
If you believe there's a better suggestion feel free to join the [translation project on Crowdin](https://crowdin.com/project/bookstack) to update translation text.

**Comment by lommes** [comment]
The translation is indeed wrong, but only exists in the informal German translation.

I updated the value on crowdin to match the english "convert book" which should be sufficient since the text above explains what happens

**Comment by eldan0815** [comment]
@lommes Thank you very much. 
@ssddanbrown Thank you, I will join the translation project next time (if @lommes isn't so fast ;) )

**Comment by ssddanbrown** [comment]
Thank you @lommes for updating!
And thanks @eldan0815 for reporting and for looking to get involved.

I'll therefore close this off.
