### ISSUE TITLE
OIDC Discovery Error: cURL error 28: Resolving timed out after 5000 milliseconds

### ISSUE THREAD

**Issue by jothoma1** [BookStackApp/BookStack#4922]
### Describe the Bug

When a user click on the SSO login button for connecting there is a timeout **but only when the user is logging in after an inactivity period or the first time of the day (same behavior)**.
The login with our Keycloak OIDC works great with other apps (grafana, itop, etc) without this behavior
When the timeout occurs, user retry a second time and it works flawlessly
It's like Bookstack is freezed for a small delay and the OIDC dialog is slower with this delay so we have more than 5000 milliseconds

Bookstack is installed on a Debian 12 VM and Keycloak on another Debian 12. No Firewall between the 2, no CPU or RAM usage.

### Steps to Reproduce

Works fine with OIDC login with other apps (grafana and itop are ok everytime)
Same as this one : https://github.com/BookStackApp/BookStack/issues/3360

### Expected Behaviour

Instantly have Keycloak login without delay 

### Screenshots or Additional Context

![image](https://github.com/BookStackApp/BookStack/assets/19167503/e9c0da71-0b16-4108-9293-5f36a7012968)

### Browser Details

Firefox / Chrome / Edge ->same

### Exact BookStack Version

24.02.2

**Comment by ssddanbrown** [comment]
Hi @jothoma1,
Could you measure the general time to the `openid-configuration` endpoint from the BookStack host system via this:

```bash
curl -o /dev/null -s -w 'Establish Connection: %{time_connect}s\nTTFB: %{time_starttransfer}s\nTotal: %{time_total}s\n'  https://keyclock.auth-server.com/path/to/.well-known/openid-configuration
```

Ideally the results from first run of the day, then second run too.

**Comment by jothoma1** [comment]
Hi @ssddanbrown 
Yes sure, here it is : 
![image](https://github.com/BookStackApp/BookStack/assets/19167503/7e12bacd-034e-4f34-942c-c188d42f5147)
You can see the first one is above 5s and the second one is fast

What i dont understand is when comparing with grafana for example, we dont have this behavior, it's super fast but in the config we dont use OIDC discovery but auth_url / token_url / api_url and signout_redirect_url

**Comment by ssddanbrown** [comment]
@jothoma1 I'm guessing it's either a delay in DNS resolution, or a delay in keycloak serving this specific endpoint for the first time in a while, which is the helped by DNS/keycloak-side caching.

You could re-run the curl command again later (at a point where the delay would typically come back) but with a `--resolve keyclock.auth-server.com:443:192.168.1.1`, replacing `192.168.1.1` with the keycloak server IP, to help indicate if this is a DNS issue. You'd need to be careful not to query the keycloak host address before running that to ensure the value won't be cached before-hand. If it runs quick with this option, then it's likely DNS.

Maybe you could also create a new container (docker run into bash to start in a new container, rather than exec into the running container) to see if the previous curl command consistently runs slow on first run (even if doing the same again via a new container instance right after). This method may not be accurate for diagnosing though if it's an upstream DNS resolving issue, only if it's local to the container instance.

**Comment by jothoma1** [comment]
Thanks a lot @ssddanbrown 
i have made the test and yes i think it's a DNS issue but dont really know where for the moment...
The only thing i notice is the VM (debian 12) have a conf for DNS in /etc/resolv.conf and in /etc/network/interfaces 
but in /etc/network/interfaces there is only one DNS server (but it's a valid DNS server)
when i add my keycloak server in /etc/hosts it works flawlessly ... i will investigate more
you can close, sorry for this mistake it's not a bookstack issue
Thanks again for your work !
