### ISSUE TITLE
Advise about the payment feature

### ISSUE THREAD

**Issue by zhanggaoxuan** [BookStackApp/BookStack#4973]
### Describe the feature you'd like

If reader want to read, for "book" or "chapter" or "page"  or part of the "content", the reader must be the vip of the website owner or must type the password or must pay some money.

The admin can set at the control panel about which he want to control. "for "book" or "chapter" or "page"  or part of the "content"" also the admin can use short code to set those

### Describe the benefits this would bring to existing BookStack users

The BookStack users can use these earn money to write books.

### Can the goal of this request already be achieved via other means?

the best way is add features and can be set  at the control panel

the easiest way is make a short code

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

### How long have you been using BookStack?

Not using yet, just scoping

### Additional context

the payment can be stripe, 2checkout or alipay

**Comment by ssddanbrown** [comment]
Thanks for the suggestion @zhanggaoxuan but I'd consider any kind of payment integration as out of scope for the core platform we're building/maintaining here.

It may be possible to hack something relevant in yourself using our methods of hacking/extension: https://www.bookstackapp.com/docs/admin/hacking-bookstack/

Otherwise I'm going to close this off as out of scope.
