### ISSUE TITLE
Feature Request: Like Button on Pages & Favourite / Saving Pages

### ISSUE THREAD

**Issue by stuartajd** [BookStackApp/BookStack#505]
As an addition to the comments system, a like system could be nice to show appreciation for the page without leaving a comment. 

Could be something similar to this?

![Example](https://i.imgur.com/Mg6plst.png)

In addition, allowing the saving or marking pages as favourite and the ability to quickly navigate back to them from a list or column on the main dashboard. Similar to GitHub stars. This would allow users in instances where there are lots of pages being viewed, to easily navigate to specific pages.

**Comment by dsaundersWizmo** [comment]
I prefer that the 'Like' option isn't there myself; I'm not sure what sort of value that adds to the documentation, especially if it's internal?  My personal opinion is that it kind of detracts from the simplicity and mission statement of Bookstack to make it more of a social platform.

That being said, Favorites was something I was just going to submit as a feature request.  You could call them "**Book Marks**".

**Comment by aljawaid** [comment]
Favourites, or bookmarks (as they would be referred to in a real book) would be ideal per-user.

To expand, it would be nicer to then (in the future) have admin allow certain 'bookmarks' as mandatory for certain users/roles.

**Comment by hahmed09** [comment]
Will be keen to have bookmarks!

**Comment by ssddanbrown** [comment]
I've just opened #2063 to gather feedback on the naming of such a feature as has been requested here.

**Comment by ssddanbrown** [comment]
An implementation of a favourites system has now been merged in from #2748 and is therefore scheduled to be part of the next feature release. 

Since that was the most desired part of the original request, based upon the comments, and since I'd consider "likes" or similar to be out of scope unless there's a significant benefit to existing BookStack users, I'll now consider this closed. Thanks @stuartajd for your original request.
