### ISSUE TITLE
Include API for Services like diagram.net

### ISSUE THREAD

**Issue by dominikschroeck** [BookStackApp/BookStack#5092]
### Describe the feature you'd like

It would be great to have an API that allows for integrations such as the great modelling tool diagrams.net

### Describe the benefits this would bring to existing BookStack users

We love to document concepts in bookstack for our clients. However, to be more interactive and update diagrams, we'd love to see diagrams.net in Bookstack for interactive documentation

### Can the goal of this request already be achieved via other means?

No

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

### How long have you been using BookStack?

1 to 5 years

**Comment by ssddanbrown** [comment]
Hi @dominikschroeck,

I'm not really sure what such an API would look like, since many front-end services can do quite different things.
I'm also not keen on further supporting dynamic elements due to their impact on what we can expect, build for, and assure in terms of keeping to standard portable content types that can work in other formats (export/print).

To focus on your current desire of diagrams.net, what exactly do you want upon our existing integration/use of  diagrams.net?

**Comment by ssddanbrown** [comment]
Since there's been no further follow up on this idea, I'm going to go ahead and close this off.
