### ISSUE TITLE
Docker updates wipe out all config

### ISSUE THREAD

**Issue by callahan22** [BookStackApp/BookStack#5097]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

I am using WatchTower to keep the BookStack Docker container up-to-date. Twice now, I've gone back to look at BookStack and it's deleted all my config. All users are gone (using Azure AAD/App Reg to auth against AAD). The DB container is not being auto updated.

I'm using : https://hub.docker.com/r/linuxserver/bookstack

I've had to rebuild the users and profiles/images twice now on the last 2 updates. One the first update/break, I lost all the articles my users had uploaded. Luckily this time, we had no articles in the DB.

If there is a process that I'm missing to do the Docker updates? It seems to be over-writing configured components of the app settings on update.

Thanks for any suggestions you have.

### Exact BookStack Version

24.05.2

### Hosting Environment

Ubuntu 20.04.6 LTS

**Comment by ssddanbrown** [comment]
Hi @callahan22,
Docker containers are intended to be destroyed, which destroys everything in the container unless required locations are mounted as volumes to the host.

It sounds like you don't have the required paths mounted, so they are not persistent between container instances.
How exactly are you running/managing these containers? (eg. share docker-compose file if using).

> I am using WatchTower to keep the BookStack Docker container up-to-date

If active, I'd avoid any level of auto-update. I've seen many instances of things going wrong via this method (mostly due to timeouts etc) which then make it unlcear to trace logs for underlying errors.
I'd instead advise using WatchTower just to advise of updates, then update manually.

**Comment by ssddanbrown** [comment]
Since there's been no further follow up on this I'll go ahead and close it off.
