### ISSUE TITLE
Import Export Function Word Documents and OneNote

### ISSUE THREAD

**Issue by spoonerarthur** [BookStackApp/BookStack#5128]
### Describe the feature you'd like

Hello,
I have OneNote 2016 notebooks in a local files, not in the Cloud or MS365 Enviroment.
I want to migrate to bookstack.
Because bookstack has more potential and it is browser-based.
At the moment I only can Export the sections with the pages to one big Word File.
For the Import to Word I need a automatic separation.
Maybe that is possible, but I don't know.

Also a Export from Bookstack to Word would be nice.

Regards Arthur

### Describe the benefits this would bring to existing BookStack users

Import and Export with other Users and Wiki Systems

### Can the goal of this request already be achieved via other means?

I don't know

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

### How long have you been using BookStack?

Under 1 months

**Comment by ssddanbrown** [comment]
Thanks for the suggestion @spoonerarthur, but I'd consider the support of such formats outside of the scope of our target support since they are an external complex and somewhat proprietary moving target. Therefore I'm going to close this off since it's out of scope and/or covered by existing other issues.

BookStack has a REST API, so if you're able to script your conversion using external tools, you could then use the API to created pages from that.

Related issues: #1273, #4258, #3064
