### ISSUE TITLE
Extend callouts to allow longer notes with heading, more than one paragraph, lists etc.

### ISSUE THREAD

**Issue by ilpssun** [BookStackApp/BookStack#5137]
### Describe the feature you'd like

We use BookStack as a platform for our user documentation.  In the docs, we often find that we would like to highlight an important point that should be visualized as a callout.  This works fine for single-paragraph notes.  However, we often have a situation where we'd like to include either a heading, a second paragraph or even a bullet list of items into the callout.  So basically, we'd like to switch from a per-paragraph formatting of callouts to a `div`-based formatting, which can wrap several `h…`, `p`, `ul`/`ol` tags.

Currently, a callout with more than one paragraph would look something like this:
![image](https://github.com/user-attachments/assets/c9309268-6208-44f8-9720-4808163137e7)

It is currently visualized as four separate blocks.  The requested feature would combine the four “blocks” into a single callout containing a heading, a list and two paragraphs.

### Describe the benefits this would bring to existing BookStack users

The benefit from this change is that more complex annotations in user documentation would be supported.  I think that this is a typical use-case for more comprehensive documentation projects.

### Can the goal of this request already be achieved via other means?

Currently not, as far as I am aware.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

### How long have you been using BookStack?

1 to 5 years

**Comment by ssddanbrown** [comment]
Thank you for the request. Personally I'd prefer to keep the callout formats to be simple block level elements used for calling out rather than have them become more complex containers.

In regards to the state benefit, I'm not too keen on making changes in the name of supporting complexity, since the same justification could be used for any addition to the editor which is not a sustainable approach.

Note, you can create breaks in the via `Ctrl/Cmd + Enter` to start text on a new line, between this and other inline formatting options, you may be able to emulate what you need.

**Comment by ssddanbrown** [comment]
I'm going to go ahead and close this off with the reasoning as provided above.
