### ISSUE TITLE
Better Sort

### ISSUE THREAD

**Issue by dsaundersWizmo** [BookStackApp/BookStack#519]
### For Feature Requests

Desired Feature: Sorting is quite difficult in Bookstack for a couple of reasons--

When I go to sort, It lists all chapters and pages.  If I have a book with 10 chapters and 20 pages, sorting it is an exercise in patience.  The dragging is nice but it's not auto scrolling.  But there are a couple of other problems, like if I want to sort topics in alphabetical order I need to do it manually.

It would be nice to have automatic sorting options, even if they were applied manually by users in the sort screen.

- Sort Chapters and/or Pages by criteria separately
- Sort by Alphabetical title
- Sort by Date Created (asc/desc)
- Sort by most viewed

Automatic sorting options could be defined, either updating sort when items are added or as a housekeeping in the database Event Scheduler.

**Comment by galaxyfeeder** [comment]
I like this idea, just having this kindof automatic sorting option inside the sort page.

**Comment by tmikaeld** [comment]
Would like the same to be applied to Books as well, it's a big issue when you have many books to find the one you need.

**Comment by ssddanbrown** [comment]
As of the latest release, sort helpers have been added to the book sort screen:
https://www.bookstackapp.com/blog/beta-release-v0-26-0/#book-sort-helpers

I'm going to close this now due to the above mentioned change, and since the original issue was fairly broad. If there are remaining improvements you'd like to see please open a new issue.
