### ISSUE TITLE
The IP address is incorrect if it is behind the AWS ALB (ECS Version).

### ISSUE THREAD

**Issue by racson** [BookStackApp/BookStack#5202]
### Describe the Bug

<img width="359" alt="Screenshot 2024-09-12 at 5 56 55 PM" src="https://github.com/user-attachments/assets/2460cb87-c1d2-4d77-a0f0-c790d72d305c">

### Steps to Reproduce

Deploy BookStack into ECS.
EC2 Target Group point to ECS.
ALB point to Target Group filter by subdomain.

### Expected Behaviour

The IP address should display the correct external IP or be forwarded by the CDN/load balancer.

### Exact BookStack Version

v24.05.4

**Comment by ssddanbrown** [comment]
Hi @racson,
If you set an `APP_PROXIES="127.0.0.1,127.0.0.2"` option (bit with your proxy IPs) then BookStack will then pick up IPs from other common headers (like `X-Forwarded-For`). You can also use a value of `*` as a wildcard.

Looks like we need to document this somewhere, since I think it's only mentioned [in this post currently](https://www.bookstackapp.com/blog/bookstack-release-v21-10/#ip-address-in-audit-log).
