### ISSUE TITLE
Add WYSIWYG editor button as part of Logical Theme Hack

### ISSUE THREAD

**Issue by LachTrip** [BookStackApp/BookStack#5207]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

I understand there is a method for adding WYSIWYG editor buttons through custom HTML head, however I was hoping to find a way to do so as part of a logical theme so as to avoid using in app settings.

### Exact BookStack Version

v24.03-dev

### Hosting Environment

Debian 12, installed using official docker-compose

**Comment by ssddanbrown** [comment]
Hi @LachTrip,
You could do this via the [visual theme system](https://github.com/BookStackApp/BookStack/blob/development/dev/docs/visual-theme-system.md) to just add a custom script with the required code, in a location that's loaded when the editor is.

You'd just need to ensure any script tags have a nonce attribute applied as reflected below since otherwise they'd be blocked:

```html
<script nonce="{{ $cspNonce }}">
    // JS code here
</script>
```

**Comment by LachTrip** [comment]
Thanks @ssddanbrown,
Missed a step and was using a blade template completely unrelated.
