### ISSUE TITLE
test_gif_thumbnail_generation fails after release

### ISSUE THREAD

**Issue by ramel-contria** [BookStackApp/BookStack#5208]
### Describe the Bug

Since the latest release of BookStack, the test_gif_thumbnail_generation test fails and returns the following:

```
1) Tests\Uploads\ImageTest::test_gif_thumbnail_generation
Failed asserting that 2 matches expected 1.
```
I think it might be a dependancy through `composer install` that makes the test fail.

### Steps to Reproduce

1. `git pull origin release`
2. `composer install`
3. `php artisan migrate --database=mysql_testing`
4. `php artisan db:seed --class=DummyContentSeeder --database=mysql_testing`
5. `php vendor/bin/phpunit --filter test_gif_thumbnail_generation`

### Expected Behaviour

Expected would be that the test would not fail.

### Screenshots or Additional Context

We are currently planning on using BookStack for our company to use as a know-how tool, and are adding some custom code through the theming functionality. For this, we use the release branch as a base and not the developent, since we do not want yet to be supported functions on our end. During our pipelines, we test next to our own tests the regular tests aswell, and this is where we noticed the problem with the test.

### Exact BookStack Version

v.24.05.4

**Comment by ssddanbrown** [comment]
Hi @ramel-contria,
The problem seems resolved in `development` now, maybe due to dependency (project or system) updates.

Just a warning I can't assure that tests will always pass in all environments in development or release.
Sometimes releases will go out with failing tests, where those tests can pass in other environments and/or where the test may not be important enough to delay release.

If this test continues to fail, feel free to provide extra context/info about what you may find the underlying issue to be, and/or suggestions to make the test more reliable in general.
