### ISSUE TITLE
Export and import from Bookstack

### ISSUE THREAD

**Issue by jerdzho** [BookStackApp/BookStack#5210]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

How do I export my books from Bookstack (for backups)? And how do I import them later?

### Exact BookStack Version

v24.05.4

### Hosting Environment

Docker container on Ubuntu server 20.04

**Comment by ssddanbrown** [comment]
Hi @jerdzho,
There is no partial (specific book) import/export built in outside of custom API work, and this has been requested via #3313.

For whole system level backup restore, we have [some guidance here](https://www.bookstackapp.com/docs/admin/backup-restore/) although exact steps may differ in a docker-based context, and can depend on container image used. I have a video covering backup/restore operations for a linuxserver docker-based compose setup here: 
https://www.youtube.com/watch?v=6A8hLuQTkKQ

**Comment by ssddanbrown** [comment]
Since this was answered with no further discussion or follow up I'll go ahead and close this off.

**Comment by ItsNoted** [comment]
A more simplified export and import would make updating with breaking changes much less intimidating. I'm surprised this hasn't been more closely examined.

**Comment by ssddanbrown** [comment]
@ItsNoted I have developed single command export/import via [the System CLI as detailed on this page](https://www.bookstackapp.com/docs/admin/system-cli/#backup) but it's still in alpha/beta due to limited testing feedback.
Generally export/import would not be expected to be easier than updating via breaking changes (until needing to specifically migrate from an unsupported OS).
