### ISSUE TITLE
Not possible to assign roles to users

### ISSUE THREAD

**Issue by benjaminbittner-ba** [BookStackApp/BookStack#5216]
### Describe the Bug

It is not possible to assign roles to users.

### Steps to Reproduce

1. Go to any user
2. assing role
3. save the change
4. -> not saved
5. it is also not logged in the Audit-Logs

### Expected Behaviour

Roles should be saved and changes should be logged.

### Exact BookStack Version

v24.05.2

**Comment by ssddanbrown** [comment]
Hi @benjaminbittner-ba,

- Are other user profile settings changes saved/reflected after save/submit?
- How are you running BookStack? What kind of installation process did you follow?

**Comment by benjaminbittner-ba** [comment]
Hello @ssddanbrown 

- Bookstack was freshly installed 2 years ago via installation script on an ubuntu vm. Only bookstack is running on this vm. 
- No changes in user settings are saved currently: Name, Profile Pic, Roles, etc

**Comment by ssddanbrown** [comment]
@benjaminbittner-ba thanks for confirming.

- Does saving a role work okay?
- After saving a user, are you returned to the form or the user list?
- Do any inputs have red text after saving?
  - Specifically check the password fields. Have heard previous reports of user's browser autofill attempting to auto-fill the password field, which then means the submit does not validate since the password confirmation field does not match.

**Comment by benjaminbittner-ba** [comment]
@ssddanbrown thanks your quick assistance, without your hints we wouldn't have found the error. It was indeed a rouge space in the password field...
