### ISSUE TITLE
error 404 trying to delete a page

### ISSUE THREAD

**Issue by chrisoros** [BookStackApp/BookStack#5218]
### Describe the Bug

Hi - I added a page to a book, then when I tried to save the page, I received a 404 error. Now on the book's table of contents page the  bad page shows as an entry, but trying access the page throws a 404. there isn't a way I can find to just delete the page from the Book's table of contents. How can I delete the page without requiring me to enter the page, since I cannot access the page as it throws a 404 error. 
thank you! 

### Steps to Reproduce

1. go to book's table of contents, there is no way to delete a page from this screen. 

### Expected Behaviour

be able to delete a page without having to be inside the page. 

### Browser Details

Chrome, FF, Vivaldi

### Exact BookStack Version

23.05.1

**Comment by ssddanbrown** [comment]
Hi @chrisoros,
Potentially this is caught in a permission issue.

- Does the creation show in the app audit log (Settings > Audit Log).
- Does the page show as a draft (purple by default) or a published page (blue by default)?
- Is this book accessible when logged in through an account that has the original admin role assigned? (This should always have access).
- Can you try the ["Regenerate Access Permissions" command](https://www.bookstackapp.com/docs/admin/commands/#regenerate-access-permissions) and see if you're able to access afterwards?
- Can you try updating your instance to the latest release, to see if you're running into an issue that has since been resolved? (Be sure to backup your instance/host before updating!)

**Comment by chrisoros** [comment]
hi @ssddanbrown  - thanks for your suggestions!
yes, the page shows in the app audit logs
yes, it shows published , e.g, blue. 
the book is accessible from admin, but that one page is not. other pages in the same book are accessible.
tried regenerate access permissions and the same '404 - File or directory not found', but only for that one page. 

I have not done an update, but I have daily backups of the files and the db. I'd like to delete the page without having to do a full upgrade. That page doesn't have any content, it is just a page the book thinks it has. I'd really just like to delete that page so it doesn't show up in the book's table of contents. all the other pages in that same book are fine. I'm surprised there seems to be no way to delete a page from a book without having to be inside of that page's hyperlink.

**Comment by ssddanbrown** [comment]
Can you share a view of the exact error screen you see?

Just wonder if it's actually something else hijacking/handling the request.

**Comment by ssddanbrown** [comment]
Since there's been no further follow-up I'll go ahead and close this off.
