### ISSUE TITLE
Settings Customization

### ISSUE THREAD

**Issue by dlastnoel** [BookStackApp/BookStack#5219]
### Describe the feature you'd like

In relation to #5103 by @okaeiz, can we request that also in the settings page, whatever applied custom head content in the block, the settings page will also be affected? Maybe we can it as an entry to the .env file or a checkbox in the settings? Again, thanks for these amazing app. It was absolutely game changer!

### Describe the benefits this would bring to existing BookStack users

Users can opt out to customize the ui of the settings page.

### Can the goal of this request already be achieved via other means?

More granular way of customization.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

### How long have you been using BookStack?

3 months to 1 year

**Comment by ssddanbrown** [comment]
Hi @dlastnoel,
Thanks for the request.

It would be good to understand an actual use-case for this to understand it's actual value since this is not a common request, and I'm not keen on adding settings/options to ensure additional methods of customization in edge-cases, particular where there are alternative means.

You could alternatively use the [logical theme system](https://github.com/BookStackApp/BookStack/blob/development/dev/docs/visual-theme-system.md) to override a template and add your own code to customize all views (including settings).

**Comment by dlastnoel** [comment]
> Hi @dlastnoel,
> Thanks for the request.
> 
> It would be good to understand an actual use-case for this to understand it's actual value since this is not a common request, and I'm not keen on adding settings/options to ensure additional methods of customization in edge-cases, particular where there are alternative means.
> 
> You could alternatively use the [logical theme system](https://github.com/BookStackApp/BookStack/blob/development/dev/docs/visual-theme-system.md) to override a template and add your own code to customize all views (including settings).

- Hi! I just think making it uniform is a bit more consistent. I don't know for the others but for me it is. Maybe we opt out for a pull request if someone may actually do it? Hehe cheers!

**Comment by ssddanbrown** [comment]
I wouldn't really look to merge a PR if it's adding extra settings just for this. I prefer not to have settings just to account for edge-cases, especially if the desire can be achieve via other means.

**Comment by ssddanbrown** [comment]
I'm going to go ahead and close this off as per my reasoning above.
