### ISSUE TITLE
Please ensure all cards have a CSS ID for use with custom header

### ISSUE THREAD

**Issue by lxtv** [BookStackApp/BookStack#522]
### For Feature Requests

Desired Feature:

Loving the latest version; however, I did have to edit home-custom.blade.php to add an id tag to the "Recently Updated" card so that I could hide it using custom CSS. There may be other similar cards but that's the one I encountered. Thanks.

**Comment by cmd-durapart** [comment]
On that note: The sidebar menu is now divided into divs of class card, with their own ID - but on some of the cards, you first have a div of class card, then a h3 header text, and then a new div inside the first one, with the ID.

It would be better if the identifier was set on the card div directly, so we can hide the entire card by element, instead of leaving floating headers without adding extra css.

![floating header](https://user-images.githubusercontent.com/47022058/51729419-ef528000-2073-11e9-804a-b2d16be9133a.JPG)

**Comment by ssddanbrown** [comment]
I'm going to close this off since many of the main listing sections now have their own IDs, although I must confirm that these are not deemed a stable API.
