### ISSUE TITLE
User can be created with malformed email

### ISSUE THREAD

**Issue by vmario89** [BookStackApp/BookStack#5253]
### Describe the Bug

With recent Bookstack we can create buggy users, which will never get an email.

### Steps to Reproduce

go to /settings/users and create a new user

### Expected Behaviour

Please add some validator scheme. i expect to be allowed to enter only valid mail addresses like mail@domain.tld

### Screenshots or Additional Context

![grafik](https://github.com/user-attachments/assets/d52da923-87bb-45a0-bac2-f84cff680920)

### Exact BookStack Version

v24.10

**Comment by ssddanbrown** [comment]
Hi @vmario89,

Emails without an TLD can technically be valid. Here's a fun list: https://en.m.wikipedia.org/wiki/Email_address#Valid_email_addresses
I don't want to complicate things up to, what would effectively be, attempting to prevent user error since that can occur anyway via mispelling, and this isn't something that's been previously reported as an issue in the last 9 years either.

**Comment by vmario89** [comment]
Hi. thanks for the answer. I understand your arguments and agree with the practical side. I just was wondering because i never have seen it anywhere else. I just reported it, because it happened to me randomly when typing the mail address and hitting enter, seeing that the input was accepted

`admin@example (local domain name with no [TLD](https://en.m.wikipedia.org/wiki/Top-level_domain), although ICANN highly discourages dotless email addresses[[31]](https://en.m.wikipedia.org/wiki/Email_address#cite_note-31))` - technically you are right and it might be a breaking change for some setups of existing bookstack instances. So i am closing this
