### ISSUE TITLE
Support more efficient content layout in book page listing

### ISSUE THREAD

**Issue by mackcoding** [BookStackApp/BookStack#530]
### For Feature Requests

Desired Feature: On the books page, there would be less scrolling if the "books" list was laid out in a table. All the pages could benefit from this. On the page view, especially, would be ideal if it was aligned from the left.  I know this scales down based on your resolution, but there is so much white space even on a common resolution such as 1920x1080.

**Comment by Ethanb00** [comment]
Personally, I love the current look and feel. My only suggestion would be to allow for custom (click and drag) or preset (old-new, etc) organization of the book on the list. That way a system book that I rarely need to look at could be at the bottom, while my most used books could be up top.

**Comment by mackcoding** [comment]
I really like the grid layout. It is perfect, and changeable! Perhaps we can have a similar option for the page view.

**Comment by tuedang** [comment]
Perfect, I like this grid layout. Looking forward to seeing it in next release.

**Comment by bisherbas** [comment]
Related #1131

**Comment by ssddanbrown** [comment]
Since some form of grid view was added after this issue was created, and since the design of the application has changed quite a bit since 2017, I'm going to close this off. Feel free to create a new issue if required if there are any specific outstanding requirements that would greatly benefit you and other BookStack users.
