### ISSUE TITLE
Add ability to create issues in external tool when saving BookStack content

### ISSUE THREAD

**Issue by tomcodes** [BookStackApp/BookStack#5336]
### Describe the feature you'd like

Hello!

I have managed to switch all our internal documentation to BookStack at my work: we are really enjoying it so thanks a lot!

We have also started using BookStack to store meeting minutes. We are also using Linear to track all our non-code related work.

I would like to have the ability to create issues in Linear.app when saving content in BookStack. One can imagine the same can be done for any open issue tracker that can accept new issues from the API.

Here is how I envision it:

- Tag content in a specific manner in BookStack (maybe something like `TODO @tom Integrate new layout`
- Have an optional observer in BookStack
- Create the issue and assign it in Linear.app

Is this something that might be of interest for other people besides me?

I would be happy to work on this feature and would love any feedback on this idea.

Thank you!

---

Reference:

https://developers.linear.app/docs/guides/how-to-create-new-issues-using-linear.new

### Describe the benefits this would bring to existing BookStack users

This feature could be beneficial for people using BookStack and an external issue tracker as it would ease the creation of issues.

### Can the goal of this request already be achieved via other means?

Unsure

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

### How long have you been using BookStack?

1 to 5 years

**Comment by ssddanbrown** [comment]
Hi @tomcodes,
To keep scope and maintenance reasonable, I don't look to integrate with specific external tools so wouldn't look to include any such functionality in the realms of what we support.

That said, BookStack does have some existing built in options for connecting with external systems/tools that could be utilised in a case like this:

- Webhooks: On the desired events, you could fire webhooks to an external custom app, or use something like N8N/Zapier/Power-Automate, to recieve the webhook event then do something further as desired (create the issue in Linear).
- API: The BookStack REST API could be polled by an external app to check for new content (look for the desired events) then perform the desired external actions (create the issue in Linear).
- [Logical theme system](https://github.com/BookStackApp/BookStack/blob/development/dev/docs/logical-theme-system.md): This allows watching certain events in BookStack so that custom code/logic can be ran on those events. Using this, you could have custom PHP code to directly call external APIs or perform any actions desired.

Just a note: That link you referenced looks like it's more for end-users, to send them to a pre-filled form to edit & submit rather than for automated systems to fully create new issues.
Automated systems would probably instead use their [`issueCreate` GraphQL mutation](https://studio.apollographql.com/public/Linear-API/variant/current/schema/reference/objects/Mutation#issueCreate)

**Comment by tomcodes** [comment]
Hello and thank you very much for having taken the time to reply in that detailed fashion, really appreciate it.

I will be sure to check the resources you linked me to, it indeed seems feasible with webhooks.

Thanks also for correcting my link on the actual API call (GraphQL mutation).

I'll close this issue as it is not relevant to BookStack itself. Maybe I will reply back if I have a working solution that could be helpful to others.

Best regards.

**Comment by ssddanbrown** [comment]
@tomcodes Happy to help. Feel free to still comment on this thread, or via discord, if you need any extra advice on the BookStack side of things when looking into this further.
