### ISSUE TITLE
Request for Update Procedure: Ubuntu 22.04.1 LTS and BookStack v23.10.2

### ISSUE THREAD

**Issue by echaabane** [BookStackApp/BookStack#5348]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

Dear BookStack Support Team,

I am currently running a virtual machine with Ubuntu 22.04.1 LTS and BookStack version 23.10.2. I would like to update both the operating system and BookStack to the latest available versions.

Could you please provide the recommended procedure or documentation to safely perform these updates? Specifically:

Are there any pre-update steps I should take (e.g., backups, configurations)?
Are there any known compatibility issues between the latest Ubuntu and the latest BookStack versions?
Any post-update checks or troubleshooting steps to ensure the system runs smoothly?
Thank you in advance for your guidance.

Best regards,
Elias

### Exact BookStack Version

v23.10.2

### Log Content

...

### Hosting Environment

Ubuntu 22.04

**Comment by ssddanbrown** [comment]
Hi @echaabane,

I've just published a video to demonstrate and guide this process: https://www.youtube.com/watch?v=mboD-66YsfM

To provide an overview of the steps (in order):

- Backup host system
- Backup application files
- Update current system
- Run Ubuntu upgrade process
- Fix issues (likely due to PHP)
- Run updates for BookStack

Refer to the video for details on any of these steps.

**Comment by ssddanbrown** [comment]
I'll therefore go ahead and close this off but feel free to still comment here, or on discord, if you have questions or need further help.
