### ISSUE TITLE
Hide language preference for guest account

### ISSUE THREAD

**Issue by BuchoMarales** [BookStackApp/BookStack#5356]
### Describe the Bug

Hi Guys,

First of all, muchas gracias, for what you have created so far :) Been enjoying BookStack

One issue I have stumbled upon though is it allowing me to select a language different to English under the default Guest user settings and even saving the settings, yet if I try loading the frontpage or go back to the user settings everything will still be in English with language settings defaulted back to English.

Works flawlessly for a standard user though

Thanks for your help and efforts 

### Steps to Reproduce

1. Go to Settings >> Users >> Guest
2. Set Preferred Language to anything but English
3. Save settings
4. Go to the landing page as a Guest user.
5. Confirm everything is in English
6. Go to Settings >> Users >> Guest
7. Confirm Preferred Language is set to English

### Expected Behaviour

Expect it to save language settings for a Guest user

### Browser Details

Chrome Version 131.0.6778.109 (Official Build) (64-bit)

### Exact BookStack Version

BookStack v24.10.3

**Comment by ssddanbrown** [comment]
Hi @BuchoMarales,
The default language (and that used for guest users) can be configured as detailed in our docs here:
https://www.bookstackapp.com/docs/admin/language-config/

By default, the autodetection of the language based upon browser preferences will used, which is configured via a `APP_AUTO_LANG_PUBLIC` as detailed on that page.

Maybe we should hide the language preference option though for the guest user to prevent future confusion, since it is effectively redundant.

**Comment by BuchoMarales** [comment]
Hi @ssddanbrown,

Thanks for checking ! Now everything is all good :) 

Thanks a lot

**Comment by ssddanbrown** [comment]
@BuchoMarales Good to hear!

I've recategorised this issue to focus on, and made changes in a8ef820443cc444423f0fd21c4e1ce9fb64cbac0, to hide the language preference for the guest user to help avoid any similar confusion in future.
This will be part of the next feature release.
