### ISSUE TITLE
Customizable Navbar

### ISSUE THREAD

**Issue by tenten8401** [BookStackApp/BookStack#544]
As the title says, I think it'd be nice to get customizable navbars, something like what http://readme.io does.
https://readme.readme.io/

**Comment by ssddanbrown** [comment]
Thanks for the request but I'm going to now close this off since:

- Our [visual theme system](https://github.com/BookStackApp/BookStack/blob/master/dev/docs/visual-theme-system.md) has matured allowing customization to any view used by BookStack, for those technically inclined.
- This has had little other demand over the last 4 years.
