### ISSUE TITLE
Feature req: revisions of attachments

### ISSUE THREAD

**Issue by tdkl** [BookStackApp/BookStack#545]
Desired Feature: revision support for attachments

Would it be possible to implement revisions of attached files to the page? So user can easily attach the file with the same name to the page in the new revision.

Use-case: 

1) user creates a page and uploads file a.docx
2) then edits the page (creating revision no. 2) and uploads same a.docx, but with changes, so it's actually a new version of the file,
3) attached a.docx is now the last uploaded, revision no. 2 same as the page.
4) if user reverts to revision no. 1, it reverts the a.docx (or it has an option to revert) as well.

Thoughts?

**Comment by Hammerfest** [comment]
Instead of making a duplicate, im going to post on this one.

Recommend change title to:
[FeatureRequest]: Additional Revision Coverage

The reason why is that I was recently working on a flowchart with the nice built-in draw.io and after my last save, poof, the flowchart was gone, and there where ZERO revisions for ANY of the edits I had done, literally only the first time I made the flowchart and hit save and when I first made the page so 2 total revisions despite that I had done at least 14 different edit's to the flowchart.

Its been a week and I am still not even interested in remaking it despite that I need to get it done...

**Comment by ssddanbrown** [comment]
Hi @Hammerfest,

If you have not done so already, it might be worth looking in the drawing manager to see if it's there. I think every "drawing save" action gets saved as a new drawing in there. You can access via the button dropdown, as the screenshot below, if using the WYSIWYG editor:

![image](https://user-images.githubusercontent.com/8343178/57243704-a9bc3080-702e-11e9-8084-e47e1363438f.png)

If using the markdown editor, you can ctrl+click the drawing link to show the manager, Or temporarily switch to the WYSIWYG editor.

**Comment by Hammerfest** [comment]
Yes, I had looked here before I went postal and deleted the page, sadly, only the current one (blank) and the last one in the other revision I saw (many revisions ago) where there :(

**Comment by ssddanbrown** [comment]
Since there's been little demand for this feature in the past 3 years, and since it would take a great deal of effort to implement, I'm going to close this off. Thanks @tdkl for sharing your original request.

**Comment by Hammerfest** [comment]
No worries, I had to switch to a different solution, I am sure others did as well.
