### ISSUE TITLE
Require email confirmation setting not ignored when domain restriction is in place

### ISSUE THREAD

**Issue by tuaris** [BookStackApp/BookStack#573]
* BookStack Version: 0.18.4
* PHP Version: 7.1
* MySQL Version: MariaDB 10.2

This setting does not do what it says.

> If domain restriction is used then email confirmation will be required and the below value will be ignored.

However, I believe that the current behavior is correct and should be kept.  The text should be corrected/removed.  Additionally, the signup process should not prompt the user that email conformation is pending.

##### Expected Behavior

User log in is blocked, pending email confirmation

##### Current Behavior

User is able to log in.

##### Steps to Reproduce

Domain restriction is enabled.
Require email confirmation is disabled
User signs up, gets prompted to confirm email.
User attempts to log in

**Comment by ssddanbrown** [comment]
Thank you for raising this issue. 

I think its important that email confirmation is forced, At least for now, otherwise the domain restriction is essentially useless and it ensures a security-first approach.

The only place I can think where not-forcing email would be ideal is when only using social authentication options which is not yet a possible feature.
