### ISSUE TITLE
Question about users

### ISSUE THREAD

**Issue by clemmy** [BookStackApp/BookStack#578]
Hello, I was reading the documentation for auth and I was wondering if it's possible to limit the users who can sign up to have view/edit access on a self-hosted BookStack instance.

**Comment by RaghavSood** [comment]
You can create roles with the view-only permissions on certain books (or all, if you like)

**Comment by ssddanbrown** [comment]
Hi @clemmy,

Yes, This is possible. You can create a role, Suited to your required permissions, then select that role to be assigned for new users. Here's a screenshot of the settings for this:

![bookstack-registration-settings](https://user-images.githubusercontent.com/8343178/32463571-255b1ccc-c335-11e7-8be6-f378712a5732.png)

Since the above should answer your question I will close this issue. Feel free to comment if you have further questions though and I will re-open this.
