### ISSUE TITLE
Remove artisan as a command-line requirement

### ISSUE THREAD

**Issue by vladaman** [BookStackApp/BookStack#606]
**Desired Feature:**
We are trying to install BookStack on a generic PHP Hosting and problem is there is no generic SQL Schema to be applied. On remote hosting we can't run php artisan ... so It would be nice to have some web based installer (like wordpress and others...)

At least it would be nice to include SQL to apply manually to hosted DB.

**Comment by ssddanbrown** [comment]
Thanks for opening this issue. Removal of composer as an install requirement is already open under #161 so I will alter the title of this issue to focus on artisan.

We'd also need to provide simple update options since these also rely on artisan.

Artisan can be called from code so we can use this but it needs to be protected from external abuse.

**Comment by lommes** [comment]
This shouldn't be too hard since it is possible to [call artisan commands from code](https://laravel.com/docs/5.5/artisan#programmatically-executing-commands) easily

**Comment by ssddanbrown** [comment]
Since there has been little interest for this in the last few years, and since removing reliance on using the artisan cli will take a fair bit of effort, I'm going to close this off.
