### ISSUE TITLE
Crossed a thousand stars!

### ISSUE THREAD

**Issue by Abijeet** [BookStackApp/BookStack#612]
Congrats and Thank you @ssddanbrown!

**Comment by ssddanbrown** [comment]
Wooohooo! That is awesome! Especially with the lack of promotion I've done for the project. :sweat_smile: 

A massive thanks to all contributors and issue raisers so far, With a special thanks to both you, @Abijeet, and @lommes as you've both been doing great work responding to issues, providing input and contributing code. 

I'l put up a blog post tomorrow to celebrate, along with the launch of v0.19.
Here's to another 1000 stars :beers:

**Comment by Abijeet** [comment]
@ssddanbrown - Cheers.

What's your roadmap for going out of beta and releasing a 1.0? 

Also, I'll see if I can update the website a bit. I'll review the website, and create a new issue to make a list of the changes that can be made.

**Comment by ssddanbrown** [comment]
@Abijeet Just before you jump into the website, Note that I have started some changes on the [v0.19 branch](https://github.com/BookStackApp/website/tree/v0.19). Mainly just updates to what's already there to bring it up to date.

In terms of roadmap for 1.0. It's still hard to say, Was waiting for things to stabilise really but I'd say there some core things to be implemented:

* Smoother installation/update process that does not rely on composer/git. Maybe without artisan aswell?
* Permission system changes - Want to revise this system a bit to be more intuitive to work with the entity tree more efficiently.
* Maybe subchapters/Bookshelves. (Just another layer).
* Deeper customisation possibilities - Got some ideas for this where blade files / icons could be overridden.
* Instance-wide exporting for migration or backup.
* Notification system.

The above is just the chunky features I had in mind required for v1. Got some ideas for each. Don't really want to commit to a v1 though until closer as there's no need to add additional pressure for no reason and I'd rather implement features slowly and thoroughly rather than rush just to meet a v1 deadline.
