### ISSUE TITLE
Feature Request: simple dompdf styling in settings

### ISSUE THREAD

**Issue by pabloalbrecht** [BookStackApp/BookStack#642]
### For Feature Requests

Desired Feature: 

- The ability to design a simple header/footer to be rendered in a PDF export (or HTML export).
- The ability to submit CSS 2.1 styling in the Settings of BookStack, this would allow us to at least change the font family / size / colors of the outputs.

**Comment by ssddanbrown** [comment]
I'm going to now close this off since the original requests are now possible in some way:

- The [visual theme system](https://github.com/BookStackApp/BookStack/blob/development/dev/docs/visual-theme-system.md) can be used to tweak the export templates to add a header and footer. I made [a video on this process here](https://www.youtube.com/watch?v=5bZ7zlNEphc).
- CSS tweaks can be made targeting child elements of `.export-format-pdf`, since this class is applied to the body during pdf exports. You can simple place such tweaks in the "Custom HTML Head Content" customization setting.
