### ISSUE TITLE
Can I use Memcached or Redis for the large Userbase?

### ISSUE THREAD

**Issue by yoginth** [BookStackApp/BookStack#648]
Can I use Memcached or Redis for the large Userbase?

I'm using **Ubuntu server with 2GB RAM and 4 Core CPU**, how many **concurrent** users can BookStack have with this configuration, _and for what optimizing what cache engine should I use?_

**Comment by ssddanbrown** [comment]
Hi @yoginth,
I don't really have any data on high-concurrency usage of BookStack. It will depend on what actions those users perform, How heavily permissions are used and other parameters.

Both Memcached or Redis can be used for both caching and sessions. I'm not sure which would serve best for high-concurrency.

Generally BookStack is focused on the small-mid scale environments such as internal company wiki use rather than a general, large-scale wiki. Something like mediawiki would be better for larger-scale use since it's much more battle-tested.
