### ISSUE TITLE
Issues with the ubuntu 16.04 installer script

### ISSUE THREAD

**Issue by spacekookie** [BookStackApp/BookStack#655]
I'm having some issues installing bookstack on Ubuntu 16.04. I should mention that it is an Ubuntu 16.04 `lxc` container, running an nginx on the host doing ssl termination and then proxy-ing everything into the container.

### For Bug Reports

* BookStack Version: v0.19.0
* PHP Version: 7.0.22-0ubuntu0.16.04.1
* MySQL Version: mysql  Ver 14.14 Distrib 5.7.20

##### Current Behavior
After the setup two errors occur

1. Parts of the login page (https://wiki.spacekookie.de), namely the logo, are sent over http which makes browsers paranoid
2. The user (admin@admin.com, password) combination doesn't let me log-into my wiki to change settings either

According to the setup script the installation was however successful. So...not really sure what to do here.
I don't really think this has anything to do with running Bookstack inside a container but I thought I'd just mention it.

##### Steps to Reproduce
1. Inside a fresh lxc Ubuntu 16.04 container download the installer script
2. Run the installer script
3. Go to the installed website

**Comment by yoginth** [comment]
site is not working

**Comment by spacekookie** [comment]
What do you mean by that? What site? In what way?

**Comment by ssddanbrown** [comment]
Hi @spacekookie, Sorry to hear you are having issues. Just tested it and I think issue 2 is directly related to issue 1. The login request simply redirects to the https versions of the page (But does not submit the data). Once issue 1 is sorted issue 2 should also be fixed.

In regards to issue 1, This will be due to proxies and how the framework responds to proxies.
To start off, Try setting `APP_URL=https://wiki.spacekookie.de` in your `.env` file as that should force the base url of all urls generated by the system.

Let me know how that goes.

**Comment by spacekookie** [comment]
@ssddanbrown Awesome, yes thank you! I was searching for a file like that but was looking at the .php files for configuration (not a PHP dev 😝). This works now, I can log-in and Firefox is happy too.

Thank you for the quick support and for writing such a sexy looking piece of wiki software ❤️

**Comment by ssddanbrown** [comment]
Awesome, Happy to hear that sorted it
