### ISSUE TITLE
[Feature/Enhancement] Publication Details and Copyright on Export

### ISSUE THREAD

**Issue by PWA-GouldA** [BookStackApp/BookStack#667]
##  Publication Details and Copyright on Export

This feature should provide for a page containing the publication and general copyright details.

For example:

### Book Title
Summary of book.

**Author Name(s)**

This version was published on **publication date**

General information about book publication.

© **Start Year** - **End Year** **Author name(s)** **Optional Company name**

**Comment by ssddanbrown** [comment]
I'm going to close this off since this has had little demand since opening, and since it's now possible to alter export templates using our [visual theme system](https://github.com/BookStackApp/BookStack/blob/development/dev/docs/visual-theme-system.md), as demoed [in my video here](https://www.youtube.com/watch?v=5bZ7zlNEphc).
