### ISSUE TITLE
Auth with Twitch

### ISSUE THREAD

**Issue by moutonnoireu** [BookStackApp/BookStack#680]
### Feature Requests

Desired Feature : Login with twitch

I would like to have a way to login with Twitch to bookstack. How could I do that if the request is not accepted ? Thanks for the help !

**Comment by lommes** [comment]
It shouldn't be too hard, since there already is a [socialite provider for twitch](http://socialiteproviders.github.io/providers/twitch/).

There are some recent PRs to integrate [okta](https://github.com/BookStackApp/BookStack/pull/598) and [gitlab](https://github.com/BookStackApp/BookStack/pull/626) which might give you an introduction on how to do it. Feel free to create a pull request to integrate it into bookstack.

**Comment by moutonnoireu** [comment]
I will try in the next days, it doesn't seem too hard. Thanks for the input :)

**Comment by moutonnoireu** [comment]
https://github.com/BookStackApp/BookStack/pull/684

**Comment by ssddanbrown** [comment]
Completed as part of #684. Merged in as of commit 2d41a4f0644d6e0e654a663153f9594bd39396d0
