### ISSUE TITLE
Issue with links, when create book

### ISSUE THREAD

**Issue by S1AnGeR** [BookStackApp/BookStack#731]
### For Bug Reports

* BookStack Version: v0.20.0
* PHP Version: 7.1-x64
* MySQL Version: MariaDB-10.2-x64

##### Expected Behavior
1) links with "-" and spaces beetwen must contain only one "-" 
2) links with different language - transliterate into english. 

##### Current Behavior
1) if I named my book    **test - build** , link looks like **test---build** , how can I change it to **test-build** ( even if I have spaces in book name)
2)because I name books on russian , its little problem here, links looks like: http://bookstack/public/books/%D0%B4%D0%BE%D0%BA%D1%83%D0%B2%D0%B8%D0%BA%D0%B8---1001225 
or on chrome:
![links](https://user-images.githubusercontent.com/5192883/36949184-9bcc9628-1fed-11e8-8c1e-376a61fbdf3a.png)

Is that any way to turn on english translit?

##### Steps to Reproduce
1) name book with spaces and "-" on russian 
2) watch for 1-step result in chrome .

**Comment by ssddanbrown** [comment]
Hi @S1AnGeR, Thanks for creating this issue.
Does the `-` issue actually cause any errors at all or is the issue purely visual?

In regards to translating urls to English, I'm not sure this is something I'd think is worth adding to the project due to the complexity involved. I would have generally thought you'd want the url to read in the same language as the content? Is it simply the length of the encoded URL that's the issue here?

It is possible to create a short link to any page if it's for sharing. You can highlight any page content and a popup will appear with a link. This link will be to the exact block you highlighted. Remove everything after the `#` in the url to link just to the page.

**Comment by ssddanbrown** [comment]
Since the last comment on this issue is relatively old I'm going to close this. If the issue remains and is something you still require to be fixed please open a new issue, referencing this one.
