### ISSUE TITLE
Installing with --no-dev fails

### ISSUE THREAD

**Issue by lommes** [BookStackApp/BookStack#742]
When you try to install BookStack with ```composer install --no-dev``` this will fail since some packages like barryvdh/laravel-ide-helper are not installed, but expected in config/app.php.

Installing with the no-dev option is a thing often used by deployment-systems. I use [deployer](https://deployer.org/) and have to override some solid defaults to make it work. Also composer might change the way how they deal with packages in require-dev and only load require packages by default.

If the package is required for running BookStack it should be included in the required section. Are the entries in app.php still required or are these packages already using autodiscovery (at least laravel-ide-helper does)? If so, we can remove them.

**Comment by ssddanbrown** [comment]
@lommes Yeah, I totally agree with the above. 

It looks like all the third party providers have auto-discovery but I know for the PDF libs and Intervention I used non-default aliases/Facades since the defaults are very generic and could get confused with other classes. Not sure if that will have an impact and how auto-discovery works there.

**Comment by ssddanbrown** [comment]
Just pushed c6844324d0e354e728b385b8d238780cd65052e7 to cover this.

I've left the non-dev service providers in there as it's nice to be able to see all required app service providers used listed in one place.
