### ISSUE TITLE
offical books page per user.

### ISSUE THREAD

**Issue by junlicn** [BookStackApp/BookStack#764]
### For Feature Requests

Desired Feature:  
I want to have a books page for every user like "/books" , but at current every user's page is not what I want .  for example : " /user/3"  
social  purpose:   Every one has his own book page and could show it to public as a seperate space.  And at the public index page,  we can see  most important books or articles in different way. 

In fact, I want to see a site, which  every one can build his own knowledge base / architecture  by create books,  and every one could see the important content from others.  all is public.

### For Bug Reports

* BookStack Version *(Found in settings, Please don't put 'latest')*: N/A
* PHP Version: N/A
* MySQL Version: N/A

**Comment by ssddanbrown** [comment]
Thanks for your request @junlicn.

I'm going to close this unfortunately, due to straying a little too far away from the core idea of the project. BookStack is really designed to be a single, collaborative wiki, instead of being a collection of user-specific wikis. 

You may actually being able to emulate what you're after using some of the "create-own" role permissions and the future API could help automate things like user book creation.
