### ISSUE TITLE
Missing guide how to install on shared host

### ISSUE THREAD

**Issue by vladaman** [BookStackApp/BookStack#794]
Given I have shared webhost without ability to run composer or artisan, how do I install and update BookStack files?

**Comment by ssddanbrown** [comment]
Hi @vladaman, I'm afraid there's not really a guide for this yet. All shared hosts have different abilities, libraries and software installed making it hard to create a guide that suits all. Encouraging installation in restrictive shared hosting environments also leads to a higher chance of an insecure setup.

It is something I'd like to support at some point, and I do plan to make the installation process easier, but nothing is available at this time.

Alternatively, Since BookStack is built on Laravel you can try searching for `Laravel installation guides` for your specific host to see possibilities.

**Comment by mackcoding** [comment]
@vladaman  what shared hosting? Do you have shell access? Have you contacted the host?

**Comment by shmooth** [comment]
i'm hoping to find hosted bookstack so i can pay someone $10/mo to host my pickup soccer site. i just want to click and go. if we know of anyone, i'm happy to update the installation docs. thanks.

**Comment by ssddanbrown** [comment]
As per my comment above, We're not really looking to support shared hosting at this time and the documentation has been updated to reflect this so I will close this request.
