### ISSUE TITLE
Switch between Markdown and WYSIWYG when editing pages

### ISSUE THREAD

**Issue by pommetjehorlepiep** [BookStackApp/BookStack#842]
Desired Feature:

I'd love to be able to switch between Markdown & WYSIWYG when editing pages.

Much better than: go into the settings, change the editing mode and edit page(s) and once finished go back in settings to set mode back again.

**Comment by ffub** [comment]
I would also like this. This functionality is handled well bit a number of static site editors such as https://www.siteleaf.com/

**Comment by ssddanbrown** [comment]
Thanks for opening this feature request. 

This is very closely related to  #119 and #458.

@ffub Have you seen any more complex editors that do this? Many I've seen are really built markdown-first so are fairly limited to just the core markdown formattings options. Just something that includes tables & text alignment and possibly custom formats.

**Comment by NickeZ** [comment]
XWiki allows the author of the document to switch between markup formats in a lossy way.

**Comment by JHenneberg** [comment]
The TOAST ui editor looks realy promising. 
Markdown Wysiwyg Editor - Productive and Extensible
https://ui.toast.com/tui-editor

![alt](https://uicdn.toast.com/tui-editor/tui-editor-preview-1520325258239.gif)

**Comment by tlnagy** [comment]
> The TOAST ui editor looks realy promising.

This would be amazing. I think I'll have a much easier time convincing my group to use the markdown version of the wiki if it included some WYSIWYG features. Right now there's a trade-off: portability in markdown mode and discoverability/convenience in WYSIWYG mode.

**Comment by GammaGames** [comment]
I've actually used toast in projects, it's very good. I have the option to switch between the WYSIWYG editor and the regular markdown editor so it's easy for anyone to use how they want.

**Comment by kayvanaarssen** [comment]
This would be awesome. We use this in our Wordpress KB as well

**Comment by Dalarialus** [comment]
I'd really like to see this happen as well. I think that the ability to switch between markdown and WYSIWYG during editing would really help to balance functionality with ease of use.

**Comment by ssddanbrown** [comment]
PR #3387 has now been merged, which allows switching of editor type (If role permissions allow) from within the editor.
The editor type is then saved against the page itself, and uses the system setting as a default.
[A preview can be seen here. ](https://user-images.githubusercontent.com/8343178/164977916-9c8beee1-8578-43cd-b877-accb55e97fb6.mp4)

This isn't as instant as front-end switching (As per something like ToastUI) since we swap editor implementation depending on choice and we need to show a confirmation due to fundamental impacts of changing the editor. But it should be a lot faster and friendlier than current approaches, to cover most fundamental needs of this request.

There are two choices when moving from WYSIWYG to Markdown:

- Stable - This retains existing HTML content in Markdown to avoid any potential functionality breakages or loss of formatting. This is similar to switching the global option now then re-opening a page for edit.
- Clean - This is a system-cleaned markdown output, which is much nicer but has potential for formatting loss and potential functionality breaks (Things depending on HTML attributes/IDs for example).

The code for this has been merged and is targeted for the next feature release (Likely v22.04), So I'll therefore close this issue off.
