### ISSUE TITLE
Show when a user last logged in

### ISSUE THREAD

**Issue by Shackelford-Arden** [BookStackApp/BookStack#848]
# User Management

I'd love to have the ability to at least see when a user last logged in. The purpose of this would be to remove the user and keep things clean in terms of user management. Though, if possible, I'd like the user's name to still show for page author, etc.

Maybe when the user has been deleted, their name simply shows as "<name> (Removed)" or something like that.

**Comment by ssddanbrown** [comment]
@Shackelford-Arden Thanks for your suggestions.I agree that being able to see the last login time would be really helpful.

In regards to the deletion, Maybe a long-term solution for this would be to add functionality to allow admins to disable user accounts which would prevent logins but would keep references to created items? Would that suit your requirement?

I'll update the issue title to be focused on viewing last login, Let me know on the above and I'll open a new issue specifically for disabling if that solution suits.

**Comment by Shackelford-Arden** [comment]
@ssddanbrown Disabling is an awesome way to do that! I like that. I would wonder if there'd be a way to have views or at least filtering so you can keep the user list clean but still have the option of seeing the disabled users if needed.

Thanks! One of these days I'll figure out enough Laraval/VueJS to add something other than requests lol...

**Comment by Cave-Johnson** [comment]
Would love to see the user last login time added to the admin dashboard. The ability to disable an account as well would be a great security improvement without messing with content

**Comment by ssddanbrown** [comment]
From what I can tell, The original request here was the ability to easily identify inactive users, although the intended method to do so was via visibility of last login.

Using last login alone is a bit complicated, Since the different authentication methods and different session timeouts can result in a questionable figure.

For the next release (v0.31) I have implemented the following:

![image](https://user-images.githubusercontent.com/8343178/99908038-09912f80-2cd8-11eb-80ae-1b82677d4209.png)

The user list will have a "latest activity" sortable column so you can identify likely inactive users.
Also within the update the tracked activity, which can affect this "Latest Activity" figure is much more extensive and includes admin operations & logins. If you need to specifically look for login events you could still then do this manually via the audit log or database.

Since I believe this solution covers the original ability intent, I'll close this off.

**Comment by Cave-Johnson** [comment]
This looks fantastic, thanks Dan!
