### ISSUE TITLE
Feature - Copy CodeBlock Button

### ISSUE THREAD

**Issue by zhdenny** [BookStackApp/BookStack#858]
Desired Feature:

Include a convenient way to Copy **inline code** and **code blocks**. I've included an examples below. Plenty of forums, wikis, etc have these features and I would hope BookStack incorporates them as well. Thanks!

https://addons.cdn.mozilla.net/user-media/previews/full/147/147284.png?modified=1420286517

https://meta-s3-cdn.freetls.fastly.net/optimized/3X/5/c/5c6c0c86a3406d6f1ad35b2af585f110a4740640_1_690x285.jpg

**Comment by ssddanbrown** [comment]
Hi @zhdenny, Thanks for the good suggestion.

I've now added this feature to BookStack to be part of the next release.
I have not added it for inline code since that's only really to be used for very simple snippets and it would complicate the UI adding a copy button to these but all code blocks within page content will have a copy button available.
