### ISSUE TITLE
UI: Comments - Inline code - Exceeds the comments container

### ISSUE THREAD

**Issue by manohar566** [BookStackApp/BookStack#860]
### For Bug Reports

* BookStack Version: v0.20-dev
* PHP Version: 7.0
* MySQL Version: 

##### Expected Behavior
Comment content should not cross the container 

##### Current Behavior
Inline code block - exceeds the comments container.

##### Steps to Reproduce
Change the styles to break the words in the code block.

Attached screenshot:
![bookstack-1](https://user-images.githubusercontent.com/8279205/40589017-4391b3cc-6204-11e8-8260-3a0765d5e326.png)

**Comment by ssddanbrown** [comment]
Hi @manohar566,

Thanks for reporting this and offering a pull request.

Note that after a page reload the code block should be parsed by codemirror to be in a scrollable code-block anyway as shown here:

![image](https://user-images.githubusercontent.com/8343178/40609154-b9bd9014-6265-11e8-8022-b86e15526337.png)

I'm hesitant to merge in your changes in #861 due to the fact the changes will mean white-space is not preserved in the code-block which I think it pretty essential for code-based content.

**Comment by manohar566** [comment]
Hi @ssddanbrown,
Thanks for pointing that out. I'll make the necessary change and push back soon.

**Comment by ssddanbrown** [comment]
Since the last comment on this issue is relatively old I'm going to close this. If the issue remains and is something you still require to be fixed please comment and this can be reopened if required.
