### ISSUE TITLE
Markdown Editors - https://stackedit.io/ - Spell Check

### ISSUE THREAD

**Issue by dtw-chriss** [BookStackApp/BookStack#866]
### For Feature Requests

Please implement https://stackedit.io/ markdown editor or an editor with spell check.  It is difficult to write documentation without it.  Thanks for your consideration.

**Comment by rohitpaul** [comment]
This would be great!

**Comment by ssddanbrown** [comment]
Hi @dtw-chriss,
Thanks for this request.

Since spell-checking is the real requirement of this I'm going to close this issue as a duplicate since this is already open under #693.


Stackedit is good but it's a platform in itself. We could integrate with the online version but I would not want to replace the current, in-built, markdown editor since that's well integrated and works without external requirements. It would be a case of supporting an additional editor option which is a large undertaking by itself and I don't think there's enough to gain for it to be viable at this stage.
