### ISSUE TITLE
Databaseless

### ISSUE THREAD

**Issue by dtw-chriss** [BookStackApp/BookStack#867]
### For Feature Requests

Think i'd be great to use static pages and/or GitHub and Gitlab as a repository.  Seems like they already do version control very well.  The database may be a bit redundant.  Thanks for your consideration.

**Comment by ssddanbrown** [comment]
Hi @dtw-chriss,
Thanks for raising this issue.

Since this is very similar to #776 I'm going to close this as a duplicate.
Please see my comments there for this and feel free to continue that conversation.

The database is used for a lot more than to just hold the page content. I would like to at some point build a full system export via command which you could easily automate into version control like git but that may still be a little way off.
