### ISSUE TITLE
Desired Feature: Time to read

### ISSUE THREAD

**Issue by TBK** [BookStackApp/BookStack#872]
Display the approximate time it takes to read a page.

Example:
![image](https://user-images.githubusercontent.com/858296/40860948-76b70f18-65e7-11e8-9ccb-f676f8cf5906.png)

Code example:
https://gist.github.com/mynameispj/3170442

**Comment by Abijeet** [comment]
Hi @TBK , Thanks for filing this feature request.

Since this is very similar to https://github.com/BookStackApp/BookStack/issues/852 I'm going to close this as a duplicate.

Please add a +1 to that issue to add your vote, including the code sample and image that you've added here as they may be helpful during development. :)

**Comment by TBK** [comment]
My search foo was not strong enough.  I will add the info and a +1 to the other request 👍
