### ISSUE TITLE
CSP best practice

### ISSUE THREAD

**Issue by TBK** [BookStackApp/BookStack#880]
CSP deems inline CSS & JS unsafe - https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/style-src

Currently BookStack requires `Content-Security-Policy: style-src 'self' 'unsafe-inline';  script-src 'self' 'unsafe-inline';`` because of the inline CSS code in https://github.com/BookStackApp/BookStack/blob/master/resources/views/partials/custom-styles.blade.php and JS code https://github.com/BookStackApp/BookStack/blob/master/resources/views/settings/index.blade.php#L162

Another CSP issue is with the use of .globalEval in app.js.

Would a possible solution for custom-styles.blade.php be to move the css code to a file and update the file when the value is changed through the settings page?

I have not been able to trace .globalEval but I think it is coming from jQuery.

**Comment by mlhbeckmann** [comment]
Are there any updates on this? I am running Bookstack behind my NGINX reverse proxy and have to following CSP's in place:

`add_header Content-Security-Policy: "default-src 'none'; font-src https://fonts.gstatic.com 'self';img-src 'self'; object-src 'none' 'self'; script-src 'self'; style-src 'self';";`

This works fine, however with this CSP in place, the cover images of Books and Shelves are no longer visible. This is especially curious, because the images within pages are visible as always, which doesn't make sense to me. When inspecting a book cover without the CSP in place, I can see, that the image source is as expected

```
<div class="featured-image-container" style="background-image: url('https://bookstack.domain.com/uploads/images/cover_book/2021-05/image.jpg')">
        </div>
```
So in theory the CSP I have should work, right? But for some reason and only for the covers, images don't show up.

**Comment by ssddanbrown** [comment]
I'm going to close this off since the CSP situation in BookStack has changed since this request. CSP is now built-in using nonce-based CSP rules.
