### ISSUE TITLE
Bad Documentation for Beginners

### ISSUE THREAD

**Issue by iBooster** [BookStackApp/BookStack#889]
### For Feature Requests

Hey there,

the documentation is, to be honest, really bad.

I just wanted to add an simple click counter to the pages. But i can't find any possibilitys to do that.
But i am an noob with laravel, so maybe the fault is on my side.

But i would love to get some possibilitys to produce my own extensions.

Maybe anybody can help me.

**Comment by ssddanbrown** [comment]
Hi @iBooster , Thanks for opening this issue.

Yeah, I'm aware the docs need work. That said, Providing information on a 'click counter' is quite specific and BookStack isn't really set-up for `extensions` at the moment, since BookStack is primarily to be a ready-to-go docs system rather than an extensible platform, which is why you cannot find documentation on this.

Further customization options have been requested and some are in the works.

Since there's nothing directly actionable on this issue I'm going to close it. If there's something specific to be improved in the documentations or a specific topic you'd like help on please open a new issue with more information on what you require.

**Comment by iBooster** [comment]
Okay, i fully understand that. But i need to customize it anyway. So would it be possible to get a little text where i can find „hooks“.

Is the project structure a result of laravel? Maybe this can help me to finde those hooks by myself

**Comment by ssddanbrown** [comment]
@iBooster Yes, The project structure generally follows Laravel's defaults. Be aware that any customization at this level though has the potential to cause update issues going forward.

**Comment by iBooster** [comment]
The possibility of extensions would minimize this potential
