### ISSUE TITLE
Second German translation | How can i set an standard language for all new users?

### ISSUE THREAD

**Issue by iBooster** [BookStackApp/BookStack#890]
### For Feature Requests

Okay, because I don't know Git(hub) ... I put this in here:

I have added an SECOND german translation.

In German speaking countrys, there are an formal and non formal way to talk to an person, while in english there is only one way, the "you". But in german, there is "Du" (non-formal) and "Sie" (formal).

Because the actual german translation is in formal german, i have added an non-formal translation.

You can download it from my Google Drive link below, would be nice if someone could add this official.

By the way, how can I set an other standard language?

https://drive.google.com/file/d/1J7gve1z35NZCBjXL-EcX7hIAAssiFKqQ/view?usp=sharing

**Comment by ssddanbrown** [comment]
Hi @iBooster,

You can set the default language by adding `APP_LANG=your_lang` in the `.env` file where `your_lang` is the folder name used in the `lang` folder. Keep your custom files backed-up safely though as they could be overwritten upon update.

Are formal and non-formal German official language variations? If there are only small tweaks between them it may not be worth officially supporting both. Would the variant used change depending on how BookStack is used then? Sorry, Not very familiar with German myself.

Details of setting a default language should really by in the docs so I'll mark this as a required doc-update and close it once added.

**Comment by iBooster** [comment]
Thanks for the fast answer. I already thought about it that it would be this easy to set the default language ;)

And for the Non-formal german part: in german it is a real thing with non formal an formal. http://angelikasgerman.co.uk/du-or-sie-when-to-be-formal-or-informal-in-germany/

In my opinion it can change the user expirience completely. While the non-formal german is most of the time choosen for private users (those who visit the page for their personal reasons), you choose the formal german for business users (like on a company website in the b2b area, for example).

If it is worth to support both of them? Well i dont know. For my project i use the non-formal german, because i speak to students and it is way more personal than the formal way (it is like you would call your users „Sir“ or „Miss/es“).

**Comment by ezzra** [comment]
Yes its definitely worth supporting both of them! Well, it depends on how you use the language, one can get around the problematic when using passive forms ("The book has been created" instead of "You created the book"), but this often appears as artificially. And the difference between using formal or informal style in german has a big influence.

I am just planning to use bookstack for a german speaking project, as I noticed for now, the german translation isn't even completed yet, it looks like the translator left out all translation where the word `shelf` is used, thats indeed hard to translate to german because "Schrank" sounds very gruff :)

I will try to take care for this and keep you updated here, do not hesitate to ping me here if are also interested in this.

**Comment by ezzra** [comment]
just fyi, I did a pull request with informal german language files based on the latest translation. Both variants will be available in settings dropdown like "Deutsch (Sie) | Deutsch (Du)"

**Comment by ssddanbrown** [comment]
Now merged, Code in master, ready to be in the next release so will close this issue. Thanks again @ezzra  and @iBooster.
