### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by mehrdaad** [BookStackApp/BookStack#963]
Hello, it would be really nice to add RTL support on viewing the wiki content.  
This would include 2 sections:
1- Adding RTL button to the text editor which essentially makes the text RTL.
2- Viewing pages correctly for RTL text.

**Comment by mehrdaad** [comment]
Would anyone answer if this is possible

**Comment by ssddanbrown** [comment]
Hi @mehrdaad,
Thanks for opening this request.

RTL support has already been requested under #939 so I will therefore close this as a duplicate.

Since the first RTL language in BookStack (#945) is to be included for next release basic RTL support is targeted for BookStack v0.24 although it will be very much experimental.

**Comment by mehrdaad** [comment]
Hi, the pr you references to, is unrelated to my request. I'm looking for the ability to edit text on RTL mode and render text that way.

**Comment by mehrdaad** [comment]
@ssddanbrown All I had to do was include ``directionality`` plugin and add ``ltr rtl`` buttons to the toolbar.
