### ISSUE TITLE
Login with AzureAD without creating a profile first

### ISSUE THREAD

**Issue by onggie** [BookStackApp/BookStack#968]
As we would like to automate the process of a user accessing BookStack, we would like the ability (much like the LDAP intergration) that upon signing in using AzureAD, BookStack would create a profile at the same point in time.

**Comment by ssddanbrown** [comment]
Hi @onggie, Sorry for the delay in my response. I think I must of missed this request before.

This actually has always been possible if registration was enabled. They'd just have to select the Azure option on the registration page instead of the login page.

As of the last release, v0.24, You can now allow auto-registration for social auth options which will auto-register as requested from the login screen. [Details of this can be found here](https://www.bookstackapp.com/docs/admin/third-party-auth/#automatic-registration-email-confirmation).
