### ISSUE TITLE
 Page content section role based visibility control

### ISSUE THREAD

**Issue by tiredofit** [BookStackApp/BookStack#978]
**Describe the feature you'd like**
This would be a feature that based on the users role memberships (let's just use Grades as an example) to show specific content for those with that membership of the role. IE In a learning "library" environment in a Book or chapter called "The Human Body" showed more detail for specific members, shielding it from people who were not of age.

**Describe the benefits this feature would bring to BookStack users**
This would be very useful in a learning environment, with more and more learners using digital systems to get information that was specific to the topic they were researching.

**Comment by ssddanbrown** [comment]
Hi @tiredofit,
Thanks for this request.
You are already able to set per-role permissions per Book, Chapter or Page which should allow you to control visibility.

Control per-section of the content a page is kind of possible but is not straightforward to use and has limitations since it is a bit of a hacky use of multiple BookStack features but I could detail it if you'd wish.

**Comment by tiredofit** [comment]
Hi @ssddanbrown If you did have some time to unpack even some thoughts on how to go about doing it that would be great! Our usage case for this would be a distance learning school where we would have books and chapters and pages based on topics for learning. Keeping all the content on same page would be fantastic to avoid duplication.

**Comment by ssddanbrown** [comment]
Within BookStack you can include sections of other pages, or all page content, within another page using a certain tag. To find this tag select the text of a section and you'll get a popup with a link. Click the 'link' icon on the left and this will show the include tag instead:

![image](https://user-images.githubusercontent.com/8343178/44617846-c9297980-a862-11e8-8ea8-615cc39a87f9.png)

You can then paste this tag when editing another page to dynamically include the text of that section in any other page. Permissions should be enforced for this include so the tag will not show content unless the viewer has permissions to view the page where the content is being included from.

As I said, Not straightforward but kind of possible.

**Comment by ssddanbrown** [comment]
Since it's been a couple of years and this feature request has had little demand, while being something which would be tricky to implement while adding extra complexity to some of the core features of BookStack, I'm going to close this off as out of scope.

Thanks @tiredofit for the original suggestion here and for your continued involvement in the project.
