### ISSUE TITLE
Weird Image upload error

### ISSUE THREAD

**Issue by Kimyeti** [BookStackApp/BookStack#988]
Hi

I can't upload any preview images on my books. The images shows as a broken link like so:

https://i.imgur.com/S2i2Vlh.jpg
https://i.imgur.com/OL9zbJk.jpg

When I click on the broken image link then it shows me the correct path to the image in a new tab.

I can get it to show the image if I open the inspector tool in Chrome and copy the link in manually. Of course the image will disapear when I refresh the page though.

Before:
https://i.imgur.com/sg8Wc5j.jpg

After:
https://i.imgur.com/ogBEcfZ.jpg

Server info: 
Arch Linux
PHP 7.2.5 (All modules installed)
MariaDB

I've tried 4 different browsers with the same result.

Hope someone can be at help to resolve this bug.

**Comment by Abijeet** [comment]
Hi @Kimyeti 

Sorry to hear that you are having trouble.

Image uploads in BookStack are handled via an AJAX call. I'd like you to do the following,

1. Open up the DEV tools and under the network tab see the network request that happens when you upload a file. Check if the status code is 200 or if there is an error in the response body.
2. Check the log file on the server. They should be present inside the root of your BookStack folder - `storage > logs > laravel.log`.

**Comment by ssddanbrown** [comment]
Since the last comment on this issue is relatively old I'm going to close this. If the issue remains and is something you still require to be fixed please open a new issue, referencing this one.
