### ISSUE TITLE
Official Docker image on Docker Hub

### ISSUE THREAD

**Issue by verwilst** [BookStackApp/BookStack#989]
**Describe the feature you'd like**
An official Docker image would allow for a more solid base to build Helm charts for example.

**Describe the benefits this feature would bring to BookStack users**
Official support, not having to depend on personal docker containers that can be discontinued as soon as the creator stops using Bookstack or can't find the time/courage to update it.

**Comment by ssddanbrown** [comment]
Thanks for the request @verwilst.
I'm going to close this as out-of-scope, Simply because maintaining an official docker image will distract from the core project and there are existing docker implementations that are much more knowledgeably put together and maintained than I could ever achieve such as the linuxserver.io  image:
https://github.com/linuxserver/docker-bookstack
